Azerotcore-wotlk: instance_nexus::instance_nexus_InstanceMapScript Struct Reference
instance_nexus::instance_nexus_InstanceMapScript Struct Reference
Public Member Functions
instance_nexus_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *gameObject) override
void OnGameObjectRemove (GameObject *gameObject) override
void SetData (uint32 type, uint32) override
bool SetBossState (uint32 id, EncounterState state) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 40 of file instance_nexus.cpp.
Constructor & Destructor Documentation
instance_nexus_InstanceMapScript()
instance_nexus::instance_nexus_InstanceMapScript::instance_nexus_InstanceMapScript (Map * map) inline
Definition at line 42 of file instance_nexus.cpp.
 : InstanceScript(map) {}
Member Function Documentation
GetSaveData()
std::string instance_nexus::instance_nexus_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 155 of file instance_nexus.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "N E X " << GetBossSaveData();
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData().
Initialize()
void instance_nexus::instance_nexus_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 44 of file instance_nexus.cpp.
         {
             SetBossNumber(MAX_ENCOUNTERS);
             LoadDoorData(doorData);
         }
References doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
Load()
void instance_nexus::instance_nexus_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 162 of file instance_nexus.cpp.
         {
             if( !in )
                 return;
             char dataHead1, dataHead2, dataHead3;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2 >> dataHead3;
             if (dataHead1 == 'N' && dataHead2 == 'E' && dataHead3 == 'X')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
         }
References IN_PROGRESS, MAX_ENCOUNTERS, NOT_STARTED, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 50 of file instance_nexus.cpp.
         {
             Map::PlayerList const& players = instance->GetPlayers();
             TeamId TeamIdInInstance = TEAM_NEUTRAL;
             if (!players.isEmpty())
                 if (Player* pPlayer = players.begin()->GetSource())
                     TeamIdInInstance = pPlayer->GetTeamId();
             switch (creature->GetEntry())
             {
                 case NPC_ALLIANCE_RANGER:
                     creature->SetFaction(FACTION_MONSTER_2);
                     if (TeamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_HORDE_RANGER);
                     break;
                 case NPC_ALLIANCE_BERSERKER:
                     creature->SetFaction(FACTION_MONSTER_2);
                     if (TeamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_HORDE_BERSERKER);
                     break;
                 case NPC_ALLIANCE_COMMANDER:
                     creature->SetFaction(FACTION_MONSTER_2);
                     if (TeamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_HORDE_COMMANDER);
                     break;
                 case NPC_ALLIANCE_CLERIC:
                     creature->SetFaction(FACTION_MONSTER_2);
                     if (TeamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_HORDE_CLERIC);
                     break;
                 case NPC_COMMANDER_STOUTBEARD:
                     creature->SetFaction(FACTION_MONSTER_2);
                     if (TeamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_COMMANDER_KOLURG);
                     break;
             }
         }
References MapRefMgr::begin(), FACTION_MONSTER_2, Object::GetEntry(), Map::GetPlayers(), InstanceScript::instance, LinkedListHead::isEmpty(), NPC_ALLIANCE_BERSERKER, NPC_ALLIANCE_CLERIC, NPC_ALLIANCE_COMMANDER, NPC_ALLIANCE_RANGER, NPC_COMMANDER_KOLURG, NPC_COMMANDER_STOUTBEARD, NPC_HORDE_BERSERKER, NPC_HORDE_CLERIC, NPC_HORDE_COMMANDER, NPC_HORDE_RANGER, Unit::SetFaction(), TEAM_ALLIANCE, TEAM_NEUTRAL, and Creature::UpdateEntry().
OnGameObjectCreate()
void instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectCreate (GameObject * gameObject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 88 of file instance_nexus.cpp.
         {
             switch (gameObject->GetEntry())
             {
                 case GO_TELESTRA_SPHERE:
                     if (GetBossState(DATA_TELESTRA_ORB) != DONE && GetBossState(DATA_MAGUS_TELESTRA_EVENT) == DONE)
                         gameObject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     AddDoor(gameObject, true);
                     break;
                 case GO_ANOMALUS_SPHERE:
                     if (GetBossState(DATA_ANOMALUS_ORB) != DONE && GetBossState(DATA_ANOMALUS_EVENT) == DONE)
                         gameObject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     AddDoor(gameObject, true);
                     break;
                 case GO_ORMOROK_SPHERE:
                     if (GetBossState(DATA_ORMOROK_ORB) != DONE && GetBossState(DATA_ORMOROK_EVENT) == DONE)
                         gameObject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     AddDoor(gameObject, true);
                     break;
             }
         }
References InstanceScript::AddDoor(), DATA_ANOMALUS_EVENT, DATA_ANOMALUS_ORB, DATA_MAGUS_TELESTRA_EVENT, DATA_ORMOROK_EVENT, DATA_ORMOROK_ORB, DATA_TELESTRA_ORB, DONE, GAMEOBJECT_FLAGS, InstanceScript::GetBossState(), Object::GetEntry(), GO_ANOMALUS_SPHERE, GO_FLAG_NOT_SELECTABLE, GO_ORMOROK_SPHERE, GO_TELESTRA_SPHERE, and Object::RemoveFlag().
OnGameObjectRemove()
void instance_nexus::instance_nexus_InstanceMapScript::OnGameObjectRemove (GameObject * gameObject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 110 of file instance_nexus.cpp.
         {
             switch (gameObject->GetEntry())
             {
                 case GO_TELESTRA_SPHERE:
                 case GO_ANOMALUS_SPHERE:
                 case GO_ORMOROK_SPHERE:
                     AddDoor(gameObject, false);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_ANOMALUS_SPHERE, GO_ORMOROK_SPHERE, and GO_TELESTRA_SPHERE.
SetBossState()
bool instance_nexus::instance_nexus_InstanceMapScript::SetBossState (uint32 id, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 141 of file instance_nexus.cpp.
         {
             if (!InstanceScript::SetBossState(id, state))
                 return false;
             if (state != DONE || id > DATA_ORMOROK_EVENT)
                 return true;
             BossInfo const* bossInfo = GetBossInfo(id + DATA_TELESTRA_ORB);
             for (DoorSet::const_iterator i = bossInfo->door[DOOR_TYPE_PASSAGE].begin(); i != bossInfo->door[DOOR_TYPE_PASSAGE].end(); ++i)
                 (*i)->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             return true;
         }
References DATA_ORMOROK_EVENT, DATA_TELESTRA_ORB, DONE, BossInfo::door, DOOR_TYPE_PASSAGE, GAMEOBJECT_FLAGS, InstanceScript::GetBossInfo(), GO_FLAG_NOT_SELECTABLE, and InstanceScript::SetBossState().
Referenced by Load(), and SetData().
SetData()
void instance_nexus::instance_nexus_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
Definition at line 122 of file instance_nexus.cpp.
         {
             switch (type)
             {
                 case GO_TELESTRA_SPHERE:
                     SetBossState(DATA_TELESTRA_ORB, NOT_STARTED);
                     SetBossState(DATA_TELESTRA_ORB, DONE);
                     break;
                 case GO_ANOMALUS_SPHERE:
                     SetBossState(DATA_ANOMALUS_ORB, NOT_STARTED);
                     SetBossState(DATA_ANOMALUS_ORB, DONE);
                     break;
                 case GO_ORMOROK_SPHERE:
                     SetBossState(DATA_ORMOROK_ORB, NOT_STARTED);
                     SetBossState(DATA_ORMOROK_ORB, DONE);
                     break;
             }
         }
References DATA_ANOMALUS_ORB, DATA_ORMOROK_ORB, DATA_TELESTRA_ORB, DONE, GO_ANOMALUS_SPHERE, GO_ORMOROK_SPHERE, GO_TELESTRA_SPHERE, NOT_STARTED, and SetBossState().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/Nexus/instance_nexus.cpp