Azerotcore-wotlk: deps/recastnavigation/Detour/Source/DetourAlloc.cpp File Reference
DetourAlloc.cpp File Reference
#include <stdlib.h>
#include "DetourAlloc.h"
Functions
static void * dtAllocDefault (size_t size, dtAllocHint)
static void dtFreeDefault (void *ptr)
void dtAllocSetCustom (dtAllocFunc *allocFunc, dtFreeFunc *freeFunc)
void * dtAlloc (size_t size, dtAllocHint hint)
void dtFree (void *ptr)
Variables
static dtAllocFunc * sAllocFunc = dtAllocDefault
static dtFreeFunc * sFreeFunc = dtFreeDefault
Function Documentation
dtAlloc()
void* dtAlloc (size_t size, dtAllocHint hint)
Allocates a memory block.
Parameters
[in] size The size, in bytes of memory, to allocate.
[in] hint A hint to the allocator on how long the memory is expected to be in use.
Returns
A pointer to the beginning of the allocated memory block, or null if the allocation failed.
See also
dtFree
Definition at line 41 of file DetourAlloc.cpp.
 {
     return sAllocFunc(size, hint);
 }
References sAllocFunc.
Referenced by createBVTree(), dtAllocNavMesh(), dtAllocNavMeshQuery(), dtCreateNavMeshData(), dtNodePool::dtNodePool(), dtNodeQueue::dtNodeQueue(), dtNavMeshQuery::init(), dtNavMesh::init(), and MMAP::MMapMgr::loadMap().
dtAllocDefault()
static void* dtAllocDefault (size_t size, dtAllocHint) static
Definition at line 22 of file DetourAlloc.cpp.
 {
     return malloc(size);
 }
Referenced by dtAllocSetCustom().
dtAllocSetCustom()
void dtAllocSetCustom (dtAllocFunc * allocFunc, dtFreeFunc * freeFunc)
Sets the base custom allocation functions to be used by Detour.
Parameters
[in] allocFunc The memory allocation function to be used by dtAlloc
[in] freeFunc The memory de-allocation function to be used by dtFree
Definition at line 35 of file DetourAlloc.cpp.
 {
     sAllocFunc = allocFunc ? allocFunc : dtAllocDefault;
     sFreeFunc = freeFunc ? freeFunc : dtFreeDefault;
 }
References dtAllocDefault(), dtFreeDefault(), sAllocFunc, and sFreeFunc.
Referenced by World::SetInitialWorldSettings().
dtFree()
void dtFree (void * ptr)
Deallocates a memory block.
Parameters
[in] ptr A pointer to a memory block previously allocated using dtAlloc.
See also
dtAlloc
Definition at line 46 of file DetourAlloc.cpp.
 {
     if (ptr)
         sFreeFunc(ptr);
 }
References ptr(), and sFreeFunc.
Referenced by ContinentBuilder::Build(), createBVTree(), dtCreateNavMeshData(), dtFreeNavMesh(), dtFreeNavMeshQuery(), dtNavMeshQuery::init(), MMAP::MMapMgr::loadMap(), dtNavMesh::removeTile(), BuilderThread::svc(), dtNavMesh::~dtNavMesh(), dtNavMeshQuery::~dtNavMeshQuery(), dtNodePool::~dtNodePool(), and dtNodeQueue::~dtNodeQueue().
dtFreeDefault()
static void dtFreeDefault (void * ptr) static
Definition at line 27 of file DetourAlloc.cpp.
 {
     free(ptr);
 }
References ptr().
Referenced by dtAllocSetCustom().
Variable Documentation
sAllocFunc
dtAllocFunc* sAllocFunc = dtAllocDefault static
Definition at line 32 of file DetourAlloc.cpp.
Referenced by dtAlloc(), and dtAllocSetCustom().
sFreeFunc
dtFreeFunc* sFreeFunc = dtFreeDefault static
Definition at line 33 of file DetourAlloc.cpp.
Referenced by dtAllocSetCustom(), and dtFree().