Azerotcore-wotlk: Acore::PlayerAtMinimumRangeAway Class Reference
Acore::PlayerAtMinimumRangeAway Class Reference
#include <GridNotifiers.h>
Public Member Functions
PlayerAtMinimumRangeAway (Unit const *unit, float fMinRange)
bool operator() (Player *player)
Private Attributes
Unit const * unit
float fRange
Detailed Description
Definition at line 1431 of file GridNotifiers.h.
Constructor & Destructor Documentation
PlayerAtMinimumRangeAway()
Acore::PlayerAtMinimumRangeAway::PlayerAtMinimumRangeAway (Unit const * unit, float fMinRange) inline
Definition at line 1434 of file GridNotifiers.h.
 : unit(unit), fRange(fMinRange) {}
Member Function Documentation
operator()()
bool Acore::PlayerAtMinimumRangeAway::operator() (Player * player) inline
Definition at line 1435 of file GridNotifiers.h.
         {
             //No threat list check, must be done explicit if expected to be in combat with creature
             if (!player->IsGameMaster() && player->IsAlive() && !unit->IsWithinDist(player, fRange, false))
                 return true;
             return false;
         }
References fRange, Unit::IsAlive(), Player::IsGameMaster(), WorldObject::IsWithinDist(), and unit.
Member Data Documentation
fRange
float Acore::PlayerAtMinimumRangeAway::fRange private
Definition at line 1446 of file GridNotifiers.h.
Referenced by operator()().
unit
Unit const* Acore::PlayerAtMinimumRangeAway::unit private
Definition at line 1445 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h