Azerotcore-wotlk: deps/mysqllite/include/m_ctype.h File Reference
m_ctype.h File Reference
#include <my_attribute.h>
#include "my_global.h"
Classes
struct unicase_info_st
struct uni_ctype_st
struct my_uni_idx_st
struct my_match_t
struct my_collation_handler_st
struct my_charset_handler_st
struct charset_info_st
Macros
#define MY_CS_NAME_SIZE 32
#define MY_CS_CTYPE_TABLE_SIZE 257
#define MY_CS_TO_LOWER_TABLE_SIZE 256
#define MY_CS_TO_UPPER_TABLE_SIZE 256
#define MY_CS_SORT_ORDER_TABLE_SIZE 256
#define MY_CS_TO_UNI_TABLE_SIZE 256
#define CHARSET_DIR "charsets/"
#define my_wc_t ulong
#define MY_CS_REPLACEMENT_CHARACTER 0xFFFD
#define MB2(x) (x)
#define MY_PUT_MB2(s, code) { (s)[0]= code >> 8; (s)[1]= code & 0xFF; }
#define MY_CS_ILSEQ 0 /* Wrong by sequence: wb_wc */
#define MY_CS_ILUNI 0 /* Cannot encode Unicode to charset: wc_mb */
#define MY_CS_TOOSMALL -101 /* Need at least one byte: wc_mb and mb_wc */
#define MY_CS_TOOSMALL2 -102 /* Need at least two bytes: wc_mb and mb_wc */
#define MY_CS_TOOSMALL3 -103 /* Need at least three bytes: wc_mb and mb_wc */
#define MY_CS_TOOSMALL4 -104 /* Need at least 4 bytes: wc_mb and mb_wc */
#define MY_CS_TOOSMALL5 -105 /* Need at least 5 bytes: wc_mb and mb_wc */
#define MY_CS_TOOSMALL6 -106 /* Need at least 6 bytes: wc_mb and mb_wc */
#define MY_CS_TOOSMALLN(n) (-100-(n))
#define MY_SEQ_INTTAIL 1
#define MY_SEQ_SPACES 2
#define MY_CS_COMPILED 1 /* compiled-in sets */
#define MY_CS_CONFIG 2 /* sets that have a *.conf file */
#define MY_CS_INDEX 4 /* sets listed in the Index file */
#define MY_CS_LOADED 8 /* sets that are currently loaded */
#define MY_CS_BINSORT 16 /* if binary sort order */
#define MY_CS_PRIMARY 32 /* if primary collation */
#define MY_CS_STRNXFRM 64 /* if strnxfrm is used for sort */
#define MY_CS_UNICODE 128 /* is a charset is BMP Unicode */
#define MY_CS_READY 256 /* if a charset is initialized */
#define MY_CS_AVAILABLE 512 /* If either compiled-in or loaded*/
#define MY_CS_CSSORT 1024 /* if case sensitive sort order */
#define MY_CS_HIDDEN 2048 /* don't display in SHOW */
#define MY_CS_PUREASCII 4096 /* if a charset is pure ascii */
#define MY_CS_NONASCII 8192 /* if not ASCII-compatible */
#define MY_CS_UNICODE_SUPPLEMENT 16384 /* Non-BMP Unicode characters */
#define MY_CHARSET_UNDEFINED 0
#define MY_REPERTOIRE_ASCII 1 /* Pure ASCII U+0000..U+007F */
#define MY_REPERTOIRE_EXTENDED 2 /* Extended characters: U+0080..U+FFFF */
#define MY_REPERTOIRE_UNICODE30 3 /* ASCII | EXTENDED: U+0000..U+FFFF */
#define CHARSET_INFO_DEFINED
#define ILLEGAL_CHARSET_INFO_NUMBER (~0U)
#define MY_UTF8MB3 "utf8"
#define MY_UTF8MB4 "utf8mb4"
#define _MY_U 01 /* Upper case */
#define _MY_L 02 /* Lower case */
#define _MY_NMR 04 /* Numeral (digit) */
#define _MY_SPC 010 /* Spacing character */
#define _MY_PNT 020 /* Punctuation */
#define _MY_CTR 040 /* Control character */
#define _MY_B 0100 /* Blank */
#define _MY_X 0200 /* heXadecimal digit */
#define my_isascii(c) (!((c) & ~0177))
#define my_toascii(c) ((c) & 0177)
#define my_tocntrl(c) ((c) & 31)
#define my_toprint(c) ((c) | 64)
#define my_toupper(s, c) (char) ((s)->to_upper[(uchar) (c)])
#define my_tolower(s, c) (char) ((s)->to_lower[(uchar) (c)])
#define my_isalpha(s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_U | _MY_L))
#define my_isupper(s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_U)
#define my_islower(s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_L)
#define my_isdigit(s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_NMR)
#define my_isxdigit(s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_X)
#define my_isalnum(s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_U | _MY_L | _MY_NMR))
#define my_isspace(s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_SPC)
#define my_ispunct(s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_PNT)
#define my_isprint(s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_PNT | _MY_U | _MY_L | _MY_NMR | _MY_B))
#define my_isgraph(s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_PNT | _MY_U | _MY_L | _MY_NMR))
#define my_iscntrl(s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_CTR)
#define my_isvar(s, c) (my_isalnum(s,c) || (c) == '_')
#define my_isvar_start(s, c) (my_isalpha(s,c) || (c) == '_')
#define my_binary_compare(s) ((s)->state & MY_CS_BINSORT)
#define use_strnxfrm(s) ((s)->state & MY_CS_STRNXFRM)
#define my_strnxfrm(s, a, b, c, d) ((s)->coll->strnxfrm((s), (a), (b), (c), (d)))
#define my_strnncoll(s, a, b, c, d) ((s)->coll->strnncoll((s), (a), (b), (c), (d), 0))
#define my_like_range(s, a, b, c, d, e, f, g, h, i, j) ((s)->coll->like_range((s), (a), (b), (c), (d), (e), (f), (g), (h), (i), (j)))
#define my_wildcmp(cs, s, se, w, we, e, o, m) ((cs)->coll->wildcmp((cs),(s),(se),(w),(we),(e),(o),(m)))
#define my_strcasecmp(s, a, b) ((s)->coll->strcasecmp((s), (a), (b)))
#define my_charpos(cs, b, e, num) (cs)->cset->charpos((cs), (const char*) (b), (const char *)(e), (num))
#define use_mb(s) ((s)->cset->ismbchar != NULL)
#define my_ismbchar(s, a, b) ((s)->cset->ismbchar((s), (a), (b)))
#define my_mbcharlen(s, a) 1
#define my_caseup_str(s, a) ((s)->cset->caseup_str((s), (a)))
#define my_casedn_str(s, a) ((s)->cset->casedn_str((s), (a)))
#define my_strntol(s, a, b, c, d, e) ((s)->cset->strntol((s),(a),(b),(c),(d),(e)))
#define my_strntoul(s, a, b, c, d, e) ((s)->cset->strntoul((s),(a),(b),(c),(d),(e)))
#define my_strntoll(s, a, b, c, d, e) ((s)->cset->strntoll((s),(a),(b),(c),(d),(e)))
#define my_strntoull(s, a, b, c, d, e) ((s)->cset->strntoull((s),(a),(b),(c),(d),(e)))
#define my_strntod(s, a, b, c, d) ((s)->cset->strntod((s),(a),(b),(c),(d)))
Typedefs
typedef struct unicase_info_st MY_UNICASE_INFO
typedef struct uni_ctype_st MY_UNI_CTYPE
typedef struct my_uni_idx_st MY_UNI_IDX
typedef struct my_collation_handler_st MY_COLLATION_HANDLER
typedef int(* my_charset_conv_mb_wc) (struct charset_info_st *, my_wc_t *, const uchar *, const uchar *)
typedef int(* my_charset_conv_wc_mb) (struct charset_info_st *, my_wc_t, uchar *, uchar *)
typedef size_t(* my_charset_conv_case) (struct charset_info_st *, char *, size_t, char *, size_t)
typedef struct my_charset_handler_st MY_CHARSET_HANDLER
typedef struct charset_info_st CHARSET_INFO
Enumerations
enum my_lex_states {
MY_LEX_START , MY_LEX_CHAR , MY_LEX_IDENT , MY_LEX_IDENT_SEP ,
MY_LEX_IDENT_START , MY_LEX_REAL , MY_LEX_HEX_NUMBER , MY_LEX_BIN_NUMBER ,
MY_LEX_CMP_OP , MY_LEX_LONG_CMP_OP , MY_LEX_STRING , MY_LEX_COMMENT ,
MY_LEX_END , MY_LEX_OPERATOR_OR_IDENT , MY_LEX_NUMBER_IDENT , MY_LEX_INT_OR_REAL ,
MY_LEX_REAL_OR_POINT , MY_LEX_BOOL , MY_LEX_EOL , MY_LEX_ESCAPE ,
MY_LEX_LONG_COMMENT , MY_LEX_END_LONG_COMMENT , MY_LEX_SEMICOLON , MY_LEX_SET_VAR ,
MY_LEX_USER_END , MY_LEX_HOSTNAME , MY_LEX_SKIP , MY_LEX_USER_VARIABLE_DELIMITER ,
MY_LEX_SYSTEM_VAR , MY_LEX_IDENT_OR_KEYWORD , MY_LEX_IDENT_OR_HEX , MY_LEX_IDENT_OR_BIN ,
MY_LEX_IDENT_OR_NCHAR , MY_LEX_STRING_OR_DELIMITER
}
Functions
static my_bool my_cs_have_contractions (CHARSET_INFO *cs)
static my_bool my_cs_can_be_contraction_head (CHARSET_INFO *cs, my_wc_t wc)
static my_bool my_cs_can_be_contraction_tail (CHARSET_INFO *cs, my_wc_t wc)
static uint16 * my_cs_contraction2_weight (CHARSET_INFO *cs, my_wc_t wc1, my_wc_t wc2)
size_t my_strnxfrm_simple (CHARSET_INFO *, uchar *, size_t, const uchar *, size_t)
size_t my_strnxfrmlen_simple (CHARSET_INFO *, size_t)
int my_strnncoll_simple (CHARSET_INFO *, const uchar *, size_t, const uchar *, size_t, my_bool)
int my_strnncollsp_simple (CHARSET_INFO *, const uchar *, size_t, const uchar *, size_t, my_bool diff_if_only_endspace_difference)
void my_hash_sort_simple (CHARSET_INFO *cs, const uchar *key, size_t len, ulong *nr1, ulong *nr2)
size_t my_lengthsp_8bit (CHARSET_INFO *cs, const char *ptr, size_t length)
uint my_instr_simple (struct charset_info_st *, const char *b, size_t b_length, const char *s, size_t s_length, my_match_t *match, uint nmatch)
size_t my_caseup_str_8bit (CHARSET_INFO *, char *)
size_t my_casedn_str_8bit (CHARSET_INFO *, char *)
size_t my_caseup_8bit (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
size_t my_casedn_8bit (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
int my_strcasecmp_8bit (CHARSET_INFO *cs, const char *, const char *)
int my_mb_wc_8bit (CHARSET_INFO *cs, my_wc_t *wc, const uchar *s, const uchar *e)
int my_wc_mb_8bit (CHARSET_INFO *cs, my_wc_t wc, uchar *s, uchar *e)
int my_mb_ctype_8bit (CHARSET_INFO *, int *, const uchar *, const uchar *)
int my_mb_ctype_mb (CHARSET_INFO *, int *, const uchar *, const uchar *)
size_t my_scan_8bit (CHARSET_INFO *cs, const char *b, const char *e, int sq)
size_t my_snprintf_8bit (struct charset_info_st *, char *to, size_t n, const char *fmt,...) ATTRIBUTE_FORMAT(printf
size_t long my_strntol_8bit (CHARSET_INFO *, const char *s, size_t l, int base, char **e, int *err)
ulong my_strntoul_8bit (CHARSET_INFO *, const char *s, size_t l, int base, char **e, int *err)
longlong my_strntoll_8bit (CHARSET_INFO *, const char *s, size_t l, int base, char **e, int *err)
ulonglong my_strntoull_8bit (CHARSET_INFO *, const char *s, size_t l, int base, char **e, int *err)
double my_strntod_8bit (CHARSET_INFO *, char *s, size_t l, char **e, int *err)
size_t my_long10_to_str_8bit (CHARSET_INFO *, char *to, size_t l, int radix, long int val)
size_t my_longlong10_to_str_8bit (CHARSET_INFO *, char *to, size_t l, int radix, longlong val)
longlong my_strtoll10_8bit (CHARSET_INFO *cs, const char *nptr, char **endptr, int *error)
longlong my_strtoll10_ucs2 (CHARSET_INFO *cs, const char *nptr, char **endptr, int *error)
ulonglong my_strntoull10rnd_8bit (CHARSET_INFO *cs, const char *str, size_t length, int unsigned_fl, char **endptr, int *error)
ulonglong my_strntoull10rnd_ucs2 (CHARSET_INFO *cs, const char *str, size_t length, int unsigned_fl, char **endptr, int *error)
void my_fill_8bit (CHARSET_INFO *cs, char *to, size_t l, int fill)
my_bool my_like_range_simple (CHARSET_INFO *cs, const char *ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char *min_str, char *max_str, size_t *min_length, size_t *max_length)
my_bool my_like_range_mb (CHARSET_INFO *cs, const char *ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char *min_str, char *max_str, size_t *min_length, size_t *max_length)
my_bool my_like_range_generic (CHARSET_INFO *cs, const char *ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char *min_str, char *max_str, size_t *min_length, size_t *max_length)
int my_wildcmp_8bit (CHARSET_INFO *, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
int my_wildcmp_bin (CHARSET_INFO *, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
size_t my_numchars_8bit (CHARSET_INFO *, const char *b, const char *e)
size_t my_numcells_8bit (CHARSET_INFO *, const char *b, const char *e)
size_t my_charpos_8bit (CHARSET_INFO *, const char *b, const char *e, size_t pos)
size_t my_well_formed_len_8bit (CHARSET_INFO *, const char *b, const char *e, size_t pos, int *error)
uint my_mbcharlen_8bit (CHARSET_INFO *, uint c)
size_t my_caseup_str_mb (CHARSET_INFO *, char *)
size_t my_casedn_str_mb (CHARSET_INFO *, char *)
size_t my_caseup_mb (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
size_t my_casedn_mb (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
size_t my_caseup_mb_varlen (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
size_t my_casedn_mb_varlen (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
size_t my_caseup_ujis (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
size_t my_casedn_ujis (CHARSET_INFO *, char *src, size_t srclen, char *dst, size_t dstlen)
int my_strcasecmp_mb (CHARSET_INFO *cs, const char *, const char *)
int my_wildcmp_mb (CHARSET_INFO *, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
size_t my_numchars_mb (CHARSET_INFO *, const char *b, const char *e)
size_t my_numcells_mb (CHARSET_INFO *, const char *b, const char *e)
size_t my_charpos_mb (CHARSET_INFO *, const char *b, const char *e, size_t pos)
size_t my_well_formed_len_mb (CHARSET_INFO *, const char *b, const char *e, size_t pos, int *error)
uint my_instr_mb (struct charset_info_st *, const char *b, size_t b_length, const char *s, size_t s_length, my_match_t *match, uint nmatch)
int my_strnncoll_mb_bin (CHARSET_INFO *cs, const uchar *s, size_t slen, const uchar *t, size_t tlen, my_bool t_is_prefix)
int my_strnncollsp_mb_bin (CHARSET_INFO *cs, const uchar *a, size_t a_length, const uchar *b, size_t b_length, my_bool diff_if_only_endspace_difference)
int my_wildcmp_mb_bin (CHARSET_INFO *cs, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
int my_strcasecmp_mb_bin (CHARSET_INFO *cs __attribute__((unused)), const char *s, const char *t)
void my_hash_sort_mb_bin (CHARSET_INFO *cs __attribute__((unused)), const uchar *key, size_t len, ulong *nr1, ulong *nr2)
size_t my_strnxfrm_unicode (CHARSET_INFO *, uchar *dst, size_t dstlen, const uchar *src, size_t srclen)
size_t my_strnxfrm_unicode_full_bin (CHARSET_INFO *, uchar *dst, size_t dstlen, const uchar *src, size_t srclen)
size_t my_strnxfrmlen_unicode_full_bin (CHARSET_INFO *, size_t)
int my_wildcmp_unicode (CHARSET_INFO *cs, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many, MY_UNICASE_INFO **weights)
my_bool my_parse_charset_xml (const char *bug, size_t len, int(*add)(CHARSET_INFO *cs))
char * my_strchr (CHARSET_INFO *cs, const char *str, const char *end, pchar c)
size_t my_strcspn (CHARSET_INFO *cs, const char *str, const char *end, const char *accept)
my_bool my_propagate_simple (CHARSET_INFO *cs, const uchar *str, size_t len)
my_bool my_propagate_complex (CHARSET_INFO *cs, const uchar *str, size_t len)
uint my_string_repertoire (CHARSET_INFO *cs, const char *str, ulong len)
my_bool my_charset_is_ascii_based (CHARSET_INFO *cs)
my_bool my_charset_is_8bit_pure_ascii (CHARSET_INFO *cs)
uint my_charset_repertoire (CHARSET_INFO *cs)
my_bool my_charset_is_ascii_compatible (CHARSET_INFO *cs)
size_t my_vsnprintf_ex (CHARSET_INFO *cs, char *to, size_t n, const char *fmt, va_list ap)
Variables
MY_UNICASE_INFO * my_unicase_default [256]
MY_UNICASE_INFO * my_unicase_turkish [256]
MY_UNI_CTYPE my_uni_ctype [256]
MY_COLLATION_HANDLER my_collation_mb_bin_handler
MY_COLLATION_HANDLER my_collation_8bit_bin_handler
MY_COLLATION_HANDLER my_collation_8bit_simple_ci_handler
MY_COLLATION_HANDLER my_collation_ucs2_uca_handler
MY_CHARSET_HANDLER my_charset_8bit_handler
MY_CHARSET_HANDLER my_charset_ucs2_handler
MYSQL_PLUGIN_IMPORT CHARSET_INFO my_charset_bin
MYSQL_PLUGIN_IMPORT CHARSET_INFO my_charset_latin1
MYSQL_PLUGIN_IMPORT CHARSET_INFO my_charset_filename
CHARSET_INFO my_charset_big5_chinese_ci
CHARSET_INFO my_charset_big5_bin
CHARSET_INFO my_charset_cp932_japanese_ci
CHARSET_INFO my_charset_cp932_bin
CHARSET_INFO my_charset_cp1250_czech_ci
CHARSET_INFO my_charset_eucjpms_japanese_ci
CHARSET_INFO my_charset_eucjpms_bin
CHARSET_INFO my_charset_euckr_korean_ci
CHARSET_INFO my_charset_euckr_bin
CHARSET_INFO my_charset_gb2312_chinese_ci
CHARSET_INFO my_charset_gb2312_bin
CHARSET_INFO my_charset_gbk_chinese_ci
CHARSET_INFO my_charset_gbk_bin
CHARSET_INFO my_charset_latin1_german2_ci
CHARSET_INFO my_charset_latin1_bin
CHARSET_INFO my_charset_latin2_czech_ci
CHARSET_INFO my_charset_sjis_japanese_ci
CHARSET_INFO my_charset_sjis_bin
CHARSET_INFO my_charset_tis620_thai_ci
CHARSET_INFO my_charset_tis620_bin
CHARSET_INFO my_charset_ucs2_general_ci
CHARSET_INFO my_charset_ucs2_bin
CHARSET_INFO my_charset_ucs2_unicode_ci
CHARSET_INFO my_charset_ujis_japanese_ci
CHARSET_INFO my_charset_ujis_bin
CHARSET_INFO my_charset_utf16_bin
CHARSET_INFO my_charset_utf16_general_ci
CHARSET_INFO my_charset_utf16_unicode_ci
CHARSET_INFO my_charset_utf32_bin
CHARSET_INFO my_charset_utf32_general_ci
CHARSET_INFO my_charset_utf32_unicode_ci
CHARSET_INFO my_charset_utf8_general_ci
CHARSET_INFO my_charset_utf8_unicode_ci
CHARSET_INFO my_charset_utf8_bin
CHARSET_INFO my_charset_utf8mb4_bin
CHARSET_INFO my_charset_utf8mb4_general_ci
CHARSET_INFO my_charset_utf8mb4_unicode_ci
Macro Definition Documentation
_MY_B
#define _MY_B 0100 /* Blank */
Definition at line 595 of file m_ctype.h.
_MY_CTR
#define _MY_CTR 040 /* Control character */
Definition at line 594 of file m_ctype.h.
_MY_L
#define _MY_L 02 /* Lower case */
Definition at line 590 of file m_ctype.h.
_MY_NMR
#define _MY_NMR 04 /* Numeral (digit) */
Definition at line 591 of file m_ctype.h.
_MY_PNT
#define _MY_PNT 020 /* Punctuation */
Definition at line 593 of file m_ctype.h.
_MY_SPC
#define _MY_SPC 010 /* Spacing character */
Definition at line 592 of file m_ctype.h.
_MY_U
#define _MY_U 01 /* Upper case */
Definition at line 589 of file m_ctype.h.
_MY_X
#define _MY_X 0200 /* heXadecimal digit */
Definition at line 596 of file m_ctype.h.
CHARSET_DIR
#define CHARSET_DIR "charsets/"
Definition at line 37 of file m_ctype.h.
CHARSET_INFO_DEFINED
#define CHARSET_INFO_DEFINED
Definition at line 272 of file m_ctype.h.
ILLEGAL_CHARSET_INFO_NUMBER
#define ILLEGAL_CHARSET_INFO_NUMBER (~0U)
Definition at line 310 of file m_ctype.h.
MB2
#define MB2 (x) (x)
Definition at line 53 of file m_ctype.h.
my_binary_compare
#define my_binary_compare (s) ((s)->state & MY_CS_BINSORT)
Definition at line 621 of file m_ctype.h.
my_casedn_str
#define my_casedn_str (s, a) ((s)->cset->casedn_str((s), (a)))
Definition at line 641 of file m_ctype.h.
my_caseup_str
#define my_caseup_str (s, a) ((s)->cset->caseup_str((s), (a)))
Definition at line 640 of file m_ctype.h.
my_charpos
#define my_charpos (cs, b, e, num) (cs)->cset->charpos((cs), (const char*) (b), (const char *)(e), (num))
Definition at line 629 of file m_ctype.h.
MY_CHARSET_UNDEFINED
#define MY_CHARSET_UNDEFINED 0
Definition at line 110 of file m_ctype.h.
MY_CS_AVAILABLE
#define MY_CS_AVAILABLE 512 /* If either compiled-in or loaded*/
Definition at line 104 of file m_ctype.h.
MY_CS_BINSORT
#define MY_CS_BINSORT 16 /* if binary sort order */
Definition at line 99 of file m_ctype.h.
MY_CS_COMPILED
#define MY_CS_COMPILED 1 /* compiled-in sets */
Definition at line 95 of file m_ctype.h.
MY_CS_CONFIG
#define MY_CS_CONFIG 2 /* sets that have a *.conf file */
Definition at line 96 of file m_ctype.h.
MY_CS_CSSORT
#define MY_CS_CSSORT 1024 /* if case sensitive sort order */
Definition at line 105 of file m_ctype.h.
MY_CS_CTYPE_TABLE_SIZE
#define MY_CS_CTYPE_TABLE_SIZE 257
Definition at line 31 of file m_ctype.h.
MY_CS_HIDDEN
#define MY_CS_HIDDEN 2048 /* don't display in SHOW */
Definition at line 106 of file m_ctype.h.
MY_CS_ILSEQ
#define MY_CS_ILSEQ 0 /* Wrong by sequence: wb_wc */
Definition at line 79 of file m_ctype.h.
MY_CS_ILUNI
#define MY_CS_ILUNI 0 /* Cannot encode Unicode to charset: wc_mb */
Definition at line 80 of file m_ctype.h.
MY_CS_INDEX
#define MY_CS_INDEX 4 /* sets listed in the Index file */
Definition at line 97 of file m_ctype.h.
MY_CS_LOADED
#define MY_CS_LOADED 8 /* sets that are currently loaded */
Definition at line 98 of file m_ctype.h.
MY_CS_NAME_SIZE
#define MY_CS_NAME_SIZE 32
Definition at line 30 of file m_ctype.h.
MY_CS_NONASCII
#define MY_CS_NONASCII 8192 /* if not ASCII-compatible */
Definition at line 108 of file m_ctype.h.
MY_CS_PRIMARY
#define MY_CS_PRIMARY 32 /* if primary collation */
Definition at line 100 of file m_ctype.h.
MY_CS_PUREASCII
#define MY_CS_PUREASCII 4096 /* if a charset is pure ascii */
Definition at line 107 of file m_ctype.h.
MY_CS_READY
#define MY_CS_READY 256 /* if a charset is initialized */
Definition at line 103 of file m_ctype.h.
MY_CS_REPLACEMENT_CHARACTER
#define MY_CS_REPLACEMENT_CHARACTER 0xFFFD
Definition at line 41 of file m_ctype.h.
MY_CS_SORT_ORDER_TABLE_SIZE
#define MY_CS_SORT_ORDER_TABLE_SIZE 256
Definition at line 34 of file m_ctype.h.
MY_CS_STRNXFRM
#define MY_CS_STRNXFRM 64 /* if strnxfrm is used for sort */
Definition at line 101 of file m_ctype.h.
MY_CS_TO_LOWER_TABLE_SIZE
#define MY_CS_TO_LOWER_TABLE_SIZE 256
Definition at line 32 of file m_ctype.h.
MY_CS_TO_UNI_TABLE_SIZE
#define MY_CS_TO_UNI_TABLE_SIZE 256
Definition at line 35 of file m_ctype.h.
MY_CS_TO_UPPER_TABLE_SIZE
#define MY_CS_TO_UPPER_TABLE_SIZE 256
Definition at line 33 of file m_ctype.h.
MY_CS_TOOSMALL
#define MY_CS_TOOSMALL -101 /* Need at least one byte: wc_mb and mb_wc */
Definition at line 81 of file m_ctype.h.
MY_CS_TOOSMALL2
#define MY_CS_TOOSMALL2 -102 /* Need at least two bytes: wc_mb and mb_wc */
Definition at line 82 of file m_ctype.h.
MY_CS_TOOSMALL3
#define MY_CS_TOOSMALL3 -103 /* Need at least three bytes: wc_mb and mb_wc */
Definition at line 83 of file m_ctype.h.
MY_CS_TOOSMALL4
#define MY_CS_TOOSMALL4 -104 /* Need at least 4 bytes: wc_mb and mb_wc */
Definition at line 85 of file m_ctype.h.
MY_CS_TOOSMALL5
#define MY_CS_TOOSMALL5 -105 /* Need at least 5 bytes: wc_mb and mb_wc */
Definition at line 86 of file m_ctype.h.
MY_CS_TOOSMALL6
#define MY_CS_TOOSMALL6 -106 /* Need at least 6 bytes: wc_mb and mb_wc */
Definition at line 87 of file m_ctype.h.
MY_CS_TOOSMALLN
#define MY_CS_TOOSMALLN (n) (-100-(n))
Definition at line 89 of file m_ctype.h.
MY_CS_UNICODE
#define MY_CS_UNICODE 128 /* is a charset is BMP Unicode */
Definition at line 102 of file m_ctype.h.
MY_CS_UNICODE_SUPPLEMENT
#define MY_CS_UNICODE_SUPPLEMENT 16384 /* Non-BMP Unicode characters */
Definition at line 109 of file m_ctype.h.
my_isalnum
#define my_isalnum (s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_U | _MY_L | _MY_NMR))
Definition at line 610 of file m_ctype.h.
my_isalpha
#define my_isalpha (s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_U | _MY_L))
Definition at line 605 of file m_ctype.h.
my_isascii
#define my_isascii (c) (!((c) & ~0177))
Definition at line 599 of file m_ctype.h.
my_iscntrl
#define my_iscntrl (s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_CTR)
Definition at line 615 of file m_ctype.h.
my_isdigit
#define my_isdigit (s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_NMR)
Definition at line 608 of file m_ctype.h.
my_isgraph
#define my_isgraph (s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_PNT | _MY_U | _MY_L | _MY_NMR))
Definition at line 614 of file m_ctype.h.
my_islower
#define my_islower (s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_L)
Definition at line 607 of file m_ctype.h.
my_ismbchar
#define my_ismbchar (s, a, b) ((s)->cset->ismbchar((s), (a), (b)))
Definition at line 633 of file m_ctype.h.
my_isprint
#define my_isprint (s, c) (((s)->ctype+1)[(uchar) (c)] & (_MY_PNT | _MY_U | _MY_L | _MY_NMR | _MY_B))
Definition at line 613 of file m_ctype.h.
my_ispunct
#define my_ispunct (s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_PNT)
Definition at line 612 of file m_ctype.h.
my_isspace
#define my_isspace (s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_SPC)
Definition at line 611 of file m_ctype.h.
my_isupper
#define my_isupper (s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_U)
Definition at line 606 of file m_ctype.h.
my_isvar
#define my_isvar (s, c) (my_isalnum(s,c) || (c) == '_')
Definition at line 618 of file m_ctype.h.
my_isvar_start
#define my_isvar_start (s, c) (my_isalpha(s,c) || (c) == '_')
Definition at line 619 of file m_ctype.h.
my_isxdigit
#define my_isxdigit (s, c) (((s)->ctype+1)[(uchar) (c)] & _MY_X)
Definition at line 609 of file m_ctype.h.
my_like_range
#define my_like_range (s, a, b, c, d, e, f, g, h, i, j) ((s)->coll->like_range((s), (a), (b), (c), (d), (e), (f), (g), (h), (i), (j)))
Definition at line 625 of file m_ctype.h.
my_mbcharlen
#define my_mbcharlen (s, a) 1
Definition at line 637 of file m_ctype.h.
MY_PUT_MB2
#define MY_PUT_MB2 (s, code) { (s)[0]= code >> 8; (s)[1]= code & 0xFF; }
Definition at line 54 of file m_ctype.h.
MY_REPERTOIRE_ASCII
#define MY_REPERTOIRE_ASCII 1 /* Pure ASCII U+0000..U+007F */
Definition at line 113 of file m_ctype.h.
MY_REPERTOIRE_EXTENDED
#define MY_REPERTOIRE_EXTENDED 2 /* Extended characters: U+0080..U+FFFF */
Definition at line 114 of file m_ctype.h.
MY_REPERTOIRE_UNICODE30
#define MY_REPERTOIRE_UNICODE30 3 /* ASCII | EXTENDED: U+0000..U+FFFF */
Definition at line 115 of file m_ctype.h.
MY_SEQ_INTTAIL
#define MY_SEQ_INTTAIL 1
Definition at line 91 of file m_ctype.h.
MY_SEQ_SPACES
#define MY_SEQ_SPACES 2
Definition at line 92 of file m_ctype.h.
my_strcasecmp
#define my_strcasecmp (s, a, b) ((s)->coll->strcasecmp((s), (a), (b)))
Definition at line 628 of file m_ctype.h.
my_strnncoll
#define my_strnncoll (s, a, b, c, d) ((s)->coll->strnncoll((s), (a), (b), (c), (d), 0))
Definition at line 624 of file m_ctype.h.
my_strntod
#define my_strntod (s, a, b, c, d) ((s)->cset->strntod((s),(a),(b),(c),(d)))
Definition at line 646 of file m_ctype.h.
my_strntol
#define my_strntol (s, a, b, c, d, e) ((s)->cset->strntol((s),(a),(b),(c),(d),(e)))
Definition at line 642 of file m_ctype.h.
my_strntoll
#define my_strntoll (s, a, b, c, d, e) ((s)->cset->strntoll((s),(a),(b),(c),(d),(e)))
Definition at line 644 of file m_ctype.h.
my_strntoul
#define my_strntoul (s, a, b, c, d, e) ((s)->cset->strntoul((s),(a),(b),(c),(d),(e)))
Definition at line 643 of file m_ctype.h.
my_strntoull
#define my_strntoull (s, a, b, c, d, e) ((s)->cset->strntoull((s),(a),(b),(c),(d),(e)))
Definition at line 645 of file m_ctype.h.
my_strnxfrm
#define my_strnxfrm (s, a, b, c, d) ((s)->coll->strnxfrm((s), (a), (b), (c), (d)))
Definition at line 623 of file m_ctype.h.
my_toascii
#define my_toascii (c) ((c) & 0177)
Definition at line 600 of file m_ctype.h.
my_tocntrl
#define my_tocntrl (c) ((c) & 31)
Definition at line 601 of file m_ctype.h.
my_tolower
#define my_tolower (s, c) (char) ((s)->to_lower[(uchar) (c)])
Definition at line 604 of file m_ctype.h.
my_toprint
#define my_toprint (c) ((c) | 64)
Definition at line 602 of file m_ctype.h.
my_toupper
#define my_toupper (s, c) (char) ((s)->to_upper[(uchar) (c)])
Definition at line 603 of file m_ctype.h.
MY_UTF8MB3
#define MY_UTF8MB3 "utf8"
Definition at line 355 of file m_ctype.h.
MY_UTF8MB4
#define MY_UTF8MB4 "utf8mb4"
Definition at line 356 of file m_ctype.h.
my_wc_t
#define my_wc_t ulong
Definition at line 39 of file m_ctype.h.
my_wildcmp
#define my_wildcmp (cs, s, se, w, we, e, o, m) ((cs)->coll->wildcmp((cs),(s),(se),(w),(we),(e),(o),(m)))
Definition at line 627 of file m_ctype.h.
use_mb
#define use_mb (s) ((s)->cset->ismbchar != NULL)
Definition at line 632 of file m_ctype.h.
use_strnxfrm
#define use_strnxfrm (s) ((s)->state & MY_CS_STRNXFRM)
Definition at line 622 of file m_ctype.h.
Typedef Documentation
CHARSET_INFO
typedef struct charset_info_st CHARSET_INFO
my_charset_conv_case
typedef size_t(* my_charset_conv_case) (struct charset_info_st *, char *, size_t, char *, size_t)
Definition at line 197 of file m_ctype.h.
my_charset_conv_mb_wc
typedef int(* my_charset_conv_mb_wc) (struct charset_info_st *, my_wc_t *, const uchar *, const uchar *)
Definition at line 193 of file m_ctype.h.
my_charset_conv_wc_mb
typedef int(* my_charset_conv_wc_mb) (struct charset_info_st *, my_wc_t, uchar *, uchar *)
Definition at line 195 of file m_ctype.h.
MY_CHARSET_HANDLER
typedef struct my_charset_handler_st MY_CHARSET_HANDLER
MY_COLLATION_HANDLER
typedef struct my_collation_handler_st MY_COLLATION_HANDLER
MY_UNI_CTYPE
typedef struct uni_ctype_st MY_UNI_CTYPE
MY_UNI_IDX
typedef struct my_uni_idx_st MY_UNI_IDX
MY_UNICASE_INFO
typedef struct unicase_info_st MY_UNICASE_INFO
Enumeration Type Documentation
my_lex_states
enum my_lex_states
Enumerator
MY_LEX_START
MY_LEX_CHAR
MY_LEX_IDENT
MY_LEX_IDENT_SEP
MY_LEX_IDENT_START
MY_LEX_REAL
MY_LEX_HEX_NUMBER
MY_LEX_BIN_NUMBER
MY_LEX_CMP_OP
MY_LEX_LONG_CMP_OP
MY_LEX_STRING
MY_LEX_COMMENT
MY_LEX_END
MY_LEX_OPERATOR_OR_IDENT
MY_LEX_NUMBER_IDENT
MY_LEX_INT_OR_REAL
MY_LEX_REAL_OR_POINT
MY_LEX_BOOL
MY_LEX_EOL
MY_LEX_ESCAPE
MY_LEX_LONG_COMMENT
MY_LEX_END_LONG_COMMENT
MY_LEX_SEMICOLON
MY_LEX_SET_VAR
MY_LEX_USER_END
MY_LEX_HOSTNAME
MY_LEX_SKIP
MY_LEX_USER_VARIABLE_DELIMITER
MY_LEX_SYSTEM_VAR
MY_LEX_IDENT_OR_KEYWORD
MY_LEX_IDENT_OR_HEX
MY_LEX_IDENT_OR_BIN
MY_LEX_IDENT_OR_NCHAR
MY_LEX_STRING_OR_DELIMITER
Definition at line 131 of file m_ctype.h.
 {
   MY_LEX_START, MY_LEX_CHAR, MY_LEX_IDENT,
   MY_LEX_IDENT_SEP, MY_LEX_IDENT_START,
   MY_LEX_REAL, MY_LEX_HEX_NUMBER, MY_LEX_BIN_NUMBER,
   MY_LEX_CMP_OP, MY_LEX_LONG_CMP_OP, MY_LEX_STRING, MY_LEX_COMMENT, MY_LEX_END,
   MY_LEX_OPERATOR_OR_IDENT, MY_LEX_NUMBER_IDENT, MY_LEX_INT_OR_REAL,
   MY_LEX_REAL_OR_POINT, MY_LEX_BOOL, MY_LEX_EOL, MY_LEX_ESCAPE,
   MY_LEX_LONG_COMMENT, MY_LEX_END_LONG_COMMENT, MY_LEX_SEMICOLON,
   MY_LEX_SET_VAR, MY_LEX_USER_END, MY_LEX_HOSTNAME, MY_LEX_SKIP,
   MY_LEX_USER_VARIABLE_DELIMITER, MY_LEX_SYSTEM_VAR,
   MY_LEX_IDENT_OR_KEYWORD,
   MY_LEX_IDENT_OR_HEX, MY_LEX_IDENT_OR_BIN, MY_LEX_IDENT_OR_NCHAR,
   MY_LEX_STRING_OR_DELIMITER
 };
Function Documentation
my_casedn_8bit()
size_t my_casedn_8bit (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_casedn_mb()
size_t my_casedn_mb (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_casedn_mb_varlen()
size_t my_casedn_mb_varlen (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_casedn_str_8bit()
size_t my_casedn_str_8bit (CHARSET_INFO * cs, char * str)
Definition at line 206 of file ctype-simple.c.
 {
   register uchar *map= cs->to_lower;
   char *str_orig= str;
   while ((*str= (char) map[(uchar) *str]) != 0)
     str++;
   return (size_t) (str - str_orig);
 }
References charset_info_st::to_lower.
my_casedn_str_mb()
size_t my_casedn_str_mb (CHARSET_INFO * , char *)
my_casedn_ujis()
size_t my_casedn_ujis (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_caseup_8bit()
size_t my_caseup_8bit (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_caseup_mb()
size_t my_caseup_mb (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_caseup_mb_varlen()
size_t my_caseup_mb_varlen (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_caseup_str_8bit()
size_t my_caseup_str_8bit (CHARSET_INFO * cs, char * str)
Definition at line 196 of file ctype-simple.c.
 {
   register uchar *map= cs->to_upper;
   char *str_orig= str;
   while ((*str= (char) map[(uchar) *str]) != 0)
     str++;
   return (size_t) (str - str_orig);
 }
References charset_info_st::to_upper.
my_caseup_str_mb()
size_t my_caseup_str_mb (CHARSET_INFO * , char *)
my_caseup_ujis()
size_t my_caseup_ujis (CHARSET_INFO * , char * src, size_t srclen, char * dst, size_t dstlen)
my_charpos_8bit()
size_t my_charpos_8bit (CHARSET_INFO * , const char * b, const char * e, size_t pos)
my_charpos_mb()
size_t my_charpos_mb (CHARSET_INFO * , const char * b, const char * e, size_t pos)
my_charset_is_8bit_pure_ascii()
my_bool my_charset_is_8bit_pure_ascii (CHARSET_INFO * cs)
Definition at line 399 of file ctype.c.
 {
   size_t code;
   if (!cs->tab_to_uni)
     return 0;
   for (code= 0; code < 256; code++)
   {
     if (cs->tab_to_uni[code] > 0x7F)
       return 0;
   }
   return 1;
 }
References my_cs_file_info::cs, and charset_info_st::tab_to_uni.
Referenced by add_collation().
my_charset_is_ascii_based()
my_bool my_charset_is_ascii_based (CHARSET_INFO * cs)
Definition at line 383 of file ctype.c.
 {
   return
     (cs->mbmaxlen == 1 && cs->tab_to_uni && cs->tab_to_uni['{'] == '{') ||
     (cs->mbminlen == 1 && cs->mbmaxlen > 1);
 }
References my_cs_file_info::cs, charset_info_st::mbmaxlen, charset_info_st::mbminlen, and charset_info_st::tab_to_uni.
my_charset_is_ascii_compatible()
my_bool my_charset_is_ascii_compatible (CHARSET_INFO * cs)
Definition at line 419 of file ctype.c.
 {
   uint i;
   if (!cs->tab_to_uni)
     return 1;
   for (i= 0; i < 128; i++)
   {
     if (cs->tab_to_uni[i] != i)
       return 0;
   }
   return 1;
 }
References my_cs_file_info::cs, and charset_info_st::tab_to_uni.
Referenced by add_collation().
my_charset_repertoire()
uint my_charset_repertoire (CHARSET_INFO * cs)
Definition at line 349 of file ctype.c.
 {
   return cs->state & MY_CS_PUREASCII ?
     MY_REPERTOIRE_ASCII : MY_REPERTOIRE_UNICODE30;
 }
References my_cs_file_info::cs, MY_CS_PUREASCII, MY_REPERTOIRE_ASCII, MY_REPERTOIRE_UNICODE30, and charset_info_st::state.
my_cs_can_be_contraction_head()
static my_bool my_cs_can_be_contraction_head (CHARSET_INFO * cs, my_wc_t wc) inline static
Definition at line 367 of file m_ctype.h.
 {
   return ((const char *)cs->contractions)[0x40*0x40 + (wc & 0xFF)];
 }
References charset_info_st::contractions.
my_cs_can_be_contraction_tail()
static my_bool my_cs_can_be_contraction_tail (CHARSET_INFO * cs, my_wc_t wc) inline static
Definition at line 373 of file m_ctype.h.
 {
   return ((const char *)cs->contractions)[0x40*0x40 + (wc & 0xFF)];
 }
References charset_info_st::contractions.
my_cs_contraction2_weight()
static uint16* my_cs_contraction2_weight (CHARSET_INFO * cs, my_wc_t wc1, my_wc_t wc2) inline static
Definition at line 379 of file m_ctype.h.
 {
   return &cs->contractions[(wc1 - 0x40) * 0x40 + wc2 - 0x40];
 }
References charset_info_st::contractions.
my_cs_have_contractions()
static my_bool my_cs_have_contractions (CHARSET_INFO * cs) inline static
Definition at line 361 of file m_ctype.h.
 {
   return cs->contractions != NULL;
 }
References charset_info_st::contractions, and NULL.
my_fill_8bit()
void my_fill_8bit (CHARSET_INFO * cs, char * to, size_t l, int fill)
my_hash_sort_mb_bin()
void my_hash_sort_mb_bin (CHARSET_INFO *cs __attribute__(unused), const uchar * key, size_t len, ulong * nr1, ulong * nr2)
my_hash_sort_simple()
void my_hash_sort_simple (CHARSET_INFO * cs, const uchar * key, size_t len, ulong * nr1, ulong * nr2)
Definition at line 302 of file ctype-simple.c.
 {
   register uchar *sort_order=cs->sort_order;
   const uchar *end;
   /*
     Remove end space. We have to do this to be able to compare
     'A ' and 'A' as identical
   */
   end= skip_trailing_space(key, len);
   for (; key < (uchar*) end ; key++)
   {
     nr1[0]^=(ulong) ((((uint) nr1[0] & 63)+nr2[0]) *
          ((uint) sort_order[(uint) *key])) + (nr1[0] << 8);
     nr2[0]+=3;
   }
 }
References skip_trailing_space(), and charset_info_st::sort_order.
my_instr_mb()
uint my_instr_mb (struct charset_info_st * , const char * b, size_t b_length, const char * s, size_t s_length, my_match_t * match, uint nmatch)
my_instr_simple()
uint my_instr_simple (struct charset_info_st * cs, const char * b, size_t b_length, const char * s, size_t s_length, my_match_t * match, uint nmatch)
Definition at line 1065 of file ctype-simple.c.
 {
   register const uchar *str, *search, *end, *search_end;
   if (s_length <= b_length)
   {
     if (!s_length)
     {
       if (nmatch)
       {
         match->beg= 0;
         match->end= 0;
         match->mb_len= 0;
       }
       return 1;     /* Empty string is always found */
     }
     str= (const uchar*) b;
     search= (const uchar*) s;
     end= (const uchar*) b+b_length-s_length+1;
     search_end= (const uchar*) s + s_length;
 skip:
     while (str != end)
     {
       if (cs->sort_order[*str++] == cs->sort_order[*search])
       {
     register const uchar *i,*j;
     i= str;
     j= search+1;
     while (j != search_end)
       if (cs->sort_order[*i++] != cs->sort_order[*j++])
             goto skip;
     if (nmatch > 0)
     {
       match[0].beg= 0;
       match[0].end= (size_t) (str- (const uchar*)b-1);
       match[0].mb_len= match[0].end;
       if (nmatch > 1)
       {
         match[1].beg= match[0].end;
         match[1].end= match[0].end+s_length;
         match[1].mb_len= match[1].end-match[1].beg;
       }
     }
     return 2;
       }
     }
   }
   return 0;
 }
References b, my_match_t::beg, my_match_t::end, my_match_t::mb_len, and charset_info_st::sort_order.
my_lengthsp_8bit()
size_t my_lengthsp_8bit (CHARSET_INFO * cs, const char * ptr, size_t length)
my_like_range_generic()
my_bool my_like_range_generic (CHARSET_INFO * cs, const char * ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char * min_str, char * max_str, size_t * min_length, size_t * max_length)
my_like_range_mb()
my_bool my_like_range_mb (CHARSET_INFO * cs, const char * ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char * min_str, char * max_str, size_t * min_length, size_t * max_length)
my_like_range_simple()
my_bool my_like_range_simple (CHARSET_INFO * cs, const char * ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char * min_str, char * max_str, size_t * min_length, size_t * max_length)
Definition at line 940 of file ctype-simple.c.
 {
   const char *end= ptr + ptr_length;
   char *min_org=min_str;
   char *min_end=min_str+res_length;
   size_t charlen= res_length / cs->mbmaxlen;
   for (; ptr != end && min_str != min_end && charlen > 0 ; ptr++, charlen--)
   {
     if (*ptr == escape && ptr+1 != end)
     {
       ptr++;                    /* Skip escape */
       *min_str++= *max_str++ = *ptr;
       continue;
     }
     if (*ptr == w_one)              /* '_' in SQL */
     {
       *min_str++='\0';              /* This should be min char */
       *max_str++= (char) cs->max_sort_char;
       continue;
     }
     if (*ptr == w_many)             /* '%' in SQL */
     {
       /* Calculate length of keys */
       *min_length= ((cs->state & MY_CS_BINSORT) ?
                     (size_t) (min_str - min_org) :
                     res_length);
       *max_length= res_length;
       do
       {
     *min_str++= 0;
     *max_str++= (char) cs->max_sort_char;
       } while (min_str != min_end);
       return 0;
     }
     *min_str++= *max_str++ = *ptr;
   }
  *min_length= *max_length = (size_t) (min_str - min_org);
   while (min_str != min_end)
     *min_str++= *max_str++ = ' ';      /* Because if key compression */
   return 0;
 }
References G3D::escape(), charset_info_st::max_sort_char, charset_info_st::mbmaxlen, MY_CS_BINSORT, ptr(), and charset_info_st::state.
my_long10_to_str_8bit()
size_t my_long10_to_str_8bit (CHARSET_INFO * , char * to, size_t l, int radix, long int val)
my_longlong10_to_str_8bit()
size_t my_longlong10_to_str_8bit (CHARSET_INFO * , char * to, size_t l, int radix, longlong val)
my_mb_ctype_8bit()
int my_mb_ctype_8bit (CHARSET_INFO * cs, int * ctype, const uchar * s, const uchar * e)
Definition at line 1267 of file ctype-simple.c.
 {
   if (s >= e)
   {
     *ctype= 0;
     return MY_CS_TOOSMALL;
   }
   *ctype= cs->ctype[*s + 1];
   return 1;
 }
References charset_info_st::ctype, and MY_CS_TOOSMALL.
my_mb_ctype_mb()
int my_mb_ctype_mb (CHARSET_INFO * , int * , const uchar * , const uchar *)
my_mb_wc_8bit()
int my_mb_wc_8bit (CHARSET_INFO * cs, my_wc_t * wc, const uchar * s, const uchar * e)
my_mbcharlen_8bit()
uint my_mbcharlen_8bit (CHARSET_INFO * , uint c)
my_numcells_8bit()
size_t my_numcells_8bit (CHARSET_INFO * , const char * b, const char * e)
my_numcells_mb()
size_t my_numcells_mb (CHARSET_INFO * , const char * b, const char * e)
my_numchars_8bit()
size_t my_numchars_8bit (CHARSET_INFO * , const char * b, const char * e)
my_numchars_mb()
size_t my_numchars_mb (CHARSET_INFO * , const char * b, const char * e)
my_parse_charset_xml()
my_bool my_parse_charset_xml (const char * bug, size_t len, int(*)(CHARSET_INFO *cs) add)
Definition at line 296 of file ctype.c.
 {
   MY_XML_PARSER p;
   struct my_cs_file_info i;
   my_bool rc;
   my_xml_parser_create(&p);
   my_xml_set_enter_handler(&p,cs_enter);
   my_xml_set_value_handler(&p,cs_value);
   my_xml_set_leave_handler(&p,cs_leave);
   i.add_collation= add_collation;
   my_xml_set_user_data(&p,(void*)&i);
   rc= (my_xml_parse(&p,buf,len) == MY_XML_OK) ? FALSE : TRUE;
   my_xml_parser_free(&p);
   return rc;
 }
References add_collation(), my_cs_file_info::add_collation, cs_enter(), cs_leave(), cs_value(), FALSE, MY_XML_OK, my_xml_parse(), my_xml_parser_create(), my_xml_parser_free(), my_xml_set_enter_handler(), my_xml_set_leave_handler(), my_xml_set_user_data(), my_xml_set_value_handler(), and TRUE.
Referenced by my_read_charset_file().
my_propagate_complex()
my_bool my_propagate_complex (CHARSET_INFO * cs, const uchar * str, size_t len)
my_propagate_simple()
my_bool my_propagate_simple (CHARSET_INFO * cs, const uchar * str, size_t len)
my_scan_8bit()
size_t my_scan_8bit (CHARSET_INFO * cs, const char * b, const char * e, int sq)
Definition at line 990 of file ctype-simple.c.
 {
   const char *str0= str;
   switch (sq)
   {
   case MY_SEQ_INTTAIL:
     if (*str == '.')
     {
       for(str++ ; str != end && *str == '0' ; str++);
       return (size_t) (str - str0);
     }
     return 0;
   case MY_SEQ_SPACES:
     for ( ; str < end ; str++)
     {
       if (!my_isspace(cs,*str))
         break;
     }
     return (size_t) (str - str0);
   default:
     return 0;
   }
 }
References my_isspace, MY_SEQ_INTTAIL, and MY_SEQ_SPACES.
my_snprintf_8bit()
size_t my_snprintf_8bit (struct charset_info_st * , char * to, size_t n, const char * fmt, ...)
my_strcasecmp_8bit()
int my_strcasecmp_8bit (CHARSET_INFO * cs, const char * s, const char * t)
Definition at line 241 of file ctype-simple.c.
 {
   register uchar *map=cs->to_upper;
   while (map[(uchar) *s] == map[(uchar) *t++])
     if (!*s++) return 0;
   return ((int) map[(uchar) s[0]] - (int) map[(uchar) t[-1]]);
 }
References charset_info_st::to_upper.
my_strcasecmp_mb()
int my_strcasecmp_mb (CHARSET_INFO * cs, const char * , const char *)
my_strcasecmp_mb_bin()
int my_strcasecmp_mb_bin (CHARSET_INFO *cs __attribute__(unused), const char * s, const char * t)
my_strchr()
char* my_strchr (CHARSET_INFO * cs, const char * str, const char * end, pchar c)
Definition at line 63 of file my_strchr.c.
 {
   uint mbl;
   while (str < end)
   {
     mbl= my_mbcharlen(cs, *(uchar *)str);
     if (mbl < 2)
     {
       if (*str == c)
         return((char *)str);
       str++;
     }
     else
       str+= mbl;
   }
   return(0);
 }
References mpq::c, and my_mbcharlen.
my_strcspn()
size_t my_strcspn (CHARSET_INFO * cs, const char * str, const char * str_end, const char * reject)
Calculate the length of the initial segment of 'str' which consists entirely of characters not in 'reject'.
Note
The reject string points to single-byte characters so it is only possible to find the first occurrence of a single-byte character. Multi-byte characters in 'str' are treated as not matching any character in the reject string.
Todo:
should be moved to CHARSET_INFO if it's going to be called frequently.
Definition at line 100 of file my_strchr.c.
 {
   SCAN_STRING(cs, str, str_end, reject, strlen(reject), EQU);
 }
References EQU, and SCAN_STRING.
my_string_repertoire()
uint my_string_repertoire (CHARSET_INFO * cs, const char * str, ulong len)
Definition at line 319 of file ctype.c.
 {
   const char *strend= str + length;
   if (cs->mbminlen == 1)
   {
     for ( ; str < strend; str++)
     {
       if (((uchar) *str) > 0x7F)
         return MY_REPERTOIRE_UNICODE30;
     }
   }
   else
   {
     my_wc_t wc;
     int chlen;
     for (;
          (chlen= cs->cset->mb_wc(cs, &wc, (uchar*) str, (uchar*) strend)) > 0;
          str+= chlen)
     {
       if (wc > 0x7F)
         return MY_REPERTOIRE_UNICODE30;
     }
   }
   return MY_REPERTOIRE_ASCII;
 }
References my_cs_file_info::cs, charset_info_st::cset, G3D::length(), my_charset_handler_st::mb_wc, charset_info_st::mbminlen, MY_REPERTOIRE_ASCII, MY_REPERTOIRE_UNICODE30, my_wc_t, and strend().
my_strnncoll_mb_bin()
int my_strnncoll_mb_bin (CHARSET_INFO * cs, const uchar * s, size_t slen, const uchar * t, size_t tlen, my_bool t_is_prefix)
my_strnncoll_simple()
int my_strnncoll_simple (CHARSET_INFO * cs, const uchar * s, size_t slen, const uchar * t, size_t tlen, my_bool t_is_prefix)
Definition at line 99 of file ctype-simple.c.
 {
   size_t len = ( slen > tlen ) ? tlen : slen;
   uchar *map= cs->sort_order;
   if (t_is_prefix && slen > tlen)
     slen=tlen;
   while (len--)
   {
     if (map[*s++] != map[*t++])
       return ((int) map[s[-1]] - (int) map[t[-1]]);
   }
   /*
     We can't use (slen - tlen) here as the result may be outside of the
     precision of a signed int
   */
   return slen > tlen ? 1 : slen < tlen ? -1 : 0 ;
 }
References charset_info_st::sort_order.
my_strnncollsp_mb_bin()
int my_strnncollsp_mb_bin (CHARSET_INFO * cs, const uchar * a, size_t a_length, const uchar * b, size_t b_length, my_bool diff_if_only_endspace_difference)
my_strnncollsp_simple()
int my_strnncollsp_simple (CHARSET_INFO * cs, const uchar * a, size_t a_length, const uchar * b, size_t b_length, my_bool diff_if_only_endspace_difference)
Definition at line 150 of file ctype-simple.c.
 {
   const uchar *map= cs->sort_order, *end;
   size_t length;
   int res;
 #ifndef VARCHAR_WITH_DIFF_ENDSPACE_ARE_DIFFERENT_FOR_UNIQUE
   diff_if_only_endspace_difference= 0;
 #endif
   end= a + (length= min(a_length, b_length));
   while (a < end)
   {
     if (map[*a++] != map[*b++])
       return ((int) map[a[-1]] - (int) map[b[-1]]);
   }
   res= 0;
   if (a_length != b_length)
   {
     int swap= 1;
     if (diff_if_only_endspace_difference)
       res= 1;                                   /* Assume 'a' is bigger */
     /*
       Check the next not space character of the longer key. If it's < ' ',
       then it's smaller than the other key.
     */
     if (a_length < b_length)
     {
       /* put shorter key in s */
       a_length= b_length;
       a= b;
       swap= -1;                                 /* swap sign of result */
       res= -res;
     }
     for (end= a + a_length-length; a < end ; a++)
     {
       if (map[*a] != map[' '])
     return (map[*a] < map[' ']) ? -swap : swap;
     }
   }
   return res;
 }
References mpq::a, b, G3D::length(), min, charset_info_st::sort_order, and swap().
my_strntod_8bit()
double my_strntod_8bit (CHARSET_INFO * , char * s, size_t l, char ** e, int * err)
my_strntol_8bit()
size_t long my_strntol_8bit (CHARSET_INFO * cs, const char * s, size_t l, int base, char ** e, int * err)
Definition at line 324 of file ctype-simple.c.
 {
   int negative;
   register uint32 cutoff;
   register uint cutlim;
   register uint32 i;
   register const char *s;
   register uchar c;
   const char *save, *e;
   int overflow;
   *err= 0;              /* Initialize error indicator */
   s = nptr;
   e = nptr+l;
   for ( ; s<e && my_isspace(cs, *s) ; s++);
   if (s == e)
   {
     goto noconv;
   }
   /* Check for a sign.  */
   if (*s == '-')
   {
     negative = 1;
     ++s;
   }
   else if (*s == '+')
   {
     negative = 0;
     ++s;
   }
   else
     negative = 0;
   save = s;
   cutoff = ((uint32)~0L) / (uint32) base;
   cutlim = (uint) (((uint32)~0L) % (uint32) base);
   overflow = 0;
   i = 0;
   for (c = *s; s != e; c = *++s)
   {
     if (c>='0' && c<='9')
       c -= '0';
     else if (c>='A' && c<='Z')
       c = c - 'A' + 10;
     else if (c>='a' && c<='z')
       c = c - 'a' + 10;
     else
       break;
     if (c >= base)
       break;
     if (i > cutoff || (i == cutoff && c > cutlim))
       overflow = 1;
     else
     {
       i *= (uint32) base;
       i += c;
     }
   }
   if (s == save)
     goto noconv;
   if (endptr != NULL)
     *endptr = (char *) s;
   if (negative)
   {
     if (i  > (uint32) INT_MIN32)
       overflow = 1;
   }
   else if (i > INT_MAX32)
     overflow = 1;
   if (overflow)
   {
     err[0]= ERANGE;
     return negative ? INT_MIN32 : INT_MAX32;
   }
   return (negative ? -((long) i) : (long) i);
 noconv:
   err[0]= EDOM;
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0L;
 }
References mpq::c, INT_MAX32, INT_MIN32, mpq::l, my_isspace, and NULL.
my_strntoll_8bit()
longlong my_strntoll_8bit (CHARSET_INFO * , const char * s, size_t l, int base, char ** e, int * err)
my_strntoul_8bit()
ulong my_strntoul_8bit (CHARSET_INFO * cs, const char * s, size_t l, int base, char ** e, int * err)
Definition at line 420 of file ctype-simple.c.
 {
   int negative;
   register uint32 cutoff;
   register uint cutlim;
   register uint32 i;
   register const char *s;
   register uchar c;
   const char *save, *e;
   int overflow;
   *err= 0;              /* Initialize error indicator */
   s = nptr;
   e = nptr+l;
   for( ; s<e && my_isspace(cs, *s); s++);
   if (s==e)
   {
     goto noconv;
   }
   if (*s == '-')
   {
     negative = 1;
     ++s;
   }
   else if (*s == '+')
   {
     negative = 0;
     ++s;
   }
   else
     negative = 0;
   save = s;
   cutoff = ((uint32)~0L) / (uint32) base;
   cutlim = (uint) (((uint32)~0L) % (uint32) base);
   overflow = 0;
   i = 0;
   for (c = *s; s != e; c = *++s)
   {
     if (c>='0' && c<='9')
       c -= '0';
     else if (c>='A' && c<='Z')
       c = c - 'A' + 10;
     else if (c>='a' && c<='z')
       c = c - 'a' + 10;
     else
       break;
     if (c >= base)
       break;
     if (i > cutoff || (i == cutoff && c > cutlim))
       overflow = 1;
     else
     {
       i *= (uint32) base;
       i += c;
     }
   }
   if (s == save)
     goto noconv;
   if (endptr != NULL)
     *endptr = (char *) s;
   if (overflow)
   {
     err[0]= ERANGE;
     return (~(uint32) 0);
   }
   return (negative ? -((long) i) : (long) i);
 noconv:
   err[0]= EDOM;
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0L;
 }
References mpq::c, mpq::l, my_isspace, and NULL.
my_strntoull10rnd_8bit()
ulonglong my_strntoull10rnd_8bit (CHARSET_INFO * cs, const char * str, size_t length, int unsigned_fl, char ** endptr, int * error)
my_strntoull10rnd_ucs2()
ulonglong my_strntoull10rnd_ucs2 (CHARSET_INFO * cs, const char * str, size_t length, int unsigned_fl, char ** endptr, int * error)
my_strntoull_8bit()
ulonglong my_strntoull_8bit (CHARSET_INFO * cs, const char * s, size_t l, int base, char ** e, int * err)
Definition at line 603 of file ctype-simple.c.
 {
   int negative;
   register ulonglong cutoff;
   register uint cutlim;
   register ulonglong i;
   register const char *s, *e;
   const char *save;
   int overflow;
   *err= 0;              /* Initialize error indicator */
   s = nptr;
   e = nptr+l;
   for(; s<e && my_isspace(cs,*s); s++);
   if (s == e)
   {
     goto noconv;
   }
   if (*s == '-')
   {
     negative = 1;
     ++s;
   }
   else if (*s == '+')
   {
     negative = 0;
     ++s;
   }
   else
     negative = 0;
   save = s;
   cutoff = (~(ulonglong) 0) / (unsigned long int) base;
   cutlim = (uint) ((~(ulonglong) 0) % (unsigned long int) base);
   overflow = 0;
   i = 0;
   for ( ; s != e; s++)
   {
     register uchar c= *s;
     if (c>='0' && c<='9')
       c -= '0';
     else if (c>='A' && c<='Z')
       c = c - 'A' + 10;
     else if (c>='a' && c<='z')
       c = c - 'a' + 10;
     else
       break;
     if (c >= base)
       break;
     if (i > cutoff || (i == cutoff && c > cutlim))
       overflow = 1;
     else
     {
       i *= (ulonglong) base;
       i += c;
     }
   }
   if (s == save)
     goto noconv;
   if (endptr != NULL)
     *endptr = (char *) s;
   if (overflow)
   {
     err[0]= ERANGE;
     return (~(ulonglong) 0);
   }
   return (negative ? -((longlong) i) : (longlong) i);
 noconv:
   err[0]= EDOM;
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0L;
 }
References mpq::c, mpq::l, my_isspace, and NULL.
my_strnxfrm_simple()
size_t my_strnxfrm_simple (CHARSET_INFO * cs, uchar * dest, size_t len, const uchar * src, size_t srclen)
Definition at line 74 of file ctype-simple.c.
 {
   uchar *map= cs->sort_order;
   size_t dstlen= len;
   set_if_smaller(len, srclen);
   if (dest != src)
   {
     const uchar *end;
     for ( end=src+len; src < end ;  )
       *dest++= map[*src++];
   }
   else
   {
     const uchar *end;
     for ( end=dest+len; dest < end ; dest++)
       *dest= (char) map[(uchar) *dest];
   }
   if (dstlen > len)
     bfill(dest, dstlen - len, ' ');
   return dstlen;
 }
References bfill, set_if_smaller, and charset_info_st::sort_order.
my_strnxfrm_unicode()
size_t my_strnxfrm_unicode (CHARSET_INFO * cs, uchar * dst, size_t dstlen, const uchar * src, size_t srclen)
Definition at line 1905 of file ctype-utf8.c.
 {
   my_wc_t wc;
   int res;
   uchar *de= dst + dstlen;
   uchar *de_beg= de - 1;
   const uchar *se = src + srclen;
   MY_UNICASE_INFO **uni_plane= (cs->state & MY_CS_BINSORT) ?
                                 NULL : cs->caseinfo;
   LINT_INIT(wc);
   DBUG_ASSERT(src);
   while (dst < de_beg)
   {
     if ((res= cs->cset->mb_wc(cs,&wc, src, se)) <= 0)
       break;
     src+=res;
     if (uni_plane)
       my_tosort_unicode(uni_plane, &wc);
     *dst++= (uchar) (wc >> 8);
     if (dst < de)
       *dst++= (uchar) (wc & 0xFF);
   }
   while (dst < de_beg) /* Fill the tail with keys for space character */
   {
     *dst++= 0x00;
     *dst++= 0x20;
   }
   if (dst < de)  /* Clear the last byte, if "dstlen" was an odd number */
     *dst= 0x00;
   return dstlen;
 }
References charset_info_st::caseinfo, charset_info_st::cset, DBUG_ASSERT, LINT_INIT, my_charset_handler_st::mb_wc, MY_CS_BINSORT, my_tosort_unicode(), my_wc_t, NULL, and charset_info_st::state.
my_strnxfrm_unicode_full_bin()
size_t my_strnxfrm_unicode_full_bin (CHARSET_INFO * cs, uchar * dst, size_t dstlen, const uchar * src, size_t srclen)
Definition at line 1951 of file ctype-utf8.c.
 {
   my_wc_t wc;
   uchar *de= dst + dstlen;
   uchar *de_beg= de - 2; /* The beginning of the last chunk */
   const uchar *se = src + srclen;
   LINT_INIT(wc);
   DBUG_ASSERT(src);
   DBUG_ASSERT(cs->state & MY_CS_BINSORT);
   while (dst < de_beg)
   {
     int res;
     if ((res= cs->cset->mb_wc(cs, &wc, src, se)) <= 0)
       break;
     src+= res;
     *dst++= (uchar) (wc >> 16);
     *dst++= (uchar) ((wc >> 8) & 0xFF);
     *dst++= (uchar) (wc & 0xFF);
   }
   while (dst < de_beg) /* Fill the tail with keys for space character */
   {
     *dst++= 0x00;
     *dst++= 0x00;
     *dst++= 0x20;
   }
   /* Clear the last one or two bytes, if "dstlen" was not divisible by 3 */
   if (dst < de)
   {
     *dst++= 0x00;
     if (dst < de)
       *dst= 0x00;
   }
   return dstlen;
 }
References charset_info_st::cset, DBUG_ASSERT, LINT_INIT, my_charset_handler_st::mb_wc, MY_CS_BINSORT, my_wc_t, and charset_info_st::state.
my_strnxfrmlen_simple()
size_t my_strnxfrmlen_simple (CHARSET_INFO * cs, size_t len)
Definition at line 28 of file ctype-simple.c.
 {
   return len * (cs->strxfrm_multiply ? cs->strxfrm_multiply : 1);
 }
References charset_info_st::strxfrm_multiply.
my_strnxfrmlen_unicode_full_bin()
size_t my_strnxfrmlen_unicode_full_bin (CHARSET_INFO * cs, size_t len)
Definition at line 1995 of file ctype-utf8.c.
 {
   return ((len + 3) / cs->mbmaxlen) * 3;
 }
References charset_info_st::mbmaxlen.
my_strtoll10_8bit()
longlong my_strtoll10_8bit (CHARSET_INFO * cs, const char * nptr, char ** endptr, int * error)
my_strtoll10_ucs2()
longlong my_strtoll10_ucs2 (CHARSET_INFO * cs, const char * nptr, char ** endptr, int * error)
my_vsnprintf_ex()
size_t my_vsnprintf_ex (CHARSET_INFO * cs, char * to, size_t n, const char * fmt, va_list ap)
Produces output string according to a format string
See the detailed documentation around my_snprintf_service_st
Parameters
cs string charset
to buffer where processed string will be place
n size of buffer
par format string
ap list of parameters
Return values
length of result string
Definition at line 537 of file my_vsnprintf.c.
 {
   char *start=to, *end=to+n-1;
   size_t length, width;
   uint print_type, have_longlong;
   for (; *fmt ; fmt++)
   {
     if (*fmt != '%')
     {
       if (to == end)                            /* End of buffer */
     break;
       *to++= *fmt;                            /* Copy ordinary char */
       continue;
     }
     fmt++;                  /* skip '%' */
     length= width= 0;
     print_type= 0;
     /* Read max fill size (only used with %d and %u) */
     if (my_isdigit(&my_charset_latin1, *fmt))
     {
       fmt= get_length(fmt, &length, &print_type);
       if (*fmt == '$')
       {
         to= process_args(cs, to, end, (fmt+1), length, ap);
         return (size_t) (to - start);
       }
     }
     else
     {
       if (*fmt == '`')
       {
         print_type|= ESCAPED_ARG;
         fmt++;
       }
       if (*fmt == '-')
         fmt++;
       if (*fmt == '*')
       {
         fmt++;
         length= va_arg(ap, int);
       }
       else
         fmt= get_length(fmt, &length, &print_type);
     }
     if (*fmt == '.')
     {
       fmt++;
       if (*fmt == '*')
       {
         fmt++;
         width= va_arg(ap, int);
       }
       else
         fmt= get_width(fmt, &width);
     }
     else
       width= SIZE_T_MAX;
     fmt= check_longlong(fmt, &have_longlong);
     if (*fmt == 's')                /* String parameter */
     {
       reg2 char *par= va_arg(ap, char *);
       to= process_str_arg(cs, to, end, width, par, print_type);
       continue;
     }
     else if (*fmt == 'b')               /* Buffer parameter */
     {
       char *par = va_arg(ap, char *);
       to= process_bin_arg(to, end, width, par);
       continue;
     }
     else if (*fmt == 'f' || *fmt == 'g')
     {
       double d= va_arg(ap, double);
       to= process_dbl_arg(to, end, width, d, *fmt);
       continue;
     }
     else if (*fmt == 'd' || *fmt == 'i' || *fmt == 'u' || *fmt == 'x' ||
              *fmt == 'X' || *fmt == 'p' || *fmt == 'o')
     {
       /* Integer parameter */
       longlong larg;
       if (*fmt == 'p')
         have_longlong= (sizeof(void *) == sizeof(longlong));
       if (have_longlong)
         larg = va_arg(ap,longlong);
       else if (*fmt == 'd' || *fmt == 'i')
         larg = va_arg(ap, int);
       else
         larg= va_arg(ap, uint);
       to= process_int_arg(to, end, length, larg, *fmt, print_type);
       continue;
     }
     else if (*fmt == 'c')                       /* Character parameter */
     {
       register int larg;
       if (to == end)
         break;
       larg = va_arg(ap, int);
       *to++= (char) larg;
       continue;
     }
     /* We come here on '%%', unknown code or too long parameter */
     if (to == end)
       break;
     *to++='%';              /* % used as % or unknown code */
   }
   DBUG_ASSERT(to <= end);
   *to='\0';             /* End of errmessage */
   return (size_t) (to - start);
 }
References check_longlong(), mpq::d, DBUG_ASSERT, ESCAPED_ARG, fmt, get_length(), get_width(), G3D::length(), my_charset_latin1, my_isdigit, process_args(), process_bin_arg(), process_dbl_arg(), process_int_arg(), process_str_arg(), reg2, SIZE_T_MAX, and width.
Referenced by my_error(), my_printf_error(), and my_vsnprintf().
my_wc_mb_8bit()
int my_wc_mb_8bit (CHARSET_INFO * cs, my_wc_t wc, uchar * s, uchar * e)
Definition at line 261 of file ctype-simple.c.
 {
   MY_UNI_IDX *idx;
   if (str >= end)
     return MY_CS_TOOSMALL;
   for (idx=cs->tab_from_uni; idx->tab ; idx++)
   {
     if (idx->from <= wc && idx->to >= wc)
     {
       str[0]= idx->tab[wc - idx->from];
       return (!str[0] && wc) ? MY_CS_ILUNI : 1;
     }
   }
   return MY_CS_ILUNI;
 }
References idx, MY_CS_ILUNI, MY_CS_TOOSMALL, and charset_info_st::tab_from_uni.
my_well_formed_len_8bit()
size_t my_well_formed_len_8bit (CHARSET_INFO * , const char * b, const char * e, size_t pos, int * error)
my_well_formed_len_mb()
size_t my_well_formed_len_mb (CHARSET_INFO * , const char * b, const char * e, size_t pos, int * error)
my_wildcmp_8bit()
int my_wildcmp_8bit (CHARSET_INFO * cs, const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many)
Definition at line 844 of file ctype-simple.c.
 {
   int result= -1;           /* Not found, using wildcards */
   while (wildstr != wildend)
   {
     while (*wildstr != w_many && *wildstr != w_one)
     {
       if (*wildstr == escape && wildstr+1 != wildend)
     wildstr++;
       if (str == str_end || likeconv(cs,*wildstr++) != likeconv(cs,*str++))
     return(1);              /* No match */
       if (wildstr == wildend)
     return(str != str_end);     /* Match if both are at end */
       result=1;                 /* Found an anchor char     */
     }
     if (*wildstr == w_one)
     {
       do
       {
     if (str == str_end)         /* Skip one char if possible */
       return(result);
     INC_PTR(cs,str,str_end);
       } while (++wildstr < wildend && *wildstr == w_one);
       if (wildstr == wildend)
     break;
     }
     if (*wildstr == w_many)
     {                       /* Found w_many */
       uchar cmp;
       wildstr++;
       /* Remove any '%' and '_' from the wild search string */
       for (; wildstr != wildend ; wildstr++)
       {
     if (*wildstr == w_many)
       continue;
     if (*wildstr == w_one)
     {
       if (str == str_end)
         return(-1);
       INC_PTR(cs,str,str_end);
       continue;
     }
     break;                  /* Not a wild character */
       }
       if (wildstr == wildend)
     return(0);              /* Ok if w_many is last */
       if (str == str_end)
     return(-1);
       if ((cmp= *wildstr) == escape && wildstr+1 != wildend)
     cmp= *++wildstr;
       INC_PTR(cs,wildstr,wildend);  /* This is compared trough cmp */
       cmp=likeconv(cs,cmp);
       do
       {
     while (str != str_end && (uchar) likeconv(cs,*str) != cmp)
       str++;
     if (str++ == str_end) return(-1);
     {
       int tmp=my_wildcmp_8bit(cs,str,str_end,wildstr,wildend,escape,w_one,
                   w_many);
       if (tmp <= 0)
         return(tmp);
     }
       } while (str != str_end && wildstr[0] != w_many);
       return(-1);
     }
   }
   return(str != str_end ? 1 : 0);
 }
References cmp, G3D::escape(), INC_PTR, likeconv, and my_wildcmp_8bit().
Referenced by my_wildcmp_8bit().
my_wildcmp_bin()
int my_wildcmp_bin (CHARSET_INFO * cs, const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many)
Definition at line 321 of file ctype-bin.c.
 {
   int result= -1;           /* Not found, using wildcards */
   while (wildstr != wildend)
   {
     while (*wildstr != w_many && *wildstr != w_one)
     {
       if (*wildstr == escape && wildstr+1 != wildend)
     wildstr++;
       if (str == str_end || likeconv(cs,*wildstr++) != likeconv(cs,*str++))
     return(1);          /* No match */
       if (wildstr == wildend)
     return(str != str_end);     /* Match if both are at end */
       result=1;             /* Found an anchor char */
     }
     if (*wildstr == w_one)
     {
       do
       {
     if (str == str_end)     /* Skip one char if possible */
       return(result);
     INC_PTR(cs,str,str_end);
       } while (++wildstr < wildend && *wildstr == w_one);
       if (wildstr == wildend)
     break;
     }
     if (*wildstr == w_many)
     {                   /* Found w_many */
       uchar cmp;
       wildstr++;
       /* Remove any '%' and '_' from the wild search string */
       for (; wildstr != wildend ; wildstr++)
       {
     if (*wildstr == w_many)
       continue;
     if (*wildstr == w_one)
     {
       if (str == str_end)
         return(-1);
       INC_PTR(cs,str,str_end);
       continue;
     }
     break;              /* Not a wild character */
       }
       if (wildstr == wildend)
     return(0);          /* match if w_many is last */
       if (str == str_end)
     return(-1);
       if ((cmp= *wildstr) == escape && wildstr+1 != wildend)
     cmp= *++wildstr;
       INC_PTR(cs,wildstr,wildend);  /* This is compared through cmp */
       cmp=likeconv(cs,cmp);
       do
       {
     while (str != str_end && (uchar) likeconv(cs,*str) != cmp)
       str++;
     if (str++ == str_end)
       return(-1);
     {
       int tmp=my_wildcmp_bin(cs,str,str_end,wildstr,wildend,escape,w_one,
                  w_many);
       if (tmp <= 0)
         return(tmp);
     }
       } while (str != str_end && wildstr[0] != w_many);
       return(-1);
     }
   }
   return(str != str_end ? 1 : 0);
 }
References cmp, G3D::escape(), INC_PTR, likeconv, and my_wildcmp_bin().
Referenced by my_wildcmp_bin().
my_wildcmp_mb()
int my_wildcmp_mb (CHARSET_INFO * , const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many)
my_wildcmp_mb_bin()
int my_wildcmp_mb_bin (CHARSET_INFO * cs, const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many)
my_wildcmp_unicode()
int my_wildcmp_unicode (CHARSET_INFO * cs, const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many, MY_UNICASE_INFO ** weights)
Definition at line 1749 of file ctype-utf8.c.
 {
   int result= -1;                             /* Not found, using wildcards */
   my_wc_t s_wc, w_wc;
   int scan;
   int (*mb_wc)(struct charset_info_st *, my_wc_t *,
                const uchar *, const uchar *);
   mb_wc= cs->cset->mb_wc;
   while (wildstr != wildend)
   {
     while (1)
     {
       my_bool escaped= 0;
       if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                        (const uchar*)wildend)) <= 0)
         return 1;
       if (w_wc == (my_wc_t) w_many)
       {
         result= 1;                                /* Found an anchor char */
         break;
       }
       wildstr+= scan;
       if (w_wc ==  (my_wc_t) escape && wildstr < wildend)
       {
         if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                          (const uchar*)wildend)) <= 0)
           return 1;
         wildstr+= scan;
         escaped= 1;
       }
       if ((scan= mb_wc(cs, &s_wc, (const uchar*)str,
                        (const uchar*)str_end)) <= 0)
         return 1;
       str+= scan;
       if (!escaped && w_wc == (my_wc_t) w_one)
       {
         result= 1;                                /* Found an anchor char */
       }
       else
       {
         if (weights)
         {
           my_tosort_unicode(weights, &s_wc);
           my_tosort_unicode(weights, &w_wc);
         }
         if (s_wc != w_wc)
           return 1;                               /* No match */
       }
       if (wildstr == wildend)
         return (str != str_end);                  /* Match if both are at end */
     }
     if (w_wc == (my_wc_t) w_many)
     {                                             /* Found w_many */
       /* Remove any '%' and '_' from the wild search string */
       for ( ; wildstr != wildend ; )
       {
         if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                          (const uchar*)wildend)) <= 0)
           return 1;
         if (w_wc == (my_wc_t)w_many)
         {
           wildstr+= scan;
           continue;
         }
         if (w_wc == (my_wc_t)w_one)
         {
           wildstr+= scan;
           if ((scan= mb_wc(cs, &s_wc, (const uchar*)str,
                            (const uchar*)str_end)) <=0)
             return 1;
           str+= scan;
           continue;
         }
         break;                                        /* Not a wild character */
       }
       if (wildstr == wildend)
         return 0;                                /* Ok if w_many is last */
       if (str == str_end)
         return -1;
       if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                        (const uchar*)wildend)) <=0)
         return 1;
       wildstr+= scan;
       if (w_wc ==  (my_wc_t)escape)
       {
         if (wildstr < wildend)
         {
           if ((scan= mb_wc(cs, &w_wc, (const uchar*)wildstr,
                            (const uchar*)wildend)) <=0)
             return 1;
           wildstr+= scan;
         }
       }
       while (1)
       {
         /* Skip until the first character from wildstr is found */
         while (str != str_end)
         {
           if ((scan= mb_wc(cs, &s_wc, (const uchar*)str,
                            (const uchar*)str_end)) <=0)
             return 1;
           if (weights)
           {
             my_tosort_unicode(weights, &s_wc);
             my_tosort_unicode(weights, &w_wc);
           }
           if (s_wc == w_wc)
             break;
           str+= scan;
         }
         if (str == str_end)
           return -1;
         str+= scan;
         result= my_wildcmp_unicode(cs, str, str_end, wildstr, wildend,
                                    escape, w_one, w_many,
                                    weights);
         if (result <= 0)
           return result;
       }
     }
   }
   return (str != str_end ? 1 : 0);
 }
References charset_info_st::cset, G3D::escape(), my_charset_handler_st::mb_wc, my_tosort_unicode(), my_wc_t, and my_wildcmp_unicode().
Referenced by my_wildcmp_unicode(), and my_wildcmp_utf8().
Variable Documentation
my_charset_8bit_handler
MY_CHARSET_HANDLER my_charset_8bit_handler extern
Definition at line 1660 of file ctype-simple.c.
Referenced by simple_cs_init_functions().
my_charset_big5_bin
CHARSET_INFO my_charset_big5_bin extern
Referenced by init_compiled_charsets().
my_charset_big5_chinese_ci
CHARSET_INFO my_charset_big5_chinese_ci extern
Referenced by init_compiled_charsets().
my_charset_bin
MYSQL_PLUGIN_IMPORT CHARSET_INFO my_charset_bin extern
Definition at line 549 of file ctype-bin.c.
Referenced by init_compiled_charsets(), lf_hash_init(), and safe_hash_init().
my_charset_cp1250_czech_ci
CHARSET_INFO my_charset_cp1250_czech_ci extern
Referenced by init_compiled_charsets().
my_charset_cp932_bin
CHARSET_INFO my_charset_cp932_bin extern
Referenced by init_compiled_charsets().
my_charset_cp932_japanese_ci
CHARSET_INFO my_charset_cp932_japanese_ci extern
Referenced by init_compiled_charsets().
my_charset_eucjpms_bin
CHARSET_INFO my_charset_eucjpms_bin extern
Referenced by init_compiled_charsets().
my_charset_eucjpms_japanese_ci
CHARSET_INFO my_charset_eucjpms_japanese_ci extern
Referenced by init_compiled_charsets().
my_charset_euckr_bin
CHARSET_INFO my_charset_euckr_bin extern
Referenced by init_compiled_charsets().
my_charset_euckr_korean_ci
CHARSET_INFO my_charset_euckr_korean_ci extern
Referenced by init_compiled_charsets().
my_charset_filename
MYSQL_PLUGIN_IMPORT CHARSET_INFO my_charset_filename extern
Definition at line 4296 of file ctype-utf8.c.
Referenced by init_compiled_charsets().
my_charset_gb2312_bin
CHARSET_INFO my_charset_gb2312_bin extern
Referenced by init_compiled_charsets().
my_charset_gb2312_chinese_ci
CHARSET_INFO my_charset_gb2312_chinese_ci extern
Referenced by init_compiled_charsets().
my_charset_gbk_bin
CHARSET_INFO my_charset_gbk_bin extern
Referenced by init_compiled_charsets().
my_charset_gbk_chinese_ci
CHARSET_INFO my_charset_gbk_chinese_ci extern
Referenced by init_compiled_charsets().
my_charset_latin1
MYSQL_PLUGIN_IMPORT CHARSET_INFO my_charset_latin1 extern
Definition at line 419 of file ctype-latin1.c.
Referenced by atoi_octal(), fetch_string_with_conversion(), find_type(), get_argument(), get_bool_argument(), get_charset_name_alias(), get_charset_number_internal(), get_collation_number_internal(), get_length(), get_width(), handle_options(), init_compiled_charsets(), internal_str2dec(), my_b_vprintf(), my_os_charset_to_mysql_charset(), my_vsnprintf(), my_vsnprintf_ex(), search_default_file_with_ext(), str2int(), str_list_find(), and str_to_time().
my_charset_latin1_bin
CHARSET_INFO my_charset_latin1_bin extern
Definition at line 751 of file ctype-latin1.c.
Referenced by init_compiled_charsets().
my_charset_latin1_german2_ci
CHARSET_INFO my_charset_latin1_german2_ci extern
Definition at line 718 of file ctype-latin1.c.
Referenced by init_compiled_charsets().
my_charset_latin2_czech_ci
CHARSET_INFO my_charset_latin2_czech_ci extern
Referenced by init_compiled_charsets().
my_charset_sjis_bin
CHARSET_INFO my_charset_sjis_bin extern
Referenced by init_compiled_charsets().
my_charset_sjis_japanese_ci
CHARSET_INFO my_charset_sjis_japanese_ci extern
Referenced by init_compiled_charsets().
my_charset_tis620_bin
CHARSET_INFO my_charset_tis620_bin extern
Referenced by init_compiled_charsets().
my_charset_tis620_thai_ci
CHARSET_INFO my_charset_tis620_thai_ci extern
Referenced by init_compiled_charsets().
my_charset_ucs2_bin
CHARSET_INFO my_charset_ucs2_bin extern
Referenced by init_compiled_charsets().
my_charset_ucs2_general_ci
CHARSET_INFO my_charset_ucs2_general_ci extern
Referenced by init_compiled_charsets().
my_charset_ucs2_handler
MY_CHARSET_HANDLER my_charset_ucs2_handler extern
my_charset_ucs2_unicode_ci
CHARSET_INFO my_charset_ucs2_unicode_ci extern
Referenced by add_collation(), and init_compiled_charsets().
my_charset_ujis_bin
CHARSET_INFO my_charset_ujis_bin extern
Referenced by init_compiled_charsets().
my_charset_ujis_japanese_ci
CHARSET_INFO my_charset_ujis_japanese_ci extern
Referenced by init_compiled_charsets().
my_charset_utf16_bin
CHARSET_INFO my_charset_utf16_bin extern
Referenced by init_compiled_charsets().
my_charset_utf16_general_ci
CHARSET_INFO my_charset_utf16_general_ci extern
Referenced by init_compiled_charsets().
my_charset_utf16_unicode_ci
CHARSET_INFO my_charset_utf16_unicode_ci extern
Referenced by add_collation(), and init_compiled_charsets().
my_charset_utf32_bin
CHARSET_INFO my_charset_utf32_bin extern
Referenced by init_compiled_charsets().
my_charset_utf32_general_ci
CHARSET_INFO my_charset_utf32_general_ci extern
Referenced by init_compiled_charsets().
my_charset_utf32_unicode_ci
CHARSET_INFO my_charset_utf32_unicode_ci extern
Referenced by add_collation(), and init_compiled_charsets().
my_charset_utf8_bin
CHARSET_INFO my_charset_utf8_bin extern
Definition at line 2817 of file ctype-utf8.c.
Referenced by init_compiled_charsets().
my_charset_utf8_general_ci
CHARSET_INFO my_charset_utf8_general_ci extern
Definition at line 2784 of file ctype-utf8.c.
Referenced by init_compiled_charsets(), my_error(), and my_printf_error().
my_charset_utf8_unicode_ci
CHARSET_INFO my_charset_utf8_unicode_ci extern
Referenced by add_collation(), and init_compiled_charsets().
my_charset_utf8mb4_bin
CHARSET_INFO my_charset_utf8mb4_bin extern
Referenced by init_compiled_charsets().
my_charset_utf8mb4_general_ci
CHARSET_INFO my_charset_utf8mb4_general_ci extern
Referenced by init_compiled_charsets().
my_charset_utf8mb4_unicode_ci
CHARSET_INFO my_charset_utf8mb4_unicode_ci extern
Referenced by add_collation(), and init_compiled_charsets().
my_collation_8bit_bin_handler
MY_COLLATION_HANDLER my_collation_8bit_bin_handler extern
Definition at line 485 of file ctype-bin.c.
Referenced by simple_cs_init_functions().
my_collation_8bit_simple_ci_handler
MY_COLLATION_HANDLER my_collation_8bit_simple_ci_handler extern
Definition at line 1691 of file ctype-simple.c.
Referenced by simple_cs_init_functions().
my_collation_mb_bin_handler
MY_COLLATION_HANDLER my_collation_mb_bin_handler extern
my_collation_ucs2_uca_handler
MY_COLLATION_HANDLER my_collation_ucs2_uca_handler extern
my_uni_ctype
MY_UNI_CTYPE my_uni_ctype[256] extern
Definition at line 1223 of file my_uctype.h.
my_unicase_default
MY_UNICASE_INFO* my_unicase_default[256] extern
Definition at line 1507 of file ctype-utf8.c.
my_unicase_turkish
MY_UNICASE_INFO* my_unicase_turkish[256] extern
Definition at line 1686 of file ctype-utf8.c.