Azerotcore-wotlk: instance_blackrock_spire::instance_blackrock_spireMapScript Struct Reference
instance_blackrock_spire::instance_blackrock_spireMapScript Struct Reference
Public Member Functions
instance_blackrock_spireMapScript (InstanceMap *map)
void CreatureLooted (Creature *creature, LootType loot) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
bool SetBossState (uint32 type, EncounterState state) override
void ProcessEvent (WorldObject *, uint32 eventId) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void SummonSolakarWave (uint8 number)
ObjectGuid GetGuidData (uint32 type) const override
void Update (uint32 diff) override
void Dragonspireroomstore ()
void Dragonspireroomcheck ()
std::string GetSaveData () override
void Load (const char *strIn) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
Public Attributes
uint32 CurrentSolakarWave = 0
uint32 SolakarState = NOT_STARTED
std::vector< TempSummon * > SolakarSummons
Public Attributes inherited from InstanceScript
Map * instance
Protected Attributes
EventMap Events
ObjectGuid HighlordOmokk
ObjectGuid ShadowHunterVoshgajin
ObjectGuid WarMasterVoone
ObjectGuid MotherSmolderweb
ObjectGuid UrokDoomhowl
ObjectGuid QuartermasterZigris
ObjectGuid GizrultheSlavener
ObjectGuid Halycon
ObjectGuid OverlordWyrmthalak
ObjectGuid PyroguardEmberseer
ObjectGuid WarchiefRendBlackhand
ObjectGuid Gyth
ObjectGuid LordVictorNefarius
ObjectGuid TheBeast
ObjectGuid GeneralDrakkisath
ObjectGuid go_emberseerin
ObjectGuid go_doors
ObjectGuid go_emberseerout
ObjectGuid go_blackrockaltar
ObjectGuid go_roomrunes [7]
ObjectGuid go_emberseerrunes [7]
GuidVector runecreaturelist [7]
ObjectGuid go_portcullis_active
ObjectGuid go_urokPile
ObjectGuid go_urokChallenge
std::vector< ObjectGuid > go_urokOgreCirles
std::vector< ObjectGuid > UrokMobs
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 77 of file instance_blackrock_spire.cpp.
Constructor & Destructor Documentation
instance_blackrock_spireMapScript()
instance_blackrock_spire::instance_blackrock_spireMapScript::instance_blackrock_spireMapScript (InstanceMap * map) inline
Definition at line 83 of file instance_blackrock_spire.cpp.
                                                             : InstanceScript(map)
         {
             SetBossNumber(EncounterCount);
             LoadMinionData(minionData);
             LoadDoorData(doorData);
             CurrentSolakarWave = 0;
             SolakarState       = NOT_STARTED;
             SolakarSummons.clear();
         }
References CurrentSolakarWave, doorData, EncounterCount, InstanceScript::LoadDoorData(), InstanceScript::LoadMinionData(), minionData, NOT_STARTED, InstanceScript::SetBossNumber(), SolakarState, and SolakarSummons.
Member Function Documentation
CreatureLooted()
void instance_blackrock_spire::instance_blackrock_spireMapScript::CreatureLooted (Creature * creature, LootType loot) inline override virtual
Reimplemented from InstanceScript.
Definition at line 93 of file instance_blackrock_spire.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_THE_BEAST:
                     if (loot == LOOT_SKINNING)
                     {
                         creature->CastSpell(creature, SPELL_FINKLE_IS_EINHORN, true);
                     }
                     break;
             }
         }
References Unit::CastSpell(), Object::GetEntry(), LOOT_SKINNING, NPC_THE_BEAST, and SPELL_FINKLE_IS_EINHORN.
Dragonspireroomcheck()
void instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomcheck () inline
Definition at line 581 of file instance_blackrock_spire.cpp.
         {
             Creature* mob = nullptr;
             GameObject* rune = nullptr;
             for (uint8 i = 0; i < 7; ++i)
             {
                 bool _mobAlive = false;
                 rune = instance->GetGameObject(go_roomrunes[i]);
                 if (!rune)
                     continue;
                 if (rune->GetGoState() == GO_STATE_ACTIVE)
                 {
                     for (ObjectGuid const& guid : runecreaturelist[i])
                     {
                         mob = instance->GetCreature(guid);
                         if (mob && mob->IsAlive())
                             _mobAlive = true;
                     }
                 }
                 if (!_mobAlive && rune->GetGoState() == GO_STATE_ACTIVE)
                 {
                     HandleGameObject(ObjectGuid::Empty, false, rune);
                     switch (rune->GetEntry())
                     {
                         case GO_HALL_RUNE_1:
                             SetBossState(DATA_HALL_RUNE_1, DONE);
                             break;
                         case GO_HALL_RUNE_2:
                             SetBossState(DATA_HALL_RUNE_2, DONE);
                             break;
                         case GO_HALL_RUNE_3:
                             SetBossState(DATA_HALL_RUNE_3, DONE);
                             break;
                         case GO_HALL_RUNE_4:
                             SetBossState(DATA_HALL_RUNE_4, DONE);
                             break;
                         case GO_HALL_RUNE_5:
                             SetBossState(DATA_HALL_RUNE_5, DONE);
                             break;
                         case GO_HALL_RUNE_6:
                             SetBossState(DATA_HALL_RUNE_6, DONE);
                             break;
                         case GO_HALL_RUNE_7:
                             SetBossState(DATA_HALL_RUNE_7, DONE);
                             break;
                         default:
                             break;
                     }
                 }
             }
             if (GetBossState(DATA_HALL_RUNE_1) == DONE && GetBossState(DATA_HALL_RUNE_2) == DONE && GetBossState(DATA_HALL_RUNE_3) == DONE &&
                     GetBossState(DATA_HALL_RUNE_4) == DONE && GetBossState(DATA_HALL_RUNE_5) == DONE && GetBossState(DATA_HALL_RUNE_6) == DONE &&
                     GetBossState(DATA_HALL_RUNE_7) == DONE)
             {
                 SetBossState(DATA_DRAGONSPIRE_ROOM, DONE);
                 if (GameObject* door1 = instance->GetGameObject(go_emberseerin))
                     HandleGameObject(ObjectGuid::Empty, true, door1);
                 if (GameObject* door2 = instance->GetGameObject(go_doors))
                     HandleGameObject(ObjectGuid::Empty, true, door2);
                 if (GameObject* door3 = instance->GetGameObject(go_emberseerin))
                     HandleGameObject(ObjectGuid::Empty, true, door3);
             }
         }
References DATA_DRAGONSPIRE_ROOM, DATA_HALL_RUNE_1, DATA_HALL_RUNE_2, DATA_HALL_RUNE_3, DATA_HALL_RUNE_4, DATA_HALL_RUNE_5, DATA_HALL_RUNE_6, DATA_HALL_RUNE_7, DONE, ObjectGuid::Empty, InstanceScript::GetBossState(), Map::GetCreature(), Object::GetEntry(), Map::GetGameObject(), GameObject::GetGoState(), go_doors, go_emberseerin, GO_HALL_RUNE_1, GO_HALL_RUNE_2, GO_HALL_RUNE_3, GO_HALL_RUNE_4, GO_HALL_RUNE_5, GO_HALL_RUNE_6, GO_HALL_RUNE_7, go_roomrunes, GO_STATE_ACTIVE, InstanceScript::HandleGameObject(), InstanceScript::instance, Unit::IsAlive(), runecreaturelist, and SetBossState().
Referenced by Update().
Dragonspireroomstore()
void instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomstore () inline
Definition at line 555 of file instance_blackrock_spire.cpp.
         {
             for (uint8 i = 0; i < 7; ++i)
             {
                 // Refresh the creature list
                 runecreaturelist[i].clear();
                 if (GameObject* rune = instance->GetGameObject(go_roomrunes[i]))
                 {
                     for (uint8 j = 0; j < 3; ++j)
                     {
                         std::list<Creature*> creatureList;
                         GetCreatureListWithEntryInGrid(creatureList, rune, DragonspireMobs[j], 15.0f);
                         for (std::list<Creature*>::iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
{
                             if (Creature* creature = *itr)
{
                                 runecreaturelist[i].push_back(creature->GetGUID());
                             }
                         }
                     }
                 }
             }
         }
References DragonspireMobs, GetCreatureListWithEntryInGrid(), Map::GetGameObject(), go_roomrunes, InstanceScript::instance, and runecreaturelist.
Referenced by Update().
GetData()
uint32 instance_blackrock_spire::instance_blackrock_spireMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 413 of file instance_blackrock_spire.cpp.
         {
             if (type == DATA_SOLAKAR_FLAMEWREATH)
             {
                 return SolakarState;
             }
             else
             {
                 return InstanceScript::GetData(type);
             }
         }
References DATA_SOLAKAR_FLAMEWREATH, ZoneScript::GetData(), and SolakarState.
GetGuidData()
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 445 of file instance_blackrock_spire.cpp.
         {
             switch (type)
             {
                 case DATA_HIGHLORD_OMOKK:
                     return HighlordOmokk;
                 case DATA_SHADOW_HUNTER_VOSHGAJIN:
                     return ShadowHunterVoshgajin;
                 case DATA_WARMASTER_VOONE:
                     return WarMasterVoone;
                 case DATA_MOTHER_SMOLDERWEB:
                     return MotherSmolderweb;
                 case DATA_UROK_DOOMHOWL:
                     return UrokDoomhowl;
                 case DATA_QUARTERMASTER_ZIGRIS:
                     return QuartermasterZigris;
                 case DATA_GIZRUL_THE_SLAVENER:
                     return GizrultheSlavener;
                 case DATA_HALYCON:
                     return Halycon;
                 case DATA_OVERLORD_WYRMTHALAK:
                     return OverlordWyrmthalak;
                 case DATA_PYROGAURD_EMBERSEER:
                     return PyroguardEmberseer;
                 case DATA_WARCHIEF_REND_BLACKHAND:
                     return WarchiefRendBlackhand;
                 case DATA_GYTH:
                     return Gyth;
                 case DATA_THE_BEAST:
                     return TheBeast;
                 case DATA_GENERAL_DRAKKISATH:
                     return GeneralDrakkisath;
                 case GO_EMBERSEER_IN:
                     return go_emberseerin;
                 case GO_DOORS:
                     return go_doors;
                 case GO_EMBERSEER_OUT:
                     return go_emberseerout;
                 case GO_HALL_RUNE_1:
                     return go_roomrunes[0];
                 case GO_HALL_RUNE_2:
                     return go_roomrunes[1];
                 case GO_HALL_RUNE_3:
                     return go_roomrunes[2];
                 case GO_HALL_RUNE_4:
                     return go_roomrunes[3];
                 case GO_HALL_RUNE_5:
                     return go_roomrunes[4];
                 case GO_HALL_RUNE_6:
                     return go_roomrunes[5];
                 case GO_HALL_RUNE_7:
                     return go_roomrunes[6];
                 case GO_EMBERSEER_RUNE_1:
                     return go_emberseerrunes[0];
                 case GO_EMBERSEER_RUNE_2:
                     return go_emberseerrunes[1];
                 case GO_EMBERSEER_RUNE_3:
                     return go_emberseerrunes[2];
                 case GO_EMBERSEER_RUNE_4:
                     return go_emberseerrunes[3];
                 case GO_EMBERSEER_RUNE_5:
                     return go_emberseerrunes[4];
                 case GO_EMBERSEER_RUNE_6:
                     return go_emberseerrunes[5];
                 case GO_EMBERSEER_RUNE_7:
                     return go_emberseerrunes[6];
                 case GO_PORTCULLIS_ACTIVE:
                     return go_portcullis_active;
                 case GO_UROK_PILE:
                     return go_urokPile;
                 case GO_UROK_CHALLENGE:
                     return go_urokChallenge;
                 default:
                     break;
             }
             return ObjectGuid::Empty;
         }
References DATA_GENERAL_DRAKKISATH, DATA_GIZRUL_THE_SLAVENER, DATA_GYTH, DATA_HALYCON, DATA_HIGHLORD_OMOKK, DATA_MOTHER_SMOLDERWEB, DATA_OVERLORD_WYRMTHALAK, DATA_PYROGAURD_EMBERSEER, DATA_QUARTERMASTER_ZIGRIS, DATA_SHADOW_HUNTER_VOSHGAJIN, DATA_THE_BEAST, DATA_UROK_DOOMHOWL, DATA_WARCHIEF_REND_BLACKHAND, DATA_WARMASTER_VOONE, ObjectGuid::Empty, GeneralDrakkisath, GizrultheSlavener, GO_DOORS, go_doors, GO_EMBERSEER_IN, GO_EMBERSEER_OUT, GO_EMBERSEER_RUNE_1, GO_EMBERSEER_RUNE_2, GO_EMBERSEER_RUNE_3, GO_EMBERSEER_RUNE_4, GO_EMBERSEER_RUNE_5, GO_EMBERSEER_RUNE_6, GO_EMBERSEER_RUNE_7, go_emberseerin, go_emberseerout, go_emberseerrunes, GO_HALL_RUNE_1, GO_HALL_RUNE_2, GO_HALL_RUNE_3, GO_HALL_RUNE_4, GO_HALL_RUNE_5, GO_HALL_RUNE_6, GO_HALL_RUNE_7, GO_PORTCULLIS_ACTIVE, go_portcullis_active, go_roomrunes, GO_UROK_CHALLENGE, GO_UROK_PILE, go_urokChallenge, go_urokPile, Gyth, Halycon, HighlordOmokk, MotherSmolderweb, OverlordWyrmthalak, PyroguardEmberseer, QuartermasterZigris, ShadowHunterVoshgajin, TheBeast, UrokDoomhowl, WarchiefRendBlackhand, and WarMasterVoone.
GetSaveData()
std::string instance_blackrock_spire::instance_blackrock_spireMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 650 of file instance_blackrock_spire.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "B S " << GetBossSaveData();
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Load()
void instance_blackrock_spire::instance_blackrock_spireMapScript::Load (const char * strIn) inline override virtual
Reimplemented from InstanceScript.
Definition at line 661 of file instance_blackrock_spire.cpp.
         {
             if (!strIn)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(strIn);
             char dataHead1, dataHead2;
             std::istringstream loadStream(strIn);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'B' && dataHead2 == 'S')
             {
                 for (uint8 i = 0; i < EncounterCount; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References EncounterCount, IN_PROGRESS, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 106 of file instance_blackrock_spire.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_UROK_MAGUS:
                     [[fallthrough]];
                 case NPC_UROK_ENFORCER:
                     UrokMobs.push_back(creature->GetGUID());
                     break;
                 case NPC_HIGHLORD_OMOKK:
                     HighlordOmokk = creature->GetGUID();
                     break;
                 case NPC_SHADOW_HUNTER_VOSHGAJIN:
                     ShadowHunterVoshgajin = creature->GetGUID();
                     break;
                 case NPC_WARMASTER_VOONE:
                     WarMasterVoone = creature->GetGUID();
                     break;
                 case NPC_MOTHER_SMOLDERWEB:
                     MotherSmolderweb = creature->GetGUID();
                     break;
                 case NPC_UROK_DOOMHOWL:
                     UrokDoomhowl = creature->GetGUID();
                     break;
                 case NPC_QUARTERMASTER_ZIGRIS:
                     QuartermasterZigris = creature->GetGUID();
                     break;
                 case NPC_GIZRUL_THE_SLAVENER:
                     GizrultheSlavener = creature->GetGUID();
                     break;
                 case NPC_HALYCON:
                     Halycon = creature->GetGUID();
                     break;
                 case NPC_OVERLORD_WYRMTHALAK:
                     OverlordWyrmthalak = creature->GetGUID();
                     break;
                 case NPC_PYROGAURD_EMBERSEER:
                     PyroguardEmberseer = creature->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         creature->DisappearAndDie();
                     break;
                 case NPC_WARCHIEF_REND_BLACKHAND:
                     if (GetBossState(DATA_GYTH) != IN_PROGRESS)
                     {
                         WarchiefRendBlackhand = creature->GetGUID();
                     }
                     if (GetBossState(DATA_GYTH) == DONE)
                         creature->DisappearAndDie();
                     break;
                 case NPC_GYTH:
                     Gyth = creature->GetGUID();
                     break;
                 case NPC_THE_BEAST:
                     TheBeast = creature->GetGUID();
                     break;
                 case NPC_GENERAL_DRAKKISATH:
                     GeneralDrakkisath = creature->GetGUID();
                     break;
                 case NPC_LORD_VICTOR_NEFARIUS:
                     LordVictorNefarius = creature->GetGUID();
                     if (GetBossState(DATA_GYTH) == DONE)
                         creature->DisappearAndDie();
                     break;
                 case NPC_FINKLE_EINHORN:
                     creature->AI()->Talk(SAY_FINKLE_GANG);
                     break;
                 case NPC_CHROMATIC_ELITE_GUARD:
                     AddMinion(creature, true);
                     break;
             }
         }
References InstanceScript::AddMinion(), Creature::AI(), DATA_GYTH, DATA_PYROGAURD_EMBERSEER, Creature::DisappearAndDie(), DONE, GeneralDrakkisath, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GizrultheSlavener, Gyth, Halycon, HighlordOmokk, IN_PROGRESS, LordVictorNefarius, MotherSmolderweb, NPC_CHROMATIC_ELITE_GUARD, NPC_FINKLE_EINHORN, NPC_GENERAL_DRAKKISATH, NPC_GIZRUL_THE_SLAVENER, NPC_GYTH, NPC_HALYCON, NPC_HIGHLORD_OMOKK, NPC_LORD_VICTOR_NEFARIUS, NPC_MOTHER_SMOLDERWEB, NPC_OVERLORD_WYRMTHALAK, NPC_PYROGAURD_EMBERSEER, NPC_QUARTERMASTER_ZIGRIS, NPC_SHADOW_HUNTER_VOSHGAJIN, NPC_THE_BEAST, NPC_UROK_DOOMHOWL, NPC_UROK_ENFORCER, NPC_UROK_MAGUS, NPC_WARCHIEF_REND_BLACKHAND, NPC_WARMASTER_VOONE, OverlordWyrmthalak, PyroguardEmberseer, QuartermasterZigris, SAY_FINKLE_GANG, ShadowHunterVoshgajin, CreatureAI::Talk(), TheBeast, UrokDoomhowl, UrokMobs, WarchiefRendBlackhand, and WarMasterVoone.
OnGameObjectCreate()
void instance_blackrock_spire::instance_blackrock_spireMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 179 of file instance_blackrock_spire.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_EMBERSEER_IN:
                     go_emberseerin = go->GetGUID();
                     HandleGameObject(ObjectGuid::Empty, GetBossState(DATA_DRAGONSPIRE_ROOM) == DONE, go);
                     break;
                 case GO_DOORS:
                     go_doors = go->GetGUID();
                     if (GetBossState(DATA_DRAGONSPIRE_ROOM) == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
                 case GO_EMBERSEER_OUT:
                     go_emberseerout = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
                 case GO_HALL_RUNE_1:
                     go_roomrunes[0] = go->GetGUID();
                     if (GetBossState(DATA_HALL_RUNE_1) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_HALL_RUNE_2:
                     go_roomrunes[1] = go->GetGUID();
                     if (GetBossState(DATA_HALL_RUNE_2) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_HALL_RUNE_3:
                     go_roomrunes[2] = go->GetGUID();
                     if (GetBossState(DATA_HALL_RUNE_3) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_HALL_RUNE_4:
                     go_roomrunes[3] = go->GetGUID();
                     if (GetBossState(DATA_HALL_RUNE_4) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_HALL_RUNE_5:
                     go_roomrunes[4] = go->GetGUID();
                     if (GetBossState(DATA_HALL_RUNE_5) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_HALL_RUNE_6:
                     go_roomrunes[5] = go->GetGUID();
                     if (GetBossState(DATA_HALL_RUNE_6) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_HALL_RUNE_7:
                     go_roomrunes[6] = go->GetGUID();
                     if (GetBossState(DATA_HALL_RUNE_7) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_EMBERSEER_RUNE_1:
                     go_emberseerrunes[0] = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_EMBERSEER_RUNE_2:
                     go_emberseerrunes[1] = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_EMBERSEER_RUNE_3:
                     go_emberseerrunes[2] = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_EMBERSEER_RUNE_4:
                     go_emberseerrunes[3] = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_EMBERSEER_RUNE_5:
                     go_emberseerrunes[4] = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_EMBERSEER_RUNE_6:
                     go_emberseerrunes[5] = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_EMBERSEER_RUNE_7:
                     go_emberseerrunes[6] = go->GetGUID();
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == DONE)
                         HandleGameObject(ObjectGuid::Empty, false, go);
                     break;
                 case GO_PORTCULLIS_ACTIVE:
                     go_portcullis_active = go->GetGUID();
                     if (GetBossState(DATA_GYTH) == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
                 case GO_UROK_PILE:
                     go_urokPile = go->GetGUID();
                     break;
                 case GO_UROK_CIRCLE:
                     go_urokOgreCirles.push_back(go->GetGUID());
                     break;
                 case GO_UROK_CHALLENGE:
                     go_urokChallenge = go->GetGUID();
                     break;
                 default:
                     break;
             }
             InstanceScript::OnGameObjectCreate(go);
         }
References DATA_DRAGONSPIRE_ROOM, DATA_GYTH, DATA_HALL_RUNE_1, DATA_HALL_RUNE_2, DATA_HALL_RUNE_3, DATA_HALL_RUNE_4, DATA_HALL_RUNE_5, DATA_HALL_RUNE_6, DATA_HALL_RUNE_7, DATA_PYROGAURD_EMBERSEER, DONE, ObjectGuid::Empty, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_DOORS, go_doors, GO_EMBERSEER_IN, GO_EMBERSEER_OUT, GO_EMBERSEER_RUNE_1, GO_EMBERSEER_RUNE_2, GO_EMBERSEER_RUNE_3, GO_EMBERSEER_RUNE_4, GO_EMBERSEER_RUNE_5, GO_EMBERSEER_RUNE_6, GO_EMBERSEER_RUNE_7, go_emberseerin, go_emberseerout, go_emberseerrunes, GO_HALL_RUNE_1, GO_HALL_RUNE_2, GO_HALL_RUNE_3, GO_HALL_RUNE_4, GO_HALL_RUNE_5, GO_HALL_RUNE_6, GO_HALL_RUNE_7, GO_PORTCULLIS_ACTIVE, go_portcullis_active, go_roomrunes, GO_UROK_CHALLENGE, GO_UROK_CIRCLE, GO_UROK_PILE, go_urokChallenge, go_urokOgreCirles, go_urokPile, InstanceScript::HandleGameObject(), and InstanceScript::OnGameObjectCreate().
ProcessEvent()
void instance_blackrock_spire::instance_blackrock_spireMapScript::ProcessEvent (WorldObject * , uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
Definition at line 316 of file instance_blackrock_spire.cpp.
         {
             switch (eventId)
             {
                 case EVENT_PYROGUARD_EMBERSEER:
                     if (GetBossState(DATA_PYROGAURD_EMBERSEER) == NOT_STARTED)
                     {
                         if (Creature* Emberseer = instance->GetCreature(PyroguardEmberseer))
                             Emberseer->AI()->SetData(1, 1);
                     }
                     break;
                 case EVENT_UROK_DOOMHOWL:
                     if (GetBossState(DATA_UROK_DOOMHOWL) == NOT_STARTED)
                     {
                         SetBossState(DATA_UROK_DOOMHOWL, IN_PROGRESS);
                         if (GameObject* pile = instance->GetGameObject(go_urokPile))
{
                             pile->SetLootState(GO_JUST_DEACTIVATED);
                         }
                     }
                     break;
                 default:
                     break;
             }
         }
References DATA_PYROGAURD_EMBERSEER, DATA_UROK_DOOMHOWL, EVENT_PYROGUARD_EMBERSEER, EVENT_UROK_DOOMHOWL, InstanceScript::GetBossState(), Map::GetCreature(), Map::GetGameObject(), GO_JUST_DEACTIVATED, go_urokPile, IN_PROGRESS, InstanceScript::instance, NOT_STARTED, PyroguardEmberseer, and SetBossState().
SetBossState()
bool instance_blackrock_spire::instance_blackrock_spireMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 288 of file instance_blackrock_spire.cpp.
         {
             if (!InstanceScript::SetBossState(type, state))
                 return false;
             switch (type)
             {
                 case DATA_WARCHIEF_REND_BLACKHAND:
                     if (state == FAIL)
                     {
                         if (Creature* rend = instance->GetCreature(WarchiefRendBlackhand))
{
                             rend->Respawn(true);
                         }
                         if (Creature* nefarius = instance->GetCreature(LordVictorNefarius))
{
                             nefarius->AI()->Talk(SAY_NEFARIUS_REND_WIPE);
                         }
                     }
                     break;
                 default:
                     break;
             }
             return true;
         }
References DATA_WARCHIEF_REND_BLACKHAND, FAIL, Map::GetCreature(), InstanceScript::instance, LordVictorNefarius, SAY_NEFARIUS_REND_WIPE, InstanceScript::SetBossState(), and WarchiefRendBlackhand.
Referenced by Dragonspireroomcheck(), Load(), ProcessEvent(), and SetData().
SetData()
void instance_blackrock_spire::instance_blackrock_spireMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 342 of file instance_blackrock_spire.cpp.
         {
             switch (type)
             {
                 case AREATRIGGER:
                     if (data == AREATRIGGER_DRAGONSPIRE_HALL)
                     {
                         if (GetBossState(DATA_DRAGONSPIRE_ROOM) != DONE)
                             Events.ScheduleEvent(EVENT_DARGONSPIRE_ROOM_STORE, 1000);
                     }
                     break;
                 case DATA_SOLAKAR_FLAMEWREATH:
                     switch(data)
                     {
                         case IN_PROGRESS:
                             if (SolakarState == NOT_STARTED)
{
                                 Events.ScheduleEvent(EVENT_SOLAKAR_WAVE, 500);
                             }
                             break;
                         case FAIL:
                             for (const auto& creature : SolakarSummons)
{
                                 creature->RemoveFromWorld();
                             }
                             SolakarSummons.clear();
                             CurrentSolakarWave = 0;
                             SetData(DATA_SOLAKAR_FLAMEWREATH, NOT_STARTED);
                             break;
                         case DONE:
                             break;
                     }
                     SolakarState = data;
                     break;
                 case DATA_UROK_DOOMHOWL:
                     if (data == FAIL)
                     {
                         if (GetBossState(DATA_UROK_DOOMHOWL) != NOT_STARTED)
{
                             SetBossState(DATA_UROK_DOOMHOWL, NOT_STARTED);
                             if (GameObject* challenge = instance->GetGameObject(go_urokChallenge))
{
                                 challenge->Delete();
                             }
                             if (GameObject* pile = instance->GetGameObject(go_urokPile))
{
                                 pile->SetLootState(GO_READY);
                                 pile->Respawn();
                             }
                             for (const auto& circleGUID : go_urokOgreCirles)
{
                                 if (GameObject* circle = instance->GetGameObject(circleGUID))
{
                                     circle->Delete();
                                 }
                             }
                             for (const auto& mobGUID : UrokMobs)
{
                                 if (Creature* mob = instance->GetCreature(mobGUID))
{
                                     mob->DespawnOrUnsummon();
                                 }
                             }
                         }
                     }
                     break;
                 default:
                     break;
             }
         }
References AREATRIGGER, AREATRIGGER_DRAGONSPIRE_HALL, CurrentSolakarWave, DATA_DRAGONSPIRE_ROOM, DATA_SOLAKAR_FLAMEWREATH, DATA_UROK_DOOMHOWL, DONE, EVENT_DARGONSPIRE_ROOM_STORE, EVENT_SOLAKAR_WAVE, FAIL, InstanceScript::GetBossState(), Map::GetCreature(), Map::GetGameObject(), GO_READY, go_urokChallenge, go_urokOgreCirles, go_urokPile, IN_PROGRESS, InstanceScript::instance, NOT_STARTED, SetBossState(), SolakarState, SolakarSummons, and UrokMobs.
SummonSolakarWave()
void instance_blackrock_spire::instance_blackrock_spireMapScript::SummonSolakarWave (uint8 number) inline
Definition at line 425 of file instance_blackrock_spire.cpp.
         {
             if (number < MAX_WAVE_COUNT)
             {
                 SolakarSummons.push_back(instance->SummonCreature(NPC_ROOKERY_GUARDIAN, SolakarPosLeft));
                 SolakarSummons.push_back(instance->SummonCreature(NPC_ROOKERY_HATCHER, SolakarPosRight));
                 if (number == 0)
                 {
                     if (Creature* FirstHatcher = SolakarSummons.back()) // works because we spawned a hatcher second
                     {
                         FirstHatcher->AI()->Talk(SAY_SOLAKAR_FIRST_HATCHER);
                     }
                 }
             }
             else if (number == MAX_WAVE_COUNT)
             {
                 SolakarSummons.push_back(instance->SummonCreature(NPC_SOLAKAR, SolakarPosBoss));
             }
         }
References InstanceScript::instance, MAX_WAVE_COUNT, NPC_ROOKERY_GUARDIAN, NPC_ROOKERY_HATCHER, NPC_SOLAKAR, SAY_SOLAKAR_FIRST_HATCHER, SolakarPosBoss, SolakarPosLeft, SolakarPosRight, SolakarSummons, and Map::SummonCreature().
Referenced by Update().
Update()
void instance_blackrock_spire::instance_blackrock_spireMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 524 of file instance_blackrock_spire.cpp.
         {
             Events.Update(diff);
             while (uint32 eventId = Events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_DARGONSPIRE_ROOM_STORE:
                         Dragonspireroomstore();
                         Events.ScheduleEvent(EVENT_DARGONSPIRE_ROOM_CHECK, 3000);
                         break;
                     case EVENT_DARGONSPIRE_ROOM_CHECK:
                         Dragonspireroomcheck();
                         if ((GetBossState(DATA_DRAGONSPIRE_ROOM) != DONE))
                             Events.ScheduleEvent(EVENT_DARGONSPIRE_ROOM_CHECK, 3000);
                         break;
                     case EVENT_SOLAKAR_WAVE:
                         SummonSolakarWave(CurrentSolakarWave);
                         if (CurrentSolakarWave < MAX_WAVE_COUNT)
{
                             Events.ScheduleEvent(EVENT_SOLAKAR_WAVE, TIMER_SOLAKAR_WAVE);
                             CurrentSolakarWave++;
                         }
                         break;
                     default:
                         break;
                 }
             }
         }
References CurrentSolakarWave, DATA_DRAGONSPIRE_ROOM, DONE, Dragonspireroomcheck(), Dragonspireroomstore(), EVENT_DARGONSPIRE_ROOM_CHECK, EVENT_DARGONSPIRE_ROOM_STORE, EVENT_SOLAKAR_WAVE, InstanceScript::GetBossState(), MAX_WAVE_COUNT, SummonSolakarWave(), and TIMER_SOLAKAR_WAVE.
Member Data Documentation
CurrentSolakarWave
uint32 instance_blackrock_spire::instance_blackrock_spireMapScript::CurrentSolakarWave = 0
Definition at line 79 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spireMapScript(), SetData(), and Update().
Events
EventMap instance_blackrock_spire::instance_blackrock_spireMapScript::Events protected
Definition at line 695 of file instance_blackrock_spire.cpp.
GeneralDrakkisath
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::GeneralDrakkisath protected
Definition at line 710 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
GizrultheSlavener
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::GizrultheSlavener protected
Definition at line 702 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
go_blackrockaltar
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_blackrockaltar protected
Definition at line 714 of file instance_blackrock_spire.cpp.
go_doors
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_doors protected
Definition at line 712 of file instance_blackrock_spire.cpp.
Referenced by Dragonspireroomcheck(), GetGuidData(), and OnGameObjectCreate().
go_emberseerin
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_emberseerin protected
Definition at line 711 of file instance_blackrock_spire.cpp.
Referenced by Dragonspireroomcheck(), GetGuidData(), and OnGameObjectCreate().
go_emberseerout
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_emberseerout protected
Definition at line 713 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
go_emberseerrunes
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_emberseerrunes[7] protected
Definition at line 716 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
go_portcullis_active
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_portcullis_active protected
Definition at line 718 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
go_roomrunes
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_roomrunes[7] protected
Definition at line 715 of file instance_blackrock_spire.cpp.
Referenced by Dragonspireroomcheck(), Dragonspireroomstore(), GetGuidData(), and OnGameObjectCreate().
go_urokChallenge
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_urokChallenge protected
Definition at line 720 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), OnGameObjectCreate(), and SetData().
go_urokOgreCirles
std::vector<ObjectGuid> instance_blackrock_spire::instance_blackrock_spireMapScript::go_urokOgreCirles protected
Definition at line 721 of file instance_blackrock_spire.cpp.
Referenced by OnGameObjectCreate(), and SetData().
go_urokPile
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::go_urokPile protected
Definition at line 719 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), OnGameObjectCreate(), ProcessEvent(), and SetData().
Gyth
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::Gyth protected
Definition at line 707 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
Halycon
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::Halycon protected
Definition at line 703 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
HighlordOmokk
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::HighlordOmokk protected
Definition at line 696 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
LordVictorNefarius
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::LordVictorNefarius protected
Definition at line 708 of file instance_blackrock_spire.cpp.
Referenced by OnCreatureCreate(), and SetBossState().
MotherSmolderweb
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::MotherSmolderweb protected
Definition at line 699 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
OverlordWyrmthalak
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::OverlordWyrmthalak protected
Definition at line 704 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
PyroguardEmberseer
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::PyroguardEmberseer protected
Definition at line 705 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and ProcessEvent().
QuartermasterZigris
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::QuartermasterZigris protected
Definition at line 701 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
runecreaturelist
GuidVector instance_blackrock_spire::instance_blackrock_spireMapScript::runecreaturelist[7] protected
Definition at line 717 of file instance_blackrock_spire.cpp.
Referenced by Dragonspireroomcheck(), and Dragonspireroomstore().
ShadowHunterVoshgajin
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::ShadowHunterVoshgajin protected
Definition at line 697 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
SolakarState
uint32 instance_blackrock_spire::instance_blackrock_spireMapScript::SolakarState = NOT_STARTED
Definition at line 80 of file instance_blackrock_spire.cpp.
Referenced by GetData(), instance_blackrock_spireMapScript(), and SetData().
SolakarSummons
std::vector<TempSummon*> instance_blackrock_spire::instance_blackrock_spireMapScript::SolakarSummons
Definition at line 81 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spireMapScript(), SetData(), and SummonSolakarWave().
TheBeast
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::TheBeast protected
Definition at line 709 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
UrokDoomhowl
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::UrokDoomhowl protected
Definition at line 700 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
UrokMobs
std::vector<ObjectGuid> instance_blackrock_spire::instance_blackrock_spireMapScript::UrokMobs protected
Definition at line 722 of file instance_blackrock_spire.cpp.
Referenced by OnCreatureCreate(), and SetData().
WarchiefRendBlackhand
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::WarchiefRendBlackhand protected
Definition at line 706 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SetBossState().
WarMasterVoone
ObjectGuid instance_blackrock_spire::instance_blackrock_spireMapScript::WarMasterVoone protected
Definition at line 698 of file instance_blackrock_spire.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp