Azerotcore-wotlk: LastPhaseIceTombTargetSelector Struct Reference
LastPhaseIceTombTargetSelector Struct Reference
Public Member Functions
LastPhaseIceTombTargetSelector (Creature *source)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 240 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
LastPhaseIceTombTargetSelector()
LastPhaseIceTombTargetSelector::LastPhaseIceTombTargetSelector (Creature * source) inline
Definition at line 243 of file boss_sindragosa.cpp.
 : _source(source) { }
Member Function Documentation
operator()()
bool LastPhaseIceTombTargetSelector::operator() (Unit const * target) const inline
Definition at line 244 of file boss_sindragosa.cpp.
     {
         if (!target)
             return false;
         if (target->GetExactDist(_source) > 80.0f)
             return false;
         if (target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (target->HasAura(SPELL_FROST_IMBUED_BLADE))
             return false;
         if (target->IsImmunedToDamageOrSchool(SPELL_SCHOOL_MASK_ALL) || target->HasAura(SPELL_ICE_TOMB_UNTARGETABLE) || target->HasAura(SPELL_ICE_TOMB_DAMAGE) || target->HasAura(SPELL_TANK_MARKER_AURA) || target->HasAuraType(SPELL_AURA_SPIRIT_OF_REDEMPTION))
             return false;
         return target != _source->GetVictim();
     }
References _source, Position::GetExactDist(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasAura(), Unit::HasAuraType(), Unit::IsImmunedToDamageOrSchool(), SPELL_AURA_SPIRIT_OF_REDEMPTION, SPELL_FROST_IMBUED_BLADE, SPELL_ICE_TOMB_DAMAGE, SPELL_ICE_TOMB_UNTARGETABLE, SPELL_SCHOOL_MASK_ALL, SPELL_TANK_MARKER_AURA, and TYPEID_PLAYER.
Member Data Documentation
_source
Creature const* LastPhaseIceTombTargetSelector::_source private
Definition at line 265 of file boss_sindragosa.cpp.
Referenced by mpq::Archive::__repr__(), and operator()().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp