Azerotcore-wotlk: G3D::CoordinateFrame Class Reference
G3D::CoordinateFrame Class Reference
A rigid body RT (rotation-translation) transformation.
#include <CoordinateFrame.h>
Public Member Functions
CoordinateFrame (const Any &any)
Any toAny () const
bool operator== (const CoordinateFrame &other) const
bool operator!= (const CoordinateFrame &other) const
bool fuzzyEq (const CoordinateFrame &other) const
bool fuzzyIsIdentity () const
bool isIdentity () const
CoordinateFrame ()
CoordinateFrame (const Point3 &_translation)
CoordinateFrame (const Matrix3 &rotation, const Point3 &translation)
CoordinateFrame (const Matrix3 &rotation)
CoordinateFrame (const class UprightFrame &f)
std::string toXYZYPRDegreesString () const
CoordinateFrame (class BinaryInput &b)
void deserialize (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
CoordinateFrame (const CoordinateFrame &other)
CoordinateFrame inverse () const
~CoordinateFrame ()
class Matrix4 toMatrix4 () const
void getXYZYPRRadians (float &x, float &y, float &z, float &yaw, float &pitch, float &roll) const
void getXYZYPRDegrees (float &x, float &y, float &z, float &yaw, float &pitch, float &roll) const
std::string toXML () const
float getHeading () const
CoordinateFrame toObjectSpace (const CoordinateFrame &c) const
Vector4 toObjectSpace (const Vector4 &v) const
Vector4 toWorldSpace (const Vector4 &v) const
Point3 pointToWorldSpace (const Point3 &v) const
Point3 pointToObjectSpace (const Point3 &v) const
Vector3 vectorToWorldSpace (const Vector3 &v) const
Vector3 normalToWorldSpace (const Vector3 &v) const
class Ray toObjectSpace (const Ray &r) const
Ray toWorldSpace (const Ray &r) const
Frustum toWorldSpace (const Frustum &f) const
Vector3 vectorToObjectSpace (const Vector3 &v) const
Vector3 normalToObjectSpace (const Vector3 &v) const
void pointToWorldSpace (const Array< Point3 > &v, Array< Point3 > &vout) const
void normalToWorldSpace (const Array< Vector3 > &v, Array< Vector3 > &vout) const
void vectorToWorldSpace (const Array< Vector3 > &v, Array< Vector3 > &vout) const
void pointToObjectSpace (const Array< Point3 > &v, Array< Point3 > &vout) const
void normalToObjectSpace (const Array< Vector3 > &v, Array< Vector3 > &vout) const
void vectorToObjectSpace (const Array< Vector3 > &v, Array< Vector3 > &vout) const
void toWorldSpace (const class AABox &b, class AABox &result) const
class Box toWorldSpace (const class AABox &b) const
class Box toWorldSpace (const class Box &b) const
class Cylinder toWorldSpace (const class Cylinder &b) const
class Capsule toWorldSpace (const class Capsule &b) const
class Plane toWorldSpace (const class Plane &p) const
class Sphere toWorldSpace (const class Sphere &b) const
class Triangle toWorldSpace (const class Triangle &t) const
class Box toObjectSpace (const AABox &b) const
class Box toObjectSpace (const Box &b) const
class Plane toObjectSpace (const Plane &p) const
class Sphere toObjectSpace (const Sphere &b) const
Triangle toObjectSpace (const Triangle &t) const
CoordinateFrame operator* (const CoordinateFrame &other) const
CoordinateFrame operator+ (const Vector3 &v) const
CoordinateFrame operator- (const Vector3 &v) const
void moveTowards (const CoordinateFrame &goal, float maxTranslation, float maxRotation)
void lookAt (const Point3 &target)
void lookAt (const Point3 &target, Vector3 up)
Vector3 lookVector () const
class Ray lookRay () const
Vector3 upVector () const
Vector3 rightVector () const
Vector3 leftVector () const
CoordinateFrame lerp (const CoordinateFrame &other, float alpha) const
Static Public Member Functions
static CoordinateFrame fromXYZYPRRadians (float x, float y, float z, float yaw=0.0f, float pitch=0.0f, float roll=0.0f)
static CoordinateFrame fromXYZYPRDegrees (float x, float y, float z, float yaw=0.0f, float pitch=0.0f, float roll=0.0f)
Public Attributes
Matrix3 rotation
Point3 translation
Detailed Description
A rigid body RT (rotation-translation) transformation.
CoordinateFrame abstracts a 4x4 matrix that maps object space to world space:
v_world = C * v_object
CoordinateFrame::rotation is the upper 3x3 submatrix, CoordinateFrame::translation is the right 3x1 column. The 4th row is always [0 0 0 1], so it isn't stored.
So you don't have to remember which way the multiplication and transformation work, it provides explicit toWorldSpace and toObjectSpace methods. Also, points, vectors (directions), and surface normals transform differently, so they have separate methods.
Some helper functions transform whole primitives like boxes in and out of object space.
Convert to Matrix4 using CoordinateFrame::toMatrix4. You can construct a CoordinateFrame from a Matrix4 using Matrix4::approxCoordinateFrame, however, because a Matrix4 is more general than a CoordinateFrame, some information may be lost.
See also
G3D::UprightFrame, G3D::PhysicsFrame, G3D::Matrix4, G3D::Quat
Definition at line 59 of file CoordinateFrame.h.
Constructor & Destructor Documentation
CoordinateFrame() [1/8]
G3D::CoordinateFrame::CoordinateFrame (const Any & any)
Parameters
any Must be in one of the following forms:
CFrame((matrix3 expr), (Point3 expr))
CFrame::fromXYZYPRDegrees(#, #, #, #, #, #)
CFrame { rotation = (Matrix3 expr), translation = (Point3 expr) }
Point3(...)
Matrix3(...)
Definition at line 45 of file CoordinateFrame.cpp.
{
     *this = CFrame();
     const std::string& n = toUpper(any.name());
     if (beginsWith(n, "VECTOR3") || beginsWith(n, "POINT3")) {
         translation = Point3(any);
     } else if (beginsWith(n, "MATRIX3")) {
         rotation = Matrix3(any);
     } else if (beginsWith(n, "MATRIX4")) {
         *this = Matrix4(any).approxCoordinateFrame();
     } else if ((n == "CFRAME") || (n == "COORDINATEFRAME")) {
         any.verifyType(Any::TABLE, Any::ARRAY);
         if (any.type() == Any::ARRAY) {
             any.verifySize(2);
             rotation    = any[0];
             translation = any[1];
         } else {
             AnyTableReader r(any);
             r.getIfPresent("translation", translation);
             r.getIfPresent("rotation", rotation);
             r.verifyDone();
         }
     } else if (beginsWith(n, "PHYSICSFRAME") || beginsWith(n, "PFRAME")) {
         *this = PhysicsFrame(any);
 //    } else if (beginsWith(n, "UPRIGHTFRAME") || beginsWith(n, "UFRAME")) {
 //        *this = UprightFrame(any);
     } else {
         any.verifyName("CFrame::fromXYZYPRDegrees", "CoordinateFrame::fromXYZYPRDegrees");
         any.verifyType(Any::ARRAY);
         any.verifySize(3, 6);
         int s = any.size();
         *this = fromXYZYPRDegrees(any[0], any[1], any[2],
                                   (s > 3) ? (float)any[3].number() : 0.0f,
                                   (s > 4) ? (float)any[4].number() : 0.0f,
                                   (s > 5) ? (float)any[5].number() : 0.0f);
     }
 }
References G3D::any(), G3D::Matrix4::approxCoordinateFrame(), G3D::Any::ARRAY, G3D::beginsWith(), fromXYZYPRDegrees(), G3D::AnyTableReader::getIfPresent(), rotation, G3D::Any::TABLE, G3D::toUpper(), translation, and G3D::AnyTableReader::verifyDone().
CoordinateFrame() [2/8]
G3D::CoordinateFrame::CoordinateFrame ()
Initializes to the identity coordinate frame.
Definition at line 110 of file CoordinateFrame.cpp.
                                  :
     rotation(Matrix3::identity()), translation(Vector3::zero()) {
 }
Referenced by fromXYZYPRRadians(), lerp(), operator*(), operator+(), and operator-().
CoordinateFrame() [3/8]
G3D::CoordinateFrame::CoordinateFrame (const Point3 & _translation) inline
Definition at line 99 of file CoordinateFrame.h.
                                                 :
         rotation(Matrix3::identity()), translation(_translation) {
     }
CoordinateFrame() [4/8]
G3D::CoordinateFrame::CoordinateFrame (const Matrix3 & rotation, const Point3 & translation) inline
Definition at line 103 of file CoordinateFrame.h.
                                                                         :
         rotation(rotation), translation(translation) {
     }
CoordinateFrame() [5/8]
G3D::CoordinateFrame::CoordinateFrame (const Matrix3 & rotation) inline
Definition at line 107 of file CoordinateFrame.h.
                                              :
         rotation(rotation), translation(Point3::zero()) {
     }
CoordinateFrame() [6/8]
G3D::CoordinateFrame::CoordinateFrame (const class UprightFrame & f)
Definition at line 105 of file CoordinateFrame.cpp.
{
     *this = f.toCoordinateFrame();
 }
References f().
CoordinateFrame() [7/8]
G3D::CoordinateFrame::CoordinateFrame (class BinaryInput & b)
Definition at line 340 of file CoordinateFrame.cpp.
                                                      : rotation(Matrix3::zero()) {
     deserialize(b);
 }
References b, and deserialize().
CoordinateFrame() [8/8]
G3D::CoordinateFrame::CoordinateFrame (const CoordinateFrame & other) inline
Definition at line 130 of file CoordinateFrame.h.
                                                   :
         rotation(other.rotation), translation(other.translation) {}
~CoordinateFrame()
G3D::CoordinateFrame::~CoordinateFrame () inline
Definition at line 143 of file CoordinateFrame.h.
 {}
Member Function Documentation
deserialize()
void G3D::CoordinateFrame::deserialize (class BinaryInput & b)
Definition at line 345 of file CoordinateFrame.cpp.
{
     rotation.deserialize(b);
     translation.deserialize(b);
 }
References b, G3D::Matrix3::deserialize(), G3D::Vector3::deserialize(), rotation, and translation.
Referenced by CoordinateFrame(), and G3D::GCamera::deserialize().
fromXYZYPRDegrees()
CoordinateFrame G3D::CoordinateFrame::fromXYZYPRDegrees (float x, float y, float z, float yaw = 0.0f, float pitch = 0.0f, float roll = 0.0f) static
Construct a coordinate frame from translation = (x,y,z) and rotations (in that order) about Y, object space X, object space Z. Note that because object-space axes are used, these are not equivalent to Euler angles; they are known as Tait-Bryan rotations and are more convenient for intuitive positioning.
Definition at line 142 of file CoordinateFrame.cpp.
{
     return fromXYZYPRRadians(x, y, z, toRadians(yaw), toRadians(pitch), toRadians(roll));
 }
References fromXYZYPRRadians(), G3D::toRadians(), G3D::x, G3D::y, and G3D::z.
Referenced by CoordinateFrame(), and G3D::AnyVal::deserialize().
fromXYZYPRRadians()
CoordinateFrame G3D::CoordinateFrame::fromXYZYPRRadians (float x, float y, float z, float yaw = 0.0f, float pitch = 0.0f, float roll = 0.0f) static
Definition at line 114 of file CoordinateFrame.cpp.
{
     const Matrix3& rotation = Matrix3::fromEulerAnglesYXZ(yaw, pitch, roll);
     const Vector3 translation(x, y, z);
     return CoordinateFrame(rotation, translation);
 }
References CoordinateFrame(), G3D::Matrix3::fromEulerAnglesYXZ(), rotation, translation, G3D::x, G3D::y, and G3D::z.
Referenced by fromXYZYPRDegrees().
fuzzyEq()
bool G3D::CoordinateFrame::fuzzyEq (const CoordinateFrame & other) const
Definition at line 153 of file CoordinateFrame.cpp.
{
     for (int c = 0; c < 3; ++c) {
         for (int r = 0; r < 3; ++r) {
             if (! G3D::fuzzyEq(other.rotation[r][c], rotation[r][c])) {
                 return false;
             }
         }
         if (! G3D::fuzzyEq(translation[c], other.translation[c])) {
             return false;
         }
     }
     return true;
 }
References mpq::c, G3D::fuzzyEq(), rotation, and translation.
fuzzyIsIdentity()
bool G3D::CoordinateFrame::fuzzyIsIdentity () const
Definition at line 170 of file CoordinateFrame.cpp.
{
     const Matrix3& I = Matrix3::identity();
     for (int c = 0; c < 3; ++c) {
         for (int r = 0; r < 3; ++r) {
             if (fuzzyNe(I[r][c], rotation[r][c])) {
                 return false;
             }
         }
         if (fuzzyNe(translation[c], 0)) {
             return false;
         }
     }
     return true;
 }
References mpq::c, G3D::fuzzyNe(), I, G3D::Matrix3::identity(), rotation, and translation.
getHeading()
float G3D::CoordinateFrame::getHeading () const inline
Returns the heading of the lookVector as an angle in radians relative to the world -z axis. That is, a counter-clockwise heading where north (-z) is 0 and west (-x) is PI/2.
Note that the heading ignores the Y axis, so an inverted object has an inverted heading.
Definition at line 166 of file CoordinateFrame.h.
{
         Vector3 look = rotation.column(2);
         float angle = -(float) atan2(-look.x, look.z);
         return angle;
     }
References G3D::Matrix3::column(), rotation, G3D::Vector3::x, and G3D::Vector3::z.
getXYZYPRDegrees()
void G3D::CoordinateFrame::getXYZYPRDegrees (float & x, float & y, float & z, float & yaw, float & pitch, float & roll) const
Definition at line 133 of file CoordinateFrame.cpp.
{
     getXYZYPRRadians(x, y, z, yaw, pitch, roll);
     yaw   = toDegrees(yaw);
     pitch = toDegrees(pitch);
     roll  = toDegrees(roll);
 }
References getXYZYPRRadians(), G3D::toDegrees(), G3D::x, G3D::y, and G3D::z.
Referenced by toAny(), and toXYZYPRDegreesString().
getXYZYPRRadians()
void G3D::CoordinateFrame::getXYZYPRRadians (float & x, float & y, float & z, float & yaw, float & pitch, float & roll) const
Definition at line 123 of file CoordinateFrame.cpp.
{
     x = translation.x;
     y = translation.y;
     z = translation.z;
     rotation.toEulerAnglesYXZ(yaw, pitch, roll);
 }
References rotation, G3D::Matrix3::toEulerAnglesYXZ(), translation, G3D::x, G3D::Vector3::x, G3D::y, G3D::Vector3::y, G3D::Vector3::z, and G3D::z.
Referenced by getXYZYPRDegrees().
inverse()
CoordinateFrame G3D::CoordinateFrame::inverse () const inline
Computes the inverse of this coordinate frame.
Definition at line 136 of file CoordinateFrame.h.
{
         CoordinateFrame out;
         out.rotation = rotation.transpose();
         out.translation = -out.rotation * translation;
         return out;
     }
References rotation, translation, and G3D::Matrix3::transpose().
Referenced by toObjectSpace().
isIdentity()
bool G3D::CoordinateFrame::isIdentity () const
Definition at line 188 of file CoordinateFrame.cpp.
{
     return
         (translation == Vector3::zero()) &&
         (rotation == Matrix3::identity());
 }
References G3D::Matrix3::identity(), rotation, translation, and G3D::Vector3::zero().
leftVector()
Vector3 G3D::CoordinateFrame::leftVector () const inline
If a viewer looks along the look vector, this is the viewer's "left". Useful for strafing motions and building alternative coordinate frames.
Definition at line 336 of file CoordinateFrame.h.
{
         return -rotation.column(0);
     }
References G3D::Matrix3::column(), and rotation.
lerp()
CoordinateFrame G3D::CoordinateFrame::lerp (const CoordinateFrame & other, float alpha) const
Linearly interpolates between two coordinate frames, using Quat::slerp for the rotations.
See also
moveTowards
Definition at line 419 of file CoordinateFrame.cpp.
{
     if (alpha == 1.0f) {
         return other;
     } else if (alpha == 0.0f) {
         return *this;
     } else {
         const Quat q1(this->rotation);
         const Quat q2(other.rotation);
         return CoordinateFrame(
             q1.slerp(q2, alpha).toRotationMatrix(),
             translation * (1 - alpha) + other.translation * alpha);
     }
 }
References CoordinateFrame(), rotation, G3D::Quat::slerp(), G3D::Quat::toRotationMatrix(), and translation.
lookAt() [1/2]
void G3D::CoordinateFrame::lookAt (const Point3 & target)
Definition at line 377 of file CoordinateFrame.cpp.
{
     lookAt(target, Vector3::unitY());
 }
References G3D::Vector3::unitY().
Referenced by G3D::GCamera::lookAt().
lookAt() [2/2]
void G3D::CoordinateFrame::lookAt (const Point3 & target, Vector3 up)
Definition at line 382 of file CoordinateFrame.cpp.
{
     up = up.direction();
     Vector3 look = (target - translation).direction();
     if (fabs(look.dot(up)) > .99f) {
         up = Vector3::unitX();
         if (fabs(look.dot(up)) > .99f) {
             up = Vector3::unitY();
         }
     }
     up -= look * look.dot(up);
     up = up.direction();
     Vector3 z = -look;
     Vector3 x = -z.cross(up);
     x = x.direction();
     Vector3 y = z.cross(x);
     rotation.setColumn(0, x);
     rotation.setColumn(1, y);
     rotation.setColumn(2, z);
 }
References G3D::Vector3::dot(), rotation, G3D::Matrix3::setColumn(), translation, G3D::Vector3::unitX(), G3D::Vector3::unitY(), G3D::x, G3D::y, and G3D::z.
lookRay()
Ray G3D::CoordinateFrame::lookRay () const
Returns the ray starting at the camera origin travelling in direction CoordinateFrame::lookVector.
Definition at line 148 of file CoordinateFrame.cpp.
{
     return Ray::fromOriginAndDirection(translation, lookVector());
 }
References G3D::Ray::fromOriginAndDirection(), lookVector(), and translation.
lookVector()
Vector3 G3D::CoordinateFrame::lookVector () const inline
The direction this camera is looking (its negative z axis)
Definition at line 316 of file CoordinateFrame.h.
{
         return -rotation.column(2);
     }
References G3D::Matrix3::column(), and rotation.
Referenced by lookRay(), G3D::GCamera::unproject(), and G3D::UprightFrame::UprightFrame().
moveTowards()
void G3D::CoordinateFrame::moveTowards (const CoordinateFrame & goal, float maxTranslation, float maxRotation)
Transform this coordinate frame towards goal, but not past it, goverened by maximum rotation and translations. This is a useful alternative to lerp, especially if the goal is expected to change every transformation step so that constant start and end positions will not be available.
Parameters
goal Step from this towards goal
maxTranslation Meters
maxRotation Radians
See also
lerp
Definition at line 411 of file CoordinateFrame.cpp.
{
     translation.moveTowards(goal.translation, maxTranslation);
     Quat q(rotation);
     q.moveTowards(Quat(goal.rotation), maxRotation);
     rotation = Matrix3(q);
 }
References G3D::Quat::moveTowards(), G3D::Vector3::moveTowards(), rotation, and translation.
normalToObjectSpace() [1/2]
void G3D::CoordinateFrame::normalToObjectSpace (const Array< Vector3 > & v, Array< Vector3 > & vout) const
Definition at line 474 of file CoordinateFrame.cpp.
{
     vout.resize(v.size());
     for (int i = v.size() - 1; i >= 0; --i) {
         vout[i] = normalToObjectSpace(v[i]);
     }
 }
References normalToObjectSpace(), G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
normalToObjectSpace() [2/2]
Vector3 G3D::CoordinateFrame::normalToObjectSpace (const Vector3 & v) const inline
Definition at line 237 of file CoordinateFrame.h.
{
         // Multiply on the left (same as rotation.transpose() * v)
         return v * rotation;
     }
References rotation.
Referenced by normalToObjectSpace(), and toObjectSpace().
normalToWorldSpace() [1/2]
void G3D::CoordinateFrame::normalToWorldSpace (const Array< Vector3 > & v, Array< Vector3 > & vout) const
Definition at line 447 of file CoordinateFrame.cpp.
{
     vout.resize(v.size());
     for (int i = 0; i < v.size(); ++i) {
         vout[i] = normalToWorldSpace(v[i]);
     }
 }
References normalToWorldSpace(), G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
normalToWorldSpace() [2/2]
Vector3 G3D::CoordinateFrame::normalToWorldSpace (const Vector3 & v) const inline
Definition at line 219 of file CoordinateFrame.h.
{
         return rotation * v;
     }
References rotation.
Referenced by G3D::Capsule::getRandomSurfacePoint(), G3D::Cylinder::getRandomSurfacePoint(), normalToWorldSpace(), and G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox().
operator!=()
bool G3D::CoordinateFrame::operator!= (const CoordinateFrame & other) const inline
Definition at line 84 of file CoordinateFrame.h.
{
         return !(*this == other);
     }
operator*()
CoordinateFrame G3D::CoordinateFrame::operator* (const CoordinateFrame & other) const inline
Compose: create the transformation that is other followed by this.
Definition at line 281 of file CoordinateFrame.h.
{
         return CoordinateFrame(rotation * other.rotation,
                                pointToWorldSpace(other.translation));
     }
References CoordinateFrame(), pointToWorldSpace(), rotation, and translation.
operator+()
CoordinateFrame G3D::CoordinateFrame::operator+ (const Vector3 & v) const inline
Definition at line 286 of file CoordinateFrame.h.
{
         return CoordinateFrame(rotation, translation + v);
     }
References CoordinateFrame(), rotation, and translation.
operator-()
CoordinateFrame G3D::CoordinateFrame::operator- (const Vector3 & v) const inline
Definition at line 290 of file CoordinateFrame.h.
{
         return CoordinateFrame(rotation, translation - v);
     }
References CoordinateFrame(), rotation, and translation.
operator==()
bool G3D::CoordinateFrame::operator== (const CoordinateFrame & other) const inline
Definition at line 80 of file CoordinateFrame.h.
{
         return (translation == other.translation) && (rotation == other.rotation);
     }
References rotation, and translation.
pointToObjectSpace() [1/2]
void G3D::CoordinateFrame::pointToObjectSpace (const Array< Point3 > & v, Array< Point3 > & vout) const
Definition at line 465 of file CoordinateFrame.cpp.
{
     vout.resize(v.size());
     for (int i = v.size() - 1; i >= 0; --i) {
         vout[i] = pointToObjectSpace(v[i]);
     }
 }
References pointToObjectSpace(), G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
pointToObjectSpace() [2/2]
Point3 G3D::CoordinateFrame::pointToObjectSpace (const Point3 & v) const inline
Transforms the point into object space. Assumes that the rotation matrix is orthonormal.
Definition at line 201 of file CoordinateFrame.h.
{
         float p[3];
         p[0] = v[0] - translation[0];
         p[1] = v[1] - translation[1];
         p[2] = v[2] - translation[2];
         debugAssert(G3D::fuzzyEq(fabsf(rotation.determinant()), 1.0f));
         return Point3(rotation[0][0] * p[0] + rotation[1][0] * p[1] + rotation[2][0] * p[2],
                       rotation[0][1] * p[0] + rotation[1][1] * p[1] + rotation[2][1] * p[2],
                       rotation[0][2] * p[0] + rotation[1][2] * p[1] + rotation[2][2] * p[2]);
     }
References debugAssert, G3D::Matrix3::determinant(), G3D::fuzzyEq(), rotation, and translation.
Referenced by G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), pointToObjectSpace(), and toObjectSpace().
pointToWorldSpace() [1/2]
void G3D::CoordinateFrame::pointToWorldSpace (const Array< Point3 > & v, Array< Point3 > & vout) const
Definition at line 438 of file CoordinateFrame.cpp.
{
     vout.resize(v.size());
     for (int i = 0; i < v.size(); ++i) {
         vout[i] = pointToWorldSpace(v[i]);
     }
 }
References pointToWorldSpace(), G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
pointToWorldSpace() [2/2]
Point3 G3D::CoordinateFrame::pointToWorldSpace (const Point3 & v) const inline
Transforms the point into world space.
Definition at line 191 of file CoordinateFrame.h.
{
         return Point3
         (rotation[0][0] * v[0] + rotation[0][1] * v[1] + rotation[0][2] * v[2] + translation[0],
          rotation[1][0] * v[0] + rotation[1][1] * v[1] + rotation[1][2] * v[2] + translation[1],
          rotation[2][0] * v[0] + rotation[2][1] * v[1] + rotation[2][2] * v[2] + translation[2]);
     }
References rotation, and translation.
Referenced by G3D::MeshAlg::generateGrid(), G3D::GCamera::getFarViewportCorners(), G3D::GCamera::getNearViewportCorners(), G3D::Capsule::getRandomSurfacePoint(), G3D::Cylinder::getRandomSurfacePoint(), operator*(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), pointToWorldSpace(), G3D::Capsule::randomInteriorPoint(), G3D::Cylinder::randomInteriorPoint(), and toWorldSpace().
rightVector()
Vector3 G3D::CoordinateFrame::rightVector () const inline
Definition at line 328 of file CoordinateFrame.h.
{
         return rotation.column(0);
     }
References G3D::Matrix3::column(), and rotation.
serialize()
void G3D::CoordinateFrame::serialize (class BinaryOutput & b) const
Definition at line 351 of file CoordinateFrame.cpp.
{
     rotation.serialize(b);
     translation.serialize(b);
 }
References b, rotation, G3D::Matrix3::serialize(), G3D::Vector3::serialize(), and translation.
Referenced by G3D::GCamera::serialize().
toAny()
Any G3D::CoordinateFrame::toAny () const
Converts the CFrame to an Any.
Definition at line 87 of file CoordinateFrame.cpp.
{
     float x, y, z, yaw, pitch, roll;
     getXYZYPRDegrees(x, y, z, yaw, pitch, roll);
     Any a(Any::ARRAY, "CFrame::fromXYZYPRDegrees");
     a.append(x, y, z);
     if ( ! G3D::fuzzyEq(yaw, 0.0f) || ! G3D::fuzzyEq(pitch, 0.0f) || ! G3D::fuzzyEq(roll, 0.0f)) {
         a.append(yaw);
         if (! G3D::fuzzyEq(pitch, 0.0f) || ! G3D::fuzzyEq(roll, 0.0f)) {
             a.append(pitch);
             if (! G3D::fuzzyEq(roll, 0.0f)) {
                 a.append(roll);
             }
         }
     }
     return a;
 }
References mpq::a, G3D::Any::ARRAY, G3D::fuzzyEq(), getXYZYPRDegrees(), G3D::x, G3D::y, and G3D::z.
Referenced by G3D::PhysicsFrame::toAny().
toMatrix4()
Matrix4 G3D::CoordinateFrame::toMatrix4 () const
See also Matrix4::approxCoordinateFrame
Definition at line 195 of file CoordinateFrame.cpp.
{
     return Matrix4(*this);
 }
toObjectSpace() [1/8]
Box G3D::CoordinateFrame::toObjectSpace (const AABox & b) const
Definition at line 335 of file CoordinateFrame.cpp.
{
     return toObjectSpace(Box(b));
 }
References b, and toObjectSpace().
toObjectSpace() [2/8]
Box G3D::CoordinateFrame::toObjectSpace (const Box & b) const
Definition at line 330 of file CoordinateFrame.cpp.
{
     return inverse().toWorldSpace(b);
 }
References b, inverse(), and toWorldSpace().
toObjectSpace() [3/8]
CoordinateFrame G3D::CoordinateFrame::toObjectSpace (const CoordinateFrame & c) const inline
Takes the coordinate frame into object space. this->inverse() * c
Definition at line 176 of file CoordinateFrame.h.
{
         return this->inverse() * c;
     }
References mpq::c, and inverse().
Referenced by toObjectSpace().
toObjectSpace() [4/8]
Plane G3D::CoordinateFrame::toObjectSpace (const Plane & p) const
Definition at line 210 of file CoordinateFrame.cpp.
{
     // TODO
     Vector3 N, P;
     double d;
     p.getEquation(N, d);
     P = N * (float)d;
     P = pointToObjectSpace(P);
     N = normalToObjectSpace(N);
     debugAssertM(isFinite(d), "Not implemented for infinite planes");
     return Plane(N, P);
 }
References mpq::d, debugAssertM, G3D::Plane::getEquation(), G3D::isFinite(), normalToObjectSpace(), P, and pointToObjectSpace().
toObjectSpace() [5/8]
Ray G3D::CoordinateFrame::toObjectSpace (const Ray & r) const
Definition at line 372 of file CoordinateFrame.cpp.
{
     return Ray::fromOriginAndDirection(pointToObjectSpace(r.origin()), vectorToObjectSpace(r.direction()));
 }
References G3D::Ray::direction(), G3D::Ray::fromOriginAndDirection(), G3D::Ray::origin(), pointToObjectSpace(), and vectorToObjectSpace().
toObjectSpace() [6/8]
Sphere G3D::CoordinateFrame::toObjectSpace (const Sphere & b) const
Definition at line 362 of file CoordinateFrame.cpp.
{
     return Sphere(pointToObjectSpace(b.center), b.radius);
 }
References b, and pointToObjectSpace().
toObjectSpace() [7/8]
Triangle G3D::CoordinateFrame::toObjectSpace (const Triangle & t) const
Definition at line 263 of file CoordinateFrame.cpp.
{
     return Triangle(pointToObjectSpace(t.vertex(0)),
         pointToObjectSpace(t.vertex(1)),
         pointToObjectSpace(t.vertex(2)));
 }
References pointToObjectSpace(), and G3D::Triangle::vertex().
toObjectSpace() [8/8]
Vector4 G3D::CoordinateFrame::toObjectSpace (const Vector4 & v) const inline
Definition at line 180 of file CoordinateFrame.h.
{
         return this->inverse().toWorldSpace(v);
     }
References inverse(), and toWorldSpace().
toWorldSpace() [1/11]
class Box G3D::CoordinateFrame::toWorldSpace (const class AABox & b) const
toWorldSpace() [2/11]
void G3D::CoordinateFrame::toWorldSpace (const class AABox & b, class AABox & result) const
toWorldSpace() [3/11]
class Box G3D::CoordinateFrame::toWorldSpace (const class Box & b) const
toWorldSpace() [4/11]
class Capsule G3D::CoordinateFrame::toWorldSpace (const class Capsule & b) const
toWorldSpace() [5/11]
class Cylinder G3D::CoordinateFrame::toWorldSpace (const class Cylinder & b) const
toWorldSpace() [6/11]
class Plane G3D::CoordinateFrame::toWorldSpace (const class Plane & p) const
toWorldSpace() [7/11]
class Sphere G3D::CoordinateFrame::toWorldSpace (const class Sphere & b) const
toWorldSpace() [8/11]
class Triangle G3D::CoordinateFrame::toWorldSpace (const class Triangle & t) const
toWorldSpace() [9/11]
Frustum G3D::CoordinateFrame::toWorldSpace (const Frustum & f) const
Definition at line 223 of file CoordinateFrame.cpp.
{
     Frustum g;
     g.vertexPos.resize(f.vertexPos.size());
     g.faceArray.resize(f.faceArray.size());
     for (int i = 0; i < f.vertexPos.size(); ++i) {
         g.vertexPos[i] = toWorldSpace(f.vertexPos[i]);
     }
     for (int i = 0; i < f.faceArray.size(); ++i) {
         g.faceArray[i].plane = toWorldSpace(f.faceArray[i].plane);
         for (int j = 0; j < 4; ++j) {
             g.faceArray[i].vertexIndex[j] = f.faceArray[i].vertexIndex[j];
         }
     }
     return g;
 }
References f(), G3D::Frustum::faceArray, toWorldSpace(), and G3D::Frustum::vertexPos.
toWorldSpace() [10/11]
Ray G3D::CoordinateFrame::toWorldSpace (const Ray & r) const
Definition at line 367 of file CoordinateFrame.cpp.
{
     return Ray::fromOriginAndDirection(pointToWorldSpace(r.origin()), vectorToWorldSpace(r.direction()));
 }
References G3D::Ray::direction(), G3D::Ray::fromOriginAndDirection(), G3D::Ray::origin(), pointToWorldSpace(), and vectorToWorldSpace().
toWorldSpace() [11/11]
Vector4 G3D::CoordinateFrame::toWorldSpace (const Vector4 & v) const inline
Definition at line 184 of file CoordinateFrame.h.
{
         return Vector4(rotation * Vector3(v.x, v.y, v.z) + translation * v.w, v.w);
     }
References rotation, translation, G3D::Vector4::w, G3D::Vector4::x, G3D::Vector4::y, and G3D::Vector4::z.
Referenced by G3D::GCamera::frustum(), toObjectSpace(), and toWorldSpace().
toXML()
std::string G3D::CoordinateFrame::toXML () const
Produces an XML serialization of this coordinate frame.
Deprecated:
Definition at line 200 of file CoordinateFrame.cpp.
{
     return G3D::format(
         "<COORDINATEFRAME>\n  %lf,%lf,%lf,%lf,\n  %lf,%lf,%lf,%lf,\n  %lf,%lf,%lf,%lf,\n  %lf,%lf,%lf,%lf\n</COORDINATEFRAME>\n",
         rotation[0][0], rotation[0][1], rotation[0][2], translation.x,
         rotation[1][0], rotation[1][1], rotation[1][2], translation.y,
         rotation[2][0], rotation[2][1], rotation[2][2], translation.z,
         0.0, 0.0, 0.0, 1.0);
 }
References G3D::format(), rotation, translation, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
toXYZYPRDegreesString()
std::string G3D::CoordinateFrame::toXYZYPRDegreesString () const
Definition at line 36 of file CoordinateFrame.cpp.
{
     float x,y,z,yaw,pitch,roll;
     getXYZYPRDegrees(x,y,z,yaw,pitch,roll);
     return format("CFrame::fromXYZYPRDegrees(% 5.1ff, % 5.1ff, % 5.1ff, % 5.1ff, % 5.1ff, % 5.1ff)",
                   x,y,z,yaw,pitch,roll);
 }
References G3D::format(), getXYZYPRDegrees(), G3D::x, G3D::y, and G3D::z.
upVector()
Vector3 G3D::CoordinateFrame::upVector () const inline
Up direction for this camera (its y axis).
Definition at line 324 of file CoordinateFrame.h.
{
         return rotation.column(1);
     }
References G3D::Matrix3::column(), and rotation.
vectorToObjectSpace() [1/2]
void G3D::CoordinateFrame::vectorToObjectSpace (const Array< Vector3 > & v, Array< Vector3 > & vout) const
Definition at line 483 of file CoordinateFrame.cpp.
{
     vout.resize(v.size());
     for (int i = v.size() - 1; i >= 0; --i) {
         vout[i] = vectorToObjectSpace(v[i]);
     }
 }
References G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::Array< T, MIN_ELEMENTS >::size(), and vectorToObjectSpace().
vectorToObjectSpace() [2/2]
Vector3 G3D::CoordinateFrame::vectorToObjectSpace (const Vector3 & v) const inline
Transforms the vector into object space (no translation).
Definition at line 232 of file CoordinateFrame.h.
{
         // Multiply on the left (same as rotation.transpose() * v)
         return v * rotation;
     }
References rotation.
Referenced by toObjectSpace(), and vectorToObjectSpace().
vectorToWorldSpace() [1/2]
void G3D::CoordinateFrame::vectorToWorldSpace (const Array< Vector3 > & v, Array< Vector3 > & vout) const
Definition at line 456 of file CoordinateFrame.cpp.
{
     vout.resize(v.size());
     for (int i = v.size() - 1; i >= 0; --i) {
         vout[i] = vectorToWorldSpace(v[i]);
     }
 }
References G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::Array< T, MIN_ELEMENTS >::size(), and vectorToWorldSpace().
vectorToWorldSpace() [2/2]
Vector3 G3D::CoordinateFrame::vectorToWorldSpace (const Vector3 & v) const inline
Transforms the vector into world space (no translation).
Definition at line 215 of file CoordinateFrame.h.
{
         return rotation * v;
     }
References rotation.
Referenced by toWorldSpace(), vectorToWorldSpace(), and G3D::GCamera::worldRay().
Member Data Documentation
rotation
Matrix3 G3D::CoordinateFrame::rotation
Takes object space points to world space.
Definition at line 63 of file CoordinateFrame.h.
Referenced by G3D::Matrix4::approxCoordinateFrame(), CoordinateFrame(), deserialize(), G3D::AnyVal::deserialize(), fromXYZYPRRadians(), G3D::GCamera::frustum(), fuzzyEq(), fuzzyIsIdentity(), getHeading(), G3D::Box::getLocalFrame(), G3D::Capsule::getReferenceFrame(), G3D::Cylinder::getReferenceFrame(), getXYZYPRRadians(), inverse(), isIdentity(), leftVector(), lerp(), lookAt(), lookVector(), G3D::Matrix4::Matrix4(), moveTowards(), normalToObjectSpace(), normalToWorldSpace(), operator*(), operator+(), operator-(), operator==(), G3D::PhysicsFrame::PhysicsFrame(), pointToObjectSpace(), pointToWorldSpace(), rightVector(), serialize(), G3D::UprightFrame::toCoordinateFrame(), toWorldSpace(), toXML(), upVector(), vectorToObjectSpace(), and vectorToWorldSpace().
translation
Point3 G3D::CoordinateFrame::translation
The origin of this coordinate frame in world space (or its parent's space, if nested).
Definition at line 66 of file CoordinateFrame.h.
Referenced by G3D::Matrix4::approxCoordinateFrame(), CoordinateFrame(), deserialize(), G3D::AnyVal::deserialize(), fromXYZYPRRadians(), G3D::GCamera::frustum(), fuzzyEq(), fuzzyIsIdentity(), G3D::Box::getLocalFrame(), G3D::Capsule::getReferenceFrame(), G3D::Cylinder::getReferenceFrame(), getXYZYPRRadians(), inverse(), isIdentity(), lerp(), lookAt(), lookRay(), G3D::Matrix4::Matrix4(), moveTowards(), operator*(), operator+(), operator-(), operator==(), G3D::PhysicsFrame::PhysicsFrame(), pointToObjectSpace(), pointToWorldSpace(), serialize(), G3D::GCamera::setPosition(), G3D::UprightFrame::toCoordinateFrame(), toWorldSpace(), toXML(), G3D::UprightFrame::UprightFrame(), and G3D::GCamera::worldRay().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/CoordinateFrame.h
deps/g3dlite/source/CoordinateFrame.cpp