Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/arena_inlines_a.h File Reference
arena_inlines_a.h File Reference
Functions
static unsigned arena_ind_get (const arena_t *arena)
static void arena_internal_add (arena_t *arena, size_t size)
static void arena_internal_sub (arena_t *arena, size_t size)
static size_t arena_internal_get (arena_t *arena)
static bool arena_prof_accum (tsdn_t *tsdn, arena_t *arena, uint64_t accumbytes)
static void percpu_arena_update (tsd_t *tsd, unsigned cpu)
Function Documentation
arena_ind_get()
static unsigned arena_ind_get (const arena_t * arena) inline static
Definition at line 5 of file arena_inlines_a.h.
{
     return base_ind_get(arena->base);
 }
References arena, arena_s::base, and base_ind_get().
Referenced by arena_background_thread_info_get(), arena_choose_hard(), arena_choose_impl(), arena_cleanup(), arena_decay_ticks(), arena_is_auto(), arenas_lookup_ctl(), CTL_RO_NL_GEN(), extent_alloc_wrapper_hard(), extent_arena_set(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_purge_forced_impl(), extent_purge_lazy_impl(), extent_split_impl(), iarena_cleanup(), and percpu_arena_update().
arena_internal_add()
static void arena_internal_add (arena_t * arena, size_t size) inline static
Definition at line 10 of file arena_inlines_a.h.
{
     atomic_fetch_add_zu(&arena->stats.internal, size, ATOMIC_RELAXED);
 }
References arena, ATOMIC_RELAXED, arena_stats_s::internal, and arena_s::stats.
Referenced by iallocztm(), and ipallocztm().
arena_internal_get()
static size_t arena_internal_get (arena_t * arena) inline static
Definition at line 20 of file arena_inlines_a.h.
{
     return atomic_load_zu(&arena->stats.internal, ATOMIC_RELAXED);
 }
References arena, ATOMIC_RELAXED, arena_stats_s::internal, and arena_s::stats.
Referenced by arena_stats_merge().
arena_internal_sub()
static void arena_internal_sub (arena_t * arena, size_t size) inline static
Definition at line 15 of file arena_inlines_a.h.
{
     atomic_fetch_sub_zu(&arena->stats.internal, size, ATOMIC_RELAXED);
 }
References arena, ATOMIC_RELAXED, arena_stats_s::internal, and arena_s::stats.
Referenced by idalloctm().
arena_prof_accum()
static bool arena_prof_accum (tsdn_t * tsdn, arena_t * arena, uint64_t accumbytes) inline static
Definition at line 25 of file arena_inlines_a.h.
{
     cassert(config_prof);
     if (likely(prof_interval == 0 || !prof_active_get_unlocked())) {
         return false;
     }
     return prof_accum_add(tsdn, &arena->prof_accum, accumbytes);
 }
References arena, cassert(), config_prof, likely, arena_s::prof_accum, prof_accum_add(), prof_active_get_unlocked(), and prof_interval.
Referenced by arena_malloc_small(), arena_tcache_fill_small(), large_palloc(), tcache_bin_flush_large(), tcache_bin_flush_small(), and tcache_flush_cache().
percpu_arena_update()
static void percpu_arena_update (tsd_t * tsd, unsigned cpu) inline static
Definition at line 36 of file arena_inlines_a.h.
{
     assert(have_percpu_arena);
     arena_t *oldarena = tsd_arena_get(tsd);
     assert(oldarena != NULL);
     unsigned oldind = arena_ind_get(oldarena);
     if (oldind != cpu) {
         unsigned newind = cpu;
         arena_t *newarena = arena_get(tsd_tsdn(tsd), newind, true);
         assert(newarena != NULL);
         /* Set new arena/tcache associations. */
         arena_migrate(tsd, oldind, newind);
         tcache_t *tcache = tcache_get(tsd);
         if (tcache != NULL) {
             tcache_arena_reassociate(tsd_tsdn(tsd), tcache,
                 newarena);
         }
     }
 }
References arena_get(), arena_ind_get(), arena_migrate, assert(), have_percpu_arena, NULL, tcache_arena_reassociate, tcache_get(), and tsd_tsdn().
Referenced by arena_choose_impl().