Azerotcore-wotlk: ServerPktHeader Struct Reference
ServerPktHeader Struct Reference
#include <ServerPktHeader.h>
Public Member Functions
ServerPktHeader (uint32 size, uint16 cmd)
uint8 getHeaderLength ()
bool isLargePacket () const
Public Attributes
const uint32 size
uint8 header [5]
Detailed Description
Definition at line 25 of file ServerPktHeader.h.
Constructor & Destructor Documentation
ServerPktHeader()
ServerPktHeader::ServerPktHeader (uint32 size, uint16 cmd) inline
size is the length of the payload plus the length of the opcode
Definition at line 30 of file ServerPktHeader.h.
                                              : size(size)
     {
         uint8 headerIndex=0;
         if (isLargePacket())
         {
             LOG_DEBUG("network", "initializing large server to client packet. Size: %u, cmd: %u", size, cmd);
             header[headerIndex++] = 0x80 | (0xFF & (size >> 16));
         }
         header[headerIndex++] = 0xFF &(size >> 8);
         header[headerIndex++] = 0xFF & size;
         header[headerIndex++] = 0xFF & cmd;
         header[headerIndex++] = 0xFF & (cmd >> 8);
     }
References header, isLargePacket(), LOG_DEBUG, and size.
Member Function Documentation
getHeaderLength()
uint8 ServerPktHeader::getHeaderLength () inline
Definition at line 45 of file ServerPktHeader.h.
     {
         // cmd = 2 bytes, size= 2||3bytes
         return 2 + (isLargePacket() ? 3 : 2);
     }
References isLargePacket().
Referenced by WorldSocket::Update().
isLargePacket()
bool ServerPktHeader::isLargePacket () const inline
Definition at line 51 of file ServerPktHeader.h.
     {
         return size > 0x7FFF;
     }
References size.
Referenced by getHeaderLength(), and ServerPktHeader().
Member Data Documentation
header
uint8 ServerPktHeader::header[5]
Definition at line 57 of file ServerPktHeader.h.
Referenced by ServerPktHeader(), and WorldSocket::Update().
size
const uint32 ServerPktHeader::size
Definition at line 56 of file ServerPktHeader.h.
Referenced by isLargePacket(), and ServerPktHeader().
The documentation for this struct was generated from the following file:
src/server/game/Server/Protocol/ServerPktHeader.h