Azerotcore-wotlk: deps/mysqllite/include/m_string.h File Reference
m_string.h File Reference
#include "my_global.h"
#include <stdarg.h>
#include <mysql/plugin.h>
Classes
struct st_mysql_const_lex_string
Macros
#define __USE_GNU /* We want to use stpcpy */
#define memcpy(d, s, n) bcopy ((s), (d), (n))
#define memset(A, C, B) bfill((A),(B),(C))
#define memmove(d, s, n) bmove ((d), (s), (n))
#define bfill(A, B, C) memset((A),(C),(B))
#define bzero(A, B) memset((A),0,(B))
#define strmov_overlapp(A, B) strmov(A,B)
#define strmake_overlapp(A, B, C) strmake(A,B,C)
#define NOT_FIXED_DEC 31
#define FLOATING_POINT_BUFFER (311 + NOT_FIXED_DEC)
#define MAX_DECPT_FOR_F_FORMAT DBL_DIG
#define MY_GCVT_MAX_FIELD_WIDTH (DBL_DIG + 4 + max(5, MAX_DECPT_FOR_F_FORMAT)) \
#define ll2str(A, B, C, D) int2str((A),(B),(C),(D))
#define longlong10_to_str(A, B, C) int10_to_str((A),(B),(C))
#define strtoll(A, B, C) strtol((A),(B),(C))
#define strtoull(A, B, C) strtoul((A),(B),(C))
#define HAVE_STRTOULL
#define HAVE_STRTOLL
#define longlong2str(A, B, C) ll2str((A),(B),(C),1)
#define STRING_WITH_LEN(X) (X), ((size_t) (sizeof(X) - 1))
#define USTRING_WITH_LEN(X) ((uchar*) X), ((size_t) (sizeof(X) - 1))
#define C_STRING_WITH_LEN(X) ((char *) (X)), ((size_t) (sizeof(X) - 1))
Typedefs
typedef struct st_mysql_lex_string LEX_STRING
typedef struct st_mysql_const_lex_string LEX_CSTRING
Enumerations
enum my_gcvt_arg_type { MY_GCVT_ARG_FLOAT , MY_GCVT_ARG_DOUBLE }
Functions
void bmove_upp (uchar *dst, const uchar *src, size_t len)
void bchange (uchar *dst, size_t old_len, const uchar *src, size_t new_len, size_t tot_len)
void strappend (char *s, size_t len, pchar fill)
char * strend (const char *s)
char * strcend (const char *, pchar)
char * strfill (char *s, size_t len, pchar fill)
char * strmake (char *dst, const char *src, size_t length)
char * strmov (char *dst, const char *src)
char * strnmov (char *dst, const char *src, size_t n)
char * strcont (const char *src, const char *set)
char * strxmov (char *dst, const char *src,...)
char * strxnmov (char *dst, size_t len, const char *src,...)
size_t strnlen (const char *s, size_t n)
int is_prefix (const char *, const char *)
double my_strtod (const char *str, char **end, int *error)
Converts string to double (string does not have to be zero-terminated)
double my_atof (const char *nptr)
size_t my_fcvt (double x, int precision, char *to, my_bool *error)
Converts a given floating point number to a zero-terminated string representation using the 'f' format.
size_t my_gcvt (double x, my_gcvt_arg_type type, int width, char *to, my_bool *error)
Converts a given floating point number to a zero-terminated string representation with a given field width using the 'e' format (aka scientific notation) or the 'f' one.
char * llstr (longlong value, char *buff)
char * ullstr (longlong value, char *buff)
long strtol (const char *str, char **ptr, int base)
ulong strtoul (const char *str, char **ptr, int base)
char * int2str (long val, char *dst, int radix, int upcase)
char * int10_to_str (long val, char *dst, int radix)
char * str2int (const char *src, int radix, long lower, long upper, long *val)
longlong my_strtoll10 (const char *nptr, char **endptr, int *error)
static const uchar * skip_trailing_space (const uchar *ptr, size_t len)
static void lex_string_set (LEX_STRING *lex_str, const char *c_str)
Variables
void *(* my_str_malloc)(size_t)
void(* my_str_free)(void *)
char _dig_vec_upper []
char _dig_vec_lower []
Macro Definition Documentation
__USE_GNU
#define __USE_GNU /* We want to use stpcpy */
Definition at line 27 of file m_string.h.
bfill
#define bfill (A, B, C) memset((A),(C),(B))
Definition at line 59 of file m_string.h.
bzero
#define bzero (A, B) memset((A),0,(B))
Definition at line 63 of file m_string.h.
C_STRING_WITH_LEN
#define C_STRING_WITH_LEN (X) ((char *) (X)), ((size_t) (sizeof(X) - 1))
Definition at line 211 of file m_string.h.
FLOATING_POINT_BUFFER
#define FLOATING_POINT_BUFFER (311 + NOT_FIXED_DEC)
Definition at line 142 of file m_string.h.
HAVE_STRTOLL
#define HAVE_STRTOLL
Definition at line 183 of file m_string.h.
HAVE_STRTOULL
#define HAVE_STRTOULL
Definition at line 180 of file m_string.h.
ll2str
#define ll2str (A, B, C, D) int2str((A),(B),(C),(D))
Definition at line 174 of file m_string.h.
longlong10_to_str
#define longlong10_to_str (A, B, C) int10_to_str((A),(B),(C))
Definition at line 175 of file m_string.h.
longlong2str
#define longlong2str (A, B, C) ll2str((A),(B),(C),1)
Definition at line 195 of file m_string.h.
MAX_DECPT_FOR_F_FORMAT
#define MAX_DECPT_FOR_F_FORMAT DBL_DIG
Definition at line 152 of file m_string.h.
memcpy
#define memcpy (d, s, n) bcopy ((s), (d), (n))
Definition at line 50 of file m_string.h.
memmove
#define memmove (d, s, n) bmove ((d), (s), (n))
Definition at line 52 of file m_string.h.
memset
#define memset (A, C, B) bfill((A),(B),(C))
Definition at line 51 of file m_string.h.
MY_GCVT_MAX_FIELD_WIDTH
#define MY_GCVT_MAX_FIELD_WIDTH (DBL_DIG + 4 + max(5, MAX_DECPT_FOR_F_FORMAT)) \
Definition at line 159 of file m_string.h.
NOT_FIXED_DEC
#define NOT_FIXED_DEC 31
Definition at line 135 of file m_string.h.
STRING_WITH_LEN
#define STRING_WITH_LEN (X) (X), ((size_t) (sizeof(X) - 1))
Definition at line 209 of file m_string.h.
strmake_overlapp
#define strmake_overlapp (A, B, C) strmake(A,B,C)
Definition at line 92 of file m_string.h.
strmov_overlapp
#define strmov_overlapp (A, B) strmov(A,B)
Definition at line 91 of file m_string.h.
strtoll
#define strtoll (A, B, C) strtol((A),(B),(C))
Definition at line 177 of file m_string.h.
strtoull
#define strtoull (A, B, C) strtoul((A),(B),(C))
Definition at line 178 of file m_string.h.
USTRING_WITH_LEN
#define USTRING_WITH_LEN (X) ((uchar*) X), ((size_t) (sizeof(X) - 1))
Definition at line 210 of file m_string.h.
Typedef Documentation
LEX_CSTRING
typedef struct st_mysql_const_lex_string LEX_CSTRING
Definition at line 172 of file m_string.h.
LEX_STRING
typedef struct st_mysql_lex_string LEX_STRING
Definition at line 172 of file m_string.h.
Enumeration Type Documentation
my_gcvt_arg_type
enum my_gcvt_arg_type
Enumerator
MY_GCVT_ARG_FLOAT
MY_GCVT_ARG_DOUBLE
Definition at line 124 of file m_string.h.
              {
   MY_GCVT_ARG_FLOAT,
   MY_GCVT_ARG_DOUBLE
 } my_gcvt_arg_type;
Function Documentation
bchange()
void bchange (uchar * dst, size_t old_len, const uchar * src, size_t new_len, size_t tot_len)
Referenced by my_path(), and pack_dirname().
bmove_upp()
void bmove_upp (uchar * dst, const uchar * src, size_t len)
Referenced by bchange(), fetch_float_with_conversion(), fetch_long_with_conversion(), str_to_time(), and unpack_dirname().
int10_to_str()
char* int10_to_str (long val, char * dst, int radix)
Referenced by get_charset(), and my_b_vprintf().
int2str()
char* int2str (long val, char * dst, int radix, int upcase)
is_prefix()
int is_prefix (const char * , const char *)
Referenced by get_charsets_dir(), get_defaults_options(), my_load_path(), and pack_dirname().
lex_string_set()
static void lex_string_set (LEX_STRING * lex_str, const char * c_str) inline static
Definition at line 289 of file m_string.h.
 {
   lex_str->str= (char *) c_str;
   lex_str->length= strlen(c_str);
 }
References st_mysql_lex_string::length, and st_mysql_lex_string::str.
llstr()
char* llstr (longlong value, char * buff)
Definition at line 30 of file llstr.c.
 {
   longlong10_to_str(value,buff,-10);
   return buff;
 }
References longlong10_to_str().
Referenced by getopt_ll_limit_value(), and my_print_variables().
my_atof()
double my_atof (const char * nptr)
Definition at line 474 of file dtoa.c.
 {
   int error;
   const char *end= nptr+65535;                  /* Should be enough */
   return (my_strtod(nptr, (char**) &end, &error));
 }
References error(), and my_strtod().
my_fcvt()
size_t my_fcvt (double x, int precision, char * to, my_bool * error)
Converts a given floating point number to a zero-terminated string representation using the 'f' format.
This function is a wrapper around dtoa() to do the same as sprintf(to, "%-.*f", precision, x), though the conversion is usually more precise. The only difference is in handling [-,+]infinity and nan values, in which case we print '0\0' to the output string and indicate an overflow.
Parameters
x the input floating point number.
precision the number of digits after the decimal point. All properties of sprintf() apply:
if the number of significant digits after the decimal point is less than precision, the resulting string is right-padded with zeros
if the precision is 0, no decimal point appears
if a decimal point appears, at least one digit appears before it
to pointer to the output buffer. The longest string which my_fcvt() can return is FLOATING_POINT_BUFFER bytes (including the terminating '\0').
error if not NULL, points to a location where the status of conversion is stored upon return. FALSE successful conversion TRUE the input number is [-,+]infinity or nan. The output string in this case is always '0'.
Returns
number of written characters (excluding terminating '\0')
Definition at line 89 of file dtoa.c.
 {
   int decpt, sign, len, i;
   char *res, *src, *end, *dst= to;
   char buf[DTOA_BUFF_SIZE];
   DBUG_ASSERT(precision >= 0 && precision < NOT_FIXED_DEC && to != NULL);
   res= dtoa(x, 5, precision, &decpt, &sign, &end, buf, sizeof(buf));
   if (decpt == DTOA_OVERFLOW)
   {
     dtoa_free(res, buf, sizeof(buf));
     *to++= '0';
     *to= '\0';
     if (error != NULL)
       *error= TRUE;
     return 1;
   }
   src= res;
   len= end - src;
   if (sign)
     *dst++= '-';
   if (decpt <= 0)
   {
     *dst++= '0';
     *dst++= '.';
     for (i= decpt; i < 0; i++)
       *dst++= '0';
   }
   for (i= 1; i <= len; i++)
   {
     *dst++= *src++;
     if (i == decpt && i < len)
       *dst++= '.';
   }
   while (i++ <= decpt)
     *dst++= '0';
   if (precision > 0)
   {
     if (len <= decpt)
       *dst++= '.';
     for (i= precision - max(0, (len - decpt)); i > 0; i--)
       *dst++= '0';
   }
   *dst= '\0';
   if (error != NULL)
     *error= FALSE;
   dtoa_free(res, buf, sizeof(buf));
   return dst - to;
 }
References DBUG_ASSERT, dtoa(), DTOA_BUFF_SIZE, dtoa_free(), DTOA_OVERFLOW, error(), FALSE, max, NOT_FIXED_DEC, NULL, G3D::sign(), TRUE, and G3D::x.
Referenced by fetch_float_with_conversion(), and process_dbl_arg().
my_gcvt()
size_t my_gcvt (double x, my_gcvt_arg_type type, int width, char * to, my_bool * error)
Converts a given floating point number to a zero-terminated string representation with a given field width using the 'e' format (aka scientific notation) or the 'f' one.
The format is chosen automatically to provide the most number of significant digits (and thus, precision) with a given field width. In many cases, the result is similar to that of sprintf(to, "%g", x) with a few notable differences:
the conversion is usually more precise than C library functions.
there is no 'precision' argument. instead, we specify the number of characters available for conversion (i.e. a field width).
the result never exceeds the specified field width. If the field is too short to contain even a rounded decimal representation, my_gcvt() indicates overflow and truncates the output string to the specified width.
float-type arguments are handled differently than double ones. For a float input number (i.e. when the 'type' argument is MY_GCVT_ARG_FLOAT) we deliberately limit the precision of conversion by FLT_DIG digits to avoid garbage past the significant digits.
unlike sprintf(), in cases where the 'e' format is preferred, we don't zero-pad the exponent to save space for significant digits. The '+' sign for a positive exponent does not appear for the same reason.
Parameters
x the input floating point number.
type is either MY_GCVT_ARG_FLOAT or MY_GCVT_ARG_DOUBLE. Specifies the type of the input number (see notes above).
width field width in characters. The minimal field width to hold any number representation (albeit rounded) is 7 characters ("-Ne-NNN").
to pointer to the output buffer. The result is always zero-terminated, and the longest returned string is thus 'width + 1' bytes.
error if not NULL, points to a location where the status of conversion is stored upon return. FALSE successful conversion TRUE the input number is [-,+]infinity or nan. The output string in this case is always '0'.
Returns
number of written characters (excluding terminating '\0')
Todo:
Check if it is possible and makes sense to do our own rounding on top of dtoa() instead of calling dtoa() twice in (rare) cases when the resulting string representation does not fit in the specified field width and we want to re-round the input number with fewer significant digits. Examples:
my_gcvt(-9e-3, ..., 4, ...); my_gcvt(-9e-3, ..., 2, ...); my_gcvt(1.87e-3, ..., 4, ...); my_gcvt(55, ..., 1, ...);
We do our best to minimize such cases by:
passing to dtoa() the field width as the number of significant digits
removing the sign of the number early (and decreasing the width before passing it to dtoa())
choosing the proper format to preserve the most number of significant digits.
Definition at line 212 of file dtoa.c.
 {
   int decpt, sign, len, exp_len;
   char *res, *src, *end, *dst= to, *dend= dst + width;
   char buf[DTOA_BUFF_SIZE];
   my_bool have_space, force_e_format;
   DBUG_ASSERT(width > 0 && to != NULL);
   /* We want to remove '-' from equations early */
   if (x < 0.)
     width--;
   res= dtoa(x, 4, type == MY_GCVT_ARG_DOUBLE ? width : min(width, FLT_DIG),
             &decpt, &sign, &end, buf, sizeof(buf));
   if (decpt == DTOA_OVERFLOW)
   {
     dtoa_free(res, buf, sizeof(buf));
     *to++= '0';
     *to= '\0';
     if (error != NULL)
       *error= TRUE;
     return 1;
   }
   if (error != NULL)
     *error= FALSE;
   src= res;
   len= end - res;
   /*
     Number of digits in the exponent from the 'e' conversion.
      The sign of the exponent is taken into account separetely, we don't need
      to count it here.
    */
   exp_len= 1 + (decpt >= 101 || decpt <= -99) + (decpt >= 11 || decpt <= -9);
   /*
      Do we have enough space for all digits in the 'f' format?
      Let 'len' be the number of significant digits returned by dtoa,
      and F be the length of the resulting decimal representation.
      Consider the following cases:
      1. decpt <= 0, i.e. we have "0.NNN" => F = len - decpt + 2
      2. 0 < decpt < len, i.e. we have "NNN.NNN" => F = len + 1
      3. len <= decpt, i.e. we have "NNN00" => F = decpt
   */
   have_space= (decpt <= 0 ? len - decpt + 2 :
                decpt > 0 && decpt < len ? len + 1 :
                decpt) <= width;
   /*
     The following is true when no significant digits can be placed with the
     specified field width using the 'f' format, and the 'e' format
     will not be truncated.
   */
   force_e_format= (decpt <= 0 && width <= 2 - decpt && width >= 3 + exp_len);
   /*
     Assume that we don't have enough space to place all significant digits in
     the 'f' format. We have to choose between the 'e' format and the 'f' one
     to keep as many significant digits as possible.
     Let E and F be the lengths of decimal representaion in the 'e' and 'f'
     formats, respectively. We want to use the 'f' format if, and only if F <= E.
     Consider the following cases:
     1. decpt <= 0.
        F = len - decpt + 2 (see above)
        E = len + (len > 1) + 1 + 1 (decpt <= -99) + (decpt <= -9) + 1
        ("N.NNe-MMM")
        (F <= E) <=> (len == 1 && decpt >= -1) || (len > 1 && decpt >= -2)
        We also need to ensure that if the 'f' format is chosen,
        the field width allows us to place at least one significant digit
        (i.e. width > 2 - decpt). If not, we prefer the 'e' format.
     2. 0 < decpt < len
        F = len + 1 (see above)
        E = len + 1 + 1 + ... ("N.NNeMMM")
        F is always less than E.
     3. len <= decpt <= width
        In this case we have enough space to represent the number in the 'f'
        format, so we prefer it with some exceptions.
     4. width < decpt
        The number cannot be represented in the 'f' format at all, always use
        the 'e' 'one.
   */
   if ((have_space ||
       /*
         Not enough space, let's see if the 'f' format provides the most number
         of significant digits.
       */
        ((decpt <= width && (decpt >= -1 || (decpt == -2 &&
                                             (len > 1 || !force_e_format)))) &&
          !force_e_format)) &&
        /*
          Use the 'e' format in some cases even if we have enough space for the
          'f' one. See comment for MAX_DECPT_FOR_F_FORMAT.
        */
       (!have_space || (decpt >= -MAX_DECPT_FOR_F_FORMAT + 1 &&
                        (decpt <= MAX_DECPT_FOR_F_FORMAT || len > decpt))))
   {
     /* 'f' format */
     int i;
     width-= (decpt < len) + (decpt <= 0 ? 1 - decpt : 0);
     /* Do we have to truncate any digits? */
     if (width < len)
     {
       if (width < decpt)
       {
         if (error != NULL)
           *error= TRUE;
         width= decpt;
       }
       /*
         We want to truncate (len - width) least significant digits after the
         decimal point. For this we are calling dtoa with mode=5, passing the
         number of significant digits = (len-decpt) - (len-width) = width-decpt
       */
       dtoa_free(res, buf, sizeof(buf));
       res= dtoa(x, 5, width - decpt, &decpt, &sign, &end, buf, sizeof(buf));
       src= res;
       len= end - res;
     }
     if (len == 0)
     {
       /* Underflow. Just print '0' and exit */
       *dst++= '0';
       goto end;
     }
     /*
       At this point we are sure we have enough space to put all digits
       returned by dtoa
     */
     if (sign && dst < dend)
       *dst++= '-';
     if (decpt <= 0)
     {
       if (dst < dend)
         *dst++= '0';
       if (len > 0 && dst < dend)
         *dst++= '.';
       for (; decpt < 0 && dst < dend; decpt++)
         *dst++= '0';
     }
     for (i= 1; i <= len && dst < dend; i++)
     {
       *dst++= *src++;
       if (i == decpt && i < len && dst < dend)
         *dst++= '.';
     }
     while (i++ <= decpt && dst < dend)
       *dst++= '0';
   }
   else
   {
     /* 'e' format */
     int decpt_sign= 0;
     if (--decpt < 0)
     {
       decpt= -decpt;
       width--;
       decpt_sign= 1;
     }
     width-= 1 + exp_len; /* eNNN */
     if (len > 1)
       width--;
     if (width <= 0)
     {
       /* Overflow */
       if (error != NULL)
         *error= TRUE;
       width= 0;
     }
     /* Do we have to truncate any digits? */
     if (width < len)
     {
       /* Yes, re-convert with a smaller width */
       dtoa_free(res, buf, sizeof(buf));
       res= dtoa(x, 4, width, &decpt, &sign, &end, buf, sizeof(buf));
       src= res;
       len= end - res;
       if (--decpt < 0)
         decpt= -decpt;
     }
     /*
       At this point we are sure we have enough space to put all digits
       returned by dtoa
     */
     if (sign && dst < dend)
       *dst++= '-';
     if (dst < dend)
       *dst++= *src++;
     if (len > 1 && dst < dend)
     {
       *dst++= '.';
       while (src < end && dst < dend)
         *dst++= *src++;
     }
     if (dst < dend)
       *dst++= 'e';
     if (decpt_sign && dst < dend)
       *dst++= '-';
     if (decpt >= 100 && dst < dend)
     {
       *dst++= decpt / 100 + '0';
       decpt%= 100;
       if (dst < dend)
         *dst++= decpt / 10 + '0';
     }
     else if (decpt >= 10 && dst < dend)
       *dst++= decpt / 10 + '0';
     if (dst < dend)
       *dst++= decpt % 10 + '0';
   }
 end:
   dtoa_free(res, buf, sizeof(buf));
   *dst= '\0';
   return dst - to;
 }
References DBUG_ASSERT, dtoa(), DTOA_BUFF_SIZE, dtoa_free(), DTOA_OVERFLOW, error(), FALSE, MAX_DECPT_FOR_F_FORMAT, min, MY_GCVT_ARG_DOUBLE, NULL, G3D::sign(), TRUE, width, and G3D::x.
Referenced by double2decimal(), fetch_float_with_conversion(), and process_dbl_arg().
my_strtod()
double my_strtod (const char * str, char ** end, int * error)
Converts string to double (string does not have to be zero-terminated)
This is a wrapper around dtoa's version of strtod().
Parameters
str input string
end address of a pointer to the first character after the input string. Upon return the pointer is set to point to the first rejected character.
error Upon return is set to EOVERFLOW in case of underflow or overflow.
Returns
The resulting double value. In case of underflow, 0.0 is returned. In case overflow, signed DBL_MAX is returned.
Definition at line 461 of file dtoa.c.
 {
   char buf[DTOA_BUFF_SIZE];
   double res;
   DBUG_ASSERT(end != NULL && ((str != NULL && *end != NULL) ||
                               (str == NULL && *end == NULL)) &&
               error != NULL);
   res= my_strtod_int(str, end, error, buf, sizeof(buf));
   return (*error == 0) ? res : (res < 0 ? -DBL_MAX : DBL_MAX);
 }
References DBL_MAX, DBUG_ASSERT, DTOA_BUFF_SIZE, error(), my_strtod_int(), and NULL.
Referenced by decimal2double(), getopt_double(), my_atof(), and my_strntod_8bit().
my_strtoll10()
longlong my_strtoll10 (const char * nptr, char ** endptr, int * error)
Definition at line 74 of file my_strtoll10.c.
 {
   const char *s, *end, *start, *n_end, *true_end;
   char *dummy;
   uchar c;
   unsigned long i, j, k;
   ulonglong li;
   int negative;
   ulong cutoff, cutoff2, cutoff3;
   s= nptr;
   /* If fixed length string */
   if (endptr)
   {
     end= *endptr;
     while (s != end && (*s == ' ' || *s == '\t'))
       s++;
     if (s == end)
       goto no_conv;
   }
   else
   {
     endptr= &dummy;             /* Easier end test */
     while (*s == ' ' || *s == '\t')
       s++;
     if (!*s)
       goto no_conv;
     /* This number must be big to guard against a lot of pre-zeros */
     end= s+65535;               /* Can't be longer than this */
   }
   /* Check for a sign.  */
   negative= 0;
   if (*s == '-')
   {
     *error= -1;                 /* Mark as negative number */
     negative= 1;
     if (++s == end)
       goto no_conv;
     cutoff=  MAX_NEGATIVE_NUMBER / LFACTOR2;
     cutoff2= (MAX_NEGATIVE_NUMBER % LFACTOR2) / 100;
     cutoff3=  MAX_NEGATIVE_NUMBER % 100;
   }
   else
   {
     *error= 0;
     if (*s == '+')
     {
       if (++s == end)
     goto no_conv;
     }
     cutoff=  ULONGLONG_MAX / LFACTOR2;
     cutoff2= ULONGLONG_MAX % LFACTOR2 / 100;
     cutoff3=  ULONGLONG_MAX % 100;
   }
   /* Handle case where we have a lot of pre-zero */
   if (*s == '0')
   {
     i= 0;
     do
     {
       if (++s == end)
     goto end_i;             /* Return 0 */
     }
     while (*s == '0');
     n_end= s+ INIT_CNT;
   }
   else
   {
     /* Read first digit to check that it's a valid number */
     if ((c= (*s-'0')) > 9)
       goto no_conv;
     i= c;
     n_end= ++s+ INIT_CNT-1;
   }
   /* Handle first 9 digits and store them in i */
   if (n_end > end)
     n_end= end;
   for (; s != n_end ; s++)
   {
     if ((c= (*s-'0')) > 9)
       goto end_i;
     i= i*10+c;
   }
   if (s == end)
     goto end_i;
   /* Handle next 9 digits and store them in j */
   j= 0;
   start= s;             /* Used to know how much to shift i */
   n_end= true_end= s + INIT_CNT;
   if (n_end > end)
     n_end= end;
   do
   {
     if ((c= (*s-'0')) > 9)
       goto end_i_and_j;
     j= j*10+c;
   } while (++s != n_end);
   if (s == end)
   {
     if (s != true_end)
       goto end_i_and_j;
     goto end3;
   }
   if ((c= (*s-'0')) > 9)
     goto end3;
   /* Handle the next 1 or 2 digits and store them in k */
   k=c;
   if (++s == end || (c= (*s-'0')) > 9)
     goto end4;
   k= k*10+c;
   *endptr= (char*) ++s;
   /* number string should have ended here */
   if (s != end && (c= (*s-'0')) <= 9)
     goto overflow;
   /* Check that we didn't get an overflow with the last digit */
   if (i > cutoff || (i == cutoff && ((j > cutoff2 || j == cutoff2) &&
                                      k > cutoff3)))
     goto overflow;
   li=i*LFACTOR2+ (ulonglong) j*100 + k;
   return (longlong) li;
 overflow:                   /* *endptr is set here */
   *error= MY_ERRNO_ERANGE;
   return negative ? LONGLONG_MIN : (longlong) ULONGLONG_MAX;
 end_i:
   *endptr= (char*) s;
   return (negative ? ((longlong) -(long) i) : (longlong) i);
 end_i_and_j:
   li= (ulonglong) i * lfactor[(uint) (s-start)] + j;
   *endptr= (char*) s;
   return (negative ? -((longlong) li) : (longlong) li);
 end3:
   li=(ulonglong) i*LFACTOR+ (ulonglong) j;
   *endptr= (char*) s;
   return (negative ? -((longlong) li) : (longlong) li);
 end4:
   li=(ulonglong) i*LFACTOR1+ (ulonglong) j * 10 + k;
   *endptr= (char*) s;
   if (negative)
   {
    if (li > MAX_NEGATIVE_NUMBER)
      goto overflow;
    return -((longlong) li);
   }
   return (longlong) li;
 no_conv:
   /* There was no number to convert.  */
   *error= MY_ERRNO_EDOM;
   *endptr= (char *) nptr;
   return 0;
 }
References mpq::c, error(), INIT_CNT, LFACTOR, lfactor, LFACTOR1, LFACTOR2, MAX_NEGATIVE_NUMBER, MY_ERRNO_EDOM, MY_ERRNO_ERANGE, and ULONGLONG_MAX.
Referenced by fetch_string_with_conversion(), internal_str2dec(), and my_strtoll10_8bit().
skip_trailing_space()
static const uchar* skip_trailing_space (const uchar * ptr, size_t len) inline static
Skip trailing space.
On most systems reading memory in larger chunks (ideally equal to the size of the chinks that the machine physically reads from memory) causes fewer memory access loops and hence increased performance. This is why the 'int' type is used : it's closest to that (according to how it's defined in C). So when we determine the amount of whitespace at the end of a string we do the following :
We divide the string into 3 zones : a) from the start of the string (__start) to the first multiple of sizeof(int) (__start_words) b) from the end of the string (__end) to the last multiple of sizeof(int) (__end_words) c) a zone that is aligned to sizeof(int) and can be safely accessed through an int *
We start comparing backwards from (c) char-by-char. If all we find is space then we continue
If there are elements in zone (b) we compare them as unsigned ints to a int mask (SPACE_INT) consisting of all spaces
Finally we compare the remaining part (a) of the string char by char. This covers for the last non-space unsigned int from 3. (if any)
This algorithm works well for relatively larger strings, but it will slow the things down for smaller strings (because of the additional calculations and checks compared to the naive method). Thus the barrier of length 20 is added.
Parameters
ptr pointer to the input string
len the length of the string
Returns
the last non-space character
Definition at line 263 of file m_string.h.
 {
   const uchar *end= ptr + len;
   if (len > 20)
   {
     const uchar *end_words= (const uchar *)(intptr)
       (((ulonglong)(intptr)end) / SIZEOF_INT * SIZEOF_INT);
     const uchar *start_words= (const uchar *)(intptr)
        ((((ulonglong)(intptr)ptr) + SIZEOF_INT - 1) / SIZEOF_INT * SIZEOF_INT);
     DBUG_ASSERT(((ulonglong)(intptr)ptr) >= SIZEOF_INT);
     if (end_words > ptr)
     {
       while (end > end_words && end[-1] == 0x20)
         end--;
       if (end[-1] == 0x20 && start_words < end_words)
         while (end > start_words && ((unsigned *)end)[-1] == SPACE_INT)
           end -= SIZEOF_INT;
     }
   }
   while (end > ptr && end[-1] == 0x20)
     end--;
   return (end);
 }
References DBUG_ASSERT, and ptr().
Referenced by my_hash_sort_8bit_bin(), my_hash_sort_latin1_de(), my_hash_sort_simple(), and my_lengthsp_8bit().
str2int()
char* str2int (const char * src, int radix, long lower, long upper, long * val)
Referenced by atoi_octal().
strappend()
void strappend (char * s, size_t len, pchar fill)
strcend()
char* strcend (const char * , pchar)
Referenced by check_struct_option(), dynstr_append_os_quoted(), handle_options(), init_tmpdir(), and mysql_read_default_options().
strcont()
char* strcont (const char * src, const char * set)
strend()
char* strend (const char * s)
Referenced by CLI_MYSQL_REAL_CONNECT(), deflate_rle(), expand_tilde(), find_type(), fn_ext(), get_date(), longest_match(), my_dir(), my_getwd(), my_path(), my_print_help(), my_redel(), my_string_repertoire(), search_default_file_with_ext(), and send_client_reply_packet().
strfill()
char* strfill (char * s, size_t len, pchar fill)
Definition at line 29 of file strfill.c.
 {
   while (len--) *s++ = fill;
   *(s) = '\0';
   return(s);
 } /* strfill */
References fill().
strmake()
char* strmake (char * dst, const char * src, size_t length)
Referenced by check_struct_option(), CLI_MYSQL_REAL_CONNECT(), cli_safe_read(), convert_dirname(), create_temp_file(), default_local_infile_error(), fn_format(), get_charsets_dir(), init_tmpdir(), my_getwd(), my_realpath(), my_setwd(), my_thread_name(), mysql_list_fields(), read_user_name(), search_default_file_with_ext(), send_change_user_packet(), send_client_reply_packet(), and system_filename().
strmov()
char* strmov (char * dst, const char * src)
Referenced by append_wild(), cleanup_dirname(), CLI_MYSQL_REAL_CONNECT(), cli_safe_read(), create_temp_file(), DBUGOpenFile(), default_local_infile_error(), directory_file_name(), find_type(), fn_format(), get_charset(), get_charset_by_csname(), get_charset_by_name(), handle_default_option(), handle_local_infile(), init_available_charsets(), intern_filename(), make_type(), my_dir(), my_path(), my_readlink(), my_realloc_str(), my_redel(), my_rename_with_symlink(), mysql_init(), mysql_list_dbs(), mysql_list_tables(), mysql_prune_stmt_list(), mysql_reconnect(), mysql_stmt_bind_param(), mysql_stmt_bind_result(), mysql_stmt_init(), mysql_stmt_send_long_data(), net_clear_error(), read_user_name(), search_default_file_with_ext(), set_mysql_error(), set_mysql_extended_error(), set_stmt_errmsg(), set_stmt_error(), stmt_clear_error(), unpack_filename(), and vio_peer_addr().
strnlen()
size_t strnlen (const char * s, size_t n)
Referenced by process_str_arg().
strnmov()
char* strnmov (char * dst, const char * src, size_t n)
Referenced by backtick_string(), cleanup_dirname(), create_temp_file(), find_file_in_path(), get_tty_password(), my_load_path(), process_args(), process_str_arg(), and search_default_file_with_ext().
strtol()
long strtol (const char * str, char ** ptr, int base)
Referenced by cs_value(), fill_uint16(), Field::GetInt16(), Field::GetInt32(), Field::GetInt8(), misc_commandscript::HandleAddItemCommand(), setval(), and vio_peer_addr().
strtoul()
ulong strtoul (const char * str, char ** ptr, int base)
Referenced by fill_uchar(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), Acore::Impl::HexStrToByteArray(), mysql_get_server_version(), and setval().
strxmov()
char* strxmov (char * dst, const char * src, ...)
Definition at line 37 of file strxmov.c.
 {
   va_list pvar;
   va_start(pvar,src);
   while (src != NullS) {
     while ((*dst++ = *src++)) ;
     dst--;
     src = va_arg(pvar, char *);
   }
   va_end(pvar);
   *dst = 0;         /* there might have been no sources! */
   return dst;
 }
References NullS.
Referenced by find_file_in_path(), get_charsets_dir(), get_internal_charset(), my_print_default_files(), and search_default_file_with_ext().
strxnmov()
char* strxnmov (char * dst, size_t len, const char * src, ...)
Definition at line 42 of file strxnmov.c.
 {
   va_list pvar;
   char *end_of_dst=dst+len;
   va_start(pvar,src);
   while (src != NullS)
   {
     do
     {
       if (dst == end_of_dst)
     goto end;
     }
     while ((*dst++ = *src++));
     dst--;
     src = va_arg(pvar, char *);
   }
 end:
   *dst=0;
   va_end(pvar);
   return dst;
 }
References NullS.
Referenced by my_load_path(), mysql_debug(), and mysql_load_plugin_v().
ullstr()
char* ullstr (longlong value, char * buff)
Definition at line 36 of file llstr.c.
 {
   longlong10_to_str(value,buff,10);
   return buff;
 }
References longlong10_to_str().
Referenced by getopt_ull_limit_value().
Variable Documentation
_dig_vec_lower
char _dig_vec_lower[] extern
Definition at line 24 of file int2str.c.
Referenced by int2str(), and ll2str().
_dig_vec_upper
char _dig_vec_upper[] extern
Definition at line 22 of file int2str.c.
Referenced by _db_dump_(), int2str(), ll2str(), longlong10_to_str(), mysql_hex_string(), and octet2hex().
my_str_free
void(* my_str_free) (void *) (void *) extern
Definition at line 33 of file str_alloc.c.
my_str_malloc
void*(* my_str_malloc) (size_t) (size_t) extern
Definition at line 32 of file str_alloc.c.