Azerotcore-wotlk: deps/mysqllite/include/internal/password.h File Reference
password.h File Reference
#include "my_global.h"
Functions
C_MODE_START void my_make_scrambled_password_323 (char *to, const char *password, size_t pass_len)
void my_make_scrambled_password (char *to, const char *password, size_t pass_len)
void hash_password (ulong *result, const char *password, uint password_len)
Function Documentation
hash_password()
void hash_password (ulong * result, const char * password, uint password_len)
Definition at line 118 of file password.c.
 {
   register ulong nr=1345345333L, add=7, nr2=0x12345671L;
   ulong tmp;
   const char *password_end= password + password_len;
   for (; password < password_end; password++)
   {
     if (*password == ' ' || *password == '\t')
       continue;                                 /* skip space in password */
     tmp= (ulong) (uchar) *password;
     nr^= (((nr & 63)+add)*tmp)+ (nr << 8);
     nr2+=(nr2 << 8) ^ nr;
     add+=tmp;
   }
   result[0]=nr & (((ulong) 1L << 31) -1L); /* Don't use sign bit (str2int) */;
   result[1]=nr2 & (((ulong) 1L << 31) -1L);
 }
my_make_scrambled_password()
void my_make_scrambled_password (char * to, const char * password, size_t pass_len)
Definition at line 412 of file password.c.
 {
   SHA1_CONTEXT sha1_context;
   uint8 hash_stage2[SHA1_HASH_SIZE];
   mysql_sha1_reset(&sha1_context);
   /* stage 1: hash password */
   mysql_sha1_input(&sha1_context, (uint8 *) password, (uint) pass_len);
   mysql_sha1_result(&sha1_context, (uint8 *) to);
   /* stage 2: hash stage1 output */
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, (uint8 *) to, SHA1_HASH_SIZE);
   /* separate buffer is used to pass 'to' in octet2hex */
   mysql_sha1_result(&sha1_context, hash_stage2);
   /* convert hash_stage2 to hex string */
   *to++= PVERSION41_CHAR;
   octet2hex(to, (const char*) hash_stage2, SHA1_HASH_SIZE);
 }
References mysql_sha1_input(), mysql_sha1_reset(), mysql_sha1_result(), octet2hex(), PVERSION41_CHAR, and SHA1_HASH_SIZE.
Referenced by make_scrambled_password().
my_make_scrambled_password_323()
C_MODE_START void my_make_scrambled_password_323 (char * to, const char * password, size_t pass_len)
Definition at line 147 of file password.c.
 {
   ulong hash_res[2];
   hash_password(hash_res, password, (uint) pass_len);
   sprintf(to, "%08lx%08lx", hash_res[0], hash_res[1]);
 }
References hash_password(), and sprintf().
Referenced by make_scrambled_password_323().