Azerotcore-wotlk: npc_argent_captainAI Struct Reference
npc_argent_captainAI Struct Reference
Public Member Functions
npc_argent_captainAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void DoAction (int32 action) override
void EnterCombat (Unit *) override
bool CanAIAttack (Unit const *target) const override
void EnterEvadeMode () override
void SpellHit (Unit *, SpellInfo const *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Protected Attributes
EventMap Events
InstanceScript * instance
float FollowAngle
float FollowDist
bool IsUndead
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Detailed Description
Definition at line 1198 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_argent_captainAI()
npc_argent_captainAI::npc_argent_captainAI (Creature * creature) inline
Definition at line 1201 of file icecrown_citadel.cpp.
                                              : ScriptedAI(creature), instance(creature->GetInstanceScript())
     {
         FollowAngle = PET_FOLLOW_ANGLE;
         FollowDist = PET_FOLLOW_DIST;
     }
References FollowAngle, FollowDist, PET_FOLLOW_ANGLE, and PET_FOLLOW_DIST.
Member Function Documentation
CanAIAttack()
bool npc_argent_captainAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1248 of file icecrown_citadel.cpp.
     {
         // do not see targets inside Frostwing Halls when we are not there
         return (me->GetPositionY() > 2660.0f) == (target->GetPositionY() > 2660.0f) && (target->GetTypeId() == TYPEID_PLAYER || target->IsInCombat());
     }
References Position::GetPositionY(), Object::GetTypeId(), Unit::IsInCombat(), ScriptedAI::me, and TYPEID_PLAYER.
DoAction()
void npc_argent_captainAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1229 of file icecrown_citadel.cpp.
     {
         if (action == ACTION_START_GAUNTLET)
         {
             if (Creature* crok = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_CROK_SCOURGEBANE)))
             {
                 FollowAngle = me->GetAngle(crok) + me->GetOrientation();
                 FollowDist = me->GetDistance2d(crok);
                 me->GetMotionMaster()->MoveFollow(crok, FollowDist, FollowAngle, MOTION_SLOT_IDLE);
             }
         }
     }
References ACTION_START_GAUNTLET, DATA_CROK_SCOURGEBANE, FollowAngle, FollowDist, Position::GetAngle(), ObjectAccessor::GetCreature(), WorldObject::GetDistance2d(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), instance, ScriptedAI::me, MOTION_SLOT_IDLE, and MotionMaster::MoveFollow().
EnterCombat()
void npc_argent_captainAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1242 of file icecrown_citadel.cpp.
     {
         if (IsUndead)
             DoZoneInCombat();
     }
References CreatureAI::DoZoneInCombat(), and IsUndead.
EnterEvadeMode()
void npc_argent_captainAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1254 of file icecrown_citadel.cpp.
     {
         if (!_EnterEvadeMode())
             return;
         me->GetMotionMaster()->Clear(false);
         if (Creature* crok = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_CROK_SCOURGEBANE)))
             me->GetMotionMaster()->MoveFollow(crok, FollowDist, FollowAngle, MOTION_SLOT_IDLE);
         else
             me->GetMotionMaster()->MoveTargetedHome();
         Reset();
     }
References CreatureAI::_EnterEvadeMode(), MotionMaster::Clear(), DATA_CROK_SCOURGEBANE, FollowAngle, FollowDist, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), instance, ScriptedAI::me, MOTION_SLOT_IDLE, MotionMaster::MoveFollow(), MotionMaster::MoveTargetedHome(), and Reset().
JustDied()
void npc_argent_captainAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1213 of file icecrown_citadel.cpp.
     {
         if (IsUndead)
             Talk(SAY_CAPTAIN_DEATH);
         else
             Talk(SAY_CAPTAIN_SECOND_DEATH);
         IsUndead = false;
     }
References IsUndead, SAY_CAPTAIN_DEATH, SAY_CAPTAIN_SECOND_DEATH, and CreatureAI::Talk().
KilledUnit()
void npc_argent_captainAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1223 of file icecrown_citadel.cpp.
     {
         if (victim->GetTypeId() == TYPEID_PLAYER)
             Talk(SAY_CAPTAIN_KILL);
     }
References Object::GetTypeId(), SAY_CAPTAIN_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void npc_argent_captainAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_captain_rupert::npc_captain_rupertAI, npc_captain_grondel::npc_captain_grondelAI, npc_captain_brandon::npc_captain_brandonAI, and npc_captain_arnath::npc_captain_arnathAI.
Definition at line 1207 of file icecrown_citadel.cpp.
     {
         me->SetCorpseDelay(DAY); // leave corpse for a long time so svalna can resurrect
         IsUndead = (me->GetCreatureData() && me->GetCreatureData()->id != me->GetEntry());
     }
References DAY, Creature::GetCreatureData(), Object::GetEntry(), CreatureData::id, IsUndead, ScriptedAI::me, and Creature::SetCorpseDelay().
Referenced by EnterEvadeMode(), npc_captain_arnath::npc_captain_arnathAI::Reset(), npc_captain_brandon::npc_captain_brandonAI::Reset(), npc_captain_grondel::npc_captain_grondelAI::Reset(), and npc_captain_rupert::npc_captain_rupertAI::Reset().
SpellHit()
void npc_argent_captainAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1268 of file icecrown_citadel.cpp.
     {
         if (spell->Id == SPELL_REVIVE_CHAMPION && !IsUndead)
         {
             me->setDeathState(JUST_RESPAWNED);
             uint32 newEntry = 0;
             switch (me->GetEntry())
             {
                 case NPC_CAPTAIN_ARNATH:
                     newEntry = NPC_CAPTAIN_ARNATH_UNDEAD;
                     break;
                 case NPC_CAPTAIN_BRANDON:
                     newEntry = NPC_CAPTAIN_BRANDON_UNDEAD;
                     break;
                 case NPC_CAPTAIN_GRONDEL:
                     newEntry = NPC_CAPTAIN_GRONDEL_UNDEAD;
                     break;
                 case NPC_CAPTAIN_RUPERT:
                     newEntry = NPC_CAPTAIN_RUPERT_UNDEAD;
                     break;
                 default:
                     return;
             }
             Talk(SAY_CAPTAIN_RESURRECTED);
             me->UpdateEntry(newEntry, me->GetCreatureData());
             IsUndead = true;
             DoCast(me, SPELL_UNDEATH, true);
             if (Player* p = me->SelectNearestPlayer(150.0f))
                 AttackStart(p);
             me->SetInCombatWithZone();
         }
     }
References ScriptedAI::AttackStart(), UnitAI::DoCast(), Creature::GetCreatureData(), Object::GetEntry(), SpellInfo::Id, IsUndead, JUST_RESPAWNED, ScriptedAI::me, NPC_CAPTAIN_ARNATH, NPC_CAPTAIN_ARNATH_UNDEAD, NPC_CAPTAIN_BRANDON, NPC_CAPTAIN_BRANDON_UNDEAD, NPC_CAPTAIN_GRONDEL, NPC_CAPTAIN_GRONDEL_UNDEAD, NPC_CAPTAIN_RUPERT, NPC_CAPTAIN_RUPERT_UNDEAD, SAY_CAPTAIN_RESURRECTED, WorldObject::SelectNearestPlayer(), Creature::setDeathState(), Creature::SetInCombatWithZone(), SPELL_REVIVE_CHAMPION, SPELL_UNDEATH, CreatureAI::Talk(), and Creature::UpdateEntry().
Member Data Documentation
Events
EventMap npc_argent_captainAI::Events protected
Definition at line 1303 of file icecrown_citadel.cpp.
FollowAngle
float npc_argent_captainAI::FollowAngle protected
Definition at line 1305 of file icecrown_citadel.cpp.
Referenced by DoAction(), EnterEvadeMode(), and npc_argent_captainAI().
FollowDist
float npc_argent_captainAI::FollowDist protected
Definition at line 1306 of file icecrown_citadel.cpp.
Referenced by DoAction(), EnterEvadeMode(), and npc_argent_captainAI().
instance
InstanceScript* npc_argent_captainAI::instance protected
Definition at line 1304 of file icecrown_citadel.cpp.
Referenced by DoAction(), and EnterEvadeMode().
IsUndead
bool npc_argent_captainAI::IsUndead protected
Definition at line 1307 of file icecrown_citadel.cpp.
Referenced by EnterCombat(), JustDied(), Reset(), npc_captain_arnath::npc_captain_arnathAI::Reset(), npc_captain_brandon::npc_captain_brandonAI::Reset(), npc_captain_grondel::npc_captain_grondelAI::Reset(), and SpellHit().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp