Azerotcore-wotlk: deps/mysqllite/mysys/string.c File Reference
string.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
my_bool init_dynamic_string (DYNAMIC_STRING *str, const char *init_str, size_t init_alloc, size_t alloc_increment)
my_bool dynstr_set (DYNAMIC_STRING *str, const char *init_str)
my_bool dynstr_realloc (DYNAMIC_STRING *str, size_t additional_size)
my_bool dynstr_append (DYNAMIC_STRING *str, const char *append)
my_bool dynstr_append_mem (DYNAMIC_STRING *str, const char *append, size_t length)
my_bool dynstr_trunc (DYNAMIC_STRING *str, size_t n)
my_bool dynstr_append_os_quoted (DYNAMIC_STRING *str, const char *append,...)
void dynstr_free (DYNAMIC_STRING *str)
Function Documentation
dynstr_append()
my_bool dynstr_append (DYNAMIC_STRING * str, const char * append)
Definition at line 91 of file string.c.
 {
   return dynstr_append_mem(str,append,(uint) strlen(append));
 }
References utf8::append(), and dynstr_append_mem().
dynstr_append_mem()
my_bool dynstr_append_mem (DYNAMIC_STRING * str, const char * append, size_t length)
Definition at line 97 of file string.c.
 {
   char *new_ptr;
   if (str->length+length >= str->max_length)
   {
     size_t new_length=(str->length+length+str->alloc_increment)/
       str->alloc_increment;
     new_length*=str->alloc_increment;
     if (!(new_ptr=(char*) my_realloc(str->str,new_length,MYF(MY_WME))))
       return TRUE;
     str->str=new_ptr;
     str->max_length=new_length;
   }
   memcpy(str->str + str->length,append,length);
   str->length+=length;
   str->str[str->length]=0;          /* Safety for C programs */
   return FALSE;
 }
References st_dynamic_string::alloc_increment, utf8::append(), FALSE, if(), G3D::length(), st_dynamic_string::length, st_dynamic_string::max_length, memcpy, my_realloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.
Referenced by dynstr_append(), and dynstr_append_os_quoted().
dynstr_append_os_quoted()
my_bool dynstr_append_os_quoted (DYNAMIC_STRING * str, const char * append, ...)
Definition at line 141 of file string.c.
 {
 #ifdef __WIN__
   const char *quote_str= "\"";
   const uint  quote_len= 1;
 #else
   const char *quote_str= "\'";
   const uint  quote_len= 1;
 #endif /* __WIN__ */
   my_bool ret= TRUE;
   va_list dirty_text;
   ret&= dynstr_append_mem(str, quote_str, quote_len); /* Leading quote */
   va_start(dirty_text, append);
   while (append != NullS)
   {
     const char  *cur_pos= append;
     const char *next_pos= cur_pos;
     /* Search for quote in each string and replace with escaped quote */
     while(*(next_pos= strcend(cur_pos, quote_str[0])) != '\0')
     {
       ret&= dynstr_append_mem(str, cur_pos, (uint) (next_pos - cur_pos));
       ret&= dynstr_append_mem(str ,"\\", 1);
       ret&= dynstr_append_mem(str, quote_str, quote_len);
       cur_pos= next_pos + 1;
     }
     ret&= dynstr_append_mem(str, cur_pos, (uint) (next_pos - cur_pos));
     append= va_arg(dirty_text, char *);
   }
   va_end(dirty_text);
   ret&= dynstr_append_mem(str, quote_str, quote_len); /* Trailing quote */
   return ret;
 }
References utf8::append(), dynstr_append_mem(), NullS, ret, strcend(), and TRUE.
dynstr_free()
void dynstr_free (DYNAMIC_STRING * str)
Definition at line 178 of file string.c.
 {
   my_free(str->str);
   str->str= NULL;
 }
References my_free(), NULL, and st_dynamic_string::str.
dynstr_realloc()
my_bool dynstr_realloc (DYNAMIC_STRING * str, size_t additional_size)
Definition at line 75 of file string.c.
 {
   DBUG_ENTER("dynstr_realloc");
   if (!additional_size) DBUG_RETURN(FALSE);
   if (str->length + additional_size > str->max_length)
   {
     str->max_length=((str->length + additional_size+str->alloc_increment-1)/
              str->alloc_increment)*str->alloc_increment;
     if (!(str->str=(char*) my_realloc(str->str,str->max_length,MYF(MY_WME))))
       DBUG_RETURN(TRUE);
   }
   DBUG_RETURN(FALSE);
 }
References st_dynamic_string::alloc_increment, DBUG_ENTER, DBUG_RETURN, FALSE, st_dynamic_string::length, st_dynamic_string::max_length, my_realloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.
dynstr_set()
my_bool dynstr_set (DYNAMIC_STRING * str, const char * init_str)
Definition at line 50 of file string.c.
 {
   uint length=0;
   DBUG_ENTER("dynstr_set");
   if (init_str && (length= (uint) strlen(init_str)+1) > str->max_length)
   {
     str->max_length=((length+str->alloc_increment-1)/str->alloc_increment)*
       str->alloc_increment;
     if (!str->max_length)
       str->max_length=str->alloc_increment;
     if (!(str->str=(char*) my_realloc(str->str,str->max_length,MYF(MY_WME))))
       DBUG_RETURN(TRUE);
   }
   if (init_str)
   {
     str->length=length-1;
     memcpy(str->str,init_str,length);
   }
   else
     str->length=0;
   DBUG_RETURN(FALSE);
 }
References st_dynamic_string::alloc_increment, DBUG_ENTER, DBUG_RETURN, FALSE, G3D::length(), st_dynamic_string::length, st_dynamic_string::max_length, memcpy, my_realloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.
dynstr_trunc()
my_bool dynstr_trunc (DYNAMIC_STRING * str, size_t n)
Definition at line 118 of file string.c.
 {
   str->length-=n;
   str->str[str->length]= '\0';
   return FALSE;
 }
References FALSE, st_dynamic_string::length, and st_dynamic_string::str.
init_dynamic_string()
my_bool init_dynamic_string (DYNAMIC_STRING * str, const char * init_str, size_t init_alloc, size_t alloc_increment)
Definition at line 25 of file string.c.
 {
   size_t length;
   DBUG_ENTER("init_dynamic_string");
   if (!alloc_increment)
     alloc_increment=128;
   length=1;
   if (init_str && (length= strlen(init_str)+1) < init_alloc)
     init_alloc=((length+alloc_increment-1)/alloc_increment)*alloc_increment;
   if (!init_alloc)
     init_alloc=alloc_increment;
   if (!(str->str=(char*) my_malloc(init_alloc,MYF(MY_WME))))
     DBUG_RETURN(TRUE);
   str->length=length-1;
   if (init_str)
     memcpy(str->str,init_str,length);
   str->max_length=init_alloc;
   str->alloc_increment=alloc_increment;
   DBUG_RETURN(FALSE);
 }
References st_dynamic_string::alloc_increment, DBUG_ENTER, DBUG_RETURN, FALSE, G3D::length(), st_dynamic_string::length, st_dynamic_string::max_length, memcpy, my_malloc(), MY_WME, MYF, st_dynamic_string::str, and TRUE.