Azerotcore-wotlk: BattlegroundRV Class Reference
BattlegroundRV Class Reference
#include <BattlegroundRV.h>
Public Member Functions
BattlegroundRV ()
~BattlegroundRV () override
void AddPlayer (Player *player) override
void RemovePlayer (Player *player) override
void StartingEventCloseDoors () override
void StartingEventOpenDoors () override
void Init () override
void FillInitialWorldStates (WorldPacket &d) override
void UpdateArenaWorldState () override
void HandleAreaTrigger (Player *player, uint32 trigger) override
bool SetupBattleground () override
void HandleKillPlayer (Player *player, Player *killer) override
bool HandlePlayerUnderMap (Player *player) override
GameObject * GetPillarAtPosition (Position *p)
Public Member Functions inherited from Battleground
Battleground ()
virtual ~Battleground ()
void Update (uint32 diff)
virtual void ResetBGSubclass ()
virtual void DestroyGate (Player *, GameObject *)
virtual bool AllNodesConrolledByTeam (TeamId) const
void StartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
char const * GetName () const
BattlegroundTypeId GetBgTypeID (bool GetRandom=false) const
uint32 GetInstanceID () const
BattlegroundStatus GetStatus () const
uint32 GetClientInstanceID () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetLastResurrectTime () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
uint8 GetArenaType () const
TeamId GetWinner () const
uint32 GetScriptId () const
uint32 GetBonusHonorFromKill (uint32 kills) const
bool IsRandom ()
void SetName (char const *Name)
void SetBgTypeID (BattlegroundTypeId TypeID)
void SetRandomTypeID (BattlegroundTypeId TypeID)
void SetInstanceID (uint32 InstanceID)
void SetStatus (BattlegroundStatus Status)
void SetClientInstanceID (uint32 InstanceID)
void SetStartTime (uint32 Time)
void SetEndTime (uint32 Time)
void SetLastResurrectTime (uint32 Time)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (uint8 type)
void SetArenaorBGType (bool _isArena)
void SetWinner (TeamId winner)
void SetScriptId (uint32 scriptId)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int32 diff)
void SetStartDelayTime (int32 Time)
void SetMaxPlayersPerTeam (uint32 MaxPlayers)
void SetMinPlayersPerTeam (uint32 MinPlayers)
void DecreaseInvitedCount (TeamId teamId)
void IncreaseInvitedCount (TeamId teamId)
uint32 GetInvitedCount (TeamId teamId) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (TeamId teamId) const
uint32 GetMaxFreeSlots () const
void AddSpectator (Player *p)
void RemoveSpectator (Player *p)
bool HaveSpectators ()
const SpectatorList & GetSpectators () const
void AddToBeTeleported (ObjectGuid spectator, ObjectGuid participant)
void RemoveToBeTeleported (ObjectGuid spectator)
void SpectatorsSendPacket (WorldPacket &data)
bool isArena () const
bool isBattleground () const
bool isRated () const
BattlegroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
void ReadyMarkerClicked (Player *p)
BattlegroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattlegroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
uint32 GetReviveQueueSize () const
void AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid)
void RemovePlayerFromResurrectQueue (Player *player)
void RelocateDeadPlayers (ObjectGuid queueIndex)
Relocate all players in ReviveQueue to the closest graveyard.
void StartBattleground ()
GameObject * GetBGObject (uint32 type)
Creature * GetBGCreature (uint32 type)
void SetMapId (uint32 MapID)
uint32 GetMapId () const
void SetBgMap (BattlegroundMap *map)
BattlegroundMap * GetBgMap () const
BattlegroundMap * FindBgMap () const
void SetTeamStartLoc (TeamId teamId, float X, float Y, float Z, float O)
void GetTeamStartLoc (TeamId teamId, float &X, float &Y, float &Z, float &O) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
void SendPacketToTeam (TeamId teamId, WorldPacket *packet, Player *sender=nullptr, bool self=true)
void SendPacketToAll (WorldPacket *packet)
void YellToAll (Creature *creature, const char *text, uint32 language)
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToAll (uint32 soundId)
void CastSpellOnTeam (uint32 spellId, TeamId teamId)
void RemoveAuraOnTeam (uint32 spellId, TeamId teamId)
void RewardHonorToTeam (uint32 honor, TeamId teamId)
void RewardReputationToTeam (uint32 factionId, uint32 reputation, TeamId teamId)
uint32 GetRealRepFactionForPlayer (uint32 factionId, Player *player)
void UpdateWorldState (uint32 Field, uint32 Value)
void UpdateWorldStateForPlayer (uint32 Field, uint32 Value, Player *player)
virtual void EndBattleground (TeamId winnerTeamId)
void BlockMovement (Player *player)
void SendWarningToAll (uint32 entry,...)
void SendMessageToAll (uint32 entry, ChatMsg type, Player const *source=nullptr)
void PSendMessageToAll (uint32 entry, ChatMsg type, Player const *source,...)
void SendMessage2ToAll (uint32 entry, ChatMsg type, Player const *source, uint32 strId1=0, uint32 strId2=0)
Group * GetBgRaid (TeamId teamId) const
void SetBgRaid (TeamId teamId, Group *bg_raid)
virtual void UpdatePlayerScore (Player *player, uint32 type, uint32 value, bool doAddHonor=true)
uint32 GetPlayersCountByTeam (TeamId teamId) const
uint32 GetAlivePlayersCountByTeam (TeamId teamId) const
void UpdatePlayersCountByTeam (TeamId teamId, bool remove)
void SetArenaTeamIdForTeam (TeamId teamId, uint32 ArenaTeamId)
uint32 GetArenaTeamIdForTeam (TeamId teamId) const
void SetArenaTeamRatingChangeForTeam (TeamId teamId, int32 RatingChange)
int32 GetArenaTeamRatingChangeForTeam (TeamId teamId) const
void SetArenaMatchmakerRating (TeamId teamId, uint32 MMR)
uint32 GetArenaMatchmakerRating (TeamId teamId) const
void CheckArenaAfterTimerConditions ()
void CheckArenaWinConditions ()
virtual void HandleKillUnit (Creature *, Player *)
virtual void EventPlayerDroppedFlag (Player *)
virtual void EventPlayerClickedOnFlag (Player *, GameObject *)
virtual void EventPlayerDamagedGO (Player *, GameObject *, uint32)
virtual void EventPlayerUsedGO (Player *, GameObject *)
virtual void DoAction (uint32, ObjectGuid)
virtual void HandlePlayerResurrect (Player *)
virtual GraveyardStruct const * GetClosestGraveyard (Player *player)
void AddOrSetPlayerToCorrectBgGroup (Player *player, TeamId teamId)
void RemovePlayerAtLeave (Player *player)
void HandleTriggerBuff (GameObject *gameObject)
void SetHoliday (bool is_holiday)
void SpawnBGObject (uint32 type, uint32 respawntime, uint32 forceRespawnDelay=0)
bool AddObject (uint32 type, uint32 entry, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime=0, GOState goState=GO_STATE_READY)
Creature * AddCreature (uint32 entry, uint32 type, float x, float y, float z, float o, uint32 respawntime=0, MotionTransport *transport=nullptr)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool AddSpiritGuide (uint32 type, float x, float y, float z, float o, TeamId teamId)
int32 GetObjectType (ObjectGuid guid)
void DoorOpen (uint32 type)
void DoorClose (uint32 type)
const char * GetAcoreString (int32 entry)
bool IsPlayerInBattleground (ObjectGuid guid) const
bool ToBeDeleted () const
void RewardXPAtKill (Player *killer, Player *victim)
virtual ObjectGuid GetFlagPickerGUID (TeamId=TEAM_NEUTRAL) const
virtual void SetDroppedFlagGUID (ObjectGuid, TeamId=TEAM_NEUTRAL)
uint32 GetTeamScore (TeamId teamId) const
virtual TeamId GetPrematureWinner ()
uint8 GetUniqueBracketId () const
BattlegroundAV * ToBattlegroundAV ()
BattlegroundAV const * ToBattlegroundAV () const
BattlegroundWS * ToBattlegroundWS ()
BattlegroundWS const * ToBattlegroundWS () const
BattlegroundAB * ToBattlegroundAB ()
BattlegroundAB const * ToBattlegroundAB () const
BattlegroundNA * ToBattlegroundNA ()
BattlegroundNA const * ToBattlegroundNA () const
BattlegroundBE * ToBattlegroundBE ()
BattlegroundBE const * ToBattlegroundBE () const
BattlegroundEY * ToBattlegroundEY ()
BattlegroundEY const * ToBattlegroundEY () const
BattlegroundRL * ToBattlegroundRL ()
BattlegroundRL const * ToBattlegroundRL () const
BattlegroundSA * ToBattlegroundSA ()
BattlegroundSA const * ToBattlegroundSA () const
BattlegroundDS * ToBattlegroundDS ()
BattlegroundDS const * ToBattlegroundDS () const
BattlegroundRV * ToBattlegroundRV ()
BattlegroundRV const * ToBattlegroundRV () const
BattlegroundIC * ToBattlegroundIC ()
BattlegroundIC const * ToBattlegroundIC () const
Protected Member Functions
uint32 getTimer ()
void setTimer (uint32 timer)
uint32 getState ()
void setState (uint32 state)
void TeleportUnitToNewZ (Unit *unit, float newZ, bool casting)
void CheckPositionForUnit (Unit *unit)
void UpdatePillars ()
uint32 GetPillarIdForPos (Position *p)
Protected Member Functions inherited from Battleground
void EndNow ()
void PlayerAddedToBGCheckIfBGIsRunning (Player *player)
void _ProcessResurrect (uint32 diff)
void _ProcessProgress (uint32 diff)
void _ProcessLeave (uint32 diff)
void _ProcessJoin (uint32 diff)
void _CheckSafePositions (uint32 diff)
Private Member Functions
void PostUpdateImpl (uint32 diff) override
Post-update hook.
Private Attributes
uint32 Timer
uint32 State
uint16 CheckPlayersTimer
Additional Inherited Members
Public Types inherited from Battleground
typedef std::set< Player * > SpectatorList
typedef std::map< ObjectGuid, ObjectGuid > ToBeTeleportedMap
typedef std::map< ObjectGuid, Player * > BattlegroundPlayerMap
typedef std::map< ObjectGuid, BattlegroundScore * > BattlegroundScoreMap
typedef std::map< ObjectGuid, ArenaLogEntryData > ArenaLogEntryDataMap
typedef GuidVector BGObjects
typedef GuidVector BGCreatures
Static Public Member Functions inherited from Battleground
static TeamId GetOtherTeamId (TeamId teamId)
Public Attributes inherited from Battleground
GuidSet readyMarkerClickedSet
ArenaLogEntryDataMap ArenaLogEntries
BGObjects BgObjects
BGCreatures BgCreatures
Protected Attributes inherited from Battleground
BattlegroundScoreMap PlayerScores
BattlegroundPlayerMap m_Players
std::map< ObjectGuid, GuidVector > m_ReviveQueue
uint8 m_Events
BattlegroundStartTimeIntervals StartDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 StartMessageIds [BG_STARTING_EVENT_COUNT]
bool m_BuffChange
bool m_IsRandom
BGHonorMode m_HonorMode
int32 m_TeamScores [BG_TEAMS_COUNT]
uint32 m_UpdateTimer
Detailed Description
Definition at line 89 of file BattlegroundRV.h.
Constructor & Destructor Documentation
BattlegroundRV()
BattlegroundRV::BattlegroundRV ()
Definition at line 28 of file BattlegroundRV.cpp.
 {
     BgObjects.resize(BG_RV_OBJECT_MAX);
     StartDelayTimes[BG_STARTING_EVENT_FIRST]  = BG_START_DELAY_1M;
     StartDelayTimes[BG_STARTING_EVENT_SECOND] = BG_START_DELAY_30S;
     StartDelayTimes[BG_STARTING_EVENT_THIRD]  = BG_START_DELAY_15S;
     StartDelayTimes[BG_STARTING_EVENT_FOURTH] = BG_START_DELAY_NONE;
     StartMessageIds[BG_STARTING_EVENT_FIRST]  = LANG_ARENA_ONE_MINUTE;
     StartMessageIds[BG_STARTING_EVENT_SECOND] = LANG_ARENA_THIRTY_SECONDS;
     StartMessageIds[BG_STARTING_EVENT_THIRD]  = LANG_ARENA_FIFTEEN_SECONDS;
     StartMessageIds[BG_STARTING_EVENT_FOURTH] = LANG_ARENA_HAS_BEGUN;
     CheckPlayersTimer = 0;
 }
References BG_RV_OBJECT_MAX, BG_START_DELAY_15S, BG_START_DELAY_1M, BG_START_DELAY_30S, BG_START_DELAY_NONE, BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, Battleground::BgObjects, CheckPlayersTimer, LANG_ARENA_FIFTEEN_SECONDS, LANG_ARENA_HAS_BEGUN, LANG_ARENA_ONE_MINUTE, LANG_ARENA_THIRTY_SECONDS, Battleground::StartDelayTimes, and Battleground::StartMessageIds.
~BattlegroundRV()
BattlegroundRV::~BattlegroundRV () override
Definition at line 44 of file BattlegroundRV.cpp.
 { }
Member Function Documentation
AddPlayer()
void BattlegroundRV::AddPlayer (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 179 of file BattlegroundRV.cpp.
 {
     if (GetStatus() == STATUS_WAIT_JOIN && player->GetBgTeamId() == TEAM_HORDE)
         player->SetPhaseMask(2, true);
     Battleground::AddPlayer(player);
     PlayerScores[player->GetGUID()] = new BattlegroundScore(player);
     BattlegroundRV::UpdateArenaWorldState();
 }
References Battleground::AddPlayer(), Player::GetBgTeamId(), Object::GetGUID(), Battleground::GetStatus(), Battleground::PlayerScores, Unit::SetPhaseMask(), STATUS_WAIT_JOIN, TEAM_HORDE, and UpdateArenaWorldState().
CheckPositionForUnit()
void BattlegroundRV::CheckPositionForUnit (Unit * unit) protected
Definition at line 54 of file BattlegroundRV.cpp.
 {
     // get height at current pos, if something is wrong (below or high above) - teleport
     if (!unit->IsFalling() && unit->IsAlive())
     {
         float groundZ_vmap = unit->GetMap()->GetHeight(unit->GetPositionX(), unit->GetPositionY(), 37.0f, true, 50.0f);
         float groundZ_dyntree = unit->GetMap()->GetDynamicMapTree().getHeight(unit->GetPositionX(), unit->GetPositionY(), 37.0f, 50.0f, unit->GetPhaseMask());
         if ((groundZ_vmap > 28.0f && groundZ_vmap < 29.0f) || (groundZ_dyntree > 28.0f && groundZ_dyntree < 37.0f))
         {
             float groundZ = std::max<float>(groundZ_vmap, groundZ_dyntree);
             if (unit->GetPositionZ() < groundZ - 0.2f || unit->GetPositionZ() > groundZ + 3.5f)
                 TeleportUnitToNewZ(unit, groundZ + 1.0f, true);
         }
     }
 }
References Map::GetDynamicMapTree(), Map::GetHeight(), DynamicMapTree::getHeight(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsAlive(), Unit::IsFalling(), and TeleportUnitToNewZ().
Referenced by PostUpdateImpl().
FillInitialWorldStates()
void BattlegroundRV::FillInitialWorldStates (WorldPacket & d) override virtual
Reimplemented from Battleground.
Definition at line 245 of file BattlegroundRV.cpp.
 {
     data << uint32(BG_RV_WORLD_STATE) << uint32(1);
     BattlegroundRV::UpdateArenaWorldState();
 }
References BG_RV_WORLD_STATE, and UpdateArenaWorldState().
GetPillarAtPosition()
GameObject * BattlegroundRV::GetPillarAtPosition (Position * p)
Definition at line 344 of file BattlegroundRV.cpp.
 {
     uint32 pillar = GetPillarIdForPos(p);
     if (!pillar)
         return nullptr;
     return GetBgMap()->GetGameObject(BgObjects[pillar]);
 }
References Battleground::BgObjects, Battleground::GetBgMap(), Map::GetGameObject(), and GetPillarIdForPos().
GetPillarIdForPos()
uint32 BattlegroundRV::GetPillarIdForPos (Position * p) protected
Definition at line 330 of file BattlegroundRV.cpp.
 {
     float range = 1.75f;
     if (p->GetExactDist2d(763.632385f, -306.162384f) < range)
         return BG_RV_OBJECT_PILAR_1;
     if (p->GetExactDist2d(723.644287f, -284.493256f) < 2.0f * range)
         return BG_RV_OBJECT_PILAR_2;
     if (p->GetExactDist2d(763.611145f, -261.856750f) < range)
         return BG_RV_OBJECT_PILAR_3;
     if (p->GetExactDist2d(802.211609f, -284.493256f) < 2.0f * range)
         return BG_RV_OBJECT_PILAR_4;
     return 0;
 }
References BG_RV_OBJECT_PILAR_1, BG_RV_OBJECT_PILAR_2, BG_RV_OBJECT_PILAR_3, BG_RV_OBJECT_PILAR_4, and Position::GetExactDist2d().
Referenced by GetPillarAtPosition().
getState()
uint32 BattlegroundRV::getState () inline protected
Definition at line 120 of file BattlegroundRV.h.
 { return State; };
References State.
Referenced by HandleAreaTrigger(), and PostUpdateImpl().
getTimer()
uint32 BattlegroundRV::getTimer () inline protected
Definition at line 118 of file BattlegroundRV.h.
 { return Timer; }
References Timer.
Referenced by PostUpdateImpl().
HandleAreaTrigger()
void BattlegroundRV::HandleAreaTrigger (Player * player, uint32 trigger) override virtual
Reimplemented from Battleground.
Definition at line 221 of file BattlegroundRV.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS || getState() == BG_RV_STATE_OPEN_FENCES /*during elevator rising it's possible to jump and cause areatrigger*/)
         return;
     switch (trigger)
     {
         // fire was removed in 3.2.0
         case 5473:
         case 5474:
             break;
         // OUTSIDE OF ARENA, TELEPORT!
         case 5224:
             player->NearTeleportTo(765.0f, -294.0f, 28.3f, player->GetOrientation());
             break;
         case 5226:
             player->NearTeleportTo(765.0f, -272.0f, 28.3f, player->GetOrientation());
             break;
         case 5447:
             player->NearTeleportTo(763.5f, -284, 28.276f, 2.422f);
             break;
     }
 }
References BG_RV_STATE_OPEN_FENCES, Position::GetOrientation(), getState(), Battleground::GetStatus(), Unit::NearTeleportTo(), and STATUS_IN_PROGRESS.
HandleKillPlayer()
void BattlegroundRV::HandleKillPlayer (Player * player, Player * killer) override virtual
Reimplemented from Battleground.
Definition at line 201 of file BattlegroundRV.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS)
         return;
     if (!killer)
         return;
     Battleground::HandleKillPlayer(player, killer);
     BattlegroundRV::UpdateArenaWorldState();
     CheckArenaWinConditions();
 }
References Battleground::CheckArenaWinConditions(), Battleground::GetStatus(), Battleground::HandleKillPlayer(), STATUS_IN_PROGRESS, and UpdateArenaWorldState().
HandlePlayerUnderMap()
bool BattlegroundRV::HandlePlayerUnderMap (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 215 of file BattlegroundRV.cpp.
 {
     player->NearTeleportTo(763.5f, -284, 28.276f, 2.422f);
     return true;
 }
References Unit::NearTeleportTo().
Init()
void BattlegroundRV::Init () override virtual
Reimplemented from Battleground.
Definition at line 257 of file BattlegroundRV.cpp.
 {
     //call parent's class reset
     Battleground::Init();
 }
References Battleground::Init().
PostUpdateImpl()
void BattlegroundRV::PostUpdateImpl (uint32) override private virtual
Post-update hook.
Will be called after battleground update has passed. May be used to implement custom update effects in subclasses.
Parameters
diff a time difference between two worldserver update loops in milliseconds.
See also
Update(), PreUpdateImpl().
Reimplemented from Battleground.
Definition at line 70 of file BattlegroundRV.cpp.
 {
     if (GetStatus() != STATUS_IN_PROGRESS)
         return;
     if (getTimer() < diff)
     {
         switch (getState())
         {
             case BG_RV_STATE_OPEN_FENCES:
                 for (uint8 i = BG_RV_OBJECT_FIRE_1; i <= BG_RV_OBJECT_FIREDOOR_2; ++i)
                     DoorOpen(i);
                 setTimer(BG_RV_CLOSE_FIRE_TIMER);
                 setState(BG_RV_STATE_CLOSE_FIRE);
                 for (auto itr = m_Players.begin(); itr != m_Players.end(); ++itr)
                     if (Player* player = itr->second)
                     {
                         // Demonic Circle Summon
                         if (GameObject* gObj = player->GetGameObject(48018))
{
                             gObj->Relocate(gObj->GetPositionX(), gObj->GetPositionY(), 28.28f);
                             gObj->UpdateObjectVisibility(true);
                         }
                         if (player->GetPositionZ() < 27.0f)
                             TeleportUnitToNewZ(player, 28.28f, true);
                         for (uint8 i = SUMMON_SLOT_TOTEM; i < MAX_TOTEM_SLOT; ++i)
                             if (player->m_SummonSlot[i])
                                 if (Creature* totem = GetBgMap()->GetCreature(player->m_SummonSlot[i]))
                                     if (totem->GetPositionZ() < 28.0f)
                                         TeleportUnitToNewZ(totem, 28.28f, true);
                         for (auto itr2 = player->m_Controlled.begin(); itr2 != player->m_Controlled.end(); ++itr2)
{
                             if ((*itr2)->GetPositionZ() < 28.0f)
                                 TeleportUnitToNewZ((*itr2), 28.28f, true);
                             // Xinef: override stay position
                             if (CharmInfo* charmInfo = (*itr2)->GetCharmInfo())
                                 if (charmInfo->IsAtStay())
{
                                     (*itr2)->StopMovingOnCurrentPos();
                                     charmInfo->SaveStayPosition(false);
                                 }
                         }
                     }
                 // fix ground on elevators (so aoe spells can be casted there)
                 {
                     uint32 objects[2] = {BG_RV_OBJECT_ELEVATOR_1, BG_RV_OBJECT_ELEVATOR_2};
                     for (uint8 i = 0; i < 2; ++i)
                         if (GameObject* go = GetBGObject(objects[i]))
                             go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_TRANSPORT);
                 }
                 break;
             case BG_RV_STATE_CLOSE_FIRE:
                 for (uint8 i = BG_RV_OBJECT_FIRE_1; i <= BG_RV_OBJECT_FIREDOOR_2; ++i)
                     DoorClose(i);
                 // Fire got closed after five seconds, leaves twenty seconds before toggling pillars
                 setTimer(BG_RV_FIRE_TO_PILLAR_TIMER);
                 setState(BG_RV_STATE_SWITCH_PILLARS);
                 break;
             case BG_RV_STATE_SWITCH_PILLARS:
                 UpdatePillars();
                 setTimer(BG_RV_PILLAR_SWITCH_TIMER);
                 break;
         }
     }
     else
         setTimer(getTimer() - diff);
     if (getState() == BG_RV_STATE_OPEN_FENCES)
         return;
     if (CheckPlayersTimer <= diff)
     {
         CheckPlayersTimer = 0;
         for (BattlegroundPlayerMap::iterator itr = m_Players.begin(); itr != m_Players.end(); ++itr)
             CheckPositionForUnit(itr->second);
         // maybe for pets and m_Controlled also, but not really necessary
     }
     else
         CheckPlayersTimer -= diff;
 }
References BG_RV_CLOSE_FIRE_TIMER, BG_RV_FIRE_TO_PILLAR_TIMER, BG_RV_OBJECT_ELEVATOR_1, BG_RV_OBJECT_ELEVATOR_2, BG_RV_OBJECT_FIRE_1, BG_RV_OBJECT_FIREDOOR_2, BG_RV_PILLAR_SWITCH_TIMER, BG_RV_STATE_CLOSE_FIRE, BG_RV_STATE_OPEN_FENCES, BG_RV_STATE_SWITCH_PILLARS, CheckPlayersTimer, CheckPositionForUnit(), Battleground::DoorClose(), Battleground::DoorOpen(), GAMEOBJECT_FLAGS, Battleground::GetBgMap(), Battleground::GetBGObject(), ObjectAccessor::GetCreature(), getState(), Battleground::GetStatus(), getTimer(), GO_FLAG_TRANSPORT, Battleground::m_Players, MAX_TOTEM_SLOT, setState(), setTimer(), STATUS_IN_PROGRESS, SUMMON_SLOT_TOTEM, TeleportUnitToNewZ(), and UpdatePillars().
RemovePlayer()
void BattlegroundRV::RemovePlayer (Player * player) override virtual
Reimplemented from Battleground.
Definition at line 189 of file BattlegroundRV.cpp.
 {
     if (GetStatus() == STATUS_WAIT_LEAVE)
         return;
     if (GetStatus() == STATUS_WAIT_JOIN)
         player->SetPhaseMask(1, true);
     BattlegroundRV::UpdateArenaWorldState();
     CheckArenaWinConditions();
 }
References Battleground::CheckArenaWinConditions(), Battleground::GetStatus(), Unit::SetPhaseMask(), STATUS_WAIT_JOIN, STATUS_WAIT_LEAVE, and UpdateArenaWorldState().
setState()
void BattlegroundRV::setState (uint32 state) inline protected
Definition at line 121 of file BattlegroundRV.h.
 { State = state; }
References State.
Referenced by PostUpdateImpl(), and StartingEventOpenDoors().
setTimer()
void BattlegroundRV::setTimer (uint32 timer) inline protected
Definition at line 119 of file BattlegroundRV.h.
 { Timer = timer; }
Referenced by PostUpdateImpl(), and StartingEventOpenDoors().
SetupBattleground()
bool BattlegroundRV::SetupBattleground () override virtual
Reimplemented from Battleground.
Definition at line 263 of file BattlegroundRV.cpp.
 {
     // elevators
     if (!AddObject(BG_RV_OBJECT_ELEVATOR_1, BG_RV_OBJECT_TYPE_ELEVATOR_1, 763.536377f, -294.535767f, 0.505383f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_ELEVATOR_2, BG_RV_OBJECT_TYPE_ELEVATOR_2, 763.506348f, -273.873352f, 0.505383f, 0.000000f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             // buffs
             || !AddObject(BG_RV_OBJECT_BUFF_1, BG_RV_OBJECT_TYPE_BUFF_1, 735.551819f, -284.794678f, 28.276682f, 0.034906f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_BUFF_2, BG_RV_OBJECT_TYPE_BUFF_2, 791.224487f, -284.794464f, 28.276682f, 2.600535f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             // fire
             || !AddObject(BG_RV_OBJECT_FIRE_1, BG_RV_OBJECT_TYPE_FIRE_1, 743.543457f, -283.799469f, 28.286655f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_FIRE_2, BG_RV_OBJECT_TYPE_FIRE_2, 782.971802f, -283.799469f, 28.286655f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_FIREDOOR_1, BG_RV_OBJECT_TYPE_FIREDOOR_1, 743.711060f, -284.099609f, 27.542587f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_FIREDOOR_2, BG_RV_OBJECT_TYPE_FIREDOOR_2, 783.221252f, -284.133362f, 27.535686f, 0.000000f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             // Gear
             || !AddObject(BG_RV_OBJECT_GEAR_1, BG_RV_OBJECT_TYPE_GEAR_1, 763.664551f, -261.872986f, 26.686588f, 0.000000f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_GEAR_2, BG_RV_OBJECT_TYPE_GEAR_2, 763.578979f, -306.146149f, 26.665222f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             // Pulley
             || !AddObject(BG_RV_OBJECT_PULLEY_1, BG_RV_OBJECT_TYPE_PULLEY_1, 700.722290f, -283.990662f, 39.517582f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_PULLEY_2, BG_RV_OBJECT_TYPE_PULLEY_2, 826.303833f, -283.996429f, 39.517582f, 0.000000f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             // Pilars
             || !AddObject(BG_RV_OBJECT_PILAR_1, BG_RV_OBJECT_TYPE_PILAR_1, 763.632385f, -306.162384f, 25.909504f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_PILAR_2, BG_RV_OBJECT_TYPE_PILAR_2, 723.644287f, -284.493256f, 24.648525f, 3.141593f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_PILAR_3, BG_RV_OBJECT_TYPE_PILAR_3, 763.611145f, -261.856750f, 25.909504f, 0.000000f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             || !AddObject(BG_RV_OBJECT_PILAR_4, BG_RV_OBJECT_TYPE_PILAR_4, 802.211609f, -284.493256f, 24.648525f, 0.000000f, 0, 0, 0, RESPAWN_IMMEDIATELY)
             // Arena Ready Marker
             || !AddObject(BG_RV_OBJECT_READY_MARKER_1, ARENA_READY_MARKER_ENTRY, 769.93f, -301.04f, 2.80f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300)
             || !AddObject(BG_RV_OBJECT_READY_MARKER_2, ARENA_READY_MARKER_ENTRY, 757.02f, -267.30f, 2.80f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 300)
        )
     {
         LOG_ERROR("sql.sql", "BatteGroundRV: Failed to spawn some object!");
         return false;
     }
     for (uint8 i = 0; i < BG_RV_OBJECT_MAX; ++i)
         if (GameObject* go = GetBGObject(i))
             go->SetPhaseMask(3, true);
     return true;
 }
References Battleground::AddObject(), ARENA_READY_MARKER_ENTRY, BG_RV_OBJECT_BUFF_1, BG_RV_OBJECT_BUFF_2, BG_RV_OBJECT_ELEVATOR_1, BG_RV_OBJECT_ELEVATOR_2, BG_RV_OBJECT_FIRE_1, BG_RV_OBJECT_FIRE_2, BG_RV_OBJECT_FIREDOOR_1, BG_RV_OBJECT_FIREDOOR_2, BG_RV_OBJECT_GEAR_1, BG_RV_OBJECT_GEAR_2, BG_RV_OBJECT_MAX, BG_RV_OBJECT_PILAR_1, BG_RV_OBJECT_PILAR_2, BG_RV_OBJECT_PILAR_3, BG_RV_OBJECT_PILAR_4, BG_RV_OBJECT_PULLEY_1, BG_RV_OBJECT_PULLEY_2, BG_RV_OBJECT_READY_MARKER_1, BG_RV_OBJECT_READY_MARKER_2, BG_RV_OBJECT_TYPE_BUFF_1, BG_RV_OBJECT_TYPE_BUFF_2, BG_RV_OBJECT_TYPE_ELEVATOR_1, BG_RV_OBJECT_TYPE_ELEVATOR_2, BG_RV_OBJECT_TYPE_FIRE_1, BG_RV_OBJECT_TYPE_FIRE_2, BG_RV_OBJECT_TYPE_FIREDOOR_1, BG_RV_OBJECT_TYPE_FIREDOOR_2, BG_RV_OBJECT_TYPE_GEAR_1, BG_RV_OBJECT_TYPE_GEAR_2, BG_RV_OBJECT_TYPE_PILAR_1, BG_RV_OBJECT_TYPE_PILAR_2, BG_RV_OBJECT_TYPE_PILAR_3, BG_RV_OBJECT_TYPE_PILAR_4, BG_RV_OBJECT_TYPE_PULLEY_1, BG_RV_OBJECT_TYPE_PULLEY_2, Battleground::GetBGObject(), LOG_ERROR, and RESPAWN_IMMEDIATELY.
StartingEventCloseDoors()
void BattlegroundRV::StartingEventCloseDoors () override virtual
Reimplemented from Battleground.
Definition at line 158 of file BattlegroundRV.cpp.
 {
 }
StartingEventOpenDoors()
void BattlegroundRV::StartingEventOpenDoors () override virtual
Reimplemented from Battleground.
Definition at line 162 of file BattlegroundRV.cpp.
 {
     for (BattlegroundPlayerMap::iterator itr = m_Players.begin(); itr != m_Players.end(); ++itr)
         itr->second->SetPhaseMask(1, true);
     // Buff respawn
     SpawnBGObject(BG_RV_OBJECT_BUFF_1, 90);
     SpawnBGObject(BG_RV_OBJECT_BUFF_2, 90);
     // Elevators
     DoorOpen(BG_RV_OBJECT_ELEVATOR_1);
     DoorOpen(BG_RV_OBJECT_ELEVATOR_2);
     setState(BG_RV_STATE_OPEN_FENCES);
     setTimer(BG_RV_FIRST_TIMER);
 }
References BG_RV_FIRST_TIMER, BG_RV_OBJECT_BUFF_1, BG_RV_OBJECT_BUFF_2, BG_RV_OBJECT_ELEVATOR_1, BG_RV_OBJECT_ELEVATOR_2, BG_RV_STATE_OPEN_FENCES, Battleground::DoorOpen(), Battleground::m_Players, setState(), setTimer(), and Battleground::SpawnBGObject().
TeleportUnitToNewZ()
void BattlegroundRV::TeleportUnitToNewZ (Unit * unit, float newZ, bool casting) protected
Definition at line 46 of file BattlegroundRV.cpp.
 {
     if (!unit->IsAlive())
         return;
     unit->NearTeleportTo(unit->GetPositionX(), unit->GetPositionY(), newZ, unit->GetOrientation(), casting);
     unit->m_positionZ = newZ;
 }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Unit::IsAlive(), Position::m_positionZ, and Unit::NearTeleportTo().
Referenced by CheckPositionForUnit(), and PostUpdateImpl().
UpdateArenaWorldState()
void BattlegroundRV::UpdateArenaWorldState () override virtual
Reimplemented from Battleground.
Definition at line 251 of file BattlegroundRV.cpp.
 {
     UpdateWorldState(BG_RV_WORLD_STATE_A, GetAlivePlayersCountByTeam(TEAM_ALLIANCE));
     UpdateWorldState(BG_RV_WORLD_STATE_H, GetAlivePlayersCountByTeam(TEAM_HORDE));
 }
References BG_RV_WORLD_STATE_A, BG_RV_WORLD_STATE_H, Battleground::GetAlivePlayersCountByTeam(), TEAM_ALLIANCE, TEAM_HORDE, and Battleground::UpdateWorldState().
Referenced by AddPlayer(), FillInitialWorldStates(), HandleKillPlayer(), and RemovePlayer().
UpdatePillars()
void BattlegroundRV::UpdatePillars () protected
Definition at line 304 of file BattlegroundRV.cpp.
 {
     GameObject* test = GetBgMap()->GetGameObject(BgObjects[BG_RV_OBJECT_PILAR_1]);
     if (!test)
         return;
     if (test->GetGoState() == GO_STATE_READY)
     {
         for (uint8 i = BG_RV_OBJECT_PILAR_1; i <= BG_RV_OBJECT_GEAR_2; ++i)
             if (GameObject* go = GetBgMap()->GetGameObject(BgObjects[i]))
                 go->SetGoState(GO_STATE_ACTIVE);
         for (uint8 i = BG_RV_OBJECT_PILAR_2; i <= BG_RV_OBJECT_PULLEY_2; ++i)
             if (GameObject* go = GetBgMap()->GetGameObject(BgObjects[i]))
                 go->SetGoState(GO_STATE_READY);
     }
     else
     {
         for (uint8 i = BG_RV_OBJECT_PILAR_1; i <= BG_RV_OBJECT_GEAR_2; ++i)
             if (GameObject* go = GetBgMap()->GetGameObject(BgObjects[i]))
                 go->SetGoState(GO_STATE_READY);
         for (uint8 i = BG_RV_OBJECT_PILAR_2; i <= BG_RV_OBJECT_PULLEY_2; ++i)
             if (GameObject* go = GetBgMap()->GetGameObject(BgObjects[i]))
                 go->SetGoState(GO_STATE_ACTIVE);
     }
 }
References BG_RV_OBJECT_GEAR_2, BG_RV_OBJECT_PILAR_1, BG_RV_OBJECT_PILAR_2, BG_RV_OBJECT_PULLEY_2, Battleground::BgObjects, Battleground::GetBgMap(), Map::GetGameObject(), ObjectAccessor::GetGameObject(), GameObject::GetGoState(), GO_STATE_ACTIVE, GO_STATE_READY, and GameObject::SetGoState().
Referenced by PostUpdateImpl().
Member Data Documentation
CheckPlayersTimer
uint16 BattlegroundRV::CheckPlayersTimer private
Definition at line 113 of file BattlegroundRV.h.
Referenced by BattlegroundRV(), and PostUpdateImpl().
State
uint32 BattlegroundRV::State private
Definition at line 112 of file BattlegroundRV.h.
Referenced by getState(), and setState().
Timer
uint32 BattlegroundRV::Timer private
Definition at line 111 of file BattlegroundRV.h.
Referenced by getTimer().
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/Zones/BattlegroundRV.h
src/server/game/Battlegrounds/Zones/BattlegroundRV.cpp