Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/stats.h File Reference
stats.h File Reference
Macros
#define STATS_PRINT_OPTIONS
#define OPTION(o, v, d, s) stats_print_option_num_##v,
Enumerations
enum { stats_print_tot_num_options }
Functions
void stats_print (void(*write_cb)(void *, const char *), void *cbopaque, const char *opts)
Variables
bool opt_stats_print
char opt_stats_print_opts [stats_print_tot_num_options+1]
Macro Definition Documentation
OPTION
#define OPTION (o, v, d, s) stats_print_option_num_##v,
Definition at line 17 of file stats.h.
STATS_PRINT_OPTIONS
#define STATS_PRINT_OPTIONS
Value:
    OPTION('J',     json,       false,      true)       \
    OPTION('g',     general,    true,       false)      \
    OPTION('m',     merged,     config_stats,   false)      \
    OPTION('d',     destroyed,  config_stats,   false)      \
    OPTION('a',     unmerged,   config_stats,   false)      \
    OPTION('b',     bins,       true,       false)      \
    OPTION('l',     large,      true,       false)      \
    OPTION('x',     mutex,      true,       false)      \
    OPTION('e',     extents,    true,       false)
Definition at line 5 of file stats.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
stats_print_tot_num_options
Definition at line 16 of file stats.h.
      {
 #define OPTION(o, v, d, s) stats_print_option_num_##v,
     STATS_PRINT_OPTIONS
 #undef OPTION
     stats_print_tot_num_options
 };
Function Documentation
stats_print()
void stats_print (void(*)(void *, const char *) write_cb, void * cbopaque, const char * opts)
Definition at line 1396 of file stats.c.
                       {
     int err;
     uint64_t epoch;
     size_t u64sz;
 #define OPTION(o, v, d, s) bool v = d;
     STATS_PRINT_OPTIONS
 #undef OPTION
     /*
      * Refresh stats, in case mallctl() was called by the application.
      *
      * Check for OOM here, since refreshing the ctl cache can trigger
      * allocation.  In practice, none of the subsequent mallctl()-related
      * calls in this function will cause OOM if this one succeeds.
      * */
     epoch = 1;
     u64sz = sizeof(uint64_t);
     err = je_mallctl("epoch", (void *)&epoch, &u64sz, (void *)&epoch,
         sizeof(uint64_t));
     if (err != 0) {
         if (err == EAGAIN) {
             malloc_write("<jemalloc>: Memory allocation failure in "
                 "mallctl(\"epoch\", ...)\n");
             return;
         }
         malloc_write("<jemalloc>: Failure in mallctl(\"epoch\", "
             "...)\n");
         abort();
     }
     if (opts != NULL) {
         for (unsigned i = 0; opts[i] != '\0'; i++) {
             switch (opts[i]) {
 #define OPTION(o, v, d, s) case o: v = s; break;
                 STATS_PRINT_OPTIONS
 #undef OPTION
             default:;
             }
         }
     }
     emitter_t emitter;
     emitter_init(&emitter,
         json ? emitter_output_json : emitter_output_table, write_cb,
         cbopaque);
     emitter_begin(&emitter);
     emitter_table_printf(&emitter, "___ Begin jemalloc statistics ___\n");
     emitter_json_object_kv_begin(&emitter, "jemalloc");
     if (general) {
         stats_general_print(&emitter);
     }
     if (config_stats) {
         stats_print_helper(&emitter, merged, destroyed, unmerged,
             bins, large, mutex, extents);
     }
     emitter_json_object_end(&emitter); /* Closes the "jemalloc" dict. */
     emitter_table_printf(&emitter, "--- End jemalloc statistics ---\n");
     emitter_end(&emitter);
 }
References config_stats, emitter_begin(), emitter_end(), emitter_init(), emitter_json_object_end(), emitter_json_object_kv_begin(), emitter_output_json, emitter_output_table, emitter_table_printf(), general, je_mallctl, malloc_write, NULL, stats_general_print(), stats_print_helper(), and STATS_PRINT_OPTIONS.
Variable Documentation
opt_stats_print
bool opt_stats_print extern
Definition at line 50 of file stats.c.
opt_stats_print_opts
char opt_stats_print_opts[stats_print_tot_num_options+1] extern
Definition at line 51 of file stats.c.