Azerotcore-wotlk: VendorItemData Struct Reference
VendorItemData Struct Reference
#include <CreatureData.h>
Public Member Functions
VendorItem * GetItem (uint32 slot) const
bool Empty () const
uint8 GetItemCount () const
void AddItem (uint32 item, int32 maxcount, uint32 ptime, uint32 ExtendedCost)
bool RemoveItem (uint32 item_id)
VendorItem const * FindItemCostPair (uint32 item_id, uint32 extendedCost) const
void Clear ()
Public Attributes
VendorItemList m_items
Detailed Description
Definition at line 365 of file CreatureData.h.
Member Function Documentation
AddItem()
void VendorItemData::AddItem (uint32 item, int32 maxcount, uint32 ptime, uint32 ExtendedCost) inline
Definition at line 378 of file CreatureData.h.
     {
         m_items.push_back(new VendorItem(item, maxcount, ptime, ExtendedCost));
     }
References m_items.
Referenced by ObjectMgr::AddVendorItem(), ObjectMgr::LoadReferenceVendor(), and ObjectMgr::LoadVendors().
Clear()
void VendorItemData::Clear () inline
Definition at line 384 of file CreatureData.h.
     {
         for (VendorItemList::const_iterator itr = m_items.begin(); itr != m_items.end(); ++itr)
             delete (*itr);
         m_items.clear();
     }
References m_items.
Empty()
bool VendorItemData::Empty () const inline
Definition at line 376 of file CreatureData.h.
 { return m_items.empty(); }
References m_items.
Referenced by Player::BuyItemFromVendorSlot(), and Player::PrepareGossipMenu().
FindItemCostPair()
VendorItem const * VendorItemData::FindItemCostPair (uint32 item_id, uint32 extendedCost) const
Definition at line 85 of file Creature.cpp.
 {
     for (VendorItemList::const_iterator i = m_items.begin(); i != m_items.end(); ++i)
         if ((*i)->item == item_id && (*i)->ExtendedCost == extendedCost)
             return *i;
     return nullptr;
 }
References m_items.
Referenced by ObjectMgr::IsVendorItemValid().
GetItem()
VendorItem* VendorItemData::GetItem (uint32 slot) const inline
Definition at line 369 of file CreatureData.h.
     {
         if (slot >= m_items.size())
             return nullptr;
         return m_items[slot];
     }
References m_items.
Referenced by Player::BuyItemFromVendorSlot(), and WorldSession::SendListInventory().
GetItemCount()
uint8 VendorItemData::GetItemCount () const inline
Definition at line 377 of file CreatureData.h.
 { return m_items.size(); }
References m_items.
Referenced by Player::BuyItemFromVendorSlot(), and WorldSession::SendListInventory().
RemoveItem()
bool VendorItemData::RemoveItem (uint32 item_id)
Definition at line 69 of file Creature.cpp.
 {
     bool found = false;
     for (VendorItemList::iterator i = m_items.begin(); i != m_items.end();)
     {
         if ((*i)->item == item_id)
         {
             i = m_items.erase(i++);
             found = true;
         }
         else
             ++i;
     }
     return found;
 }
References m_items.
Member Data Documentation
m_items
VendorItemList VendorItemData::m_items
Definition at line 367 of file CreatureData.h.
Referenced by AddItem(), Clear(), Empty(), FindItemCostPair(), GetItem(), GetItemCount(), and RemoveItem().
The documentation for this struct was generated from the following files:
src/server/game/Entities/Creature/CreatureData.h
src/server/game/Entities/Creature/Creature.cpp