Azerotcore-wotlk: deps/mysqllite/mysys/my_chsize.c File Reference
my_chsize.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include "m_string.h"
Functions
int my_chsize (File fd, my_off_t newlength, int filler, myf MyFlags)
Function Documentation
my_chsize()
int my_chsize (File fd, my_off_t newlength, int filler, myf MyFlags)
Definition at line 40 of file my_chsize.c.
 {
   my_off_t oldsize;
   uchar buff[IO_SIZE];
   DBUG_ENTER("my_chsize");
   DBUG_PRINT("my",("fd: %d  length: %lu  MyFlags: %d",fd,(ulong) newlength,
            MyFlags));
   if ((oldsize= my_seek(fd, 0L, MY_SEEK_END, MYF(MY_WME+MY_FAE))) == newlength)
     DBUG_RETURN(0);
   DBUG_PRINT("info",("old_size: %ld", (ulong) oldsize));
   if (oldsize > newlength)
   {
 #ifdef _WIN32
     if (my_win_chsize(fd, newlength))
     {
       my_errno= errno;
       goto err;
     }
     DBUG_RETURN(0);
 #elif defined(HAVE_FTRUNCATE)
     if (ftruncate(fd, (off_t) newlength))
     {
       my_errno= errno;
       goto err;
     }
     DBUG_RETURN(0);
 #elif defined(HAVE_CHSIZE)
     if (chsize(fd, (off_t) newlength))
     {
       my_errno=errno;
       goto err;
     }
     DBUG_RETURN(0);
 #else
     /*
       Fill space between requested length and true length with 'filler'
       We should never come here on any modern machine
     */
     if (my_seek(fd, newlength, MY_SEEK_SET, MYF(MY_WME+MY_FAE))
         == MY_FILEPOS_ERROR)
     {
       goto err;
     }
     swap_variables(my_off_t, newlength, oldsize);
 #endif
   }
   /* Full file with 'filler' until it's as big as requested */
   bfill(buff, IO_SIZE, filler);
   while (newlength-oldsize > IO_SIZE)
   {
     if (my_write(fd, buff, IO_SIZE, MYF(MY_NABP)))
       goto err;
     oldsize+= IO_SIZE;
   }
   if (my_write(fd,buff,(size_t) (newlength-oldsize), MYF(MY_NABP)))
     goto err;
   DBUG_RETURN(0);
 err:
   DBUG_PRINT("error", ("errno: %d", errno));
   if (MyFlags & MY_WME)
     my_error(EE_CANT_CHSIZE, MYF(ME_BELL+ME_WAITTANG), my_errno);
   DBUG_RETURN(1);
 } /* my_chsize */
References bfill, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_CHSIZE, errno, IO_SIZE, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILEPOS_ERROR, MY_NABP, my_seek(), MY_SEEK_END, MY_SEEK_SET, MY_WME, my_write, MYF, mpq::off_t, and swap_variables.
Referenced by inline_mysql_file_chsize().