Azerotcore-wotlk: src/server/game/Entities/Item/ItemEnchantmentMgr.h File Reference
ItemEnchantmentMgr.h File Reference
#include "Common.h"
Functions
void LoadRandomEnchantmentsTable ()
uint32 GetItemEnchantMod (int32 entry)
uint32 GenerateEnchSuffixFactor (uint32 item_id)
Function Documentation
GenerateEnchSuffixFactor()
uint32 GenerateEnchSuffixFactor (uint32 item_id)
Definition at line 123 of file ItemEnchantmentMgr.cpp.
 {
     ItemTemplate const* itemProto = sObjectMgr->GetItemTemplate(item_id);
     if (!itemProto)
         return 0;
     if (!itemProto->RandomSuffix)
         return 0;
     RandomPropertiesPointsEntry const* randomProperty = sRandomPropertiesPointsStore.LookupEntry(itemProto->ItemLevel);
     if (!randomProperty)
         return 0;
     uint32 suffixFactor;
     switch (itemProto->InventoryType)
     {
         // Items of that type don`t have points
         case INVTYPE_NON_EQUIP:
         case INVTYPE_BAG:
         case INVTYPE_TABARD:
         case INVTYPE_AMMO:
         case INVTYPE_QUIVER:
         case INVTYPE_RELIC:
             return 0;
         // Select point coefficient
         case INVTYPE_HEAD:
         case INVTYPE_BODY:
         case INVTYPE_CHEST:
         case INVTYPE_LEGS:
         case INVTYPE_2HWEAPON:
         case INVTYPE_ROBE:
             suffixFactor = 0;
             break;
         case INVTYPE_SHOULDERS:
         case INVTYPE_WAIST:
         case INVTYPE_FEET:
         case INVTYPE_HANDS:
         case INVTYPE_TRINKET:
             suffixFactor = 1;
             break;
         case INVTYPE_NECK:
         case INVTYPE_WRISTS:
         case INVTYPE_FINGER:
         case INVTYPE_SHIELD:
         case INVTYPE_CLOAK:
         case INVTYPE_HOLDABLE:
             suffixFactor = 2;
             break;
         case INVTYPE_WEAPON:
         case INVTYPE_WEAPONMAINHAND:
         case INVTYPE_WEAPONOFFHAND:
             suffixFactor = 3;
             break;
         case INVTYPE_RANGED:
         case INVTYPE_THROWN:
         case INVTYPE_RANGEDRIGHT:
             suffixFactor = 4;
             break;
         default:
             return 0;
     }
     // Select rare/epic modifier
     switch (itemProto->Quality)
     {
         case ITEM_QUALITY_UNCOMMON:
             return randomProperty->UncommonPropertiesPoints[suffixFactor];
         case ITEM_QUALITY_RARE:
             return randomProperty->RarePropertiesPoints[suffixFactor];
         case ITEM_QUALITY_EPIC:
             return randomProperty->EpicPropertiesPoints[suffixFactor];
         case ITEM_QUALITY_LEGENDARY:
         case ITEM_QUALITY_ARTIFACT:
             return 0;                                       // not have random properties
         default:
             break;
     }
     return 0;
 }
References RandomPropertiesPointsEntry::EpicPropertiesPoints, ItemTemplate::InventoryType, INVTYPE_2HWEAPON, INVTYPE_AMMO, INVTYPE_BAG, INVTYPE_BODY, INVTYPE_CHEST, INVTYPE_CLOAK, INVTYPE_FEET, INVTYPE_FINGER, INVTYPE_HANDS, INVTYPE_HEAD, INVTYPE_HOLDABLE, INVTYPE_LEGS, INVTYPE_NECK, INVTYPE_NON_EQUIP, INVTYPE_QUIVER, INVTYPE_RANGED, INVTYPE_RANGEDRIGHT, INVTYPE_RELIC, INVTYPE_ROBE, INVTYPE_SHIELD, INVTYPE_SHOULDERS, INVTYPE_TABARD, INVTYPE_THROWN, INVTYPE_TRINKET, INVTYPE_WAIST, INVTYPE_WEAPON, INVTYPE_WEAPONMAINHAND, INVTYPE_WEAPONOFFHAND, INVTYPE_WRISTS, ITEM_QUALITY_ARTIFACT, ITEM_QUALITY_EPIC, ITEM_QUALITY_LEGENDARY, ITEM_QUALITY_RARE, ITEM_QUALITY_UNCOMMON, ItemTemplate::ItemLevel, ItemTemplate::Quality, ItemTemplate::RandomSuffix, RandomPropertiesPointsEntry::RarePropertiesPoints, sObjectMgr, sRandomPropertiesPointsStore, and RandomPropertiesPointsEntry::UncommonPropertiesPoints.
Referenced by LootItem::LootItem(), and Item::UpdateItemSuffixFactor().
GetItemEnchantMod()
uint32 GetItemEnchantMod (int32 entry)
Definition at line 82 of file ItemEnchantmentMgr.cpp.
 {
     if (!entry)
         return 0;
     if (entry == -1)
         return 0;
     EnchantmentStore::const_iterator tab = RandomItemEnch.find(entry);
     if (tab == RandomItemEnch.end())
     {
         LOG_ERROR("sql.sql", "Item RandomProperty / RandomSuffix id #%u used in `item_template` but it does not have records in `item_enchantment_template` table.", entry);
         return 0;
     }
     double dRoll = rand_chance();
     float fCount = 0;
     for (EnchStoreList::const_iterator ench_iter = tab->second.begin(); ench_iter != tab->second.end(); ++ench_iter)
     {
         fCount += ench_iter->chance;
         if (fCount > dRoll)
             return ench_iter->ench;
     }
     //we could get here only if sum of all enchantment chances is lower than 100%
     dRoll = (irand(0, (int)floor(fCount * 100) + 1)) / 100;
     fCount = 0;
     for (EnchStoreList::const_iterator ench_iter = tab->second.begin(); ench_iter != tab->second.end(); ++ench_iter)
     {
         fCount += ench_iter->chance;
         if (fCount > dRoll)
             return ench_iter->ench;
     }
     return 0;
 }
References G3D::floor(), irand(), LOG_ERROR, rand_chance(), and RandomItemEnch.
Referenced by Item::GenerateItemRandomPropertyId(), and ObjectMgr::LoadItemTemplates().
LoadRandomEnchantmentsTable()
void LoadRandomEnchantmentsTable ()
Definition at line 45 of file ItemEnchantmentMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     RandomItemEnch.clear();                                 // for reload case
     //                                                 0      1      2
     QueryResult result = WorldDatabase.Query("SELECT entry, ench, chance FROM item_enchantment_template");
     if (result)
     {
         uint32 count = 0;
         do
         {
             Field* fields = result->Fetch();
             uint32 entry = fields[0].GetUInt32();
             uint32 ench = fields[1].GetUInt32();
             float chance = fields[2].GetFloat();
             if (chance > 0.000001f && chance <= 100.0f)
                 RandomItemEnch[entry].push_back(EnchStoreItem(ench, chance));
             ++count;
         } while (result->NextRow());
         LOG_INFO("server.loading", ">> Loaded %u Item Enchantment definitions in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
         LOG_INFO("server.loading", " ");
     }
     else
     {
         LOG_ERROR("sql.sql", ">> Loaded 0 Item Enchantment definitions. DB table `item_enchantment_template` is empty.");
         LOG_INFO("server.loading", " ");
     }
 }
References count(), Field::GetFloat(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_ERROR, LOG_INFO, RandomItemEnch, and WorldDatabase.
Referenced by reload_commandscript::HandleReloadItemEnchantementsCommand(), and World::SetInitialWorldSettings().