Azerotcore-wotlk: boss_sartharion_dragonAI Struct Reference
boss_sartharion_dragonAI Struct Reference
Public Member Functions
boss_sartharion_dragonAI (Creature *pCreature, uint32 bossId)
void Reset () override
void DoAction (int32 param) final
void MoveInLineOfSight (Unit *who) final
void MovementInform (uint32 type, uint32 pointId) final
void JustSummoned (Creature *summon) override
void EnterCombat (Unit *) final
void JustDied (Unit *) override
void KilledUnit (Unit *victim) final
void UpdateAI (uint32 diff) final
virtual void ClearInstance ()
virtual void HandleExtraEvent (uint32 const)
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Protected Member Functions
void RemoveTwilightPortal ()
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes
EventMap extraEvents
ObjectGuid portalGUID
bool isCalledBySartharion
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Detailed Description
Definition at line 720 of file boss_sartharion.cpp.
Constructor & Destructor Documentation
boss_sartharion_dragonAI()
boss_sartharion_dragonAI::boss_sartharion_dragonAI (Creature * pCreature, uint32 bossId) inline
Definition at line 722 of file boss_sartharion.cpp.
                                                                  : BossAI(pCreature, bossId), isCalledBySartharion(false)
     {
     }
Member Function Documentation
ClearInstance()
virtual void boss_sartharion_dragonAI::ClearInstance () inline virtual
Reimplemented in boss_sartharion_vesperon::boss_sartharion_vesperonAI, and boss_sartharion_tenebron::boss_sartharion_tenebronAI.
Definition at line 983 of file boss_sartharion.cpp.
     {
         events.Reset();
         summons.DespawnAll();
         // Remove phase shift
         instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_TWILIGHT_SHIFT);
         RemoveTwilightPortal();
     }
References SummonList::DespawnAll(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, RemoveTwilightPortal(), SPELL_TWILIGHT_SHIFT, and BossAI::summons.
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::ClearInstance(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ClearInstance(), JustDied(), Reset(), and boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies().
DoAction()
void boss_sartharion_dragonAI::DoAction (int32 param) inline final virtual
Reimplemented from UnitAI.
Definition at line 741 of file boss_sartharion.cpp.
     {
         if (param == ACTION_CALL_DRAGON && !isCalledBySartharion)
         {
             isCalledBySartharion = true;
             extraEvents.RescheduleEvent(EVENT_MINIDRAKE_SPEECH, 4000);
         }
     }
References ACTION_CALL_DRAGON, EVENT_MINIDRAKE_SPEECH, extraEvents, isCalledBySartharion, and EventMap::RescheduleEvent().
EnterCombat()
void boss_sartharion_dragonAI::EnterCombat (Unit *) inline final virtual
Reimplemented from BossAI.
Definition at line 811 of file boss_sartharion.cpp.
     {
         me->setActive(true);
         DoZoneInCombat();
         Talk(SAY_TENEBRON_AGGRO);
         if (me->IsFlying())
         {
             me->SetSpeed(MOVE_FLIGHT, 1.0f);
             me->SetCanFly(false);
         }
         if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
         {
             switch (me->GetEntry())
             {
                 case NPC_TENEBRON:
                 {
                     instance->SetBossState(DATA_TENEBRON, IN_PROGRESS);
                     break;
                 }
                 case NPC_SHADRON:
                 {
                     instance->SetBossState(DATA_SHADRON, IN_PROGRESS);
                     break;
                 }
                 case NPC_VESPERON:
                 {
                     instance->SetBossState(DATA_VESPERON, IN_PROGRESS);
                     break;
                 }
             }
         }
         if (isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) == DONE)
         {
             me->SetLootMode(0);
         }
         if (isCalledBySartharion)
         {
             if (Unit* target = SelectTarget(SELECT_TARGET_TOPAGGRO, 1, 500, true))
             {
                 AttackStart(target);
             }
         }
     }
References ScriptedAI::AttackStart(), DATA_SARTHARION, DATA_SHADRON, DATA_TENEBRON, DATA_VESPERON, DONE, CreatureAI::DoZoneInCombat(), InstanceScript::GetBossState(), Object::GetEntry(), IN_PROGRESS, BossAI::instance, isCalledBySartharion, Unit::IsFlying(), ScriptedAI::me, MOVE_FLIGHT, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, SAY_TENEBRON_AGGRO, SELECT_TARGET_TOPAGGRO, UnitAI::SelectTarget(), WorldObject::setActive(), InstanceScript::SetBossState(), Creature::SetCanFly(), Creature::SetLootMode(), Unit::SetSpeed(), and CreatureAI::Talk().
HandleExtraEvent()
virtual void boss_sartharion_dragonAI::HandleExtraEvent (uint32 const) inline virtual
Reimplemented in boss_sartharion_vesperon::boss_sartharion_vesperonAI, boss_sartharion_shadron::boss_sartharion_shadronAI, and boss_sartharion_tenebron::boss_sartharion_tenebronAI.
Definition at line 992 of file boss_sartharion.cpp.
 { }
Referenced by UpdateAI().
JustDied()
void boss_sartharion_dragonAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Reimplemented in boss_sartharion_tenebron::boss_sartharion_tenebronAI.
Definition at line 859 of file boss_sartharion.cpp.
     {
         //_JustDied();
         events.Reset();
         // Despawn minions only if not called by Sartharion
         if (!isCalledBySartharion)
         {
             summons.DespawnAll();
         }
         switch (me->GetEntry())
         {
             case NPC_TENEBRON:
             {
                 Talk(SAY_TENEBRON_DEATH);
                 if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
                 {
                     instance->SetBossState(DATA_SHADRON, DONE);
                 }
                 break;
             }
             case NPC_SHADRON:
             {
                 Talk(SAY_SHADRON_DEATH);
                 if (isCalledBySartharion)
                 {
                     if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
                     {
                         sartharion->RemoveAura(SPELL_GIFT_OF_TWILIGHT_FIRE);
                     }
                 }
                 if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
                 {
                     instance->SetBossState(DATA_SHADRON, DONE);
                 }
                 break;
             }
             case NPC_VESPERON:
             {
                 Talk(SAY_VESPERON_DEATH);
                 instance->DoAction(ACTION_CLEAR_PORTAL);
                 if (!isCalledBySartharion || instance->GetBossState(DATA_SARTHARION) != IN_PROGRESS)
                 {
                     instance->SetBossState(DATA_VESPERON, DONE);
                 }
                 break;
             }
         }
         if (!isCalledBySartharion)
         {
             ClearInstance();
         }
         else
         {
             if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
             {
                 sartharion->AI()->DoAction(ACTION_DRAKE_DIED);
             }
         }
     }
References ACTION_CLEAR_PORTAL, ACTION_DRAKE_DIED, ClearInstance(), DATA_SARTHARION, DATA_SHADRON, DATA_VESPERON, SummonList::DespawnAll(), InstanceScript::DoAction(), DONE, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), IN_PROGRESS, BossAI::instance, isCalledBySartharion, ScriptedAI::me, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, SAY_SHADRON_DEATH, SAY_TENEBRON_DEATH, SAY_VESPERON_DEATH, InstanceScript::SetBossState(), SPELL_GIFT_OF_TWILIGHT_FIRE, BossAI::summons, and CreatureAI::Talk().
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustDied().
JustSummoned()
void boss_sartharion_dragonAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Reimplemented in boss_sartharion_tenebron::boss_sartharion_tenebronAI.
Definition at line 797 of file boss_sartharion.cpp.
     {
         // Transfer summons to Sartharion
         if (isCalledBySartharion && instance->GetBossState(DATA_SARTHARION) == IN_PROGRESS)
         {
             if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
             {
                 sartharion->AI()->JustSummoned(summon);
             }
         }
         BossAI::JustSummoned(summon);
     }
References DATA_SARTHARION, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), IN_PROGRESS, BossAI::instance, isCalledBySartharion, BossAI::JustSummoned(), and ScriptedAI::me.
KilledUnit()
void boss_sartharion_dragonAI::KilledUnit (Unit * victim) inline final virtual
Reimplemented from ScriptedAI.
Definition at line 923 of file boss_sartharion.cpp.
     {
         if (victim->GetTypeId() != TYPEID_PLAYER || urand(0, 2))
         {
             return;
         }
         switch (me->GetEntry())
         {
             case NPC_TENEBRON:
             {
                 Talk(SAY_TENEBRON_SLAY);
                 break;
             }
             case NPC_SHADRON:
             {
                 Talk(SAY_SHADRON_SLAY);
                 break;
             }
             case NPC_VESPERON:
             {
                 Talk(SAY_VESPERON_SLAY);
                 break;
             }
         }
     }
References Object::GetEntry(), ScriptedAI::me, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, SAY_SHADRON_SLAY, SAY_TENEBRON_SLAY, SAY_VESPERON_SLAY, CreatureAI::Talk(), TYPEID_PLAYER, and urand().
MoveInLineOfSight()
void boss_sartharion_dragonAI::MoveInLineOfSight (Unit * who) inline final virtual
Reimplemented from CreatureAI.
Definition at line 750 of file boss_sartharion.cpp.
     {
         if (isCalledBySartharion)
             return;
         ScriptedAI::MoveInLineOfSight(who);
     }
References isCalledBySartharion, and CreatureAI::MoveInLineOfSight().
MovementInform()
void boss_sartharion_dragonAI::MovementInform (uint32 type, uint32 pointId) inline final virtual
Reimplemented from ScriptedAI.
Definition at line 758 of file boss_sartharion.cpp.
     {
         if (type != WAYPOINT_MOTION_TYPE)
         {
             return;
         }
         switch (me->GetEntry())
         {
             case NPC_TENEBRON:
             {
                 if (pointId != POINT_FINAL_TENEBRON)
                 {
                     return;
                 }
                 break;
             }
             case NPC_SHADRON:
             {
                 if (pointId != POINT_FINAL_SHADRON)
                 {
                     return;
                 }
                 break;
             }
             case NPC_VESPERON:
             {
                 if (pointId != POINT_FINAL_VESPERON)
                 {
                     return;
                 }
                 break;
             }
         }
         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
         me->SetInCombatWithZone();
     }
References Object::GetEntry(), ScriptedAI::me, NPC_SHADRON, NPC_TENEBRON, NPC_VESPERON, POINT_FINAL_SHADRON, POINT_FINAL_TENEBRON, POINT_FINAL_VESPERON, Object::RemoveFlag(), Creature::SetInCombatWithZone(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and WAYPOINT_MOTION_TYPE.
RemoveTwilightPortal()
void boss_sartharion_dragonAI::RemoveTwilightPortal () inline protected
Definition at line 994 of file boss_sartharion.cpp.
     {
         if (portalGUID)
         {
             if (GameObject* gobj = me->GetMap()->GetGameObject(portalGUID))
             {
                 gobj->Delete();
             }
             portalGUID.Clear();
         }
     }
References ObjectGuid::Clear(), Map::GetGameObject(), WorldObject::GetMap(), ScriptedAI::me, and portalGUID.
Referenced by ClearInstance(), and boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent().
Reset()
void boss_sartharion_dragonAI::Reset () inline override virtual
Reimplemented from BossAI.
Reimplemented in boss_sartharion_vesperon::boss_sartharion_vesperonAI, boss_sartharion_shadron::boss_sartharion_shadronAI, and boss_sartharion_tenebron::boss_sartharion_tenebronAI.
Definition at line 726 of file boss_sartharion.cpp.
     {
         _Reset();
         events.Reset();
         ClearInstance();
         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
         me->SetSpeed(MOVE_FLIGHT, 1.0f);
         me->SetCanFly(false);
         me->ResetLootMode();
         portalGUID.Clear();
         isCalledBySartharion = false;
         instance->DoAction(ACTION_CLEAR_PORTAL);
     }
References BossAI::_Reset(), ACTION_CLEAR_PORTAL, ObjectGuid::Clear(), ClearInstance(), InstanceScript::DoAction(), BossAI::instance, isCalledBySartharion, ScriptedAI::me, MOVE_FLIGHT, portalGUID, Object::RemoveFlag(), Creature::ResetLootMode(), Creature::SetCanFly(), Unit::SetSpeed(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::Reset(), boss_sartharion_shadron::boss_sartharion_shadronAI::Reset(), and boss_sartharion_vesperon::boss_sartharion_vesperonAI::Reset().
UpdateAI()
void boss_sartharion_dragonAI::UpdateAI (uint32 diff) inline final virtual
Reimplemented from BossAI.
Definition at line 950 of file boss_sartharion.cpp.
     {
         extraEvents.Update(diff);
         while (uint32 const eventId = extraEvents.ExecuteEvent())
         {
             HandleExtraEvent(eventId);
         }
         if (!UpdateVictim())
         {
             return;
         }
         events.Update(diff);
         if (me->HasUnitState(UNIT_STATE_CASTING))
         {
             return;
         }
         while (uint32 const eventId = events.ExecuteEvent())
         {
             ExecuteEvent(eventId);
             if (me->HasUnitState(UNIT_STATE_CASTING))
             {
                 return;
             }
         }
         DoMeleeAttackIfReady();
     }
References diff(), UnitAI::DoMeleeAttackIfReady(), EventMap::ExecuteEvent(), BossAI::ExecuteEvent(), extraEvents, HandleExtraEvent(), Unit::HasUnitState(), ScriptedAI::me, UNIT_STATE_CASTING, EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
extraEvents
EventMap boss_sartharion_dragonAI::extraEvents protected
Definition at line 1007 of file boss_sartharion.cpp.
Referenced by DoAction(), and UpdateAI().
isCalledBySartharion
bool boss_sartharion_dragonAI::isCalledBySartharion protected
Definition at line 1009 of file boss_sartharion.cpp.
Referenced by DoAction(), EnterCombat(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), JustDied(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustDied(), JustSummoned(), MoveInLineOfSight(), Reset(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::Reset(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), and boss_sartharion_vesperon::boss_sartharion_vesperonAI::SummonedCreatureDies().
portalGUID
ObjectGuid boss_sartharion_dragonAI::portalGUID protected
Definition at line 1008 of file boss_sartharion.cpp.
Referenced by boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), RemoveTwilightPortal(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp