Azerotcore-wotlk: npc_firework::npc_fireworkAI Struct Reference
npc_firework::npc_fireworkAI Struct Reference
Public Member Functions
npc_fireworkAI (Creature *creature)
bool isCluster ()
GameObject * FindNearestLauncher ()
uint32 GetFireworkSpell (uint32 entry)
uint32 GetFireworkGameObjectId ()
void Reset () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 2085 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_fireworkAI()
npc_firework::npc_fireworkAI::npc_fireworkAI (Creature * creature) inline
Definition at line 2087 of file npcs_special.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
FindNearestLauncher()
GameObject* npc_firework::npc_fireworkAI::FindNearestLauncher () inline
Definition at line 2124 of file npcs_special.cpp.
         {
             GameObject* launcher = nullptr;
             if (isCluster())
             {
                 GameObject* launcher1 = GetClosestGameObjectWithEntry(me, GO_CLUSTER_LAUNCHER_1, 0.5f);
                 GameObject* launcher2 = GetClosestGameObjectWithEntry(me, GO_CLUSTER_LAUNCHER_2, 0.5f);
                 GameObject* launcher3 = GetClosestGameObjectWithEntry(me, GO_CLUSTER_LAUNCHER_3, 0.5f);
                 GameObject* launcher4 = GetClosestGameObjectWithEntry(me, GO_CLUSTER_LAUNCHER_4, 0.5f);
                 if (launcher1)
                     launcher = launcher1;
                 else if (launcher2)
                     launcher = launcher2;
                 else if (launcher3)
                     launcher = launcher3;
                 else if (launcher4)
                     launcher = launcher4;
             }
             else
             {
                 GameObject* launcher1 = GetClosestGameObjectWithEntry(me, GO_FIREWORK_LAUNCHER_1, 0.5f);
                 GameObject* launcher2 = GetClosestGameObjectWithEntry(me, GO_FIREWORK_LAUNCHER_2, 0.5f);
                 GameObject* launcher3 = GetClosestGameObjectWithEntry(me, GO_FIREWORK_LAUNCHER_3, 0.5f);
                 if (launcher1)
                     launcher = launcher1;
                 else if (launcher2)
                     launcher = launcher2;
                 else if (launcher3)
                     launcher = launcher3;
             }
             return launcher;
         }
References GetClosestGameObjectWithEntry(), GO_CLUSTER_LAUNCHER_1, GO_CLUSTER_LAUNCHER_2, GO_CLUSTER_LAUNCHER_3, GO_CLUSTER_LAUNCHER_4, GO_FIREWORK_LAUNCHER_1, GO_FIREWORK_LAUNCHER_2, and GO_FIREWORK_LAUNCHER_3.
GetFireworkGameObjectId()
uint32 npc_firework::npc_fireworkAI::GetFireworkGameObjectId () inline
Definition at line 2194 of file npcs_special.cpp.
         {
             uint32 spellId = 0;
             switch (me->GetEntry())
             {
                 case NPC_CLUSTER_BLUE:
                     spellId = GetFireworkSpell(NPC_FIREWORK_BLUE);
                     break;
                 case NPC_CLUSTER_GREEN:
                     spellId = GetFireworkSpell(NPC_FIREWORK_GREEN);
                     break;
                 case NPC_CLUSTER_PURPLE:
                     spellId = GetFireworkSpell(NPC_FIREWORK_PURPLE);
                     break;
                 case NPC_CLUSTER_RED:
                     spellId = GetFireworkSpell(NPC_FIREWORK_RED);
                     break;
                 case NPC_CLUSTER_YELLOW:
                     spellId = GetFireworkSpell(NPC_FIREWORK_YELLOW);
                     break;
                 case NPC_CLUSTER_WHITE:
                     spellId = GetFireworkSpell(NPC_FIREWORK_WHITE);
                     break;
                 case NPC_CLUSTER_BIG_BLUE:
                     spellId = GetFireworkSpell(NPC_FIREWORK_BIG_BLUE);
                     break;
                 case NPC_CLUSTER_BIG_GREEN:
                     spellId = GetFireworkSpell(NPC_FIREWORK_BIG_GREEN);
                     break;
                 case NPC_CLUSTER_BIG_PURPLE:
                     spellId = GetFireworkSpell(NPC_FIREWORK_BIG_PURPLE);
                     break;
                 case NPC_CLUSTER_BIG_RED:
                     spellId = GetFireworkSpell(NPC_FIREWORK_BIG_RED);
                     break;
                 case NPC_CLUSTER_BIG_YELLOW:
                     spellId = GetFireworkSpell(NPC_FIREWORK_BIG_YELLOW);
                     break;
                 case NPC_CLUSTER_BIG_WHITE:
                     spellId = GetFireworkSpell(NPC_FIREWORK_BIG_WHITE);
                     break;
                 case NPC_CLUSTER_ELUNE:
                     spellId = GetFireworkSpell(urand(NPC_FIREWORK_BLUE, NPC_FIREWORK_WHITE));
                     break;
             }
             const SpellInfo* spellInfo = sSpellMgr->GetSpellInfo(spellId);
             if (spellInfo && spellInfo->Effects[0].Effect == SPELL_EFFECT_SUMMON_OBJECT_WILD)
                 return spellInfo->Effects[0].MiscValue;
             return 0;
         }
References SpellInfo::Effects, NPC_CLUSTER_BIG_BLUE, NPC_CLUSTER_BIG_GREEN, NPC_CLUSTER_BIG_PURPLE, NPC_CLUSTER_BIG_RED, NPC_CLUSTER_BIG_WHITE, NPC_CLUSTER_BIG_YELLOW, NPC_CLUSTER_BLUE, NPC_CLUSTER_ELUNE, NPC_CLUSTER_GREEN, NPC_CLUSTER_PURPLE, NPC_CLUSTER_RED, NPC_CLUSTER_WHITE, NPC_CLUSTER_YELLOW, NPC_FIREWORK_BIG_BLUE, NPC_FIREWORK_BIG_GREEN, NPC_FIREWORK_BIG_PURPLE, NPC_FIREWORK_BIG_RED, NPC_FIREWORK_BIG_WHITE, NPC_FIREWORK_BIG_YELLOW, NPC_FIREWORK_BLUE, NPC_FIREWORK_GREEN, NPC_FIREWORK_PURPLE, NPC_FIREWORK_RED, NPC_FIREWORK_WHITE, NPC_FIREWORK_YELLOW, SPELL_EFFECT_SUMMON_OBJECT_WILD, sSpellMgr, and urand().
GetFireworkSpell()
uint32 npc_firework::npc_fireworkAI::GetFireworkSpell (uint32 entry) inline
Definition at line 2161 of file npcs_special.cpp.
         {
             switch (entry)
             {
                 case NPC_FIREWORK_BLUE:
                     return SPELL_ROCKET_BLUE;
                 case NPC_FIREWORK_GREEN:
                     return SPELL_ROCKET_GREEN;
                 case NPC_FIREWORK_PURPLE:
                     return SPELL_ROCKET_PURPLE;
                 case NPC_FIREWORK_RED:
                     return SPELL_ROCKET_RED;
                 case NPC_FIREWORK_YELLOW:
                     return SPELL_ROCKET_YELLOW;
                 case NPC_FIREWORK_WHITE:
                     return SPELL_ROCKET_WHITE;
                 case NPC_FIREWORK_BIG_BLUE:
                     return SPELL_ROCKET_BIG_BLUE;
                 case NPC_FIREWORK_BIG_GREEN:
                     return SPELL_ROCKET_BIG_GREEN;
                 case NPC_FIREWORK_BIG_PURPLE:
                     return SPELL_ROCKET_BIG_PURPLE;
                 case NPC_FIREWORK_BIG_RED:
                     return SPELL_ROCKET_BIG_RED;
                 case NPC_FIREWORK_BIG_YELLOW:
                     return SPELL_ROCKET_BIG_YELLOW;
                 case NPC_FIREWORK_BIG_WHITE:
                     return SPELL_ROCKET_BIG_WHITE;
                 default:
                     return 0;
             }
         }
References NPC_FIREWORK_BIG_BLUE, NPC_FIREWORK_BIG_GREEN, NPC_FIREWORK_BIG_PURPLE, NPC_FIREWORK_BIG_RED, NPC_FIREWORK_BIG_WHITE, NPC_FIREWORK_BIG_YELLOW, NPC_FIREWORK_BLUE, NPC_FIREWORK_GREEN, NPC_FIREWORK_PURPLE, NPC_FIREWORK_RED, NPC_FIREWORK_WHITE, NPC_FIREWORK_YELLOW, SPELL_ROCKET_BIG_BLUE, SPELL_ROCKET_BIG_GREEN, SPELL_ROCKET_BIG_PURPLE, SPELL_ROCKET_BIG_RED, SPELL_ROCKET_BIG_WHITE, SPELL_ROCKET_BIG_YELLOW, SPELL_ROCKET_BLUE, SPELL_ROCKET_GREEN, SPELL_ROCKET_PURPLE, SPELL_ROCKET_RED, SPELL_ROCKET_WHITE, and SPELL_ROCKET_YELLOW.
isCluster()
bool npc_firework::npc_fireworkAI::isCluster () inline
Definition at line 2089 of file npcs_special.cpp.
         {
             switch (me->GetEntry())
             {
                 case NPC_FIREWORK_BLUE:
                 case NPC_FIREWORK_GREEN:
                 case NPC_FIREWORK_PURPLE:
                 case NPC_FIREWORK_RED:
                 case NPC_FIREWORK_YELLOW:
                 case NPC_FIREWORK_WHITE:
                 case NPC_FIREWORK_BIG_BLUE:
                 case NPC_FIREWORK_BIG_GREEN:
                 case NPC_FIREWORK_BIG_PURPLE:
                 case NPC_FIREWORK_BIG_RED:
                 case NPC_FIREWORK_BIG_YELLOW:
                 case NPC_FIREWORK_BIG_WHITE:
                     return false;
                 case NPC_CLUSTER_BLUE:
                 case NPC_CLUSTER_GREEN:
                 case NPC_CLUSTER_PURPLE:
                 case NPC_CLUSTER_RED:
                 case NPC_CLUSTER_YELLOW:
                 case NPC_CLUSTER_WHITE:
                 case NPC_CLUSTER_BIG_BLUE:
                 case NPC_CLUSTER_BIG_GREEN:
                 case NPC_CLUSTER_BIG_PURPLE:
                 case NPC_CLUSTER_BIG_RED:
                 case NPC_CLUSTER_BIG_YELLOW:
                 case NPC_CLUSTER_BIG_WHITE:
                 case NPC_CLUSTER_ELUNE:
                 default:
                     return true;
             }
         }
References NPC_CLUSTER_BIG_BLUE, NPC_CLUSTER_BIG_GREEN, NPC_CLUSTER_BIG_PURPLE, NPC_CLUSTER_BIG_RED, NPC_CLUSTER_BIG_WHITE, NPC_CLUSTER_BIG_YELLOW, NPC_CLUSTER_BLUE, NPC_CLUSTER_ELUNE, NPC_CLUSTER_GREEN, NPC_CLUSTER_PURPLE, NPC_CLUSTER_RED, NPC_CLUSTER_WHITE, NPC_CLUSTER_YELLOW, NPC_FIREWORK_BIG_BLUE, NPC_FIREWORK_BIG_GREEN, NPC_FIREWORK_BIG_PURPLE, NPC_FIREWORK_BIG_RED, NPC_FIREWORK_BIG_WHITE, NPC_FIREWORK_BIG_YELLOW, NPC_FIREWORK_BLUE, NPC_FIREWORK_GREEN, NPC_FIREWORK_PURPLE, NPC_FIREWORK_RED, NPC_FIREWORK_WHITE, and NPC_FIREWORK_YELLOW.
Reset()
void npc_firework::npc_fireworkAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2249 of file npcs_special.cpp.
         {
             if (GameObject* launcher = FindNearestLauncher())
             {
                 launcher->SendCustomAnim(ANIM_GO_LAUNCH_FIREWORK);
                 me->SetOrientation(launcher->GetOrientation() + M_PI / 2);
             }
             else
                 return;
             if (isCluster())
             {
                 // Check if we are near Elune'ara lake south, if so try to summon Omen or a minion
                 if (me->GetZoneId() == ZONE_MOONGLADE)
                 {
                     if (!me->FindNearestCreature(NPC_OMEN, 100.0f, false) && me->GetDistance2d(omenSummonPos.GetPositionX(), omenSummonPos.GetPositionY()) <= 100.0f)
                     {
                         switch (urand(0, 9))
{
                             case 0:
                             case 1:
                             case 2:
                             case 3:
                                 if (Creature* minion = me->SummonCreature(NPC_MINION_OF_OMEN, me->GetPositionX() + frand(-5.0f, 5.0f), me->GetPositionY() + frand(-5.0f, 5.0f), me->GetPositionZ(), 0.0f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
                                     minion->AI()->AttackStart(me->SelectNearestPlayer(20.0f));
                                 break;
                             case 9:
                                 me->SummonCreature(NPC_OMEN, omenSummonPos);
                                 break;
                         }
                     }
                 }
                 if (me->GetEntry() == NPC_CLUSTER_ELUNE)
                     DoCast(SPELL_LUNAR_FORTUNE);
                 float displacement = 0.7f;
                 for (uint8 i = 0; i < 4; i++)
                     me->SummonGameObject(GetFireworkGameObjectId(), me->GetPositionX() + (i % 2 == 0 ? displacement : -displacement), me->GetPositionY() + (i > 1 ? displacement : -displacement), me->GetPositionZ() + 4.0f, me->GetOrientation(), 0.0f, 0.0f, 0.0f, 0.0f, 1);
             }
             else
                 //me->CastSpell(me, GetFireworkSpell(me->GetEntry()), true);
                 me->CastSpell(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), GetFireworkSpell(me->GetEntry()), true);
         }
References ANIM_GO_LAUNCH_FIREWORK, G3D::frand(), Position::GetPositionX(), Position::GetPositionY(), M_PI, NPC_CLUSTER_ELUNE, NPC_MINION_OF_OMEN, NPC_OMEN, omenSummonPos, SPELL_LUNAR_FORTUNE, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, urand(), and ZONE_MOONGLADE.
The documentation for this struct was generated from the following file:
src/server/scripts/World/npcs_special.cpp