name: Doxygen Action
on:
  push:
    branches:
      - 'master'
jobs:
  steps:
    uses: mattnotmitt/doxygen-action@v1.3.1
    with:
      working-directory: 'src/'
      doxyfile-path: '../doc/Doxygen'
