name: Doxygen Action
on:
  push:
    branches:
      - 'master'

jobs:
  create-doc:
    name: create-doc
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          doxyfile-path: '../doc/Doxygen'
