Azerotcore-wotlk: go_warmaul_prison Class Reference
go_warmaul_prison Class Reference
Public Member Functions
go_warmaul_prison ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 583 of file zone_nagrand.cpp.
Constructor & Destructor Documentation
go_warmaul_prison()
go_warmaul_prison::go_warmaul_prison () inline
Definition at line 586 of file zone_nagrand.cpp.
 : GameObjectScript("go_warmaul_prison") { }
Member Function Documentation
OnGossipHello()
bool go_warmaul_prison::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 588 of file zone_nagrand.cpp.
     {
         go->UseDoorOrButton();
         if (player->GetQuestStatus(QUEST_FINDING_THE_SURVIVORS) != QUEST_STATUS_INCOMPLETE)
             return false;
         if (Creature* prisoner = go->FindNearestCreature(NPC_MAGHAR_PRISONER, 5.0f))
         {
             player->KilledMonsterCredit(NPC_MAGHAR_PRISONER);
             prisoner->AI()->Talk(SAY_FREE, player);
             prisoner->DespawnOrUnsummon(6000);
         }
         return true;
     }
References WorldObject::FindNearestCreature(), Player::GetQuestStatus(), Player::KilledMonsterCredit(), NPC_MAGHAR_PRISONER, QUEST_FINDING_THE_SURVIVORS, QUEST_STATUS_INCOMPLETE, SAY_FREE, and GameObject::UseDoorOrButton().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_nagrand.cpp