Azerotcore-wotlk: G3D::_internal::Welder Class Reference
G3D::_internal::Welder Class Reference
Public Types
enum { GRID_RES = 32 }
typedef Array< int > List
Public Member Functions
Welder (const Array< Vector3 > &_oldVertexArray, Array< Vector3 > &_newVertexArray, Array< int > &_toNew, Array< int > &_toOld, float _radius)
void toGridCoords (Vector3 v, int &x, int &y, int &z) const
int getIndex (const Vector3 &vertex)
void weld ()
Public Attributes
List grid [GRID_RES][GRID_RES][GRID_RES]
const Array< Vector3 > & oldVertexArray
Array< Vector3 > & newVertexArray
Array< int > & toNew
Array< int > & toOld
const float radius
Vector3 offset
Vector3 scale
Private Member Functions
Welder & operator= (const Welder &w)
Detailed Description
Definition at line 23 of file MeshAlgWeld.cpp.
Member Typedef Documentation
List
typedef Array<int> G3D::_internal::Welder::List
Indices of newVertexArray elements in or near a grid cell.
Definition at line 31 of file MeshAlgWeld.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
GRID_RES
Definition at line 33 of file MeshAlgWeld.cpp.
 {GRID_RES = 32};
Constructor & Destructor Documentation
Welder()
G3D::_internal::Welder::Welder (const Array< Vector3 > & _oldVertexArray, Array< Vector3 > & _newVertexArray, Array< int > & _toNew, Array< int > & _toOld, float _radius)
Definition at line 80 of file MeshAlgWeld.cpp.
                                    :
     oldVertexArray(_oldVertexArray),
     newVertexArray(_newVertexArray),
     toNew(_toNew),
     toOld(_toOld),
     radius(_radius) {
     // Compute a scale factor that moves the range
     // of all ordinates to [0, 1]
     Vector3 minBound = Vector3::inf();
     Vector3 maxBound = -minBound;
     for (int i = 0; i < oldVertexArray.size(); ++i) {
         minBound = minBound.min(oldVertexArray[i]);
         maxBound = maxBound.max(oldVertexArray[i]);
     }
     offset = minBound;
     scale  = maxBound - minBound;
     for (int i = 0; i < 3; ++i) {
         // The model might have zero extent along some axis
         if (fuzzyEq(scale[i], 0.0f)) {
             scale[i] = 1.0;
         } else {
             scale[i] = 1.0f / scale[i];
         }
     }
 }
References G3D::fuzzyEq(), G3D::Vector3::inf(), G3D::Vector3::max(), G3D::Vector3::min(), offset, oldVertexArray, and scale.
Member Function Documentation
getIndex()
int G3D::_internal::Welder::getIndex (const Vector3 & vertex)
Gets the index of a vertex, adding it to newVertexArray if necessary.
Definition at line 123 of file MeshAlgWeld.cpp.
{
     int closestIndex = -1;
     double distanceSquared = inf();
     int ix, iy, iz;
     toGridCoords(vertex, ix, iy, iz);
     // Check against all vertices within radius of this grid cube
     const List& list = grid[ix][iy][iz];
     for (int i = 0; i < list.size(); ++i) {
         double d = (newVertexArray[list[i]] - vertex).squaredMagnitude();
         if (d < distanceSquared) {
             distanceSquared = d;
             closestIndex = list[i];
         }
     }
     if (distanceSquared <= radius * radius) {
         return closestIndex;
     } else {
         // This is a new vertex
         int newIndex = newVertexArray.size();
         newVertexArray.append(vertex);
         // Create a new vertex and store its index in the
         // neighboring grid cells (usually, only 1 neighbor)
         Set<List*> neighbors;
         for (float dx = -1; dx <= +1; ++dx) {
             for (float dy = -1; dy <= +1; ++dy) {
                 for (float dz = -1; dz <= +1; ++dz) {
                     int ix, iy, iz;
                     toGridCoords(vertex + Vector3(dx, dy, dz) * radius, ix, iy, iz);
                     neighbors.insert(&(grid[ix][iy][iz]));
                 }
             }
         }
         Set<List*>::Iterator neighbor(neighbors.begin());
         Set<List*>::Iterator none(neighbors.end());
         while (neighbor != none) {
             (*neighbor)->append(newIndex);
             ++neighbor;
         }
         return newIndex;
     }
 }
References G3D::Set< T, HashFunc, EqualsFunc >::begin(), mpq::d, G3D::Set< T, HashFunc, EqualsFunc >::end(), grid, G3D::inf(), G3D::Set< T, HashFunc, EqualsFunc >::insert(), list(), newVertexArray, radius, and toGridCoords().
Referenced by weld().
operator=()
Welder& G3D::_internal::Welder::operator= (const Welder & w) private
toGridCoords()
void G3D::_internal::Welder::toGridCoords (Vector3 v, int & x, int & y, int & z) const
Computes the grid index from an ordinate.
Definition at line 115 of file MeshAlgWeld.cpp.
{
     v = (v - offset) * scale;
     x = iClamp(iFloor(v.x * GRID_RES), 0, GRID_RES - 1);
     y = iClamp(iFloor(v.y * GRID_RES), 0, GRID_RES - 1);
     z = iClamp(iFloor(v.z * GRID_RES), 0, GRID_RES - 1);
 }
References GRID_RES, G3D::iClamp(), G3D::iFloor(), offset, scale, G3D::x, G3D::Vector3::x, G3D::y, G3D::Vector3::y, G3D::Vector3::z, and G3D::z.
Referenced by getIndex().
weld()
void G3D::_internal::Welder::weld ()
Definition at line 181 of file MeshAlgWeld.cpp.
                   {
     newVertexArray.resize(0);
     // Prime the vertex positions
     for (int i = 0; i < oldVertexArray.size(); ++i) {
         getIndex(oldVertexArray[i]);
     }
     // Now create the official remapping by snapping to
     // nearby vertices.
     toNew.resize(oldVertexArray.size());
     toOld.resize(newVertexArray.size());
     for (int oi = 0; oi < oldVertexArray.size(); ++oi) {
         toNew[oi] = getIndex(oldVertexArray[oi]);
         toOld[toNew[oi]] = oi;
     }
 }
References getIndex(), newVertexArray, oldVertexArray, G3D::Array< T, MIN_ELEMENTS >::resize(), toNew, and toOld.
Member Data Documentation
grid
List G3D::_internal::Welder::grid[GRID_RES][GRID_RES][GRID_RES]
Definition at line 35 of file MeshAlgWeld.cpp.
Referenced by getIndex().
newVertexArray
Array<Vector3>& G3D::_internal::Welder::newVertexArray
Definition at line 38 of file MeshAlgWeld.cpp.
Referenced by getIndex(), and weld().
offset
Vector3 G3D::_internal::Welder::offset
(oldVertexArray[i] - offset) * scale is on the range [0, 1]
Definition at line 46 of file MeshAlgWeld.cpp.
Referenced by toGridCoords(), and Welder().
oldVertexArray
const Array<Vector3>& G3D::_internal::Welder::oldVertexArray
Definition at line 37 of file MeshAlgWeld.cpp.
Referenced by weld(), and Welder().
radius
const float G3D::_internal::Welder::radius
Must be less than one grid cell, not checked
Definition at line 43 of file MeshAlgWeld.cpp.
Referenced by getIndex().
scale
Vector3 G3D::_internal::Welder::scale
Definition at line 47 of file MeshAlgWeld.cpp.
Referenced by toGridCoords(), and Welder().
toNew
Array<int>& G3D::_internal::Welder::toNew
Definition at line 39 of file MeshAlgWeld.cpp.
Referenced by weld().
toOld
Array<int>& G3D::_internal::Welder::toOld
Definition at line 40 of file MeshAlgWeld.cpp.
Referenced by weld().
The documentation for this class was generated from the following file:
deps/g3dlite/source/MeshAlgWeld.cpp