Azerotcore-wotlk: boss_hydross_the_unstable::boss_hydross_the_unstableAI Struct Reference
boss_hydross_the_unstable::boss_hydross_the_unstableAI Struct Reference
Public Member Functions
boss_hydross_the_unstableAI (Creature *creature)
void Reset () override
void JustReachedHome () override
void SetForm (bool corrupt, bool initial)
void EnterCombat (Unit *who) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void JustDied (Unit *killer) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 102 of file boss_hydross_the_unstable.cpp.
Constructor & Destructor Documentation
boss_hydross_the_unstableAI()
boss_hydross_the_unstable::boss_hydross_the_unstableAI::boss_hydross_the_unstableAI (Creature * creature) inline
Definition at line 104 of file boss_hydross_the_unstable.cpp.
                                                         : BossAI(creature, DATA_HYDROSS_THE_UNSTABLE)
         {
         }
Member Function Documentation
EnterCombat()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 171 of file boss_hydross_the_unstable.cpp.
         {
             BossAI::EnterCombat(who);
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_SPELL_ENRAGE, 600000);
             events.ScheduleEvent(EVENT_CHECK_AURA, 1000);
             SetForm(false, true);
         }
References BossAI::EnterCombat(), EVENT_CHECK_AURA, EVENT_SPELL_ENRAGE, SAY_AGGRO, SetForm(), and CreatureAI::Talk().
JustDied()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 207 of file boss_hydross_the_unstable.cpp.
         {
             Talk(me->HasAura(SPELL_CORRUPTION) ? SAY_CORRUPT_DEATH : SAY_CLEAN_DEATH);
             BossAI::JustDied(killer);
         }
References Unit::HasAura(), BossAI::JustDied(), ScriptedAI::me, SAY_CLEAN_DEATH, SAY_CORRUPT_DEATH, SPELL_CORRUPTION, and CreatureAI::Talk().
JustReachedHome()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 113 of file boss_hydross_the_unstable.cpp.
         {
             BossAI::JustReachedHome();
             if (!me->HasAura(SPELL_BLUE_BEAM))
                 me->RemoveAurasDueToSpell(SPELL_CLEANSING_FIELD_AURA);
         }
References Unit::HasAura(), BossAI::JustReachedHome(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SPELL_BLUE_BEAM, and SPELL_CLEANSING_FIELD_AURA.
JustSummoned()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 190 of file boss_hydross_the_unstable.cpp.
         {
             summons.Summon(summon);
             summon->CastSpell(summon, SPELL_ELEMENTAL_SPAWNIN, true);
             summon->SetInCombatWithZone();
             if (summon->GetEntry() == NPC_PURE_SPAWN_OF_HYDROSS)
                 summon->ApplySpellImmune(0, IMMUNITY_SCHOOL, SPELL_SCHOOL_MASK_FROST, true);
             else
                 summon->ApplySpellImmune(0, IMMUNITY_SCHOOL, SPELL_SCHOOL_MASK_NATURE, true);
         }
References Unit::ApplySpellImmune(), Unit::CastSpell(), Object::GetEntry(), IMMUNITY_SCHOOL, NPC_PURE_SPAWN_OF_HYDROSS, Creature::SetInCombatWithZone(), SPELL_ELEMENTAL_SPAWNIN, SPELL_SCHOOL_MASK_FROST, SPELL_SCHOOL_MASK_NATURE, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 181 of file boss_hydross_the_unstable.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(me->HasAura(SPELL_CORRUPTION) ? SAY_CORRUPT_SLAY : SAY_CLEAN_SLAY);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, Unit::HasAura(), ScriptedAI::me, SAY_CLEAN_SLAY, SAY_CORRUPT_SLAY, SPELL_CORRUPTION, and CreatureAI::Talk().
Reset()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 108 of file boss_hydross_the_unstable.cpp.
         {
             BossAI::Reset();
         }
References BossAI::Reset().
SetForm()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::SetForm (bool corrupt, bool initial) inline
Definition at line 120 of file boss_hydross_the_unstable.cpp.
         {
             events.CancelEventGroup(GROUP_ABILITIES);
             DoResetThreat();
             if (corrupt)
             {
                 me->SetMeleeDamageSchool(SPELL_SCHOOL_NATURE);
                 me->ApplySpellImmune(0, IMMUNITY_SCHOOL, SPELL_SCHOOL_MASK_FROST, false);
                 me->ApplySpellImmune(0, IMMUNITY_SCHOOL, SPELL_SCHOOL_MASK_NATURE, true);
                 me->CastSpell(me, SPELL_CORRUPTION, true);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_CORRUPTION1, 0, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_CORRUPTION2, 15000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_CORRUPTION3, 30000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_CORRUPTION4, 45000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_CORRUPTION5, 60000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_CORRUPTION6, 75000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_VILE_SLUDGE, 7000, GROUP_ABILITIES);
             }
             else
             {
                 me->SetMeleeDamageSchool(SPELL_SCHOOL_FROST);
                 me->ApplySpellImmune(0, IMMUNITY_SCHOOL, SPELL_SCHOOL_MASK_FROST, true);
                 me->ApplySpellImmune(0, IMMUNITY_SCHOOL, SPELL_SCHOOL_MASK_NATURE, false);
                 me->RemoveAurasDueToSpell(SPELL_CORRUPTION);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_HYDROSS1, 0, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_HYDROSS2, 15000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_HYDROSS3, 30000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_HYDROSS4, 45000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_HYDROSS5, 60000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_MARK_OF_HYDROSS6, 75000, GROUP_ABILITIES);
                 events.ScheduleEvent(EVENT_SPELL_WATER_TOMB, 7000, GROUP_ABILITIES);
             }
             if (initial)
                 return;
             if (corrupt)
             {
                 Talk(SAY_SWITCH_TO_CORRUPT);
                 for (uint32 i = SPELL_SUMMON_CORRUPTED1; i <= SPELL_SUMMON_CORRUPTED4; ++i)
                     me->CastSpell(me, i, true);
             }
             else
             {
                 Talk(SAY_SWITCH_TO_CLEAN);
                 for (uint32 i = SPELL_SUMMON_PURIFIED1; i <= SPELL_SUMMON_PURIFIED4; ++i)
                     me->CastSpell(me, i, true);
             }
         }
References Unit::ApplySpellImmune(), Unit::CastSpell(), ScriptedAI::DoResetThreat(), EVENT_SPELL_MARK_OF_CORRUPTION1, EVENT_SPELL_MARK_OF_CORRUPTION2, EVENT_SPELL_MARK_OF_CORRUPTION3, EVENT_SPELL_MARK_OF_CORRUPTION4, EVENT_SPELL_MARK_OF_CORRUPTION5, EVENT_SPELL_MARK_OF_CORRUPTION6, EVENT_SPELL_MARK_OF_HYDROSS1, EVENT_SPELL_MARK_OF_HYDROSS2, EVENT_SPELL_MARK_OF_HYDROSS3, EVENT_SPELL_MARK_OF_HYDROSS4, EVENT_SPELL_MARK_OF_HYDROSS5, EVENT_SPELL_MARK_OF_HYDROSS6, EVENT_SPELL_VILE_SLUDGE, EVENT_SPELL_WATER_TOMB, GROUP_ABILITIES, IMMUNITY_SCHOOL, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SAY_SWITCH_TO_CLEAN, SAY_SWITCH_TO_CORRUPT, Creature::SetMeleeDamageSchool(), SPELL_CORRUPTION, SPELL_SCHOOL_FROST, SPELL_SCHOOL_MASK_FROST, SPELL_SCHOOL_MASK_NATURE, SPELL_SCHOOL_NATURE, SPELL_SUMMON_CORRUPTED1, SPELL_SUMMON_CORRUPTED4, SPELL_SUMMON_PURIFIED1, SPELL_SUMMON_PURIFIED4, and CreatureAI::Talk().
Referenced by EnterCombat(), and UpdateAI().
SummonedCreatureDespawn()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 202 of file boss_hydross_the_unstable.cpp.
         {
             summons.Despawn(summon);
         }
References SummonList::Despawn(), and BossAI::summons.
UpdateAI()
void boss_hydross_the_unstable::boss_hydross_the_unstableAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 213 of file boss_hydross_the_unstable.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_AURA:
                     if (me->HasAura(SPELL_BLUE_BEAM) == me->HasAura(SPELL_CORRUPTION))
                         SetForm(!me->HasAura(SPELL_BLUE_BEAM), false);
                     events.ScheduleEvent(EVENT_CHECK_AURA, 1000);
                     break;
                 case EVENT_SPELL_ENRAGE:
                     me->CastSpell(me, SPELL_ENRAGE, true);
                     break;
                 case EVENT_SPELL_MARK_OF_HYDROSS1:
                     me->CastSpell(me, SPELL_MARK_OF_HYDROSS1, false);
                     break;
                 case EVENT_SPELL_MARK_OF_HYDROSS2:
                     me->CastSpell(me, SPELL_MARK_OF_HYDROSS2, false);
                     break;
                 case EVENT_SPELL_MARK_OF_HYDROSS3:
                     me->CastSpell(me, SPELL_MARK_OF_HYDROSS3, false);
                     break;
                 case EVENT_SPELL_MARK_OF_HYDROSS4:
                     me->CastSpell(me, SPELL_MARK_OF_HYDROSS4, false);
                     break;
                 case EVENT_SPELL_MARK_OF_HYDROSS5:
                     me->CastSpell(me, SPELL_MARK_OF_HYDROSS5, false);
                     break;
                 case EVENT_SPELL_MARK_OF_HYDROSS6:
                     me->CastSpell(me, SPELL_MARK_OF_HYDROSS6, false);
                     events.ScheduleEvent(EVENT_SPELL_MARK_OF_HYDROSS6, 15000, GROUP_ABILITIES);
                     break;
                 case EVENT_SPELL_MARK_OF_CORRUPTION1:
                     me->CastSpell(me, SPELL_MARK_OF_CORRUPTION1, false);
                     break;
                 case EVENT_SPELL_MARK_OF_CORRUPTION2:
                     me->CastSpell(me, SPELL_MARK_OF_CORRUPTION2, false);
                     break;
                 case EVENT_SPELL_MARK_OF_CORRUPTION3:
                     me->CastSpell(me, SPELL_MARK_OF_CORRUPTION3, false);
                     break;
                 case EVENT_SPELL_MARK_OF_CORRUPTION4:
                     me->CastSpell(me, SPELL_MARK_OF_CORRUPTION4, false);
                     break;
                 case EVENT_SPELL_MARK_OF_CORRUPTION5:
                     me->CastSpell(me, SPELL_MARK_OF_CORRUPTION5, false);
                     break;
                 case EVENT_SPELL_MARK_OF_CORRUPTION6:
                     me->CastSpell(me, SPELL_MARK_OF_CORRUPTION6, false);
                     events.ScheduleEvent(EVENT_SPELL_MARK_OF_CORRUPTION6, 15000, GROUP_ABILITIES);
                     break;
                 case EVENT_SPELL_WATER_TOMB:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 60.0f, true))
                         me->CastSpell(target, SPELL_WATER_TOMB, false);
                     events.ScheduleEvent(EVENT_SPELL_WATER_TOMB, 7000, GROUP_ABILITIES);
                     break;
                 case EVENT_SPELL_VILE_SLUDGE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 60.0f, true))
                         me->CastSpell(target, SPELL_VILE_SLUDGE, false);
                     events.ScheduleEvent(EVENT_SPELL_VILE_SLUDGE, 15000, GROUP_ABILITIES);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_CHECK_AURA, EVENT_SPELL_ENRAGE, EVENT_SPELL_MARK_OF_CORRUPTION1, EVENT_SPELL_MARK_OF_CORRUPTION2, EVENT_SPELL_MARK_OF_CORRUPTION3, EVENT_SPELL_MARK_OF_CORRUPTION4, EVENT_SPELL_MARK_OF_CORRUPTION5, EVENT_SPELL_MARK_OF_CORRUPTION6, EVENT_SPELL_MARK_OF_HYDROSS1, EVENT_SPELL_MARK_OF_HYDROSS2, EVENT_SPELL_MARK_OF_HYDROSS3, EVENT_SPELL_MARK_OF_HYDROSS4, EVENT_SPELL_MARK_OF_HYDROSS5, EVENT_SPELL_MARK_OF_HYDROSS6, EVENT_SPELL_VILE_SLUDGE, EVENT_SPELL_WATER_TOMB, GROUP_ABILITIES, Unit::HasAura(), Unit::HasUnitState(), ScriptedAI::me, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SetForm(), SPELL_BLUE_BEAM, SPELL_CORRUPTION, SPELL_ENRAGE, SPELL_MARK_OF_CORRUPTION1, SPELL_MARK_OF_CORRUPTION2, SPELL_MARK_OF_CORRUPTION3, SPELL_MARK_OF_CORRUPTION4, SPELL_MARK_OF_CORRUPTION5, SPELL_MARK_OF_CORRUPTION6, SPELL_MARK_OF_HYDROSS1, SPELL_MARK_OF_HYDROSS2, SPELL_MARK_OF_HYDROSS3, SPELL_MARK_OF_HYDROSS4, SPELL_MARK_OF_HYDROSS5, SPELL_MARK_OF_HYDROSS6, SPELL_VILE_SLUDGE, SPELL_WATER_TOMB, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_hydross_the_unstable.cpp