Azerotcore-wotlk: deps/zlib/zutil.c File Reference
zutil.c File Reference
#include "zutil.h"
#include "gzguts.h"
Classes
struct internal_state
Functions
const char *ZEXPORT zlibVersion ()
uLong ZEXPORT zlibCompileFlags ()
const char *ZEXPORT zError (int err)
void ZLIB_INTERNAL zmemcpy (Bytef *dest, const Bytef *source, uInt len)
int ZLIB_INTERNAL zmemcmp (Bytef *s1, const Bytef *s2, uInt len) const
void ZLIB_INTERNAL zmemzero (Bytef *dest, uInt len)
voidp malloc OF ((uInt size))
voidp calloc OF ((uInt items, uInt size))
void free OF ((voidpf ptr))
voidpf ZLIB_INTERNAL zcalloc (voidpf opaque, unsigned items, unsigned size)
void ZLIB_INTERNAL zcfree (voidpf opaque, voidpf ptr)
Variables
const char *const z_errmsg [10]
Function Documentation
OF() [1/3]
voidp calloc OF ((uInt items, uInt size))
OF() [2/3]
voidp malloc OF ((uInt size))
OF() [3/3]
void free OF ((voidpf ptr))
zcalloc()
voidpf ZLIB_INTERNAL zcalloc (voidpf opaque, unsigned items, unsigned size)
Definition at line 304 of file zutil.c.
 {
     if (opaque) items += size - size; /* make compiler happy */
     return sizeof(uInt) > 2 ? (voidpf)malloc(items * size) :
                               (voidpf)calloc(items, size);
 }
Referenced by deflateInit2_(), inflateBackInit_(), and inflateInit2_().
zcfree()
void ZLIB_INTERNAL zcfree (voidpf opaque, voidpf ptr)
Definition at line 314 of file zutil.c.
 {
     free(ptr);
     if (opaque) return; /* make compiler happy */
 }
References ptr().
Referenced by deflateInit2_(), inflateBackInit_(), and inflateInit2_().
zError()
const char* ZEXPORT zError (int err)
Definition at line 136 of file zutil.c.
 {
     return ERR_MSG(err);
 }
References ERR_MSG.
Referenced by UpdateData::Compress().
zlibCompileFlags()
uLong ZEXPORT zlibCompileFlags ()
Definition at line 35 of file zutil.c.
 {
     uLong flags;
     flags = 0;
     switch ((int)(sizeof(uInt))) {
     case 2:     break;
     case 4:     flags += 1;     break;
     case 8:     flags += 2;     break;
     default:    flags += 3;
     }
     switch ((int)(sizeof(uLong))) {
     case 2:     break;
     case 4:     flags += 1 << 2;        break;
     case 8:     flags += 2 << 2;        break;
     default:    flags += 3 << 2;
     }
     switch ((int)(sizeof(voidpf))) {
     case 2:     break;
     case 4:     flags += 1 << 4;        break;
     case 8:     flags += 2 << 4;        break;
     default:    flags += 3 << 4;
     }
     switch ((int)(sizeof(z_off_t))) {
     case 2:     break;
     case 4:     flags += 1 << 6;        break;
     case 8:     flags += 2 << 6;        break;
     default:    flags += 3 << 6;
     }
 #ifdef DEBUG
     flags += 1 << 8;
 #endif
 #if defined(ASMV) || defined(ASMINF)
     flags += 1 << 9;
 #endif
 #ifdef ZLIB_WINAPI
     flags += 1 << 10;
 #endif
 #ifdef BUILDFIXED
     flags += 1 << 12;
 #endif
 #ifdef DYNAMIC_CRC_TABLE
     flags += 1 << 13;
 #endif
 #ifdef NO_GZCOMPRESS
     flags += 1L << 16;
 #endif
 #ifdef NO_GZIP
     flags += 1L << 17;
 #endif
 #ifdef PKZIP_BUG_WORKAROUND
     flags += 1L << 20;
 #endif
 #ifdef FASTEST
     flags += 1L << 21;
 #endif
 #if defined(STDC) || defined(Z_HAVE_STDARG_H)
 #  ifdef NO_vsnprintf
     flags += 1L << 25;
 #    ifdef HAS_vsprintf_void
     flags += 1L << 26;
 #    endif
 #  else
 #    ifdef HAS_vsnprintf_void
     flags += 1L << 26;
 #    endif
 #  endif
 #else
     flags += 1L << 24;
 #  ifdef NO_snprintf
     flags += 1L << 25;
 #    ifdef HAS_sprintf_void
     flags += 1L << 26;
 #    endif
 #  else
 #    ifdef HAS_snprintf_void
     flags += 1L << 26;
 #    endif
 #  endif
 #endif
     return flags;
 }
References z_off_t.
Referenced by main().
zlibVersion()
const char* ZEXPORT zlibVersion ()
Definition at line 30 of file zutil.c.
 {
     return ZLIB_VERSION;
 }
References ZLIB_VERSION.
Referenced by main().
zmemcmp()
int ZLIB_INTERNAL zmemcmp (Bytef* s1, const Bytef* s2, uInt len) const
Definition at line 163 of file zutil.c.
 {
     uInt j;
     for (j = 0; j < len; j++) {
         if (s1[j] != s2[j]) return 2*(s1[j] > s2[j])-1;
     }
     return 0;
 }
zmemcpy()
void ZLIB_INTERNAL zmemcpy (Bytef* dest, const Bytef* source, uInt len)
Definition at line 152 of file zutil.c.
 {
     if (len == 0) return;
     do {
         *dest++ = *source++; /* ??? to be unrolled */
     } while (--len != 0);
 }
Referenced by deflateCopy(), fill_window(), flush_pending(), inflate(), inflateBack(), inflateCopy(), read_buf(), and updatewindow().
zmemzero()
void ZLIB_INTERNAL zmemzero (Bytef* dest, uInt len)
Definition at line 176 of file zutil.c.
 {
     if (len == 0) return;
     do {
         *dest++ = 0;  /* ??? to be unrolled */
     } while (--len != 0);
 }
Referenced by fill_window().
Variable Documentation
z_errmsg
const char* const z_errmsg[10]
Initial value:
= {
"need dictionary",
"stream end",
"",
"file error",
"stream error",
"data error",
"insufficient memory",
"buffer error",
"incompatible version",
""}
Definition at line 17 of file zutil.c.