Azerotcore-wotlk: G3D::Any::Source Class Reference
G3D::Any::Source Class Reference
#include <Any.h>
Public Member Functions
Source ()
void set (const TextInput &ti, const Token &t)
Public Attributes
std::string filename
int line
int character
Detailed Description
Where an Any came from in a file. Useful for throwing parsing errors
Definition at line 192 of file Any.h.
Constructor & Destructor Documentation
Source()
G3D::Any::Source::Source () inline
Definition at line 198 of file Any.h.
 : line(0), character(0) {}
Member Function Documentation
set()
void G3D::Any::Source::set (const TextInput & ti, const Token & t) inline
Definition at line 200 of file Any.h.
{
             filename  = ti.filename();
             line      = t.line();
             character = t.character();
         }
References character, G3D::Token::character(), filename, G3D::TextInput::filename(), line, and G3D::Token::line().
Referenced by G3D::Any::deserialize(), and G3D::Any::deserializeBody().
Member Data Documentation
character
int G3D::Any::Source::character
Definition at line 196 of file Any.h.
Referenced by set(), and G3D::Any::verify().
filename
std::string G3D::Any::Source::filename
Definition at line 194 of file Any.h.
Referenced by G3D::Any::deserialize(), set(), G3D::Any::sourceDirectory(), and G3D::Any::verify().
line
int G3D::Any::Source::line
Definition at line 195 of file Any.h.
Referenced by set(), and G3D::Any::verify().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Any.h