Azerotcore-wotlk: deps/mysqllite/libmysql/libmysql.c File Reference
libmysql.c File Reference
#include <my_global.h>
#include <my_sys.h>
#include <my_time.h>
#include <mysys_err.h>
#include <m_string.h>
#include <m_ctype.h>
#include "mysql.h"
#include "mysql_version.h"
#include "mysqld_error.h"
#include "errmsg.h"
#include <violite.h>
#include <sys/stat.h>
#include <signal.h>
#include <time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <my_pthread.h>
#include <sql_common.h>
#include "client_settings.h"
#include <errno.h>
Classes
struct st_default_local_infile
Macros
#define INADDR_NONE -1
#define SOCKET_ERROR -1
#define MAX_LONG_DATA_LENGTH 8192
#define unsigned_field(A) ((A)->flags & UNSIGNED_FLAG)
#define DEFAULT_PREFETCH_ROWS (ulong) 1
#define RESET_SERVER_SIDE 1
#define RESET_LONG_DATA 2
#define RESET_STORE_RESULT 4
#define RESET_CLEAR_ERROR 8
#define MAX_DATE_REP_LENGTH 5
#define MAX_TIME_REP_LENGTH 13
#define MAX_DATETIME_REP_LENGTH 12
#define MAX_DOUBLE_STRING_REP_LENGTH 331
#define IS_TRUNCATED(value, is_unsigned, min, max, umax)
#define BIND_RESULT_DONE 1
#define REPORT_DATA_TRUNCATION 2
Typedefs
typedef struct st_default_local_infile default_local_infile_data
Functions
static void append_wild (char *to, char *end, const char *wild)
sig_handler my_pipe_sig_handler (int sig)
int STDCALL mysql_server_init (int argc __attribute__((unused)), char **argv __attribute__((unused)), char **groups __attribute__((unused)))
void STDCALL mysql_server_end ()
MYSQL_PARAMETERS *STDCALL mysql_get_parameters (void)
my_bool STDCALL mysql_thread_init ()
void STDCALL mysql_thread_end ()
void STDCALL mysql_debug (const char *debug __attribute__((unused)))
sig_handler my_pipe_sig_handler (int sig __attribute__((unused)))
my_bool STDCALL mysql_change_user (MYSQL *mysql, const char *user, const char *passwd, const char *db)
void read_user_name (char *name)
my_bool handle_local_infile (MYSQL *mysql, const char *net_filename)
static int default_local_infile_init (void **ptr, const char *filename, void *userdata __attribute__((unused)))
static int default_local_infile_read (void *ptr, char *buf, uint buf_len)
static void default_local_infile_end (void *ptr)
static int default_local_infile_error (void *ptr, char *error_msg, uint error_msg_len)
void mysql_set_local_infile_handler (MYSQL *mysql, int(*local_infile_init)(void **, const char *, void *), int(*local_infile_read)(void *, char *, uint), void(*local_infile_end)(void *), int(*local_infile_error)(void *, char *, uint), void *userdata)
void mysql_set_local_infile_default (MYSQL *mysql)
int STDCALL mysql_query (MYSQL *mysql, const char *query)
MYSQL_FIELD *STDCALL mysql_fetch_field (MYSQL_RES *result)
void STDCALL mysql_data_seek (MYSQL_RES *result, my_ulonglong row)
MYSQL_ROW_OFFSET STDCALL mysql_row_seek (MYSQL_RES *result, MYSQL_ROW_OFFSET row)
MYSQL_FIELD_OFFSET STDCALL mysql_field_seek (MYSQL_RES *result, MYSQL_FIELD_OFFSET field_offset)
MYSQL_RES *STDCALL mysql_list_dbs (MYSQL *mysql, const char *wild)
MYSQL_RES *STDCALL mysql_list_tables (MYSQL *mysql, const char *wild)
MYSQL_FIELD * cli_list_fields (MYSQL *mysql)
MYSQL_RES *STDCALL mysql_list_fields (MYSQL *mysql, const char *table, const char *wild)
MYSQL_RES *STDCALL mysql_list_processes (MYSQL *mysql)
int STDCALL mysql_shutdown (MYSQL *mysql, enum mysql_enum_shutdown_level shutdown_level)
int STDCALL mysql_refresh (MYSQL *mysql, uint options)
int STDCALL mysql_kill (MYSQL *mysql, ulong pid)
int STDCALL mysql_set_server_option (MYSQL *mysql, enum enum_mysql_set_option option)
int STDCALL mysql_dump_debug_info (MYSQL *mysql)
const char * cli_read_statistics (MYSQL *mysql)
const char *STDCALL mysql_stat (MYSQL *mysql)
int STDCALL mysql_ping (MYSQL *mysql)
const char *STDCALL mysql_get_server_info (MYSQL *mysql)
const char *STDCALL mysql_get_host_info (MYSQL *mysql)
uint STDCALL mysql_get_proto_info (MYSQL *mysql)
const char *STDCALL mysql_get_client_info (void)
ulong STDCALL mysql_get_client_version (void)
my_bool STDCALL mysql_eof (MYSQL_RES *res)
MYSQL_FIELD *STDCALL mysql_fetch_field_direct (MYSQL_RES *res, uint fieldnr)
MYSQL_FIELD *STDCALL mysql_fetch_fields (MYSQL_RES *res)
MYSQL_ROW_OFFSET STDCALL mysql_row_tell (MYSQL_RES *res)
MYSQL_FIELD_OFFSET STDCALL mysql_field_tell (MYSQL_RES *res)
unsigned int STDCALL mysql_field_count (MYSQL *mysql)
my_ulonglong STDCALL mysql_affected_rows (MYSQL *mysql)
my_ulonglong STDCALL mysql_insert_id (MYSQL *mysql)
const char *STDCALL mysql_sqlstate (MYSQL *mysql)
uint STDCALL mysql_warning_count (MYSQL *mysql)
const char *STDCALL mysql_info (MYSQL *mysql)
ulong STDCALL mysql_thread_id (MYSQL *mysql)
const char *STDCALL mysql_character_set_name (MYSQL *mysql)
void STDCALL mysql_get_character_set_info (MYSQL *mysql, MY_CHARSET_INFO *csinfo)
uint STDCALL mysql_thread_safe (void)
my_bool STDCALL mysql_embedded (void)
void my_net_local_init (NET *net)
ulong STDCALL mysql_hex_string (char *to, const char *from, ulong length)
ulong STDCALL mysql_escape_string (char *to, const char *from, ulong length)
ulong STDCALL mysql_real_escape_string (MYSQL *mysql, char *to, const char *from, ulong length)
void STDCALL myodbc_remove_escape (MYSQL *mysql, char *name)
static int stmt_read_row_unbuffered (MYSQL_STMT *stmt, unsigned char **row)
static int stmt_read_row_buffered (MYSQL_STMT *stmt, unsigned char **row)
static int stmt_read_row_from_cursor (MYSQL_STMT *stmt, unsigned char **row)
static int stmt_read_row_no_data (MYSQL_STMT *stmt, unsigned char **row)
static int stmt_read_row_no_result_set (MYSQL_STMT *stmt, unsigned char **row)
static void stmt_update_metadata (MYSQL_STMT *stmt, MYSQL_ROWS *data)
static my_bool setup_one_fetch_function (MYSQL_BIND *, MYSQL_FIELD *field)
static my_bool reset_stmt_handle (MYSQL_STMT *stmt, uint flags)
static my_bool my_realloc_str (NET *net, ulong length)
static void stmt_clear_error (MYSQL_STMT *stmt)
void set_stmt_error (MYSQL_STMT *stmt, int errcode, const char *sqlstate, const char *err)
void set_stmt_errmsg (MYSQL_STMT *stmt, NET *net)
my_bool cli_read_prepare_result (MYSQL *mysql, MYSQL_STMT *stmt)
MYSQL_STMT *STDCALL mysql_stmt_init (MYSQL *mysql)
int STDCALL mysql_stmt_prepare (MYSQL_STMT *stmt, const char *query, ulong length)
static void alloc_stmt_fields (MYSQL_STMT *stmt)
static void update_stmt_fields (MYSQL_STMT *stmt)
MYSQL_RES *STDCALL mysql_stmt_result_metadata (MYSQL_STMT *stmt)
MYSQL_RES *STDCALL mysql_stmt_param_metadata (MYSQL_STMT *stmt)
static void store_param_type (unsigned char **pos, MYSQL_BIND *param)
static void store_param_tinyint (NET *net, MYSQL_BIND *param)
static void store_param_short (NET *net, MYSQL_BIND *param)
static void store_param_int32 (NET *net, MYSQL_BIND *param)
static void store_param_int64 (NET *net, MYSQL_BIND *param)
static void store_param_float (NET *net, MYSQL_BIND *param)
static void store_param_double (NET *net, MYSQL_BIND *param)
static void store_param_time (NET *net, MYSQL_BIND *param)
static void net_store_datetime (NET *net, MYSQL_TIME *tm)
static void store_param_date (NET *net, MYSQL_BIND *param)
static void store_param_datetime (NET *net, MYSQL_BIND *param)
static void store_param_str (NET *net, MYSQL_BIND *param)
static void store_param_null (NET *net, MYSQL_BIND *param)
static my_bool store_param (MYSQL_STMT *stmt, MYSQL_BIND *param)
static my_bool execute (MYSQL_STMT *stmt, char *packet, ulong length)
int cli_stmt_execute (MYSQL_STMT *stmt)
static int stmt_read_row_no_data (MYSQL_STMT *stmt __attribute__((unused)), unsigned char **row __attribute__((unused)))
static int stmt_read_row_no_result_set (MYSQL_STMT *stmt __attribute__((unused)), unsigned char **row __attribute__((unused)))
my_bool STDCALL mysql_stmt_attr_set (MYSQL_STMT *stmt, enum enum_stmt_attr_type attr_type, const void *value)
my_bool STDCALL mysql_stmt_attr_get (MYSQL_STMT *stmt, enum enum_stmt_attr_type attr_type, void *value)
static void reinit_result_set_metadata (MYSQL_STMT *stmt)
static void prepare_to_fetch_result (MYSQL_STMT *stmt)
int STDCALL mysql_stmt_execute (MYSQL_STMT *stmt)
ulong STDCALL mysql_stmt_param_count (MYSQL_STMT *stmt)
my_ulonglong STDCALL mysql_stmt_affected_rows (MYSQL_STMT *stmt)
unsigned int STDCALL mysql_stmt_field_count (MYSQL_STMT *stmt)
my_ulonglong STDCALL mysql_stmt_insert_id (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_bind_param (MYSQL_STMT *stmt, MYSQL_BIND *my_bind)
my_bool STDCALL mysql_stmt_send_long_data (MYSQL_STMT *stmt, uint param_number, const char *data, ulong length)
static void read_binary_time (MYSQL_TIME *tm, uchar **pos)
static void read_binary_datetime (MYSQL_TIME *tm, uchar **pos)
static void read_binary_date (MYSQL_TIME *tm, uchar **pos)
static void fetch_string_with_conversion (MYSQL_BIND *param, char *value, uint length)
static void fetch_long_with_conversion (MYSQL_BIND *param, MYSQL_FIELD *field, longlong value, my_bool is_unsigned)
static void fetch_float_with_conversion (MYSQL_BIND *param, MYSQL_FIELD *field, double value, my_gcvt_arg_type type)
static void fetch_datetime_with_conversion (MYSQL_BIND *param, MYSQL_FIELD *field, MYSQL_TIME *my_time)
static void fetch_result_with_conversion (MYSQL_BIND *param, MYSQL_FIELD *field, uchar **row)
static void fetch_result_tinyint (MYSQL_BIND *param, MYSQL_FIELD *field, uchar **row)
static void fetch_result_short (MYSQL_BIND *param, MYSQL_FIELD *field, uchar **row)
static void fetch_result_int32 (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_int64 (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_float (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_double (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_time (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_date (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_datetime (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_bin (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void fetch_result_str (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void skip_result_fixed (MYSQL_BIND *param, MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void skip_result_with_length (MYSQL_BIND *param __attribute__((unused)), MYSQL_FIELD *field __attribute__((unused)), uchar **row)
static void skip_result_string (MYSQL_BIND *param __attribute__((unused)), MYSQL_FIELD *field, uchar **row)
static my_bool is_binary_compatible (enum enum_field_types type1, enum enum_field_types type2)
my_bool STDCALL mysql_stmt_bind_result (MYSQL_STMT *stmt, MYSQL_BIND *my_bind)
static int stmt_fetch_row (MYSQL_STMT *stmt, uchar *row)
int cli_unbuffered_fetch (MYSQL *mysql, char **row)
int STDCALL mysql_stmt_fetch (MYSQL_STMT *stmt)
int STDCALL mysql_stmt_fetch_column (MYSQL_STMT *stmt, MYSQL_BIND *my_bind, uint column, ulong offset)
int cli_read_binary_rows (MYSQL_STMT *stmt)
int STDCALL mysql_stmt_store_result (MYSQL_STMT *stmt)
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_seek (MYSQL_STMT *stmt, MYSQL_ROW_OFFSET row)
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_tell (MYSQL_STMT *stmt)
void STDCALL mysql_stmt_data_seek (MYSQL_STMT *stmt, my_ulonglong row)
my_ulonglong STDCALL mysql_stmt_num_rows (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_free_result (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_close (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_reset (MYSQL_STMT *stmt)
uint STDCALL mysql_stmt_errno (MYSQL_STMT *stmt)
const char *STDCALL mysql_stmt_sqlstate (MYSQL_STMT *stmt)
const char *STDCALL mysql_stmt_error (MYSQL_STMT *stmt)
my_bool STDCALL mysql_commit (MYSQL *mysql)
my_bool STDCALL mysql_rollback (MYSQL *mysql)
my_bool STDCALL mysql_autocommit (MYSQL *mysql, my_bool auto_mode)
my_bool STDCALL mysql_more_results (MYSQL *mysql)
int STDCALL mysql_next_result (MYSQL *mysql)
int STDCALL mysql_stmt_next_result (MYSQL_STMT *stmt)
MYSQL_RES *STDCALL mysql_use_result (MYSQL *mysql)
my_bool STDCALL mysql_read_query_result (MYSQL *mysql)
Variables
ulong net_buffer_length =8192
ulong max_allowed_packet = 1024L*1024L*1024L
static my_bool mysql_client_init = 0
static my_bool org_my_init_done = 0
static MYSQL_PARAMETERS mysql_internal_parameters
static my_bool int_is_null_true = 1
static my_bool int_is_null_false = 0
Macro Definition Documentation
BIND_RESULT_DONE
#define BIND_RESULT_DONE 1
Definition at line 1279 of file libmysql.c.
DEFAULT_PREFETCH_ROWS
#define DEFAULT_PREFETCH_ROWS (ulong) 1
Definition at line 1219 of file libmysql.c.
INADDR_NONE
#define INADDR_NONE -1
Definition at line 58 of file libmysql.c.
IS_TRUNCATED
#define IS_TRUNCATED (value, is_unsigned, min, max, umax)
Value:
        ((is_unsigned) ? (((value) > (umax) || (value) < 0) ? 1 : 0) : \
                         (((value) > (max)  || (value) < (min)) ? 1 : 0))
Definition at line 1275 of file libmysql.c.
MAX_DATE_REP_LENGTH
#define MAX_DATE_REP_LENGTH 5
Definition at line 1257 of file libmysql.c.
MAX_DATETIME_REP_LENGTH
#define MAX_DATETIME_REP_LENGTH 12
Definition at line 1269 of file libmysql.c.
MAX_DOUBLE_STRING_REP_LENGTH
#define MAX_DOUBLE_STRING_REP_LENGTH 331
Definition at line 1271 of file libmysql.c.
MAX_LONG_DATA_LENGTH
#define MAX_LONG_DATA_LENGTH 8192
Definition at line 88 of file libmysql.c.
MAX_TIME_REP_LENGTH
#define MAX_TIME_REP_LENGTH 13
Definition at line 1263 of file libmysql.c.
REPORT_DATA_TRUNCATION
#define REPORT_DATA_TRUNCATION 2
Definition at line 1285 of file libmysql.c.
RESET_CLEAR_ERROR
#define RESET_CLEAR_ERROR 8
Definition at line 1247 of file libmysql.c.
RESET_LONG_DATA
#define RESET_LONG_DATA 2
Definition at line 1245 of file libmysql.c.
RESET_SERVER_SIDE
#define RESET_SERVER_SIDE 1
Definition at line 1244 of file libmysql.c.
RESET_STORE_RESULT
#define RESET_STORE_RESULT 4
Definition at line 1246 of file libmysql.c.
SOCKET_ERROR
#define SOCKET_ERROR -1
Definition at line 81 of file libmysql.c.
unsigned_field
#define unsigned_field (A) ((A)->flags & UNSIGNED_FLAG)
Definition at line 89 of file libmysql.c.
Typedef Documentation
default_local_infile_data
typedef struct st_default_local_infile default_local_infile_data
Function Documentation
alloc_stmt_fields()
static void alloc_stmt_fields (MYSQL_STMT * stmt) static
Definition at line 1631 of file libmysql.c.
 {
   MYSQL_FIELD *fields, *field, *end;
   MEM_ROOT *alloc= &stmt->mem_root;
   MYSQL *mysql= stmt->mysql;
   DBUG_ASSERT(mysql->field_count);
   stmt->field_count= mysql->field_count;
   /*
     Get the field information for non-select statements
     like SHOW and DESCRIBE commands
   */
   if (!(stmt->fields= (MYSQL_FIELD *) alloc_root(alloc,
                          sizeof(MYSQL_FIELD) *
                          stmt->field_count)) ||
       !(stmt->bind= (MYSQL_BIND *) alloc_root(alloc,
                           sizeof(MYSQL_BIND) *
                           stmt->field_count)))
   {
     set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
     return;
   }
   for (fields= mysql->fields, end= fields+stmt->field_count,
      field= stmt->fields;
        field && fields < end; fields++, field++)
   {
     *field= *fields; /* To copy all numeric parts. */
     field->catalog=   strmake_root(alloc, fields->catalog,
                                    fields->catalog_length);
     field->db=        strmake_root(alloc, fields->db, fields->db_length);
     field->table=     strmake_root(alloc, fields->table, fields->table_length);
     field->org_table= strmake_root(alloc, fields->org_table,
                                    fields->org_table_length);
     field->name=      strmake_root(alloc, fields->name, fields->name_length);
     field->org_name=  strmake_root(alloc, fields->org_name,
                                    fields->org_name_length);
     field->def=       fields->def ? strmake_root(alloc, fields->def,
                                                  fields->def_length) : 0;
     field->def_length= field->def ? fields->def_length : 0;
     field->extension= 0; /* Avoid dangling links. */
     field->max_length= 0; /* max_length is set in mysql_stmt_store_result() */
   }
 }
References alloc_root(), st_mysql_stmt::bind, st_mysql_field::catalog, st_mysql_field::catalog_length, CR_OUT_OF_MEMORY, st_mysql_field::db, st_mysql_field::db_length, DBUG_ASSERT, st_mysql_field::def, st_mysql_field::def_length, st_mysql_field::extension, st_mysql::field_count, st_mysql_stmt::field_count, st_mysql::fields, st_mysql_stmt::fields, st_mysql_field::max_length, st_mysql_stmt::mem_root, st_mysql_stmt::mysql, st_mysql_field::name, st_mysql_field::name_length, NULL, st_mysql_field::org_name, st_mysql_field::org_name_length, st_mysql_field::org_table, st_mysql_field::org_table_length, set_stmt_error(), strmake_root(), st_mysql_field::table, st_mysql_field::table_length, and unknown_sqlstate.
Referenced by mysql_stmt_next_result(), and reinit_result_set_metadata().
append_wild()
static void append_wild (char * to, char * end, const char * wild) static
Definition at line 244 of file libmysql.c.
 {
   end-=5;                   /* Some extra */
   if (wild && wild[0])
   {
     to=strmov(to," like '");
     while (*wild && to < end)
     {
       if (*wild == '\\' || *wild == '\'')
     *to++='\\';
       *to++= *wild++;
     }
     if (*wild)                  /* Too small buffer */
       *to++='%';                /* Nicer this way */
     to[0]='\'';
     to[1]=0;
   }
 }
References strmov().
Referenced by mysql_list_dbs(), and mysql_list_tables().
cli_list_fields()
MYSQL_FIELD* cli_list_fields (MYSQL * mysql)
Definition at line 792 of file libmysql.c.
 {
   MYSQL_DATA *query;
   if (!(query= cli_read_rows(mysql,(MYSQL_FIELD*) 0,
                  protocol_41(mysql) ? 8 : 6)))
     return NULL;
   mysql->field_count= (uint) query->rows;
   return unpack_fields(query,&mysql->field_alloc,
                mysql->field_count, 1, mysql->server_capabilities);
 }
References cli_read_rows(), st_mysql::field_alloc, st_mysql::field_count, NULL, protocol_41, st_mysql_data::rows, st_mysql::server_capabilities, and unpack_fields().
cli_read_binary_rows()
int cli_read_binary_rows (MYSQL_STMT * stmt)
Definition at line 4224 of file libmysql.c.
 {
   ulong      pkt_len;
   uchar      *cp;
   MYSQL      *mysql= stmt->mysql;
   MYSQL_DATA *result= &stmt->result;
   MYSQL_ROWS *cur, **prev_ptr= &result->data;
   NET        *net;
   DBUG_ENTER("cli_read_binary_rows");
   if (!mysql)
   {
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   net = &mysql->net;
   while ((pkt_len= cli_safe_read(mysql)) != packet_error)
   {
     cp= net->read_pos;
     if (cp[0] != 254 || pkt_len >= 8)
     {
       if (!(cur= (MYSQL_ROWS*) alloc_root(&result->alloc,
                                           sizeof(MYSQL_ROWS) + pkt_len - 1)))
       {
         set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
         goto err;
       }
       cur->data= (MYSQL_ROW) (cur+1);
       *prev_ptr= cur;
       prev_ptr= &cur->next;
       memcpy((char *) cur->data, (char *) cp+1, pkt_len-1);
       cur->length= pkt_len;     /* To allow us to do sanity checks */
       result->rows++;
     }
     else
     {
       /* end of data */
       *prev_ptr= 0;
       mysql->warning_count= uint2korr(cp+1);
       mysql->server_status= uint2korr(cp+3);
       DBUG_PRINT("info",("status: %u  warning_count: %u",
                          mysql->server_status, mysql->warning_count));
       DBUG_RETURN(0);
     }
   }
   set_stmt_errmsg(stmt, net);
 err:
   DBUG_RETURN(1);
 }
References alloc_root(), cli_safe_read(), CR_OUT_OF_MEMORY, CR_SERVER_LOST, st_mysql_rows::data, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql_rows::length, memcpy, st_mysql_stmt::mysql, st_mysql::net, st_mysql_rows::next, NULL, packet_error, st_net::read_pos, st_mysql_stmt::result, st_mysql::server_status, set_stmt_errmsg(), set_stmt_error(), uint2korr, unknown_sqlstate, and st_mysql::warning_count.
cli_read_prepare_result()
my_bool cli_read_prepare_result (MYSQL * mysql, MYSQL_STMT * stmt)
Definition at line 1394 of file libmysql.c.
 {
   uchar *pos;
   uint field_count, param_count;
   ulong packet_length;
   MYSQL_DATA *fields_data;
   DBUG_ENTER("cli_read_prepare_result");
   if ((packet_length= cli_safe_read(mysql)) == packet_error)
     DBUG_RETURN(1);
   mysql->warning_count= 0;
   pos= (uchar*) mysql->net.read_pos;
   stmt->stmt_id= uint4korr(pos+1); pos+= 5;
   /* Number of columns in result set */
   field_count=   uint2korr(pos);   pos+= 2;
   /* Number of placeholders in the statement */
   param_count=   uint2korr(pos);   pos+= 2;
   if (packet_length >= 12)
     mysql->warning_count= uint2korr(pos+1);
   if (param_count != 0)
   {
     MYSQL_DATA *param_data;
     /* skip parameters data: we don't support it yet */
     if (!(param_data= (*mysql->methods->read_rows)(mysql, (MYSQL_FIELD*)0, 7)))
       DBUG_RETURN(1);
     free_rows(param_data);
   }
   if (field_count != 0)
   {
     if (!(mysql->server_status & SERVER_STATUS_AUTOCOMMIT))
       mysql->server_status|= SERVER_STATUS_IN_TRANS;
     if (!(fields_data= (*mysql->methods->read_rows)(mysql,(MYSQL_FIELD*)0,7)))
       DBUG_RETURN(1);
     if (!(stmt->fields= unpack_fields(fields_data,&stmt->mem_root,
                       field_count,0,
                       mysql->server_capabilities)))
       DBUG_RETURN(1);
   }
   stmt->field_count=  field_count;
   stmt->param_count=  (ulong) param_count;
   DBUG_PRINT("exit",("field_count: %u  param_count: %u  warning_count: %u",
                      field_count, param_count, (uint) mysql->warning_count));
   DBUG_RETURN(0);
 }
References cli_safe_read(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql_stmt::field_count, st_mysql_stmt::fields, free_rows(), st_mysql_stmt::mem_root, st_mysql::methods, st_mysql::net, packet_error, st_mysql_stmt::param_count, pos(), st_net::read_pos, st_mysql_methods::read_rows, st_mysql::server_capabilities, st_mysql::server_status, SERVER_STATUS_AUTOCOMMIT, SERVER_STATUS_IN_TRANS, st_mysql_stmt::stmt_id, uint2korr, uint4korr, unpack_fields(), and st_mysql::warning_count.
cli_read_statistics()
const char* cli_read_statistics (MYSQL * mysql)
Definition at line 937 of file libmysql.c.
 {
   mysql->net.read_pos[mysql->packet_length]=0;  /* End of stat string */
   if (!mysql->net.read_pos[0])
   {
     set_mysql_error(mysql, CR_WRONG_HOST_INFO, unknown_sqlstate);
     return mysql->net.last_error;
   }
   return (char*) mysql->net.read_pos;
 }
References CR_WRONG_HOST_INFO, st_net::last_error, st_mysql::net, st_mysql::packet_length, st_net::read_pos, set_mysql_error(), and unknown_sqlstate.
cli_stmt_execute()
int cli_stmt_execute (MYSQL_STMT * stmt)
Definition at line 2053 of file libmysql.c.
 {
   DBUG_ENTER("cli_stmt_execute");
   if (stmt->param_count)
   {
     MYSQL *mysql= stmt->mysql;
     NET        *net= &mysql->net;
     MYSQL_BIND *param, *param_end;
     char       *param_data;
     ulong length;
     uint null_count;
     my_bool    result;
     if (!stmt->bind_param_done)
     {
       set_stmt_error(stmt, CR_PARAMS_NOT_BOUND, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     if (mysql->status != MYSQL_STATUS_READY ||
         mysql->server_status & SERVER_MORE_RESULTS_EXISTS)
     {
       set_stmt_error(stmt, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     net_clear(net, 1);              /* Sets net->write_pos */
     /* Reserve place for null-marker bytes */
     null_count= (stmt->param_count+7) /8;
     if (my_realloc_str(net, null_count + 1))
     {
       set_stmt_errmsg(stmt, net);
       DBUG_RETURN(1);
     }
     bzero((char*) net->write_pos, null_count);
     net->write_pos+= null_count;
     param_end= stmt->params + stmt->param_count;
     /* In case if buffers (type) altered, indicate to server */
     *(net->write_pos)++= (uchar) stmt->send_types_to_server;
     if (stmt->send_types_to_server)
     {
       if (my_realloc_str(net, 2 * stmt->param_count))
       {
         set_stmt_errmsg(stmt, net);
         DBUG_RETURN(1);
       }
       /*
     Store types of parameters in first in first package
     that is sent to the server.
       */
       for (param= stmt->params; param < param_end ; param++)
         store_param_type(&net->write_pos, param);
     }
     for (param= stmt->params; param < param_end; param++)
     {
       /* check if mysql_stmt_send_long_data() was used */
       if (param->long_data_used)
     param->long_data_used= 0;   /* Clear for next execute call */
       else if (store_param(stmt, param))
     DBUG_RETURN(1);
     }
     length= (ulong) (net->write_pos - net->buff);
     /* TODO: Look into avoding the following memdup */
     if (!(param_data= my_memdup(net->buff, length, MYF(0))))
     {
       set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     result= execute(stmt, param_data, length);
     stmt->send_types_to_server=0;
     my_free(param_data);
     DBUG_RETURN(result);
   }
   DBUG_RETURN((int) execute(stmt,0,0));
 }
References st_mysql_stmt::bind_param_done, st_net::buff, bzero, CR_COMMANDS_OUT_OF_SYNC, CR_OUT_OF_MEMORY, CR_PARAMS_NOT_BOUND, DBUG_ENTER, DBUG_RETURN, execute(), G3D::length(), st_mysql_bind::long_data_used, my_free(), my_memdup(), my_realloc_str(), MYF, st_mysql_stmt::mysql, MYSQL_STATUS_READY, st_mysql::net, net_clear(), NULL, st_mysql_stmt::param_count, st_mysql_stmt::params, st_mysql_stmt::send_types_to_server, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_stmt_errmsg(), set_stmt_error(), st_mysql::status, store_param(), store_param_type(), unknown_sqlstate, and st_net::write_pos.
cli_unbuffered_fetch()
int cli_unbuffered_fetch (MYSQL * mysql, char ** row)
Definition at line 4125 of file libmysql.c.
 {
   if (packet_error == cli_safe_read(mysql))
     return 1;
   *row= ((mysql->net.read_pos[0] == 254) ? NULL :
      (char*) (mysql->net.read_pos+1));
   return 0;
 }
References cli_safe_read(), st_mysql::net, NULL, packet_error, and st_net::read_pos.
default_local_infile_end()
static void default_local_infile_end (void * ptr) static
Definition at line 624 of file libmysql.c.
 {
   default_local_infile_data *data= (default_local_infile_data *) ptr;
   if (data)                 /* If not error on open */
   {
     if (data->fd >= 0)
       my_close(data->fd, MYF(MY_WME));
     my_free(ptr);
   }
 }
References my_close(), my_free(), MY_WME, MYF, and ptr().
Referenced by mysql_set_local_infile_default().
default_local_infile_error()
static int default_local_infile_error (void * ptr, char * error_msg, uint error_msg_len) static
Definition at line 651 of file libmysql.c.
 {
   default_local_infile_data *data = (default_local_infile_data *) ptr;
   if (data)                 /* If not error on open */
   {
     strmake(error_msg, data->error_msg, error_msg_len);
     return data->error_num;
   }
   /* This can only happen if we got error on malloc of handle */
   strmov(error_msg, ER(CR_OUT_OF_MEMORY));
   return CR_OUT_OF_MEMORY;
 }
References CR_OUT_OF_MEMORY, ER, ptr(), strmake(), and strmov().
Referenced by mysql_set_local_infile_default().
default_local_infile_init()
static int default_local_infile_init (void ** ptr, const char * filename, void *userdata __attribute__(unused)) static
Definition at line 556 of file libmysql.c.
 {
   default_local_infile_data *data;
   char tmp_name[FN_REFLEN];
   if (!(*ptr= data= ((default_local_infile_data *)
              my_malloc(sizeof(default_local_infile_data),  MYF(0)))))
     return 1; /* out of memory */
   data->error_msg[0]= 0;
   data->error_num=    0;
   data->filename= filename;
   fn_format(tmp_name, filename, "", "", MY_UNPACK_FILENAME);
   if ((data->fd = my_open(tmp_name, O_RDONLY, MYF(0))) < 0)
   {
     data->error_num= my_errno;
     my_snprintf(data->error_msg, sizeof(data->error_msg)-1,
                 EE(EE_FILENOTFOUND), tmp_name, data->error_num);
     return 1;
   }
   return 0; /* ok */
 }
References EE, EE_FILENOTFOUND, fn_format(), FN_REFLEN, my_errno, my_malloc(), my_open(), my_snprintf(), MY_UNPACK_FILENAME, MYF, and ptr().
Referenced by mysql_set_local_infile_default().
default_local_infile_read()
static int default_local_infile_read (void * ptr, char * buf, uint buf_len) static
Definition at line 597 of file libmysql.c.
 {
   int count;
   default_local_infile_data*data = (default_local_infile_data *) ptr;
   if ((count= (int) my_read(data->fd, (uchar *) buf, buf_len, MYF(0))) < 0)
   {
     data->error_num= EE_READ; /* the errmsg for not entire file read */
     my_snprintf(data->error_msg, sizeof(data->error_msg)-1,
         EE(EE_READ),
         data->filename, my_errno);
   }
   return count;
 }
References count(), EE, EE_READ, my_errno, my_read, my_snprintf(), MYF, and ptr().
Referenced by mysql_set_local_infile_default().
execute()
static my_bool execute (MYSQL_STMT * stmt, char * packet, ulong length) static
Definition at line 2017 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   NET   *net= &mysql->net;
   uchar buff[4 /* size of stmt id */ +
              5 /* execution flags */];
   my_bool res;
   DBUG_ENTER("execute");
   DBUG_DUMP("packet", (uchar *) packet, length);
   int4store(buff, stmt->stmt_id);       /* Send stmt id to server */
   buff[4]= (char) stmt->flags;
   int4store(buff+5, 1);                         /* iteration count */
   res= test(cli_advanced_command(mysql, COM_STMT_EXECUTE, buff, sizeof(buff),
                                  (uchar*) packet, length, 1, stmt) ||
             (*mysql->methods->read_query_result)(mysql));
   stmt->affected_rows= mysql->affected_rows;
   stmt->server_status= mysql->server_status;
   stmt->insert_id= mysql->insert_id;
   if (res)
   {
     /*
       Don't set stmt error if stmt->mysql is NULL, as the error in this case
       has already been set by mysql_prune_stmt_list().
     */
     if (stmt->mysql)
       set_stmt_errmsg(stmt, net);
     DBUG_RETURN(1);
   }
   else if (mysql->status == MYSQL_STATUS_GET_RESULT)
     stmt->mysql->status= MYSQL_STATUS_STATEMENT_GET_RESULT;
   DBUG_RETURN(0);
 }
References st_mysql::affected_rows, st_mysql_stmt::affected_rows, cli_advanced_command(), COM_STMT_EXECUTE, DBUG_DUMP, DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::flags, st_mysql::insert_id, st_mysql_stmt::insert_id, int4store, G3D::length(), st_mysql::methods, st_mysql_stmt::mysql, MYSQL_STATUS_GET_RESULT, MYSQL_STATUS_STATEMENT_GET_RESULT, st_mysql::net, st_mysql_methods::read_query_result, st_mysql::server_status, st_mysql_stmt::server_status, set_stmt_errmsg(), st_mysql::status, st_mysql_stmt::stmt_id, and test.
Referenced by cli_stmt_execute().
fetch_datetime_with_conversion()
static void fetch_datetime_with_conversion (MYSQL_BIND * param, MYSQL_FIELD * field, MYSQL_TIME * my_time) static
Definition at line 3428 of file libmysql.c.
 {
   switch (param->buffer_type) {
   case MYSQL_TYPE_NULL: /* do nothing */
     break;
   case MYSQL_TYPE_DATE:
     *(MYSQL_TIME *)(param->buffer)= *my_time;
     *param->error= my_time->time_type != MYSQL_TIMESTAMP_DATE;
     break;
   case MYSQL_TYPE_TIME:
     *(MYSQL_TIME *)(param->buffer)= *my_time;
     *param->error= my_time->time_type != MYSQL_TIMESTAMP_TIME;
     break;
   case MYSQL_TYPE_DATETIME:
   case MYSQL_TYPE_TIMESTAMP:
     *(MYSQL_TIME *)(param->buffer)= *my_time;
     /* No error: time and date are compatible with datetime */
     break;
   case MYSQL_TYPE_YEAR:
     shortstore(param->buffer, my_time->year);
     *param->error= 1;
     break;
   case MYSQL_TYPE_FLOAT:
   case MYSQL_TYPE_DOUBLE:
   {
     ulonglong value= TIME_to_ulonglong(my_time);
     fetch_float_with_conversion(param, field,
                                 ulonglong2double(value), MY_GCVT_ARG_DOUBLE);
     break;
   }
   case MYSQL_TYPE_TINY:
   case MYSQL_TYPE_SHORT:
   case MYSQL_TYPE_INT24:
   case MYSQL_TYPE_LONG:
   case MYSQL_TYPE_LONGLONG:
   {
     longlong value= (longlong) TIME_to_ulonglong(my_time);
     fetch_long_with_conversion(param, field, value, TRUE);
     break;
   }
   default:
   {
     /*
       Convert time value  to string and delegate the rest to
       fetch_string_with_conversion:
     */
     char buff[MAX_DATE_STRING_REP_LENGTH];
     uint length= my_TIME_to_str(my_time, buff);
     /* Resort to string conversion */
     fetch_string_with_conversion(param, (char *)buff, length);
     break;
   }
   }
 }
References st_mysql_bind::buffer, st_mysql_bind::buffer_type, st_mysql_bind::error, fetch_float_with_conversion(), fetch_long_with_conversion(), fetch_string_with_conversion(), G3D::length(), MAX_DATE_STRING_REP_LENGTH, MY_GCVT_ARG_DOUBLE, my_time(), my_TIME_to_str(), MYSQL_TIMESTAMP_DATE, MYSQL_TIMESTAMP_TIME, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_YEAR, shortstore, TIME_to_ulonglong(), TRUE, and ulonglong2double.
Referenced by fetch_result_with_conversion().
fetch_float_with_conversion()
static void fetch_float_with_conversion (MYSQL_BIND * param, MYSQL_FIELD * field, double value, my_gcvt_arg_type type) static
Definition at line 3310 of file libmysql.c.
 {
   char *buffer= (char *)param->buffer;
   double val64 = (value < 0 ? -floor(-value) : floor(value));
   switch (param->buffer_type) {
   case MYSQL_TYPE_NULL: /* do nothing */
     break;
   case MYSQL_TYPE_TINY:
     /*
       We need to _store_ data in the buffer before the truncation check to
       workaround Intel FPU executive precision feature.
       (See http://gcc.gnu.org/bugzilla/show_bug.cgi?id=323 for details)
       Sic: AFAIU it does not guarantee to work.
     */
     if (param->is_unsigned)
       *buffer= (uint8) value;
     else
       *buffer= (int8) value;
     *param->error= val64 != (param->is_unsigned ? (double)((uint8) *buffer) :
                                                   (double)((int8) *buffer));
     break;
   case MYSQL_TYPE_SHORT:
     if (param->is_unsigned)
     {
       ushort data= (ushort) value;
       shortstore(buffer, data);
     }
     else
     {
       short data= (short) value;
       shortstore(buffer, data);
     }
     *param->error= val64 != (param->is_unsigned ? (double) (*(ushort*) buffer):
                                                   (double) (*(short*) buffer));
     break;
   case MYSQL_TYPE_LONG:
     if (param->is_unsigned)
     {
       uint32 data= (uint32) value;
       longstore(buffer, data);
     }
     else
     {
       int32 data= (int32) value;
       longstore(buffer, data);
     }
     *param->error= val64 != (param->is_unsigned ? (double) (*(uint32*) buffer):
                                                   (double) (*(int32*) buffer));
       break;
   case MYSQL_TYPE_LONGLONG:
     if (param->is_unsigned)
     {
       ulonglong data= (ulonglong) value;
       longlongstore(buffer, data);
     }
     else
     {
       longlong data= (longlong) value;
       longlongstore(buffer, data);
     }
     *param->error= val64 != (param->is_unsigned ?
                              ulonglong2double(*(ulonglong*) buffer) :
                              (double) (*(longlong*) buffer));
     break;
   case MYSQL_TYPE_FLOAT:
   {
     float data= (float) value;
     floatstore(buffer, data);
     *param->error= (*(float*) buffer) != value;
     break;
   }
   case MYSQL_TYPE_DOUBLE:
   {
     doublestore(buffer, value);
     break;
   }
   default:
   {
     /*
       Resort to fetch_string_with_conversion: this should handle
       floating point -> string conversion nicely, honor all typecodes
       and param->offset possibly set in mysql_stmt_fetch_column
     */
     char buff[FLOATING_POINT_BUFFER];
     size_t len;
     if (field->decimals >= NOT_FIXED_DEC)
       len= my_gcvt(value, type,
                    (int) min(sizeof(buff)-1, param->buffer_length),
                    buff, NULL);
     else
       len= my_fcvt(value, (int) field->decimals, buff, NULL);
     if (field->flags & ZEROFILL_FLAG && len < field->length &&
         field->length < MAX_DOUBLE_STRING_REP_LENGTH - 1)
     {
       bmove_upp((uchar*) buff + field->length, (uchar*) buff + len,
                 len);
       bfill((char*) buff, field->length - len, '0');
       len= field->length;
     }
     fetch_string_with_conversion(param, buff, len);
     break;
   }
   }
 }
References bfill, bmove_upp(), buffer, st_mysql_bind::buffer, st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, st_mysql_field::decimals, doublestore, st_mysql_bind::error, fetch_string_with_conversion(), st_mysql_field::flags, FLOATING_POINT_BUFFER, floatstore, G3D::floor(), st_mysql_bind::is_unsigned, G3D::length(), st_mysql_field::length, longlongstore, longstore, MAX_DOUBLE_STRING_REP_LENGTH, min, my_fcvt(), my_gcvt(), MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_LONG, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_TINY, NOT_FIXED_DEC, NULL, shortstore, ulonglong2double, and ZEROFILL_FLAG.
Referenced by fetch_datetime_with_conversion(), and fetch_result_with_conversion().
fetch_long_with_conversion()
static void fetch_long_with_conversion (MYSQL_BIND * param, MYSQL_FIELD * field, longlong value, my_bool is_unsigned) static
Definition at line 3201 of file libmysql.c.
 {
   char *buffer= (char *)param->buffer;
   switch (param->buffer_type) {
   case MYSQL_TYPE_NULL: /* do nothing */
     break;
   case MYSQL_TYPE_TINY:
     *param->error= IS_TRUNCATED(value, param->is_unsigned,
                                 INT_MIN8, INT_MAX8, UINT_MAX8);
     *(uchar *)param->buffer= (uchar) value;
     break;
   case MYSQL_TYPE_SHORT:
     *param->error= IS_TRUNCATED(value, param->is_unsigned,
                                 INT_MIN16, INT_MAX16, UINT_MAX16);
     shortstore(buffer, (short) value);
     break;
   case MYSQL_TYPE_LONG:
     *param->error= IS_TRUNCATED(value, param->is_unsigned,
                                 INT_MIN32, INT_MAX32, UINT_MAX32);
     longstore(buffer, (int32) value);
     break;
   case MYSQL_TYPE_LONGLONG:
     longlongstore(buffer, value);
     *param->error= param->is_unsigned != is_unsigned && value < 0;
     break;
   case MYSQL_TYPE_FLOAT:
   {
     /*
       We need to mark the local variable volatile to
       workaround Intel FPU executive precision feature.
       (See http://gcc.gnu.org/bugzilla/show_bug.cgi?id=323 for details)
     */
     volatile float data;
     if (is_unsigned)
     {
       data= (float) ulonglong2double(value);
       *param->error= ((ulonglong) value) != ((ulonglong) data);
     }
     else
     {
       data= (float)value;
       *param->error= value != ((longlong) data);
     }
     floatstore(buffer, data);
     break;
   }
   case MYSQL_TYPE_DOUBLE:
   {
     volatile double data;
     if (is_unsigned)
     {
       data= ulonglong2double(value);
       *param->error= ((ulonglong) value) != ((ulonglong) data);
     }
     else
     {
       data= (double)value;
       *param->error= value != ((longlong) data);
     }
     doublestore(buffer, data);
     break;
   }
   case MYSQL_TYPE_TIME:
   case MYSQL_TYPE_DATE:
   case MYSQL_TYPE_TIMESTAMP:
   case MYSQL_TYPE_DATETIME:
   {
     int error;
     value= number_to_datetime(value, (MYSQL_TIME *) buffer, TIME_FUZZY_DATE,
                               &error);
     *param->error= test(error);
     break;
   }
   default:
   {
     uchar buff[22];                              /* Enough for longlong */
     uchar *end= (uchar*) longlong10_to_str(value, (char*) buff,
                                            is_unsigned ? 10: -10);
     /* Resort to string conversion which supports all typecodes */
     uint length= (uint) (end-buff);
     if (field->flags & ZEROFILL_FLAG && length < field->length &&
         field->length < 21)
     {
       bmove_upp(buff+field->length,buff+length, length);
       bfill(buff, field->length - length,'0');
       length= field->length;
     }
     fetch_string_with_conversion(param, (char*) buff, length);
     break;
   }
   }
 }
References bfill, bmove_upp(), st_mysql_bind::buffer, st_mysql_bind::buffer_type, doublestore, st_mysql_bind::error, error(), fetch_string_with_conversion(), st_mysql_field::flags, floatstore, INT_MAX16, INT_MAX32, INT_MAX8, INT_MIN16, INT_MIN32, INT_MIN8, IS_TRUNCATED, st_mysql_bind::is_unsigned, G3D::length(), st_mysql_field::length, longlong10_to_str(), longlongstore, longstore, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_LONG, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, number_to_datetime(), shortstore, test, TIME_FUZZY_DATE, UINT_MAX16, UINT_MAX32, UINT_MAX8, ulonglong2double, and ZEROFILL_FLAG.
Referenced by fetch_datetime_with_conversion(), and fetch_result_with_conversion().
fetch_result_bin()
static void fetch_result_bin (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3704 of file libmysql.c.
 {
   ulong length= net_field_length(row);
   ulong copy_length= min(length, param->buffer_length);
   memcpy(param->buffer, (char *)*row, copy_length);
   *param->length= length;
   *param->error= copy_length < length;
   *row+= length;
 }
References st_mysql_bind::buffer, st_mysql_bind::buffer_length, st_mysql_bind::error, G3D::length(), st_mysql_bind::length, memcpy, min, and net_field_length().
Referenced by setup_one_fetch_function().
fetch_result_date()
static void fetch_result_date (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3688 of file libmysql.c.
 {
   MYSQL_TIME *tm= (MYSQL_TIME *)param->buffer;
   read_binary_date(tm, row);
 }
References st_mysql_bind::buffer, and read_binary_date().
Referenced by setup_one_fetch_function().
fetch_result_datetime()
static void fetch_result_datetime (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3696 of file libmysql.c.
 {
   MYSQL_TIME *tm= (MYSQL_TIME *)param->buffer;
   read_binary_datetime(tm, row);
 }
References st_mysql_bind::buffer, and read_binary_datetime().
Referenced by setup_one_fetch_function().
fetch_result_double()
static void fetch_result_double (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3670 of file libmysql.c.
 {
   double value;
   float8get(value,*row);
   doublestore(param->buffer, value);
   *row+= 8;
 }
References st_mysql_bind::buffer, doublestore, and float8get.
Referenced by setup_one_fetch_function().
fetch_result_float()
static void fetch_result_float (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3660 of file libmysql.c.
 {
   float value;
   float4get(value,*row);
   floatstore(param->buffer, value);
   *row+= 4;
 }
References st_mysql_bind::buffer, float4get, and floatstore.
Referenced by setup_one_fetch_function().
fetch_result_int32()
static void fetch_result_int32 (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3638 of file libmysql.c.
 {
   my_bool field_is_unsigned= test(field->flags & UNSIGNED_FLAG);
   uint32 data= (uint32) sint4korr(*row);
   longstore(param->buffer, data);
   *param->error= param->is_unsigned != field_is_unsigned && data > INT_MAX32;
   *row+= 4;
 }
References st_mysql_bind::buffer, st_mysql_bind::error, INT_MAX32, st_mysql_bind::is_unsigned, longstore, sint4korr, test, and UNSIGNED_FLAG.
Referenced by setup_one_fetch_function().
fetch_result_int64()
static void fetch_result_int64 (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3649 of file libmysql.c.
 {
   my_bool field_is_unsigned= test(field->flags & UNSIGNED_FLAG);
   ulonglong data= (ulonglong) sint8korr(*row);
   *param->error= param->is_unsigned != field_is_unsigned && data > LONGLONG_MAX;
   longlongstore(param->buffer, data);
   *row+= 8;
 }
References st_mysql_bind::buffer, st_mysql_bind::error, st_mysql_bind::is_unsigned, longlongstore, sint8korr, test, and UNSIGNED_FLAG.
Referenced by setup_one_fetch_function().
fetch_result_short()
static void fetch_result_short (MYSQL_BIND * param, MYSQL_FIELD * field, uchar ** row) static
Definition at line 3628 of file libmysql.c.
 {
   my_bool field_is_unsigned= test(field->flags & UNSIGNED_FLAG);
   ushort data= (ushort) sint2korr(*row);
   shortstore(param->buffer, data);
   *param->error= param->is_unsigned != field_is_unsigned && data > INT_MAX16;
   *row+= 2;
 }
References st_mysql_bind::buffer, st_mysql_bind::error, st_mysql_field::flags, INT_MAX16, st_mysql_bind::is_unsigned, shortstore, sint2korr, test, and UNSIGNED_FLAG.
Referenced by setup_one_fetch_function().
fetch_result_str()
static void fetch_result_str (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3716 of file libmysql.c.
 {
   ulong length= net_field_length(row);
   ulong copy_length= min(length, param->buffer_length);
   memcpy(param->buffer, (char *)*row, copy_length);
   /* Add an end null if there is room in the buffer */
   if (copy_length != param->buffer_length)
     ((uchar *)param->buffer)[copy_length]= '\0';
   *param->length= length;           /* return total length */
   *param->error= copy_length < length;
   *row+= length;
 }
References st_mysql_bind::buffer, st_mysql_bind::buffer_length, st_mysql_bind::error, G3D::length(), st_mysql_bind::length, memcpy, min, and net_field_length().
Referenced by setup_one_fetch_function().
fetch_result_time()
static void fetch_result_time (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3680 of file libmysql.c.
 {
   MYSQL_TIME *tm= (MYSQL_TIME *)param->buffer;
   read_binary_time(tm, row);
 }
References st_mysql_bind::buffer, and read_binary_time().
Referenced by setup_one_fetch_function().
fetch_result_tinyint()
static void fetch_result_tinyint (MYSQL_BIND * param, MYSQL_FIELD * field, uchar ** row) static
Definition at line 3618 of file libmysql.c.
 {
   my_bool field_is_unsigned= test(field->flags & UNSIGNED_FLAG);
   uchar data= **row;
   *(uchar *)param->buffer= data;
   *param->error= param->is_unsigned != field_is_unsigned && data > INT_MAX8;
   (*row)++;
 }
References st_mysql_bind::buffer, st_mysql_bind::error, st_mysql_field::flags, INT_MAX8, st_mysql_bind::is_unsigned, test, and UNSIGNED_FLAG.
Referenced by setup_one_fetch_function().
fetch_result_with_conversion()
static void fetch_result_with_conversion (MYSQL_BIND * param, MYSQL_FIELD * field, uchar ** row) static
Definition at line 3502 of file libmysql.c.
 {
   enum enum_field_types field_type= field->type;
   uint field_is_unsigned= field->flags & UNSIGNED_FLAG;
   switch (field_type) {
   case MYSQL_TYPE_TINY:
   {
     uchar value= **row;
     /* sic: we need to cast to 'signed char' as 'char' may be unsigned */
     longlong data= field_is_unsigned ? (longlong) value :
                                        (longlong) (signed char) value;
     fetch_long_with_conversion(param, field, data, 0);
     *row+= 1;
     break;
   }
   case MYSQL_TYPE_SHORT:
   case MYSQL_TYPE_YEAR:
   {
     short value= sint2korr(*row);
     longlong data= field_is_unsigned ? (longlong) (unsigned short) value :
                                        (longlong) value;
     fetch_long_with_conversion(param, field, data, 0);
     *row+= 2;
     break;
   }
   case MYSQL_TYPE_INT24: /* mediumint is sent as 4 bytes int */
   case MYSQL_TYPE_LONG:
   {
     int32 value= sint4korr(*row);
     longlong data= field_is_unsigned ? (longlong) (uint32) value :
                                        (longlong) value;
     fetch_long_with_conversion(param, field, data, 0);
     *row+= 4;
     break;
   }
   case MYSQL_TYPE_LONGLONG:
   {
     longlong value= (longlong)sint8korr(*row);
     fetch_long_with_conversion(param, field, value,
                                field->flags & UNSIGNED_FLAG);
     *row+= 8;
     break;
   }
   case MYSQL_TYPE_FLOAT:
   {
     float value;
     float4get(value,*row);
     fetch_float_with_conversion(param, field, value, MY_GCVT_ARG_FLOAT);
     *row+= 4;
     break;
   }
   case MYSQL_TYPE_DOUBLE:
   {
     double value;
     float8get(value,*row);
     fetch_float_with_conversion(param, field, value, MY_GCVT_ARG_DOUBLE);
     *row+= 8;
     break;
   }
   case MYSQL_TYPE_DATE:
   {
     MYSQL_TIME tm;
     read_binary_date(&tm, row);
     fetch_datetime_with_conversion(param, field, &tm);
     break;
   }
   case MYSQL_TYPE_TIME:
   {
     MYSQL_TIME tm;
     read_binary_time(&tm, row);
     fetch_datetime_with_conversion(param, field, &tm);
     break;
   }
   case MYSQL_TYPE_DATETIME:
   case MYSQL_TYPE_TIMESTAMP:
   {
     MYSQL_TIME tm;
     read_binary_datetime(&tm, row);
     fetch_datetime_with_conversion(param, field, &tm);
     break;
   }
   default:
   {
     ulong length= net_field_length(row);
     fetch_string_with_conversion(param, (char*) *row, length);
     *row+= length;
     break;
   }
   }
 }
References fetch_datetime_with_conversion(), fetch_float_with_conversion(), fetch_long_with_conversion(), fetch_string_with_conversion(), st_mysql_field::flags, float4get, float8get, G3D::length(), MY_GCVT_ARG_DOUBLE, MY_GCVT_ARG_FLOAT, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_SHORT, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_YEAR, net_field_length(), read_binary_date(), read_binary_datetime(), read_binary_time(), sint2korr, sint4korr, sint8korr, st_mysql_field::type, and UNSIGNED_FLAG.
Referenced by mysql_stmt_fetch_column(), and setup_one_fetch_function().
fetch_string_with_conversion()
static void fetch_string_with_conversion (MYSQL_BIND * param, char * value, uint length) static
Definition at line 3075 of file libmysql.c.
 {
   char *buffer= (char *)param->buffer;
   int err= 0;
   char *endptr= value + length;
   /*
     This function should support all target buffer types: the rest
     of conversion functions can delegate conversion to it.
   */
   switch (param->buffer_type) {
   case MYSQL_TYPE_NULL: /* do nothing */
     break;
   case MYSQL_TYPE_TINY:
   {
     longlong data= my_strtoll10(value, &endptr, &err);
     *param->error= (IS_TRUNCATED(data, param->is_unsigned,
                                  INT_MIN8, INT_MAX8, UINT_MAX8) || err > 0);
     *buffer= (uchar) data;
     break;
   }
   case MYSQL_TYPE_SHORT:
   {
     longlong data= my_strtoll10(value, &endptr, &err);
     *param->error= (IS_TRUNCATED(data, param->is_unsigned,
                                  INT_MIN16, INT_MAX16, UINT_MAX16) || err > 0);
     shortstore(buffer, (short) data);
     break;
   }
   case MYSQL_TYPE_LONG:
   {
     longlong data= my_strtoll10(value, &endptr, &err);
     *param->error= (IS_TRUNCATED(data, param->is_unsigned,
                                  INT_MIN32, INT_MAX32, UINT_MAX32) || err > 0);
     longstore(buffer, (int32) data);
     break;
   }
   case MYSQL_TYPE_LONGLONG:
   {
     longlong data= my_strtoll10(value, &endptr, &err);
     *param->error= param->is_unsigned ? err != 0 :
                                        (err > 0 || (err == 0 && data < 0));
     longlongstore(buffer, data);
     break;
   }
   case MYSQL_TYPE_FLOAT:
   {
     double data= my_strntod(&my_charset_latin1, value, length, &endptr, &err);
     float fdata= (float) data;
     *param->error= (fdata != data) | test(err);
     floatstore(buffer, fdata);
     break;
   }
   case MYSQL_TYPE_DOUBLE:
   {
     double data= my_strntod(&my_charset_latin1, value, length, &endptr, &err);
     *param->error= test(err);
     doublestore(buffer, data);
     break;
   }
   case MYSQL_TYPE_TIME:
   {
     MYSQL_TIME *tm= (MYSQL_TIME *)buffer;
     str_to_time(value, length, tm, &err);
     *param->error= test(err);
     break;
   }
   case MYSQL_TYPE_DATE:
   case MYSQL_TYPE_DATETIME:
   case MYSQL_TYPE_TIMESTAMP:
   {
     MYSQL_TIME *tm= (MYSQL_TIME *)buffer;
     (void) str_to_datetime(value, length, tm, TIME_FUZZY_DATE, &err);
     *param->error= test(err) && (param->buffer_type == MYSQL_TYPE_DATE &&
                                  tm->time_type != MYSQL_TIMESTAMP_DATE);
     break;
   }
   case MYSQL_TYPE_TINY_BLOB:
   case MYSQL_TYPE_MEDIUM_BLOB:
   case MYSQL_TYPE_LONG_BLOB:
   case MYSQL_TYPE_BLOB:
   case MYSQL_TYPE_DECIMAL:
   case MYSQL_TYPE_NEWDECIMAL:
   default:
   {
     /*
       Copy column data to the buffer taking into account offset,
       data length and buffer length.
     */
     char *start= value + param->offset;
     char *end= value + length;
     ulong copy_length;
     if (start < end)
     {
       copy_length= end - start;
       /* We've got some data beyond offset: copy up to buffer_length bytes */
       if (param->buffer_length)
         memcpy(buffer, start, min(copy_length, param->buffer_length));
     }
     else
       copy_length= 0;
     if (copy_length < param->buffer_length)
       buffer[copy_length]= '\0';
     *param->error= copy_length > param->buffer_length;
     /*
       param->length will always contain length of entire column;
       number of copied bytes may be way different:
     */
     *param->length= length;
     break;
   }
   }
 }
References st_mysql_bind::buffer, st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, doublestore, st_mysql_bind::error, floatstore, INT_MAX16, INT_MAX32, INT_MAX8, INT_MIN16, INT_MIN32, INT_MIN8, IS_TRUNCATED, st_mysql_bind::is_unsigned, G3D::length(), st_mysql_bind::length, longlongstore, longstore, memcpy, min, my_charset_latin1, my_strntod, my_strtoll10(), MYSQL_TIMESTAMP_DATE, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NEWDECIMAL, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_TINY_BLOB, st_mysql_bind::offset, shortstore, str_to_datetime(), str_to_time(), test, TIME_FUZZY_DATE, st_mysql_time::time_type, UINT_MAX16, UINT_MAX32, and UINT_MAX8.
Referenced by fetch_datetime_with_conversion(), fetch_float_with_conversion(), fetch_long_with_conversion(), and fetch_result_with_conversion().
handle_local_infile()
my_bool handle_local_infile (MYSQL * mysql, const char * net_filename)
Definition at line 443 of file libmysql.c.
 {
   my_bool result= 1;
   uint packet_length=MY_ALIGN(mysql->net.max_packet-16,IO_SIZE);
   NET *net= &mysql->net;
   int readcount;
   void *li_ptr;          /* pass state to local_infile functions */
   char *buf;        /* buffer to be filled by local_infile_read */
   struct st_mysql_options *options= &mysql->options;
   DBUG_ENTER("handle_local_infile");
   /* check that we've got valid callback functions */
   if (!(options->local_infile_init &&
     options->local_infile_read &&
     options->local_infile_end &&
     options->local_infile_error))
   {
     /* if any of the functions is invalid, set the default */
     mysql_set_local_infile_default(mysql);
   }
   /* copy filename into local memory and allocate read buffer */
   if (!(buf=my_malloc(packet_length, MYF(0))))
   {
     set_mysql_error(mysql, CR_OUT_OF_MEMORY, unknown_sqlstate);
     DBUG_RETURN(1);
   }
   /* initialize local infile (open file, usually) */
   if ((*options->local_infile_init)(&li_ptr, net_filename,
     options->local_infile_userdata))
   {
     (void) my_net_write(net,(const uchar*) "",0); /* Server needs one packet */
     net_flush(net);
     strmov(net->sqlstate, unknown_sqlstate);
     net->last_errno=
       (*options->local_infile_error)(li_ptr,
                                      net->last_error,
                                      sizeof(net->last_error)-1);
     goto err;
   }
   /* read blocks of data from local infile callback */
   while ((readcount =
       (*options->local_infile_read)(li_ptr, buf,
                     packet_length)) > 0)
   {
     if (my_net_write(net, (uchar*) buf, readcount))
     {
       DBUG_PRINT("error",
          ("Lost connection to MySQL server during LOAD DATA of local file"));
       set_mysql_error(mysql, CR_SERVER_LOST, unknown_sqlstate);
       goto err;
     }
   }
   /* Send empty packet to mark end of file */
   if (my_net_write(net, (const uchar*) "", 0) || net_flush(net))
   {
     set_mysql_error(mysql, CR_SERVER_LOST, unknown_sqlstate);
     goto err;
   }
   if (readcount < 0)
   {
     net->last_errno=
       (*options->local_infile_error)(li_ptr,
                                      net->last_error,
                                      sizeof(net->last_error)-1);
     goto err;
   }
   result=0;                 /* Ok */
 err:
   /* free up memory allocated with _init, usually */
   (*options->local_infile_end)(li_ptr);
   my_free(buf);
   DBUG_RETURN(result);
 }
References CR_OUT_OF_MEMORY, CR_SERVER_LOST, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, IO_SIZE, st_net::last_errno, st_net::last_error, st_mysql_options::local_infile_end, st_mysql_options::local_infile_error, st_mysql_options::local_infile_init, st_mysql_options::local_infile_read, st_mysql_options::local_infile_userdata, st_net::max_packet, MY_ALIGN, my_free(), my_malloc(), my_net_write(), MYF, mysql_set_local_infile_default(), st_mysql::net, net_flush(), st_mysql::options, set_mysql_error(), st_net::sqlstate, strmov(), and unknown_sqlstate.
Referenced by cli_read_query_result().
is_binary_compatible()
static my_bool is_binary_compatible (enum enum_field_types type1, enum enum_field_types type2) static
Definition at line 3782 of file libmysql.c.
 {
   static const enum enum_field_types
     range1[]= { MYSQL_TYPE_SHORT, MYSQL_TYPE_YEAR, MYSQL_TYPE_NULL },
     range2[]= { MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_NULL },
     range3[]= { MYSQL_TYPE_DATETIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_NULL },
     range4[]= { MYSQL_TYPE_ENUM, MYSQL_TYPE_SET, MYSQL_TYPE_TINY_BLOB,
                 MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_BLOB,
                 MYSQL_TYPE_VAR_STRING, MYSQL_TYPE_STRING, MYSQL_TYPE_GEOMETRY,
                 MYSQL_TYPE_DECIMAL, MYSQL_TYPE_NULL };
   static const enum enum_field_types
    *range_list[]= { range1, range2, range3, range4 },
    **range_list_end= range_list + sizeof(range_list)/sizeof(*range_list);
    const enum enum_field_types **range, *type;
   if (type1 == type2)
     return TRUE;
   for (range= range_list; range != range_list_end; ++range)
   {
     /* check that both type1 and type2 are in the same range */
     my_bool type1_found= FALSE, type2_found= FALSE;
     for (type= *range; *type != MYSQL_TYPE_NULL; type++)
     {
       type1_found|= type1 == *type;
       type2_found|= type2 == *type;
     }
     if (type1_found || type2_found)
       return type1_found && type2_found;
   }
   return FALSE;
 }
References FALSE, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_ENUM, MYSQL_TYPE_GEOMETRY, MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NULL, MYSQL_TYPE_SET, MYSQL_TYPE_SHORT, MYSQL_TYPE_STRING, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, MYSQL_TYPE_YEAR, and TRUE.
Referenced by setup_one_fetch_function().
my_net_local_init()
void my_net_local_init (NET * net)
Definition at line 1108 of file libmysql.c.
 {
   net->max_packet=   (uint) net_buffer_length;
   my_net_set_read_timeout(net, CLIENT_NET_READ_TIMEOUT);
   my_net_set_write_timeout(net, CLIENT_NET_WRITE_TIMEOUT);
   net->retry_count=  1;
   net->max_packet_size= max(net_buffer_length, max_allowed_packet);
 }
References CLIENT_NET_READ_TIMEOUT, CLIENT_NET_WRITE_TIMEOUT, max, max_allowed_packet, st_net::max_packet, st_net::max_packet_size, my_net_set_read_timeout(), my_net_set_write_timeout(), net_buffer_length, and st_net::retry_count.
Referenced by my_net_init().
my_pipe_sig_handler() [1/2]
sig_handler my_pipe_sig_handler (int sig __attribute__(unused))
Definition at line 304 of file libmysql.c.
 {
   DBUG_PRINT("info",("Hit by signal %d",sig));
 #ifdef SIGNAL_HANDLER_RESET_ON_DELIVERY
   (void) signal(SIGPIPE, my_pipe_sig_handler);
 #endif
 }
References DBUG_PRINT, and my_pipe_sig_handler().
my_pipe_sig_handler() [2/2]
sig_handler my_pipe_sig_handler (int sig)
Referenced by my_pipe_sig_handler().
my_realloc_str()
static my_bool my_realloc_str (NET * net, ulong length) static
Definition at line 1304 of file libmysql.c.
 {
   ulong buf_length= (ulong) (net->write_pos - net->buff);
   my_bool res=0;
   DBUG_ENTER("my_realloc_str");
   if (buf_length + length > net->max_packet)
   {
     res= net_realloc(net, buf_length + length);
     if (res)
     {
       strmov(net->sqlstate, unknown_sqlstate);
       strmov(net->last_error, ER(net->last_errno));
     }
     net->write_pos= net->buff+ buf_length;
   }
   DBUG_RETURN(res);
 }
References st_net::buff, DBUG_ENTER, DBUG_RETURN, ER, st_net::last_errno, st_net::last_error, G3D::length(), st_net::max_packet, net_realloc(), st_net::sqlstate, strmov(), unknown_sqlstate, and st_net::write_pos.
Referenced by cli_stmt_execute(), and store_param().
myodbc_remove_escape()
void STDCALL myodbc_remove_escape (MYSQL * mysql, char * name)
Definition at line 1174 of file libmysql.c.
 {
   char *to;
 #ifdef USE_MB
   my_bool use_mb_flag=use_mb(mysql->charset);
   char *UNINIT_VAR(end);
   if (use_mb_flag)
     for (end=name; *end ; end++) ;
 #endif
   for (to=name ; *name ; name++)
   {
 #ifdef USE_MB
     int l;
     if (use_mb_flag && (l = my_ismbchar( mysql->charset, name , end ) ) )
     {
       while (l--)
     *to++ = *name++;
       name--;
       continue;
     }
 #endif
     if (*name == '\\' && name[1])
       name++;
     *to++= *name;
   }
   *to=0;
 }
References st_mysql::charset, mpq::l, my_ismbchar, UNINIT_VAR, and use_mb.
mysql_affected_rows()
my_ulonglong STDCALL mysql_affected_rows (MYSQL * mysql)
Definition at line 1034 of file libmysql.c.
 {
   return mysql->affected_rows;
 }
References st_mysql::affected_rows.
Referenced by MySQLConnection::_Query().
mysql_autocommit()
my_bool STDCALL mysql_autocommit (MYSQL * mysql, my_bool auto_mode)
Definition at line 4723 of file libmysql.c.
 {
   DBUG_ENTER("mysql_autocommit");
   DBUG_PRINT("enter", ("mode : %d", auto_mode));
   DBUG_RETURN((my_bool) mysql_real_query(mysql, auto_mode ?
                                          "set autocommit=1":"set autocommit=0",
                                          16));
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, and mysql_real_query().
Referenced by MySQLConnection::Open().
mysql_change_user()
my_bool STDCALL mysql_change_user (MYSQL * mysql, const char * user, const char * passwd, const char * db)
Definition at line 343 of file libmysql.c.
 {
   int rc;
   CHARSET_INFO *saved_cs= mysql->charset;
   char *saved_user= mysql->user;
   char *saved_passwd= mysql->passwd;
   char *saved_db= mysql->db;
   DBUG_ENTER("mysql_change_user");
   /* Get the connection-default character set. */
   if (mysql_init_character_set(mysql))
   {
     mysql->charset= saved_cs;
     DBUG_RETURN(TRUE);
   }
   /* Use an empty string instead of NULL. */
   mysql->user= (char*)(user ? user : "");
   mysql->passwd= (char*)(passwd ? passwd : "");
   mysql->db= 0;
   rc= run_plugin_auth(mysql, 0, 0, 0, db);
   /*
     The server will close all statements no matter was the attempt
     to change user successful or not.
   */
   mysql_detach_stmt_list(&mysql->stmts, "mysql_change_user");
   if (rc == 0)
   {
     /* Free old connect information */
     my_free(saved_user);
     my_free(saved_passwd);
     my_free(saved_db);
     /* alloc new connect information */
     mysql->user= my_strdup(mysql->user, MYF(MY_WME));
     mysql->passwd= my_strdup(mysql->passwd, MYF(MY_WME));
     mysql->db= db ? my_strdup(db, MYF(MY_WME)) : 0;
   }
   else
   {
     mysql->charset= saved_cs;
     mysql->user= saved_user;
     mysql->passwd= saved_passwd;
     mysql->db= saved_db;
   }
   DBUG_RETURN(rc);
 }
References st_mysql::charset, st_mysql::db, DBUG_ENTER, DBUG_RETURN, my_free(), my_strdup(), MY_WME, MYF, mysql_detach_stmt_list(), mysql_init_character_set(), st_mysql::passwd, run_plugin_auth(), st_mysql::stmts, TRUE, and st_mysql::user.
Referenced by native_password_auth_client(), and old_password_auth_client().
mysql_character_set_name()
const char* STDCALL mysql_character_set_name (MYSQL * mysql)
Definition at line 1064 of file libmysql.c.
 {
   return mysql->charset->csname;
 }
References st_mysql::charset, and charset_info_st::csname.
mysql_commit()
my_bool STDCALL mysql_commit (MYSQL * mysql)
Definition at line 4702 of file libmysql.c.
 {
   DBUG_ENTER("mysql_commit");
   DBUG_RETURN((my_bool) mysql_real_query(mysql, "commit", 6));
 }
References DBUG_ENTER, DBUG_RETURN, and mysql_real_query().
mysql_data_seek()
void STDCALL mysql_data_seek (MYSQL_RES * result, my_ulonglong row)
Definition at line 721 of file libmysql.c.
 {
   MYSQL_ROWS    *tmp=0;
   DBUG_PRINT("info",("mysql_data_seek(%ld)",(long) row));
   if (result->data)
     for (tmp=result->data->data; row-- && tmp ; tmp = tmp->next) ;
   result->current_row=0;
   result->data_cursor = tmp;
 }
References DBUG_PRINT, and st_mysql_rows::next.
mysql_debug()
void STDCALL mysql_debug (const char *debug __attribute__(unused))
Definition at line 269 of file libmysql.c.
 {
 #ifndef DBUG_OFF
   char  *env;
   if (debug)
   {
     DBUG_PUSH(debug);
   }
   else if ((env = getenv("MYSQL_DEBUG")))
   {
     DBUG_PUSH(env);
 #if !defined(_WINVER) && !defined(WINVER)
     puts("\n-------------------------------------------------------");
     puts("MYSQL_DEBUG found. libmysql started with the following:");
     puts(env);
     puts("-------------------------------------------------------\n");
 #else
     {
       char buff[80];
       buff[sizeof(buff)-1]= 0;
       strxnmov(buff,sizeof(buff)-1,"libmysql: ", env, NullS);
       MessageBox((HWND) 0,"Debugging variable MYSQL_DEBUG used",buff,MB_OK);
     }
 #endif
   }
 #endif
 }
References DBUG_PUSH, NullS, and strxnmov().
Referenced by mysql_server_init().
mysql_dump_debug_info()
int STDCALL mysql_dump_debug_info (MYSQL * mysql)
Definition at line 930 of file libmysql.c.
 {
   DBUG_ENTER("mysql_dump_debug_info");
   DBUG_RETURN(simple_command(mysql,COM_DEBUG,0,0,0));
 }
References COM_DEBUG, DBUG_ENTER, DBUG_RETURN, and simple_command.
mysql_embedded()
my_bool STDCALL mysql_embedded (void)
Definition at line 1091 of file libmysql.c.
 {
 #ifdef EMBEDDED_LIBRARY
   return 1;
 #else
   return 0;
 #endif
 }
mysql_eof()
my_bool STDCALL mysql_eof (MYSQL_RES * res)
Definition at line 1002 of file libmysql.c.
 {
   return res->eof;
 }
References st_mysql_res::eof.
mysql_escape_string()
ulong STDCALL mysql_escape_string (char * to, const char * from, ulong length)
Definition at line 1159 of file libmysql.c.
 {
   return (uint) escape_string_for_mysql(default_charset_info, to, 0, from, length);
 }
References default_charset_info, escape_string_for_mysql(), and G3D::length().
mysql_fetch_field()
MYSQL_FIELD* STDCALL mysql_fetch_field (MYSQL_RES * result)
Definition at line 708 of file libmysql.c.
 {
   if (result->current_field >= result->field_count)
     return(NULL);
   return &result->fields[result->current_field++];
 }
References NULL.
mysql_fetch_field_direct()
MYSQL_FIELD* STDCALL mysql_fetch_field_direct (MYSQL_RES * res, uint fieldnr)
Definition at line 1007 of file libmysql.c.
 {
   return &(res)->fields[fieldnr];
 }
mysql_fetch_fields()
MYSQL_FIELD* STDCALL mysql_fetch_fields (MYSQL_RES * res)
Definition at line 1012 of file libmysql.c.
 {
   return (res)->fields;
 }
Referenced by MySQLConnection::_Query(), and PreparedResultSet::PreparedResultSet().
mysql_field_count()
unsigned int STDCALL mysql_field_count (MYSQL * mysql)
Definition at line 1029 of file libmysql.c.
 {
   return mysql->field_count;
 }
References st_mysql::field_count.
Referenced by MySQLConnection::_Query().
mysql_field_seek()
MYSQL_FIELD_OFFSET STDCALL mysql_field_seek (MYSQL_RES * result, MYSQL_FIELD_OFFSET field_offset)
Definition at line 749 of file libmysql.c.
 {
   MYSQL_FIELD_OFFSET return_value=result->current_field;
   result->current_field=field_offset;
   return return_value;
 }
mysql_field_tell()
MYSQL_FIELD_OFFSET STDCALL mysql_field_tell (MYSQL_RES * res)
Definition at line 1022 of file libmysql.c.
 {
   return (res)->current_field;
 }
mysql_get_character_set_info()
void STDCALL mysql_get_character_set_info (MYSQL * mysql, MY_CHARSET_INFO * csinfo)
Definition at line 1069 of file libmysql.c.
 {
   csinfo->number   = mysql->charset->number;
   csinfo->state    = mysql->charset->state;
   csinfo->csname   = mysql->charset->csname;
   csinfo->name     = mysql->charset->name;
   csinfo->comment  = mysql->charset->comment;
   csinfo->mbminlen = mysql->charset->mbminlen;
   csinfo->mbmaxlen = mysql->charset->mbmaxlen;
   if (mysql->options.charset_dir)
     csinfo->dir = mysql->options.charset_dir;
   else
     csinfo->dir = charsets_dir;
 }
References st_mysql::charset, st_mysql_options::charset_dir, charsets_dir, charset_info_st::comment, character_set::comment, charset_info_st::csname, character_set::csname, character_set::dir, charset_info_st::mbmaxlen, character_set::mbmaxlen, charset_info_st::mbminlen, character_set::mbminlen, charset_info_st::name, character_set::name, charset_info_st::number, character_set::number, st_mysql::options, charset_info_st::state, and character_set::state.
mysql_get_client_info()
const char* STDCALL mysql_get_client_info (void)
Definition at line 992 of file libmysql.c.
 {
   return (char*) MYSQL_SERVER_VERSION;
 }
Referenced by DatabaseWorkerPool< T >::DatabaseWorkerPool(), and MySQLConnection::Open().
mysql_get_client_version()
ulong STDCALL mysql_get_client_version (void)
Definition at line 997 of file libmysql.c.
 {
   return MYSQL_VERSION_ID;
 }
Referenced by DatabaseWorkerPool< T >::DatabaseWorkerPool().
mysql_get_host_info()
const char* STDCALL mysql_get_host_info (MYSQL * mysql)
Definition at line 979 of file libmysql.c.
 {
   return(mysql->host_info);
 }
References st_mysql::host_info.
mysql_get_parameters()
MYSQL_PARAMETERS* STDCALL mysql_get_parameters (void)
Definition at line 223 of file libmysql.c.
 {
   return &mysql_internal_parameters;
 }
References mysql_internal_parameters.
mysql_get_proto_info()
uint STDCALL mysql_get_proto_info (MYSQL * mysql)
Definition at line 986 of file libmysql.c.
 {
   return (mysql->protocol_version);
 }
References st_mysql::protocol_version.
mysql_get_server_info()
const char* STDCALL mysql_get_server_info (MYSQL * mysql)
Definition at line 972 of file libmysql.c.
 {
   return((char*) mysql->server_version);
 }
References st_mysql::server_version.
Referenced by MySQLConnection::Open().
mysql_hex_string()
ulong STDCALL mysql_hex_string (char * to, const char * from, ulong length)
Definition at line 1138 of file libmysql.c.
 {
   char *to0= to;
   const char *end;
   for (end= from + length; from < end; from++)
   {
     *to++= _dig_vec_upper[((unsigned char) *from) >> 4];
     *to++= _dig_vec_upper[((unsigned char) *from) & 0x0F];
   }
   *to= '\0';
   return (ulong) (to-to0);
 }
References _dig_vec_upper, and G3D::length().
mysql_info()
const char* STDCALL mysql_info (MYSQL * mysql)
Definition at line 1054 of file libmysql.c.
 {
   return mysql->info;
 }
References st_mysql::info.
mysql_insert_id()
my_ulonglong STDCALL mysql_insert_id (MYSQL * mysql)
Definition at line 1039 of file libmysql.c.
 {
   return mysql->insert_id;
 }
References st_mysql::insert_id.
mysql_kill()
int STDCALL mysql_kill (MYSQL * mysql, ulong pid)
Definition at line 910 of file libmysql.c.
 {
   uchar buff[4];
   DBUG_ENTER("mysql_kill");
   int4store(buff,pid);
   DBUG_RETURN(simple_command(mysql,COM_PROCESS_KILL,buff,sizeof(buff),0));
 }
References COM_PROCESS_KILL, DBUG_ENTER, DBUG_RETURN, int4store, and simple_command.
mysql_list_dbs()
MYSQL_RES* STDCALL mysql_list_dbs (MYSQL * mysql, const char * wild)
Definition at line 762 of file libmysql.c.
 {
   char buff[255];
   DBUG_ENTER("mysql_list_dbs");
   append_wild(strmov(buff,"show databases"),buff+sizeof(buff),wild);
   if (mysql_query(mysql,buff))
     DBUG_RETURN(0);
   DBUG_RETURN (mysql_store_result(mysql));
 }
References append_wild(), DBUG_ENTER, DBUG_RETURN, mysql_query(), mysql_store_result(), and strmov().
mysql_list_fields()
MYSQL_RES* STDCALL mysql_list_fields (MYSQL * mysql, const char * table, const char * wild)
Definition at line 813 of file libmysql.c.
 {
   MYSQL_RES   *result;
   MYSQL_FIELD *fields;
   char       buff[258],*end;
   DBUG_ENTER("mysql_list_fields");
   DBUG_PRINT("enter",("table: '%s'  wild: '%s'",table,wild ? wild : ""));
   end=strmake(strmake(buff, table,128)+1,wild ? wild : "",128);
   free_old_query(mysql);
   if (simple_command(mysql, COM_FIELD_LIST, (uchar*) buff,
                      (ulong) (end-buff), 1) ||
       !(fields= (*mysql->methods->list_fields)(mysql)))
     DBUG_RETURN(NULL);
   if (!(result = (MYSQL_RES *) my_malloc(sizeof(MYSQL_RES),
                      MYF(MY_WME | MY_ZEROFILL))))
     DBUG_RETURN(NULL);
   result->methods= mysql->methods;
   result->field_alloc=mysql->field_alloc;
   mysql->fields=0;
   result->field_count = mysql->field_count;
   result->fields= fields;
   result->eof=1;
   DBUG_RETURN(result);
 }
References COM_FIELD_LIST, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql::field_alloc, st_mysql::field_count, st_mysql::fields, free_old_query(), st_mysql_methods::list_fields, st_mysql::methods, my_malloc(), MY_WME, MY_ZEROFILL, MYF, NULL, simple_command, and strmake().
mysql_list_processes()
MYSQL_RES* STDCALL mysql_list_processes (MYSQL * mysql)
Definition at line 844 of file libmysql.c.
 {
   MYSQL_DATA *fields;
   uint field_count;
   uchar *pos;
   DBUG_ENTER("mysql_list_processes");
   LINT_INIT(fields);
   if (simple_command(mysql,COM_PROCESS_INFO,0,0,0))
     DBUG_RETURN(0);
   free_old_query(mysql);
   pos=(uchar*) mysql->net.read_pos;
   field_count=(uint) net_field_length(&pos);
   if (!(fields = (*mysql->methods->read_rows)(mysql,(MYSQL_FIELD*) 0,
                           protocol_41(mysql) ? 7 : 5)))
     DBUG_RETURN(NULL);
   if (!(mysql->fields=unpack_fields(fields,&mysql->field_alloc,field_count,0,
                     mysql->server_capabilities)))
     DBUG_RETURN(0);
   mysql->status=MYSQL_STATUS_GET_RESULT;
   mysql->field_count=field_count;
   DBUG_RETURN(mysql_store_result(mysql));
 }
References COM_PROCESS_INFO, DBUG_ENTER, DBUG_RETURN, st_mysql::field_alloc, st_mysql::field_count, st_mysql::fields, free_old_query(), LINT_INIT, st_mysql::methods, MYSQL_STATUS_GET_RESULT, mysql_store_result(), st_mysql::net, net_field_length(), NULL, pos(), protocol_41, st_net::read_pos, st_mysql_methods::read_rows, st_mysql::server_capabilities, simple_command, st_mysql::status, and unpack_fields().
mysql_list_tables()
MYSQL_RES* STDCALL mysql_list_tables (MYSQL * mysql, const char * wild)
Definition at line 780 of file libmysql.c.
 {
   char buff[255];
   DBUG_ENTER("mysql_list_tables");
   append_wild(strmov(buff,"show tables"),buff+sizeof(buff),wild);
   if (mysql_query(mysql,buff))
     DBUG_RETURN(0);
   DBUG_RETURN (mysql_store_result(mysql));
 }
References append_wild(), DBUG_ENTER, DBUG_RETURN, mysql_query(), mysql_store_result(), and strmov().
mysql_more_results()
my_bool STDCALL mysql_more_results (MYSQL * mysql)
Definition at line 4743 of file libmysql.c.
 {
   my_bool res;
   DBUG_ENTER("mysql_more_results");
   res= ((mysql->server_status & SERVER_MORE_RESULTS_EXISTS) ? 1: 0);
   DBUG_PRINT("exit",("More results exists ? %d", res));
   DBUG_RETURN(res);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, SERVER_MORE_RESULTS_EXISTS, and st_mysql::server_status.
Referenced by MySQLConnection::Query().
mysql_next_result()
int STDCALL mysql_next_result (MYSQL * mysql)
Definition at line 4757 of file libmysql.c.
 {
   DBUG_ENTER("mysql_next_result");
   if (mysql->status != MYSQL_STATUS_READY)
   {
     set_mysql_error(mysql, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate);
     DBUG_RETURN(1);
   }
   net_clear_error(&mysql->net);
   mysql->affected_rows= ~(my_ulonglong) 0;
   if (mysql->server_status & SERVER_MORE_RESULTS_EXISTS)
     DBUG_RETURN((*mysql->methods->next_result)(mysql));
   DBUG_RETURN(-1);              /* No more results */
 }
References st_mysql::affected_rows, CR_COMMANDS_OUT_OF_SYNC, DBUG_ENTER, DBUG_RETURN, st_mysql::methods, MYSQL_STATUS_READY, st_mysql::net, net_clear_error(), st_mysql_methods::next_result, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_mysql_error(), st_mysql::status, and unknown_sqlstate.
Referenced by CLI_MYSQL_REAL_CONNECT(), mysql_stmt_next_result(), and MySQLConnection::Query().
mysql_ping()
int STDCALL mysql_ping (MYSQL * mysql)
Definition at line 960 of file libmysql.c.
 {
   int res;
   DBUG_ENTER("mysql_ping");
   res= simple_command(mysql,COM_PING,0,0,0);
   if (res == CR_SERVER_LOST && mysql->reconnect)
     res= simple_command(mysql,COM_PING,0,0,0);
   DBUG_RETURN(res);
 }
References COM_PING, CR_SERVER_LOST, DBUG_ENTER, DBUG_RETURN, st_mysql::reconnect, and simple_command.
Referenced by MySQLConnection::Ping().
mysql_query()
int STDCALL mysql_query (MYSQL * mysql, const char * query)
Definition at line 697 of file libmysql.c.
 {
   return mysql_real_query(mysql,query, (uint) strlen(query));
 }
References mysql_real_query().
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), mysql_list_dbs(), and mysql_list_tables().
mysql_read_query_result()
my_bool STDCALL mysql_read_query_result (MYSQL * mysql)
Definition at line 4828 of file libmysql.c.
 {
   return (*mysql->methods->read_query_result)(mysql);
 }
References st_mysql::methods, and st_mysql_methods::read_query_result.
mysql_real_escape_string()
ulong STDCALL mysql_real_escape_string (MYSQL * mysql, char * to, const char * from, ulong length)
Definition at line 1165 of file libmysql.c.
 {
   if (mysql->server_status & SERVER_STATUS_NO_BACKSLASH_ESCAPES)
     return (uint) escape_quotes_for_mysql(mysql->charset, to, 0, from, length);
   return (uint) escape_string_for_mysql(mysql->charset, to, 0, from, length);
 }
References st_mysql::charset, escape_quotes_for_mysql(), escape_string_for_mysql(), G3D::length(), st_mysql::server_status, and SERVER_STATUS_NO_BACKSLASH_ESCAPES.
Referenced by MySQLConnection::EscapeString().
mysql_refresh()
int STDCALL mysql_refresh (MYSQL * mysql, uint options)
Definition at line 900 of file libmysql.c.
 {
   uchar bits[1];
   DBUG_ENTER("mysql_refresh");
   bits[0]= (uchar) options;
   DBUG_RETURN(simple_command(mysql, COM_REFRESH, bits, 1, 0));
 }
References G3D::bits(), COM_REFRESH, DBUG_ENTER, DBUG_RETURN, and simple_command.
mysql_rollback()
my_bool STDCALL mysql_rollback (MYSQL * mysql)
Definition at line 4712 of file libmysql.c.
 {
   DBUG_ENTER("mysql_rollback");
   DBUG_RETURN((my_bool) mysql_real_query(mysql, "rollback", 8));
 }
References DBUG_ENTER, DBUG_RETURN, and mysql_real_query().
mysql_row_seek()
MYSQL_ROW_OFFSET STDCALL mysql_row_seek (MYSQL_RES * result, MYSQL_ROW_OFFSET row)
Definition at line 739 of file libmysql.c.
 {
   MYSQL_ROW_OFFSET return_value=result->data_cursor;
   result->current_row= 0;
   result->data_cursor= row;
   return return_value;
 }
mysql_row_tell()
MYSQL_ROW_OFFSET STDCALL mysql_row_tell (MYSQL_RES * res)
Definition at line 1017 of file libmysql.c.
 {
   return res->data_cursor;
 }
References st_mysql_res::data_cursor.
mysql_server_end()
void STDCALL mysql_server_end (void)
Definition at line 193 of file libmysql.c.
 {
   if (!mysql_client_init)
     return;
   mysql_client_plugin_deinit();
 #ifdef EMBEDDED_LIBRARY
   end_embedded_server();
 #endif
   finish_client_errs();
   vio_end();
   /* If library called my_init(), free memory allocated by it */
   if (!org_my_init_done)
   {
     my_end(0);
   }
   else
   {
     free_charsets();
     mysql_thread_end();
   }
   mysql_client_init= org_my_init_done= 0;
 }
References finish_client_errs(), free_charsets(), my_end(), mysql_client_init, mysql_client_plugin_deinit(), mysql_thread_end(), org_my_init_done, and vio_end().
mysql_server_init()
int STDCALL mysql_server_init (int argc __attribute__(unused), char **argv __attribute__(unused), char **groups __attribute__(unused))
Definition at line 116 of file libmysql.c.
 {
   int result= 0;
   if (!mysql_client_init)
   {
     mysql_client_init=1;
     org_my_init_done=my_init_done;
     if (my_init())              /* Will init threads */
       return 1;
     init_client_errs();
     if (mysql_client_plugin_init())
       return 1;
     if (!mysql_port)
     {
       char *env;
       struct servent *serv_ptr __attribute__((unused));
       mysql_port = MYSQL_PORT;
       /*
         if builder specifically requested a default port, use that
         (even if it coincides with our factory default).
         only if they didn't do we check /etc/services (and, failing
         on that, fall back to the factory default of 3306).
         either default can be overridden by the environment variable
         MYSQL_TCP_PORT, which in turn can be overridden with command
         line options.
       */
 #if MYSQL_PORT_DEFAULT == 0
       if ((serv_ptr= getservbyname("mysql", "tcp")))
         mysql_port= (uint) ntohs((ushort) serv_ptr->s_port);
 #endif
       if ((env= getenv("MYSQL_TCP_PORT")))
         mysql_port=(uint) atoi(env);
     }
     if (!mysql_unix_port)
     {
       char *env;
 #ifdef __WIN__
       mysql_unix_port = (char*) MYSQL_NAMEDPIPE;
 #else
       mysql_unix_port = (char*) MYSQL_UNIX_ADDR;
 #endif
       if ((env = getenv("MYSQL_UNIX_PORT")))
     mysql_unix_port = env;
     }
     mysql_debug(NullS);
 #if defined(SIGPIPE) && !defined(__WIN__)
     (void) signal(SIGPIPE, SIG_IGN);
 #endif
 #ifdef EMBEDDED_LIBRARY
     if (argc > -1)
        result= init_embedded_server(argc, argv, groups);
 #endif
   }
   else
     result= (int)my_thread_init();         /* Init if new thread */
   return result;
 }
References __attribute__, init_client_errs(), my_init(), my_init_done, my_thread_init(), mysql_client_init, mysql_client_plugin_init(), mysql_debug(), mysql_port, mysql_unix_port, NullS, and org_my_init_done.
mysql_set_local_infile_default()
void mysql_set_local_infile_default (MYSQL * mysql)
Definition at line 682 of file libmysql.c.
 {
   mysql->options.local_infile_init=  default_local_infile_init;
   mysql->options.local_infile_read=  default_local_infile_read;
   mysql->options.local_infile_end=   default_local_infile_end;
   mysql->options.local_infile_error= default_local_infile_error;
 }
References default_local_infile_end(), default_local_infile_error(), default_local_infile_init(), default_local_infile_read(), st_mysql_options::local_infile_end, st_mysql_options::local_infile_error, st_mysql_options::local_infile_init, st_mysql_options::local_infile_read, and st_mysql::options.
Referenced by handle_local_infile().
mysql_set_local_infile_handler()
void mysql_set_local_infile_handler (MYSQL * mysql, int(*)(void **, const char *, void *) local_infile_init, int(*)(void *, char *, uint) local_infile_read, void(*)(void *) local_infile_end, int(*)(void *, char *, uint) local_infile_error, void * userdata)
Definition at line 666 of file libmysql.c.
 {
   mysql->options.local_infile_init=  local_infile_init;
   mysql->options.local_infile_read=  local_infile_read;
   mysql->options.local_infile_end=   local_infile_end;
   mysql->options.local_infile_error= local_infile_error;
   mysql->options.local_infile_userdata = userdata;
 }
References st_mysql_options::local_infile_end, st_mysql_options::local_infile_error, st_mysql_options::local_infile_init, st_mysql_options::local_infile_read, st_mysql_options::local_infile_userdata, and st_mysql::options.
mysql_set_server_option()
int STDCALL mysql_set_server_option (MYSQL * mysql, enum enum_mysql_set_option option)
Definition at line 920 of file libmysql.c.
 {
   uchar buff[2];
   DBUG_ENTER("mysql_set_server_option");
   int2store(buff, (uint) option);
   DBUG_RETURN(simple_command(mysql, COM_SET_OPTION, buff, sizeof(buff), 0));
 }
References COM_SET_OPTION, DBUG_ENTER, DBUG_RETURN, int2store, and simple_command.
mysql_shutdown()
int STDCALL mysql_shutdown (MYSQL * mysql, enum mysql_enum_shutdown_level shutdown_level)
Definition at line 890 of file libmysql.c.
 {
   uchar level[1];
   DBUG_ENTER("mysql_shutdown");
   level[0]= (uchar) shutdown_level;
   DBUG_RETURN(simple_command(mysql, COM_SHUTDOWN, level, 1, 0));
 }
References COM_SHUTDOWN, DBUG_ENTER, DBUG_RETURN, and simple_command.
mysql_sqlstate()
const char* STDCALL mysql_sqlstate (MYSQL * mysql)
Definition at line 1044 of file libmysql.c.
 {
   return mysql ? mysql->net.sqlstate : cant_connect_sqlstate;
 }
References cant_connect_sqlstate, st_mysql::net, and st_net::sqlstate.
mysql_stat()
const char* STDCALL mysql_stat (MYSQL * mysql)
Definition at line 950 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stat");
   if (simple_command(mysql,COM_STATISTICS,0,0,0))
     DBUG_RETURN(mysql->net.last_error);
   DBUG_RETURN((*mysql->methods->read_statistics)(mysql));
 }
References COM_STATISTICS, DBUG_ENTER, DBUG_RETURN, st_net::last_error, st_mysql::methods, st_mysql::net, st_mysql_methods::read_statistics, and simple_command.
mysql_stmt_affected_rows()
my_ulonglong STDCALL mysql_stmt_affected_rows (MYSQL_STMT * stmt)
Definition at line 2527 of file libmysql.c.
 {
   return stmt->affected_rows;
 }
References st_mysql_stmt::affected_rows.
mysql_stmt_attr_get()
my_bool STDCALL mysql_stmt_attr_get (MYSQL_STMT * stmt, enum enum_stmt_attr_type attr_type, void * value)
Definition at line 2348 of file libmysql.c.
 {
   switch (attr_type) {
   case STMT_ATTR_UPDATE_MAX_LENGTH:
     *(my_bool*) value= stmt->update_max_length;
     break;
   case STMT_ATTR_CURSOR_TYPE:
     *(ulong*) value= stmt->flags;
     break;
   case STMT_ATTR_PREFETCH_ROWS:
     *(ulong*) value= stmt->prefetch_rows;
     break;
   default:
     return TRUE;
   }
   return FALSE;
 }
References FALSE, st_mysql_stmt::flags, st_mysql_stmt::prefetch_rows, STMT_ATTR_CURSOR_TYPE, STMT_ATTR_PREFETCH_ROWS, STMT_ATTR_UPDATE_MAX_LENGTH, TRUE, and st_mysql_stmt::update_max_length.
mysql_stmt_attr_set()
my_bool STDCALL mysql_stmt_attr_set (MYSQL_STMT * stmt, enum enum_stmt_attr_type attr_type, const void * value)
Definition at line 2313 of file libmysql.c.
 {
   switch (attr_type) {
   case STMT_ATTR_UPDATE_MAX_LENGTH:
     stmt->update_max_length= value ? *(const my_bool*) value : 0;
     break;
   case STMT_ATTR_CURSOR_TYPE:
   {
     ulong cursor_type;
     cursor_type= value ? *(ulong*) value : 0UL;
     if (cursor_type > (ulong) CURSOR_TYPE_READ_ONLY)
       goto err_not_implemented;
     stmt->flags= cursor_type;
     break;
   }
   case STMT_ATTR_PREFETCH_ROWS:
   {
     ulong prefetch_rows= value ? *(ulong*) value : DEFAULT_PREFETCH_ROWS;
     if (value == 0)
       return TRUE;
     stmt->prefetch_rows= prefetch_rows;
     break;
   }
   default:
     goto err_not_implemented;
   }
   return FALSE;
 err_not_implemented:
   set_stmt_error(stmt, CR_NOT_IMPLEMENTED, unknown_sqlstate, NULL);
   return TRUE;
 }
References CR_NOT_IMPLEMENTED, CURSOR_TYPE_READ_ONLY, DEFAULT_PREFETCH_ROWS, FALSE, st_mysql_stmt::flags, NULL, st_mysql_stmt::prefetch_rows, set_stmt_error(), STMT_ATTR_CURSOR_TYPE, STMT_ATTR_PREFETCH_ROWS, STMT_ATTR_UPDATE_MAX_LENGTH, TRUE, unknown_sqlstate, and st_mysql_stmt::update_max_length.
Referenced by MySQLPreparedStatement::MySQLPreparedStatement().
mysql_stmt_bind_param()
my_bool STDCALL mysql_stmt_bind_param (MYSQL_STMT * stmt, MYSQL_BIND * my_bind)
Definition at line 2738 of file libmysql.c.
 {
   uint count=0;
   MYSQL_BIND *param, *end;
   DBUG_ENTER("mysql_stmt_bind_param");
   if (!stmt->param_count)
   {
     if ((int) stmt->state < (int) MYSQL_STMT_PREPARE_DONE)
     {
       set_stmt_error(stmt, CR_NO_PREPARE_STMT, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     DBUG_RETURN(0);
   }
   /* Allocated on prepare */
   memcpy((char*) stmt->params, (char*) my_bind,
      sizeof(MYSQL_BIND) * stmt->param_count);
   for (param= stmt->params, end= param+stmt->param_count;
        param < end ;
        param++)
   {
     param->param_number= count++;
     param->long_data_used= 0;
     /* If param->is_null is not set, then the value can never be NULL */
     if (!param->is_null)
       param->is_null= &int_is_null_false;
     /* Setup data copy functions for the different supported types */
     switch (param->buffer_type) {
     case MYSQL_TYPE_NULL:
       param->is_null= &int_is_null_true;
       break;
     case MYSQL_TYPE_TINY:
       /* Force param->length as this is fixed for this type */
       param->length= &param->buffer_length;
       param->buffer_length= 1;
       param->store_param_func= store_param_tinyint;
       break;
     case MYSQL_TYPE_SHORT:
       param->length= &param->buffer_length;
       param->buffer_length= 2;
       param->store_param_func= store_param_short;
       break;
     case MYSQL_TYPE_LONG:
       param->length= &param->buffer_length;
       param->buffer_length= 4;
       param->store_param_func= store_param_int32;
       break;
     case MYSQL_TYPE_LONGLONG:
       param->length= &param->buffer_length;
       param->buffer_length= 8;
       param->store_param_func= store_param_int64;
       break;
     case MYSQL_TYPE_FLOAT:
       param->length= &param->buffer_length;
       param->buffer_length= 4;
       param->store_param_func= store_param_float;
       break;
     case MYSQL_TYPE_DOUBLE:
       param->length= &param->buffer_length;
       param->buffer_length= 8;
       param->store_param_func= store_param_double;
       break;
     case MYSQL_TYPE_TIME:
       param->store_param_func= store_param_time;
       param->buffer_length= MAX_TIME_REP_LENGTH;
       break;
     case MYSQL_TYPE_DATE:
       param->store_param_func= store_param_date;
       param->buffer_length= MAX_DATE_REP_LENGTH;
       break;
     case MYSQL_TYPE_DATETIME:
     case MYSQL_TYPE_TIMESTAMP:
       param->store_param_func= store_param_datetime;
       param->buffer_length= MAX_DATETIME_REP_LENGTH;
       break;
     case MYSQL_TYPE_TINY_BLOB:
     case MYSQL_TYPE_MEDIUM_BLOB:
     case MYSQL_TYPE_LONG_BLOB:
     case MYSQL_TYPE_BLOB:
     case MYSQL_TYPE_VARCHAR:
     case MYSQL_TYPE_VAR_STRING:
     case MYSQL_TYPE_STRING:
     case MYSQL_TYPE_DECIMAL:
     case MYSQL_TYPE_NEWDECIMAL:
       param->store_param_func= store_param_str;
       /*
         For variable length types user must set either length or
         buffer_length.
       */
       break;
     default:
       strmov(stmt->sqlstate, unknown_sqlstate);
       sprintf(stmt->last_error,
           ER(stmt->last_errno= CR_UNSUPPORTED_PARAM_TYPE),
           param->buffer_type, count);
       DBUG_RETURN(1);
     }
     /*
       If param->length is not given, change it to point to buffer_length.
       This way we can always use *param->length to get the length of data
     */
     if (!param->length)
       param->length= &param->buffer_length;
   }
   /* We have to send/resend type information to MySQL */
   stmt->send_types_to_server= TRUE;
   stmt->bind_param_done= TRUE;
   DBUG_RETURN(0);
 }
References st_mysql_stmt::bind_param_done, st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, count(), CR_NO_PREPARE_STMT, CR_UNSUPPORTED_PARAM_TYPE, DBUG_ENTER, DBUG_RETURN, ER, int_is_null_false, int_is_null_true, st_mysql_bind::is_null, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, st_mysql_bind::length, st_mysql_bind::long_data_used, MAX_DATE_REP_LENGTH, MAX_DATETIME_REP_LENGTH, MAX_TIME_REP_LENGTH, memcpy, MYSQL_STMT_PREPARE_DONE, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NEWDECIMAL, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_STRING, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, MYSQL_TYPE_VARCHAR, NULL, st_mysql_stmt::param_count, st_mysql_bind::param_number, st_mysql_stmt::params, st_mysql_stmt::send_types_to_server, set_stmt_error(), sprintf(), st_mysql_stmt::sqlstate, st_mysql_stmt::state, store_param_date(), store_param_datetime(), store_param_double(), store_param_float(), st_mysql_bind::store_param_func, store_param_int32(), store_param_int64(), store_param_short(), store_param_str(), store_param_time(), store_param_tinyint(), strmov(), TRUE, and unknown_sqlstate.
Referenced by MySQLConnection::_Query(), and MySQLConnection::Execute().
mysql_stmt_bind_result()
my_bool STDCALL mysql_stmt_bind_result (MYSQL_STMT * stmt, MYSQL_BIND * my_bind)
Definition at line 3993 of file libmysql.c.
 {
   MYSQL_BIND *param, *end;
   MYSQL_FIELD *field;
   ulong       bind_count= stmt->field_count;
   uint        param_count= 0;
   DBUG_ENTER("mysql_stmt_bind_result");
   DBUG_PRINT("enter",("field_count: %lu", bind_count));
   if (!bind_count)
   {
     int errorcode= (int) stmt->state < (int) MYSQL_STMT_PREPARE_DONE ?
                    CR_NO_PREPARE_STMT : CR_NO_STMT_METADATA;
     set_stmt_error(stmt, errorcode, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   /*
     We only need to check that stmt->field_count - if it is not null
     stmt->bind was initialized in mysql_stmt_prepare
     stmt->bind overlaps with bind if mysql_stmt_bind_param
     is called from mysql_stmt_store_result.
   */
   if (stmt->bind != my_bind)
     memcpy((char*) stmt->bind, (char*) my_bind,
            sizeof(MYSQL_BIND) * bind_count);
   for (param= stmt->bind, end= param + bind_count, field= stmt->fields ;
        param < end ;
        param++, field++)
   {
     DBUG_PRINT("info",("buffer_type: %u  field_type: %u",
                        (uint) param->buffer_type, (uint) field->type));
     /*
       Set param->is_null to point to a dummy variable if it's not set.
       This is to make the execute code easier
     */
     if (!param->is_null)
       param->is_null= &param->is_null_value;
     if (!param->length)
       param->length= &param->length_value;
     if (!param->error)
       param->error= &param->error_value;
     param->param_number= param_count++;
     param->offset= 0;
     if (setup_one_fetch_function(param, field))
     {
       strmov(stmt->sqlstate, unknown_sqlstate);
       sprintf(stmt->last_error,
               ER(stmt->last_errno= CR_UNSUPPORTED_PARAM_TYPE),
               field->type, param_count);
       DBUG_RETURN(1);
     }
   }
   stmt->bind_result_done= BIND_RESULT_DONE;
   if (stmt->mysql->options.report_data_truncation)
     stmt->bind_result_done|= REPORT_DATA_TRUNCATION;
   DBUG_RETURN(0);
 }
References st_mysql_stmt::bind, st_mysql_stmt::bind_result_done, BIND_RESULT_DONE, st_mysql_bind::buffer_type, CR_NO_PREPARE_STMT, CR_NO_STMT_METADATA, CR_UNSUPPORTED_PARAM_TYPE, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER, st_mysql_bind::error, st_mysql_bind::error_value, st_mysql_stmt::field_count, st_mysql_stmt::fields, st_mysql_bind::is_null, st_mysql_bind::is_null_value, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, st_mysql_bind::length, st_mysql_bind::length_value, memcpy, st_mysql_stmt::mysql, MYSQL_STMT_PREPARE_DONE, NULL, st_mysql_bind::offset, st_mysql::options, st_mysql_bind::param_number, st_mysql_options::report_data_truncation, REPORT_DATA_TRUNCATION, set_stmt_error(), setup_one_fetch_function(), sprintf(), st_mysql_stmt::sqlstate, st_mysql_stmt::state, strmov(), st_mysql_field::type, and unknown_sqlstate.
Referenced by mysql_stmt_store_result(), and PreparedResultSet::PreparedResultSet().
mysql_stmt_close()
my_bool STDCALL mysql_stmt_close (MYSQL_STMT * stmt)
Definition at line 4600 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   int rc= 0;
   DBUG_ENTER("mysql_stmt_close");
   free_root(&stmt->result.alloc, MYF(0));
   free_root(&stmt->mem_root, MYF(0));
   if (mysql)
   {
     mysql->stmts= list_delete(mysql->stmts, &stmt->list);
     /*
       Clear NET error state: if the following commands come through
       successfully, connection will still be usable for other commands.
     */
     net_clear_error(&mysql->net);
     if ((int) stmt->state > (int) MYSQL_STMT_INIT_DONE)
     {
       uchar buff[MYSQL_STMT_HEADER];             /* 4 bytes - stmt id */
       if (mysql->unbuffered_fetch_owner == &stmt->unbuffered_fetch_cancelled)
         mysql->unbuffered_fetch_owner= 0;
       if (mysql->status != MYSQL_STATUS_READY)
       {
         /*
           Flush result set of the connection. If it does not belong
           to this statement, set a warning.
         */
         (*mysql->methods->flush_use_result)(mysql, TRUE);
         if (mysql->unbuffered_fetch_owner)
           *mysql->unbuffered_fetch_owner= TRUE;
         mysql->status= MYSQL_STATUS_READY;
       }
       int4store(buff, stmt->stmt_id);
       if ((rc= stmt_command(mysql, COM_STMT_CLOSE, buff, 4, stmt)))
       {
         set_stmt_errmsg(stmt, &mysql->net);
       }
     }
   }
   my_free(stmt);
   DBUG_RETURN(test(rc));
 }
References st_mysql_data::alloc, COM_STMT_CLOSE, DBUG_ENTER, DBUG_RETURN, st_mysql_methods::flush_use_result, free_root(), int4store, st_mysql_stmt::list, list_delete(), st_mysql_stmt::mem_root, st_mysql::methods, my_free(), MYF, st_mysql_stmt::mysql, MYSQL_STATUS_READY, MYSQL_STMT_HEADER, MYSQL_STMT_INIT_DONE, st_mysql::net, net_clear_error(), st_mysql_stmt::result, set_stmt_errmsg(), st_mysql_stmt::state, st_mysql::status, stmt_command, st_mysql_stmt::stmt_id, st_mysql::stmts, test, TRUE, st_mysql_stmt::unbuffered_fetch_cancelled, and st_mysql::unbuffered_fetch_owner.
Referenced by MySQLConnection::PrepareStatement(), and MySQLPreparedStatement::~MySQLPreparedStatement().
mysql_stmt_data_seek()
void STDCALL mysql_stmt_data_seek (MYSQL_STMT * stmt, my_ulonglong row)
Definition at line 4471 of file libmysql.c.
 {
   MYSQL_ROWS *tmp= stmt->result.data;
   DBUG_ENTER("mysql_stmt_data_seek");
   DBUG_PRINT("enter",("row id to seek: %ld",(long) row));
   for (; tmp && row; --row, tmp= tmp->next)
     ;
   stmt->data_cursor= tmp;
   if (!row && tmp)
   {
        /*  Rewind the counter */
     stmt->read_row_func= stmt_read_row_buffered;
     stmt->state= MYSQL_STMT_EXECUTE_DONE;
   }
   DBUG_VOID_RETURN;
 }
References st_mysql_data::data, st_mysql_stmt::data_cursor, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, MYSQL_STMT_EXECUTE_DONE, st_mysql_rows::next, st_mysql_stmt::read_row_func, st_mysql_stmt::result, st_mysql_stmt::state, and stmt_read_row_buffered().
mysql_stmt_errno()
uint STDCALL mysql_stmt_errno (MYSQL_STMT * stmt)
Definition at line 4671 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_errno");
   DBUG_RETURN(stmt->last_errno);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::last_errno.
mysql_stmt_error()
const char* STDCALL mysql_stmt_error (MYSQL_STMT * stmt)
Definition at line 4687 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_error");
   DBUG_RETURN(stmt->last_error);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::last_error.
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), PreparedResultSet::PreparedResultSet(), and MySQLConnection::PrepareStatement().
mysql_stmt_execute()
int STDCALL mysql_stmt_execute (MYSQL_STMT * stmt)
Definition at line 2484 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   DBUG_ENTER("mysql_stmt_execute");
   if (!mysql)
   {
     /* Error is already set in mysql_detatch_stmt_list */
     DBUG_RETURN(1);
   }
   if (reset_stmt_handle(stmt, RESET_STORE_RESULT | RESET_CLEAR_ERROR))
     DBUG_RETURN(1);
   /*
     No need to check for stmt->state: if the statement wasn't
     prepared we'll get 'unknown statement handler' error from server.
   */
   if (mysql->methods->stmt_execute(stmt))
     DBUG_RETURN(1);
   stmt->state= MYSQL_STMT_EXECUTE_DONE;
   if (mysql->field_count)
   {
     reinit_result_set_metadata(stmt);
     prepare_to_fetch_result(stmt);
   }
   DBUG_RETURN(test(stmt->last_errno));
 }
References DBUG_ENTER, DBUG_RETURN, st_mysql::field_count, st_mysql_stmt::last_errno, st_mysql::methods, st_mysql_stmt::mysql, MYSQL_STMT_EXECUTE_DONE, prepare_to_fetch_result(), reinit_result_set_metadata(), RESET_CLEAR_ERROR, reset_stmt_handle(), RESET_STORE_RESULT, st_mysql_stmt::state, st_mysql_methods::stmt_execute, and test.
Referenced by MySQLConnection::_Query(), and MySQLConnection::Execute().
mysql_stmt_fetch()
int STDCALL mysql_stmt_fetch (MYSQL_STMT * stmt)
Definition at line 4140 of file libmysql.c.
 {
   int rc;
   uchar *row;
   DBUG_ENTER("mysql_stmt_fetch");
   if ((rc= (*stmt->read_row_func)(stmt, &row)) ||
       ((rc= stmt_fetch_row(stmt, row)) && rc != MYSQL_DATA_TRUNCATED))
   {
     stmt->state= MYSQL_STMT_PREPARE_DONE;       /* XXX: this is buggy */
     stmt->read_row_func= (rc == MYSQL_NO_DATA) ?
       stmt_read_row_no_data : stmt_read_row_no_result_set;
   }
   else
   {
     /* This is to know in mysql_stmt_fetch_column that data was fetched */
     stmt->state= MYSQL_STMT_FETCH_DONE;
   }
   DBUG_RETURN(rc);
 }
References DBUG_ENTER, DBUG_RETURN, MYSQL_DATA_TRUNCATED, MYSQL_NO_DATA, MYSQL_STMT_FETCH_DONE, MYSQL_STMT_PREPARE_DONE, st_mysql_stmt::read_row_func, st_mysql_stmt::state, stmt_fetch_row(), stmt_read_row_no_data(), and stmt_read_row_no_result_set().
Referenced by PreparedResultSet::_NextRow().
mysql_stmt_fetch_column()
int STDCALL mysql_stmt_fetch_column (MYSQL_STMT * stmt, MYSQL_BIND * my_bind, uint column, ulong offset)
Definition at line 4178 of file libmysql.c.
 {
   MYSQL_BIND *param= stmt->bind+column;
   DBUG_ENTER("mysql_stmt_fetch_column");
   if ((int) stmt->state < (int) MYSQL_STMT_FETCH_DONE)
   {
     set_stmt_error(stmt, CR_NO_DATA, unknown_sqlstate, NULL);
     return 1;
   }
   if (column >= stmt->field_count)
   {
     set_stmt_error(stmt, CR_INVALID_PARAMETER_NO, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (!my_bind->error)
     my_bind->error= &my_bind->error_value;
   *my_bind->error= 0;
   if (param->row_ptr)
   {
     MYSQL_FIELD *field= stmt->fields+column;
     uchar *row= param->row_ptr;
     my_bind->offset= offset;
     if (my_bind->is_null)
       *my_bind->is_null= 0;
     if (my_bind->length) /* Set the length if non char/binary types */
       *my_bind->length= *param->length;
     else
       my_bind->length= &param->length_value;       /* Needed for fetch_result() */
     fetch_result_with_conversion(my_bind, field, &row);
   }
   else
   {
     if (my_bind->is_null)
       *my_bind->is_null= 1;
   }
   DBUG_RETURN(0);
 }
References st_mysql_stmt::bind, CR_INVALID_PARAMETER_NO, CR_NO_DATA, DBUG_ENTER, DBUG_RETURN, st_mysql_bind::error, st_mysql_bind::error_value, fetch_result_with_conversion(), st_mysql_stmt::field_count, st_mysql_stmt::fields, st_mysql_bind::is_null, st_mysql_bind::length, st_mysql_bind::length_value, MYSQL_STMT_FETCH_DONE, NULL, st_mysql_bind::offset, st_mysql_bind::row_ptr, set_stmt_error(), st_mysql_stmt::state, and unknown_sqlstate.
mysql_stmt_field_count()
unsigned int STDCALL mysql_stmt_field_count (MYSQL_STMT * stmt)
Definition at line 2538 of file libmysql.c.
 {
   return stmt->field_count;
 }
References st_mysql_stmt::field_count.
Referenced by MySQLConnection::_Query().
mysql_stmt_free_result()
my_bool STDCALL mysql_stmt_free_result (MYSQL_STMT * stmt)
Definition at line 4575 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_free_result");
   /* Free the client side and close the server side cursor if there is one */
   DBUG_RETURN(reset_stmt_handle(stmt, RESET_LONG_DATA | RESET_STORE_RESULT |
                                 RESET_CLEAR_ERROR));
 }
References DBUG_ENTER, DBUG_RETURN, RESET_CLEAR_ERROR, RESET_LONG_DATA, reset_stmt_handle(), and RESET_STORE_RESULT.
Referenced by PreparedResultSet::PreparedResultSet().
mysql_stmt_init()
MYSQL_STMT* STDCALL mysql_stmt_init (MYSQL * mysql)
Definition at line 1478 of file libmysql.c.
 {
   MYSQL_STMT *stmt;
   DBUG_ENTER("mysql_stmt_init");
   if (!(stmt= (MYSQL_STMT *) my_malloc(sizeof(MYSQL_STMT),
                                        MYF(MY_WME | MY_ZEROFILL))))
   {
     set_mysql_error(mysql, CR_OUT_OF_MEMORY, unknown_sqlstate);
     DBUG_RETURN(0);
   }
   init_alloc_root(&stmt->mem_root, 2048, 2048);
   init_alloc_root(&stmt->result.alloc, 4096, 4096);
   stmt->result.alloc.min_malloc= sizeof(MYSQL_ROWS);
   mysql->stmts= list_add(mysql->stmts, &stmt->list);
   stmt->list.data= stmt;
   stmt->state= MYSQL_STMT_INIT_DONE;
   stmt->mysql= mysql;
   stmt->read_row_func= stmt_read_row_no_result_set;
   stmt->prefetch_rows= DEFAULT_PREFETCH_ROWS;
   strmov(stmt->sqlstate, not_error_sqlstate);
   /* The rest of statement members was bzeroed inside malloc */
   DBUG_RETURN(stmt);
 }
References st_mysql_data::alloc, CR_OUT_OF_MEMORY, st_list::data, DBUG_ENTER, DBUG_RETURN, DEFAULT_PREFETCH_ROWS, init_alloc_root(), st_mysql_stmt::list, list_add(), st_mysql_stmt::mem_root, st_mem_root::min_malloc, my_malloc(), MY_WME, MY_ZEROFILL, MYF, st_mysql_stmt::mysql, MYSQL_STMT_INIT_DONE, not_error_sqlstate, st_mysql_stmt::prefetch_rows, st_mysql_stmt::read_row_func, st_mysql_stmt::result, set_mysql_error(), st_mysql_stmt::sqlstate, st_mysql_stmt::state, stmt_read_row_no_result_set(), st_mysql::stmts, strmov(), and unknown_sqlstate.
Referenced by MySQLConnection::PrepareStatement().
mysql_stmt_insert_id()
my_ulonglong STDCALL mysql_stmt_insert_id (MYSQL_STMT * stmt)
Definition at line 2559 of file libmysql.c.
 {
   return stmt->insert_id;
 }
References st_mysql_stmt::insert_id.
mysql_stmt_next_result()
int STDCALL mysql_stmt_next_result (MYSQL_STMT * stmt)
Definition at line 4777 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   int rc;
   DBUG_ENTER("mysql_stmt_next_result");
   if (!mysql)
     DBUG_RETURN(1);
   if (stmt->last_errno)
     DBUG_RETURN(stmt->last_errno);
   if (mysql->server_status & SERVER_MORE_RESULTS_EXISTS)
   {
     if (reset_stmt_handle(stmt, RESET_STORE_RESULT))
       DBUG_RETURN(1);
   }
   rc= mysql_next_result(mysql);
   if (rc)
   {
     set_stmt_errmsg(stmt, &mysql->net);
     DBUG_RETURN(rc);
   }
   if (mysql->status == MYSQL_STATUS_GET_RESULT)
     mysql->status= MYSQL_STATUS_STATEMENT_GET_RESULT;
   stmt->state= MYSQL_STMT_EXECUTE_DONE;
   stmt->bind_result_done= FALSE;
   if (mysql->field_count)
   {
     alloc_stmt_fields(stmt);
     prepare_to_fetch_result(stmt);
   }
   else
   {
     stmt->field_count= mysql->field_count;
   }
   DBUG_RETURN(0);
 }
References alloc_stmt_fields(), st_mysql_stmt::bind_result_done, DBUG_ENTER, DBUG_RETURN, FALSE, st_mysql::field_count, st_mysql_stmt::field_count, st_mysql_stmt::last_errno, st_mysql_stmt::mysql, mysql_next_result(), MYSQL_STATUS_GET_RESULT, MYSQL_STATUS_STATEMENT_GET_RESULT, MYSQL_STMT_EXECUTE_DONE, st_mysql::net, prepare_to_fetch_result(), reset_stmt_handle(), RESET_STORE_RESULT, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_stmt_errmsg(), st_mysql_stmt::state, and st_mysql::status.
mysql_stmt_num_rows()
my_ulonglong STDCALL mysql_stmt_num_rows (MYSQL_STMT * stmt)
Definition at line 4494 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_num_rows");
   DBUG_RETURN(stmt->result.rows);
 }
References DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::result, and st_mysql_data::rows.
Referenced by MySQLConnection::_Query(), and PreparedResultSet::PreparedResultSet().
mysql_stmt_param_count()
ulong STDCALL mysql_stmt_param_count (MYSQL_STMT * stmt)
Definition at line 2517 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_param_count");
   DBUG_RETURN(stmt->param_count);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::param_count.
Referenced by MySQLPreparedStatement::MySQLPreparedStatement().
mysql_stmt_param_metadata()
MYSQL_RES* STDCALL mysql_stmt_param_metadata (MYSQL_STMT * stmt)
Definition at line 1802 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_param_metadata");
   if (!stmt->param_count)
     DBUG_RETURN(0);
   /*
     TODO: Fix this when server sends the information.
     Till then keep a dummy prototype.
   */
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::param_count.
mysql_stmt_prepare()
int STDCALL mysql_stmt_prepare (MYSQL_STMT * stmt, const char * query, ulong length)
Definition at line 1541 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   DBUG_ENTER("mysql_stmt_prepare");
   if (!mysql)
   {
     /* mysql can be reset in mysql_close called from mysql_reconnect */
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   /*
     Reset the last error in any case: that would clear the statement
     if the previous prepare failed.
   */
   stmt->last_errno= 0;
   stmt->last_error[0]= '\0';
   if ((int) stmt->state > (int) MYSQL_STMT_INIT_DONE)
   {
     /* This is second prepare with another statement */
     uchar buff[MYSQL_STMT_HEADER];               /* 4 bytes - stmt id */
     if (reset_stmt_handle(stmt, RESET_LONG_DATA | RESET_STORE_RESULT))
       DBUG_RETURN(1);
     /*
       These members must be reset for API to
       function in case of error or misuse.
     */
     stmt->bind_param_done= stmt->bind_result_done= FALSE;
     stmt->param_count= stmt->field_count= 0;
     free_root(&stmt->mem_root, MYF(MY_KEEP_PREALLOC));
     int4store(buff, stmt->stmt_id);
     /*
       Close statement in server
       If there was a 'use' result from another statement, or from
       mysql_use_result it won't be freed in mysql_stmt_free_result and
       we should get 'Commands out of sync' here.
     */
     stmt->state= MYSQL_STMT_INIT_DONE;
     if (stmt_command(mysql, COM_STMT_CLOSE, buff, 4, stmt))
     {
       set_stmt_errmsg(stmt, &mysql->net);
       DBUG_RETURN(1);
     }
   }
   if (stmt_command(mysql, COM_STMT_PREPARE, (const uchar*) query, length, stmt))
   {
     set_stmt_errmsg(stmt, &mysql->net);
     DBUG_RETURN(1);
   }
   if ((*mysql->methods->read_prepare_result)(mysql, stmt))
   {
     set_stmt_errmsg(stmt, &mysql->net);
     DBUG_RETURN(1);
   }
   /*
     alloc_root will return valid address even in case when param_count
     and field_count are zero. Thus we should never rely on stmt->bind
     or stmt->params when checking for existence of placeholders or
     result set.
   */
   if (!(stmt->params= (MYSQL_BIND *) alloc_root(&stmt->mem_root,
                         sizeof(MYSQL_BIND)*
                                                 (stmt->param_count +
                                                  stmt->field_count))))
   {
     set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   stmt->bind= stmt->params + stmt->param_count;
   stmt->state= MYSQL_STMT_PREPARE_DONE;
   DBUG_PRINT("info", ("Parameter count: %u", stmt->param_count));
   DBUG_RETURN(0);
 }
References alloc_root(), st_mysql_stmt::bind, st_mysql_stmt::bind_param_done, st_mysql_stmt::bind_result_done, COM_STMT_CLOSE, COM_STMT_PREPARE, CR_OUT_OF_MEMORY, CR_SERVER_LOST, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FALSE, st_mysql_stmt::field_count, free_root(), int4store, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, G3D::length(), st_mysql_stmt::mem_root, st_mysql::methods, MY_KEEP_PREALLOC, MYF, st_mysql_stmt::mysql, MYSQL_STMT_HEADER, MYSQL_STMT_INIT_DONE, MYSQL_STMT_PREPARE_DONE, st_mysql::net, NULL, st_mysql_stmt::param_count, st_mysql_stmt::params, st_mysql_methods::read_prepare_result, RESET_LONG_DATA, reset_stmt_handle(), RESET_STORE_RESULT, set_stmt_errmsg(), set_stmt_error(), st_mysql_stmt::state, stmt_command, st_mysql_stmt::stmt_id, and unknown_sqlstate.
Referenced by MySQLConnection::PrepareStatement().
mysql_stmt_reset()
my_bool STDCALL mysql_stmt_reset (MYSQL_STMT * stmt)
Definition at line 4651 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_reset");
   DBUG_ASSERT(stmt != 0);
   if (!stmt->mysql)
   {
     /* mysql can be reset in mysql_close called from mysql_reconnect */
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   /* Reset the client and server sides of the prepared statement */
   DBUG_RETURN(reset_stmt_handle(stmt,
                                 RESET_SERVER_SIDE | RESET_LONG_DATA |
                                 RESET_CLEAR_ERROR));
 }
References CR_SERVER_LOST, DBUG_ASSERT, DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::mysql, NULL, RESET_CLEAR_ERROR, RESET_LONG_DATA, RESET_SERVER_SIDE, reset_stmt_handle(), set_stmt_error(), and unknown_sqlstate.
mysql_stmt_result_metadata()
MYSQL_RES* STDCALL mysql_stmt_result_metadata (MYSQL_STMT * stmt)
Definition at line 1755 of file libmysql.c.
 {
   MYSQL_RES *result;
   DBUG_ENTER("mysql_stmt_result_metadata");
   /*
     stmt->fields is only defined if stmt->field_count is not null;
     stmt->field_count is initialized in prepare.
   */
   if (!stmt->field_count)
      DBUG_RETURN(0);
   if (!(result=(MYSQL_RES*) my_malloc(sizeof(*result),
                                       MYF(MY_WME | MY_ZEROFILL))))
   {
     set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
     DBUG_RETURN(0);
   }
   result->methods=  stmt->mysql->methods;
   result->eof=      1;                      /* Marker for buffered */
   result->fields=   stmt->fields;
   result->field_count=  stmt->field_count;
   /* The rest of members of 'result' was bzeroed inside malloc */
   DBUG_RETURN(result);
 }
References CR_OUT_OF_MEMORY, DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::field_count, st_mysql_stmt::fields, st_mysql::methods, my_malloc(), MY_WME, MY_ZEROFILL, MYF, st_mysql_stmt::mysql, NULL, set_stmt_error(), and unknown_sqlstate.
Referenced by MySQLConnection::_Query().
mysql_stmt_row_seek()
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_seek (MYSQL_STMT * stmt, MYSQL_ROW_OFFSET row)
Definition at line 4443 of file libmysql.c.
 {
   MYSQL_ROW_OFFSET offset= stmt->data_cursor;
   DBUG_ENTER("mysql_stmt_row_seek");
   stmt->data_cursor= row;
   DBUG_RETURN(offset);
 }
References st_mysql_stmt::data_cursor, DBUG_ENTER, and DBUG_RETURN.
mysql_stmt_row_tell()
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_tell (MYSQL_STMT * stmt)
Definition at line 4458 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_row_tell");
   DBUG_RETURN(stmt->data_cursor);
 }
References st_mysql_stmt::data_cursor, DBUG_ENTER, and DBUG_RETURN.
mysql_stmt_send_long_data()
my_bool STDCALL mysql_stmt_send_long_data (MYSQL_STMT * stmt, uint param_number, const char * data, ulong length)
Definition at line 2898 of file libmysql.c.
 {
   MYSQL_BIND *param;
   DBUG_ENTER("mysql_stmt_send_long_data");
   DBUG_ASSERT(stmt != 0);
   DBUG_PRINT("enter",("param no: %d  data: 0x%lx, length : %ld",
               param_number, (long) data, length));
   /*
     We only need to check for stmt->param_count, if it's not null
     prepare was done.
   */
   if (param_number >= stmt->param_count)
   {
     set_stmt_error(stmt, CR_INVALID_PARAMETER_NO, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   param= stmt->params+param_number;
   if (!IS_LONGDATA(param->buffer_type))
   {
     /* Long data handling should be used only for string/binary types */
     strmov(stmt->sqlstate, unknown_sqlstate);
     sprintf(stmt->last_error, ER(stmt->last_errno= CR_INVALID_BUFFER_USE),
         param->param_number);
     DBUG_RETURN(1);
   }
   /*
     Send long data packet if there is data or we're sending long data
     for the first time.
   */
   if (length || param->long_data_used == 0)
   {
     MYSQL *mysql= stmt->mysql;
     /* Packet header: stmt id (4 bytes), param no (2 bytes) */
     uchar buff[MYSQL_LONG_DATA_HEADER];
     int4store(buff, stmt->stmt_id);
     int2store(buff + 4, param_number);
     param->long_data_used= 1;
     /*
       Note that we don't get any ok packet from the server in this case
       This is intentional to save bandwidth.
     */
     if ((*mysql->methods->advanced_command)(mysql, COM_STMT_SEND_LONG_DATA,
                                             buff, sizeof(buff), (uchar*) data,
                                             length, 1, stmt))
     {
       /*
         Don't set stmt error if stmt->mysql is NULL, as the error in this case
         has already been set by mysql_prune_stmt_list().
       */
       if (stmt->mysql)
         set_stmt_errmsg(stmt, &mysql->net);
       DBUG_RETURN(1);
     }
   }
   DBUG_RETURN(0);
 }
References st_mysql_methods::advanced_command, st_mysql_bind::buffer_type, COM_STMT_SEND_LONG_DATA, CR_INVALID_BUFFER_USE, CR_INVALID_PARAMETER_NO, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER, int2store, int4store, IS_LONGDATA, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, G3D::length(), st_mysql_bind::long_data_used, st_mysql::methods, st_mysql_stmt::mysql, MYSQL_LONG_DATA_HEADER, st_mysql::net, NULL, st_mysql_stmt::param_count, st_mysql_bind::param_number, st_mysql_stmt::params, set_stmt_errmsg(), set_stmt_error(), sprintf(), st_mysql_stmt::sqlstate, st_mysql_stmt::stmt_id, strmov(), and unknown_sqlstate.
mysql_stmt_sqlstate()
const char* STDCALL mysql_stmt_sqlstate (MYSQL_STMT * stmt)
Definition at line 4677 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_sqlstate");
   DBUG_RETURN(stmt->sqlstate);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::sqlstate.
mysql_stmt_store_result()
int STDCALL mysql_stmt_store_result (MYSQL_STMT * stmt)
Definition at line 4326 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   MYSQL_DATA *result= &stmt->result;
   DBUG_ENTER("mysql_stmt_store_result");
   if (!mysql)
   {
     /* mysql can be reset in mysql_close called from mysql_reconnect */
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (!stmt->field_count)
     DBUG_RETURN(0);
   if ((int) stmt->state < (int) MYSQL_STMT_EXECUTE_DONE)
   {
     set_stmt_error(stmt, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (stmt->last_errno)
   {
     /* An attempt to use an invalid statement handle. */
     DBUG_RETURN(1);
   }
   if (mysql->status == MYSQL_STATUS_READY &&
       stmt->server_status & SERVER_STATUS_CURSOR_EXISTS)
   {
     /*
       Server side cursor exist, tell server to start sending the rows
     */
     NET *net= &mysql->net;
     uchar buff[4 /* statement id */ +
                4 /* number of rows to fetch */];
     /* Send row request to the server */
     int4store(buff, stmt->stmt_id);
     int4store(buff + 4, (int)~0); /* number of rows to fetch */
     if (cli_advanced_command(mysql, COM_STMT_FETCH, buff, sizeof(buff),
                              (uchar*) 0, 0, 1, stmt))
     {
       /*
         Don't set stmt error if stmt->mysql is NULL, as the error in this case
         has already been set by mysql_prune_stmt_list().
       */
       if (stmt->mysql)
         set_stmt_errmsg(stmt, net);
       DBUG_RETURN(1);
     }
   }
   else if (mysql->status != MYSQL_STATUS_STATEMENT_GET_RESULT)
   {
     set_stmt_error(stmt, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (stmt->update_max_length && !stmt->bind_result_done)
   {
     /*
       We must initalize the bind structure to be able to calculate
       max_length
     */
     MYSQL_BIND  *my_bind, *end;
     MYSQL_FIELD *field;
     bzero((char*) stmt->bind, sizeof(*stmt->bind)* stmt->field_count);
     for (my_bind= stmt->bind, end= my_bind + stmt->field_count,
            field= stmt->fields;
      my_bind < end ;
      my_bind++, field++)
     {
       my_bind->buffer_type= MYSQL_TYPE_NULL;
       my_bind->buffer_length=1;
     }
     if (mysql_stmt_bind_result(stmt, stmt->bind))
       DBUG_RETURN(1);
     stmt->bind_result_done= 0;          /* No normal bind done */
   }
   if ((*mysql->methods->read_binary_rows)(stmt))
   {
     free_root(&result->alloc, MYF(MY_KEEP_PREALLOC));
     result->data= NULL;
     result->rows= 0;
     mysql->status= MYSQL_STATUS_READY;
     DBUG_RETURN(1);
   }
   /* Assert that if there was a cursor, all rows have been fetched */
   DBUG_ASSERT(mysql->status != MYSQL_STATUS_READY ||
               (mysql->server_status & SERVER_STATUS_LAST_ROW_SENT));
   if (stmt->update_max_length)
   {
     MYSQL_ROWS *cur= result->data;
     for(; cur; cur=cur->next)
       stmt_update_metadata(stmt, cur);
   }
   stmt->data_cursor= result->data;
   mysql->affected_rows= stmt->affected_rows= result->rows;
   stmt->read_row_func= stmt_read_row_buffered;
   mysql->unbuffered_fetch_owner= 0;             /* set in stmt_execute */
   mysql->status= MYSQL_STATUS_READY;        /* server is ready */
   DBUG_RETURN(0); /* Data buffered, must be fetched with mysql_stmt_fetch() */
 }
References st_mysql::affected_rows, st_mysql_stmt::affected_rows, st_mysql_stmt::bind, st_mysql_stmt::bind_result_done, st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, bzero, cli_advanced_command(), COM_STMT_FETCH, CR_COMMANDS_OUT_OF_SYNC, CR_SERVER_LOST, st_mysql_stmt::data_cursor, DBUG_ASSERT, DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::field_count, st_mysql_stmt::fields, free_root(), int4store, st_mysql_stmt::last_errno, st_mysql::methods, MY_KEEP_PREALLOC, MYF, st_mysql_stmt::mysql, MYSQL_STATUS_READY, MYSQL_STATUS_STATEMENT_GET_RESULT, mysql_stmt_bind_result(), MYSQL_STMT_EXECUTE_DONE, MYSQL_TYPE_NULL, st_mysql::net, st_mysql_rows::next, NULL, st_mysql_methods::read_binary_rows, st_mysql_stmt::read_row_func, st_mysql_stmt::result, st_mysql::server_status, st_mysql_stmt::server_status, SERVER_STATUS_CURSOR_EXISTS, SERVER_STATUS_LAST_ROW_SENT, set_stmt_errmsg(), set_stmt_error(), st_mysql_stmt::state, st_mysql::status, st_mysql_stmt::stmt_id, stmt_read_row_buffered(), stmt_update_metadata(), st_mysql::unbuffered_fetch_owner, unknown_sqlstate, and st_mysql_stmt::update_max_length.
Referenced by prepare_to_fetch_result(), and PreparedResultSet::PreparedResultSet().
mysql_thread_end()
void STDCALL mysql_thread_end (void)
Definition at line 233 of file libmysql.c.
 {
   my_thread_end();
 }
References my_thread_end().
Referenced by mysql_server_end().
mysql_thread_id()
ulong STDCALL mysql_thread_id (MYSQL * mysql)
Definition at line 1059 of file libmysql.c.
 {
   return (mysql)->thread_id;
 }
mysql_thread_init()
my_bool STDCALL mysql_thread_init (void)
Definition at line 228 of file libmysql.c.
 {
   return my_thread_init();
 }
References my_thread_init().
mysql_thread_safe()
uint STDCALL mysql_thread_safe (void)
Definition at line 1085 of file libmysql.c.
 {
   return 1;
 }
Referenced by DatabaseWorkerPool< T >::DatabaseWorkerPool().
mysql_use_result()
MYSQL_RES* STDCALL mysql_use_result (MYSQL * mysql)
Definition at line 4823 of file libmysql.c.
 {
   return (*mysql->methods->use_result)(mysql);
 }
References st_mysql::methods, and st_mysql_methods::use_result.
mysql_warning_count()
uint STDCALL mysql_warning_count (MYSQL * mysql)
Definition at line 1049 of file libmysql.c.
 {
   return mysql->warning_count;
 }
References st_mysql::warning_count.
net_store_datetime()
static void net_store_datetime (NET * net, MYSQL_TIME * tm) static
Definition at line 1907 of file libmysql.c.
 {
   char buff[MAX_DATETIME_REP_LENGTH], *pos;
   uint length;
   pos= buff+1;
   int2store(pos, tm->year);
   pos[2]= (uchar) tm->month;
   pos[3]= (uchar) tm->day;
   pos[4]= (uchar) tm->hour;
   pos[5]= (uchar) tm->minute;
   pos[6]= (uchar) tm->second;
   int4store(pos+7, tm->second_part);
   if (tm->second_part)
     length= 11;
   else if (tm->hour || tm->minute || tm->second)
     length= 7;
   else if (tm->year || tm->month || tm->day)
     length= 4;
   else
     length= 0;
   buff[0]= (char) length++;
   memcpy((char *)net->write_pos, buff, length);
   net->write_pos+= length;
 }
References st_mysql_time::day, st_mysql_time::hour, int2store, int4store, G3D::length(), MAX_DATETIME_REP_LENGTH, memcpy, st_mysql_time::minute, st_mysql_time::month, pos(), st_mysql_time::second, st_mysql_time::second_part, st_net::write_pos, and st_mysql_time::year.
Referenced by store_param_date(), and store_param_datetime().
prepare_to_fetch_result()
static void prepare_to_fetch_result (MYSQL_STMT * stmt) static
Definition at line 2413 of file libmysql.c.
 {
   if (stmt->server_status & SERVER_STATUS_CURSOR_EXISTS)
   {
     stmt->mysql->status= MYSQL_STATUS_READY;
     stmt->read_row_func= stmt_read_row_from_cursor;
   }
   else if (stmt->flags & CURSOR_TYPE_READ_ONLY)
   {
     /*
       This is a single-row result set, a result set with no rows, EXPLAIN,
       SHOW VARIABLES, or some other command which either a) bypasses the
       cursors framework in the server and writes rows directly to the
       network or b) is more efficient if all (few) result set rows are
       precached on client and server's resources are freed.
     */
     mysql_stmt_store_result(stmt);
   }
   else
   {
     stmt->mysql->unbuffered_fetch_owner= &stmt->unbuffered_fetch_cancelled;
     stmt->unbuffered_fetch_cancelled= FALSE;
     stmt->read_row_func= stmt_read_row_unbuffered;
   }
 }
References CURSOR_TYPE_READ_ONLY, FALSE, st_mysql_stmt::flags, st_mysql_stmt::mysql, MYSQL_STATUS_READY, mysql_stmt_store_result(), st_mysql_stmt::read_row_func, st_mysql_stmt::server_status, SERVER_STATUS_CURSOR_EXISTS, st_mysql::status, stmt_read_row_from_cursor(), stmt_read_row_unbuffered(), st_mysql_stmt::unbuffered_fetch_cancelled, and st_mysql::unbuffered_fetch_owner.
Referenced by mysql_stmt_execute(), and mysql_stmt_next_result().
read_binary_date()
static void read_binary_date (MYSQL_TIME * tm, uchar ** pos) static
Definition at line 3042 of file libmysql.c.
 {
   uint length= net_field_length(pos);
   if (length)
   {
     uchar *to= *pos;
     tm->year =  (uint) sint2korr(to);
     tm->month=  (uint) to[2];
     tm->day= (uint) to[3];
     tm->hour= tm->minute= tm->second= 0;
     tm->second_part= 0;
     tm->neg= 0;
     tm->time_type= MYSQL_TIMESTAMP_DATE;
     *pos+= length;
   }
   else
     set_zero_time(tm, MYSQL_TIMESTAMP_DATE);
 }
References st_mysql_time::day, st_mysql_time::hour, G3D::length(), st_mysql_time::minute, st_mysql_time::month, MYSQL_TIMESTAMP_DATE, st_mysql_time::neg, net_field_length(), pos(), st_mysql_time::second, st_mysql_time::second_part, set_zero_time(), sint2korr, st_mysql_time::time_type, and st_mysql_time::year.
Referenced by fetch_result_date(), and fetch_result_with_conversion().
read_binary_datetime()
static void read_binary_datetime (MYSQL_TIME * tm, uchar ** pos) static
Definition at line 3012 of file libmysql.c.
 {
   uint length= net_field_length(pos);
   if (length)
   {
     uchar *to= *pos;
     tm->neg=    0;
     tm->year=   (uint) sint2korr(to);
     tm->month=  (uint) to[2];
     tm->day=    (uint) to[3];
     if (length > 4)
     {
       tm->hour=   (uint) to[4];
       tm->minute= (uint) to[5];
       tm->second= (uint) to[6];
     }
     else
       tm->hour= tm->minute= tm->second= 0;
     tm->second_part= (length > 7) ? (ulong) sint4korr(to+7) : 0;
     tm->time_type= MYSQL_TIMESTAMP_DATETIME;
     *pos+= length;
   }
   else
     set_zero_time(tm, MYSQL_TIMESTAMP_DATETIME);
 }
References st_mysql_time::day, st_mysql_time::hour, G3D::length(), st_mysql_time::minute, st_mysql_time::month, MYSQL_TIMESTAMP_DATETIME, st_mysql_time::neg, net_field_length(), pos(), st_mysql_time::second, st_mysql_time::second_part, set_zero_time(), sint2korr, sint4korr, st_mysql_time::time_type, and st_mysql_time::year.
Referenced by fetch_result_datetime(), and fetch_result_with_conversion().
read_binary_time()
static void read_binary_time (MYSQL_TIME * tm, uchar ** pos) static
Definition at line 2982 of file libmysql.c.
 {
   /* net_field_length will set pos to the first byte of data */
   uint length= net_field_length(pos);
   if (length)
   {
     uchar *to= *pos;
     tm->neg=    to[0];
     tm->day=    (ulong) sint4korr(to+1);
     tm->hour=   (uint) to[5];
     tm->minute= (uint) to[6];
     tm->second= (uint) to[7];
     tm->second_part= (length > 8) ? (ulong) sint4korr(to+8) : 0;
     tm->year= tm->month= 0;
     if (tm->day)
     {
       /* Convert days to hours at once */
       tm->hour+= tm->day*24;
       tm->day= 0;
     }
     tm->time_type= MYSQL_TIMESTAMP_TIME;
     *pos+= length;
   }
   else
     set_zero_time(tm, MYSQL_TIMESTAMP_TIME);
 }
References st_mysql_time::day, st_mysql_time::hour, G3D::length(), st_mysql_time::minute, st_mysql_time::month, MYSQL_TIMESTAMP_TIME, st_mysql_time::neg, net_field_length(), pos(), st_mysql_time::second, st_mysql_time::second_part, set_zero_time(), sint4korr, st_mysql_time::time_type, and st_mysql_time::year.
Referenced by fetch_result_time(), and fetch_result_with_conversion().
read_user_name()
void read_user_name (char * name)
Definition at line 405 of file libmysql.c.
 {
   DBUG_ENTER("read_user_name");
   if (geteuid() == 0)
     (void) strmov(name,"root");     /* allow use of surun */
   else
   {
 #ifdef HAVE_GETPWUID
     struct passwd *skr;
     const char *str;
     if ((str=getlogin()) == NULL)
     {
       if ((skr=getpwuid(geteuid())) != NULL)
     str=skr->pw_name;
       else if (!(str=getenv("USER")) && !(str=getenv("LOGNAME")) &&
            !(str=getenv("LOGIN")))
     str="UNKNOWN_USER";
     }
     (void) strmake(name,str,USERNAME_LENGTH);
 #elif HAVE_CUSERID
     (void) cuserid(name);
 #else
     strmov(name,"UNKNOWN_USER");
 #endif
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, if(), name, NULL, strmake(), strmov(), and USERNAME_LENGTH.
Referenced by send_client_reply_packet().
reinit_result_set_metadata()
static void reinit_result_set_metadata (MYSQL_STMT * stmt) static
Update statement result set metadata from with the new field information sent during statement execute.
Precondition
mysql->field_count is not zero
Return values
TRUE if error: out of memory or the new result set has a different number of columns
FALSE success
Definition at line 2380 of file libmysql.c.
 {
   /* Server has sent result set metadata */
   if (stmt->field_count == 0)
   {
     /*
       This is 'SHOW'/'EXPLAIN'-like query. Current implementation of
       prepared statements can't send result set metadata for these queries
       on prepare stage. Read it now.
     */
     alloc_stmt_fields(stmt);
   }
   else
   {
     /*
       Update result set metadata if it for some reason changed between
       prepare and execute, i.e.:
       - in case of 'SELECT ?' we don't know column type unless data was
       supplied to mysql_stmt_execute, so updated column type is sent
       now.
       - if data dictionary changed between prepare and execute, for
       example a table used in the query was altered.
       Note, that now (4.1.3) we always send metadata in reply to
       COM_STMT_EXECUTE (even if it is not necessary), so either this or
       previous branch always works.
       TODO: send metadata only when it's really necessary and add a warning
       'Metadata changed' when it's sent twice.
       */
     update_stmt_fields(stmt);
   }
 }
References alloc_stmt_fields(), st_mysql_stmt::field_count, and update_stmt_fields().
Referenced by mysql_stmt_execute().
reset_stmt_handle()
static my_bool reset_stmt_handle (MYSQL_STMT * stmt, uint flags) static
Definition at line 4508 of file libmysql.c.
 {
   /* If statement hasn't been prepared there is nothing to reset */
   if ((int) stmt->state > (int) MYSQL_STMT_INIT_DONE)
   {
     MYSQL *mysql= stmt->mysql;
     MYSQL_DATA *result= &stmt->result;
     /*
       Reset stored result set if so was requested or it's a part
       of cursor fetch.
     */
     if (flags & RESET_STORE_RESULT)
     {
       /* Result buffered */
       free_root(&result->alloc, MYF(MY_KEEP_PREALLOC));
       result->data= NULL;
       result->rows= 0;
       stmt->data_cursor= NULL;
     }
     if (flags & RESET_LONG_DATA)
     {
       MYSQL_BIND *param= stmt->params, *param_end= param + stmt->param_count;
       /* Clear long_data_used flags */
       for (; param < param_end; param++)
         param->long_data_used= 0;
     }
     stmt->read_row_func= stmt_read_row_no_result_set;
     if (mysql)
     {
       if ((int) stmt->state > (int) MYSQL_STMT_PREPARE_DONE)
       {
         if (mysql->unbuffered_fetch_owner == &stmt->unbuffered_fetch_cancelled)
           mysql->unbuffered_fetch_owner= 0;
         if (stmt->field_count && mysql->status != MYSQL_STATUS_READY)
         {
           /* There is a result set and it belongs to this statement */
           (*mysql->methods->flush_use_result)(mysql, FALSE);
           if (mysql->unbuffered_fetch_owner)
             *mysql->unbuffered_fetch_owner= TRUE;
           mysql->status= MYSQL_STATUS_READY;
         }
       }
       if (flags & RESET_SERVER_SIDE)
       {
         /*
           Reset the server side statement and close the server side
           cursor if it exists.
         */
         uchar buff[MYSQL_STMT_HEADER]; /* packet header: 4 bytes for stmt id */
         int4store(buff, stmt->stmt_id);
         if ((*mysql->methods->advanced_command)(mysql, COM_STMT_RESET, buff,
                                                 sizeof(buff), 0, 0, 0, stmt))
         {
           set_stmt_errmsg(stmt, &mysql->net);
           stmt->state= MYSQL_STMT_INIT_DONE;
           return 1;
         }
       }
     }
     if (flags & RESET_CLEAR_ERROR)
       stmt_clear_error(stmt);
     stmt->state= MYSQL_STMT_PREPARE_DONE;
   }
   return 0;
 }
References st_mysql_methods::advanced_command, COM_STMT_RESET, st_mysql_stmt::data_cursor, FALSE, st_mysql_stmt::field_count, st_mysql_methods::flush_use_result, free_root(), int4store, st_mysql_bind::long_data_used, st_mysql::methods, MY_KEEP_PREALLOC, MYF, st_mysql_stmt::mysql, MYSQL_STATUS_READY, MYSQL_STMT_HEADER, MYSQL_STMT_INIT_DONE, MYSQL_STMT_PREPARE_DONE, st_mysql::net, NULL, st_mysql_stmt::param_count, st_mysql_stmt::params, st_mysql_stmt::read_row_func, RESET_CLEAR_ERROR, RESET_LONG_DATA, RESET_SERVER_SIDE, RESET_STORE_RESULT, st_mysql_stmt::result, set_stmt_errmsg(), st_mysql_stmt::state, st_mysql::status, stmt_clear_error(), st_mysql_stmt::stmt_id, stmt_read_row_no_result_set(), TRUE, st_mysql_stmt::unbuffered_fetch_cancelled, and st_mysql::unbuffered_fetch_owner.
Referenced by mysql_stmt_execute(), mysql_stmt_free_result(), mysql_stmt_next_result(), mysql_stmt_prepare(), and mysql_stmt_reset().
set_stmt_errmsg()
void set_stmt_errmsg (MYSQL_STMT * stmt, NET * net)
Set statement error code, sqlstate, and error message from NET.
Parameters
stmt a statement handle. Copy the error here.
net mysql->net. Source of the error.
Definition at line 1363 of file libmysql.c.
 {
   DBUG_ENTER("set_stmt_errmsg");
   DBUG_PRINT("enter", ("error: %d/%s '%s'",
                        net->last_errno,
                        net->sqlstate,
                        net->last_error));
   DBUG_ASSERT(stmt != 0);
   stmt->last_errno= net->last_errno;
   if (net->last_error && net->last_error[0])
     strmov(stmt->last_error, net->last_error);
   strmov(stmt->sqlstate, net->sqlstate);
   DBUG_VOID_RETURN;
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_mysql_stmt::last_errno, st_net::last_errno, st_mysql_stmt::last_error, st_net::last_error, st_mysql_stmt::sqlstate, st_net::sqlstate, and strmov().
Referenced by cli_read_binary_rows(), cli_stmt_execute(), execute(), mysql_stmt_close(), mysql_stmt_next_result(), mysql_stmt_prepare(), mysql_stmt_send_long_data(), mysql_stmt_store_result(), reset_stmt_handle(), stmt_read_row_from_cursor(), stmt_read_row_unbuffered(), and store_param().
set_stmt_error()
void set_stmt_error (MYSQL_STMT * stmt, int errcode, const char * sqlstate, const char * err)
Set statement error code, sqlstate, and error message from given errcode and sqlstate.
Definition at line 1338 of file libmysql.c.
 {
   DBUG_ENTER("set_stmt_error");
   DBUG_PRINT("enter", ("error: %d '%s'", errcode, ER(errcode)));
   DBUG_ASSERT(stmt != 0);
   if (err == 0)
     err= ER(errcode);
   stmt->last_errno= errcode;
   strmov(stmt->last_error, ER(errcode));
   strmov(stmt->sqlstate, sqlstate);
   DBUG_VOID_RETURN;
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ER, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, st_mysql_stmt::sqlstate, and strmov().
Referenced by alloc_stmt_fields(), cli_read_binary_rows(), cli_stmt_execute(), mysql_detach_stmt_list(), mysql_stmt_attr_set(), mysql_stmt_bind_param(), mysql_stmt_bind_result(), mysql_stmt_fetch_column(), mysql_stmt_prepare(), mysql_stmt_reset(), mysql_stmt_result_metadata(), mysql_stmt_send_long_data(), mysql_stmt_store_result(), stmt_read_row_no_result_set(), stmt_read_row_unbuffered(), and update_stmt_fields().
setup_one_fetch_function()
static my_bool setup_one_fetch_function (MYSQL_BIND * param, MYSQL_FIELD * field) static
Definition at line 3841 of file libmysql.c.
 {
   DBUG_ENTER("setup_one_fetch_function");
   /* Setup data copy functions for the different supported types */
   switch (param->buffer_type) {
   case MYSQL_TYPE_NULL: /* for dummy binds */
     /*
       It's not binary compatible with anything the server can return:
       no need to setup fetch_result, as it'll be reset anyway
     */
     *param->length= 0;
     break;
   case MYSQL_TYPE_TINY:
     param->fetch_result= fetch_result_tinyint;
     *param->length= 1;
     break;
   case MYSQL_TYPE_SHORT:
   case MYSQL_TYPE_YEAR:
     param->fetch_result= fetch_result_short;
     *param->length= 2;
     break;
   case MYSQL_TYPE_INT24:
   case MYSQL_TYPE_LONG:
     param->fetch_result= fetch_result_int32;
     *param->length= 4;
     break;
   case MYSQL_TYPE_LONGLONG:
     param->fetch_result= fetch_result_int64;
     *param->length= 8;
     break;
   case MYSQL_TYPE_FLOAT:
     param->fetch_result= fetch_result_float;
     *param->length= 4;
     break;
   case MYSQL_TYPE_DOUBLE:
     param->fetch_result= fetch_result_double;
     *param->length= 8;
     break;
   case MYSQL_TYPE_TIME:
     param->fetch_result= fetch_result_time;
     *param->length= sizeof(MYSQL_TIME);
     break;
   case MYSQL_TYPE_DATE:
     param->fetch_result= fetch_result_date;
     *param->length= sizeof(MYSQL_TIME);
     break;
   case MYSQL_TYPE_DATETIME:
   case MYSQL_TYPE_TIMESTAMP:
     param->fetch_result= fetch_result_datetime;
     *param->length= sizeof(MYSQL_TIME);
     break;
   case MYSQL_TYPE_TINY_BLOB:
   case MYSQL_TYPE_MEDIUM_BLOB:
   case MYSQL_TYPE_LONG_BLOB:
   case MYSQL_TYPE_BLOB:
   case MYSQL_TYPE_BIT:
     DBUG_ASSERT(param->buffer_length != 0);
     param->fetch_result= fetch_result_bin;
     break;
   case MYSQL_TYPE_VAR_STRING:
   case MYSQL_TYPE_STRING:
   case MYSQL_TYPE_DECIMAL:
   case MYSQL_TYPE_NEWDECIMAL:
   case MYSQL_TYPE_NEWDATE:
     DBUG_ASSERT(param->buffer_length != 0);
     param->fetch_result= fetch_result_str;
     break;
   default:
     DBUG_PRINT("error", ("Unknown param->buffer_type: %u",
                          (uint) param->buffer_type));
     DBUG_RETURN(TRUE);
   }
   if (! is_binary_compatible(param->buffer_type, field->type))
     param->fetch_result= fetch_result_with_conversion;
   /* Setup skip_result functions (to calculate max_length) */
   param->skip_result= skip_result_fixed;
   switch (field->type) {
   case MYSQL_TYPE_NULL: /* for dummy binds */
     param->pack_length= 0;
     field->max_length= 0;
     break;
   case MYSQL_TYPE_TINY:
     param->pack_length= 1;
     field->max_length= 4;                     /* as in '-127' */
     break;
   case MYSQL_TYPE_YEAR:
   case MYSQL_TYPE_SHORT:
     param->pack_length= 2;
     field->max_length= 6;                     /* as in '-32767' */
     break;
   case MYSQL_TYPE_INT24:
     field->max_length= 9;  /* as in '16777216' or in '-8388607' */
     param->pack_length= 4;
     break;
   case MYSQL_TYPE_LONG:
     field->max_length= 11;                    /* '-2147483647' */
     param->pack_length= 4;
     break;
   case MYSQL_TYPE_LONGLONG:
     field->max_length= 21;                    /* '18446744073709551616' */
     param->pack_length= 8;
     break;
   case MYSQL_TYPE_FLOAT:
     param->pack_length= 4;
     field->max_length= MAX_DOUBLE_STRING_REP_LENGTH;
     break;
   case MYSQL_TYPE_DOUBLE:
     param->pack_length= 8;
     field->max_length= MAX_DOUBLE_STRING_REP_LENGTH;
     break;
   case MYSQL_TYPE_TIME:
     field->max_length= 15;                    /* 19:23:48.123456 */
     param->skip_result= skip_result_with_length;
     break;
   case MYSQL_TYPE_DATE:
     field->max_length= 10;                    /* 2003-11-11 */
     param->skip_result= skip_result_with_length;
     break;
   case MYSQL_TYPE_DATETIME:
   case MYSQL_TYPE_TIMESTAMP:
     param->skip_result= skip_result_with_length;
     field->max_length= MAX_DATE_STRING_REP_LENGTH;
     break;
   case MYSQL_TYPE_DECIMAL:
   case MYSQL_TYPE_NEWDECIMAL:
   case MYSQL_TYPE_ENUM:
   case MYSQL_TYPE_SET:
   case MYSQL_TYPE_GEOMETRY:
   case MYSQL_TYPE_TINY_BLOB:
   case MYSQL_TYPE_MEDIUM_BLOB:
   case MYSQL_TYPE_LONG_BLOB:
   case MYSQL_TYPE_BLOB:
   case MYSQL_TYPE_VAR_STRING:
   case MYSQL_TYPE_STRING:
   case MYSQL_TYPE_BIT:
   case MYSQL_TYPE_NEWDATE:
     param->skip_result= skip_result_string;
     break;
   default:
     DBUG_PRINT("error", ("Unknown field->type: %u", (uint) field->type));
     DBUG_RETURN(TRUE);
   }
   DBUG_RETURN(FALSE);
 }
References st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FALSE, st_mysql_bind::fetch_result, fetch_result_bin(), fetch_result_date(), fetch_result_datetime(), fetch_result_double(), fetch_result_float(), fetch_result_int32(), fetch_result_int64(), fetch_result_short(), fetch_result_str(), fetch_result_time(), fetch_result_tinyint(), fetch_result_with_conversion(), is_binary_compatible(), st_mysql_bind::length, MAX_DATE_STRING_REP_LENGTH, MAX_DOUBLE_STRING_REP_LENGTH, st_mysql_field::max_length, MYSQL_TYPE_BIT, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_ENUM, MYSQL_TYPE_FLOAT, MYSQL_TYPE_GEOMETRY, MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NEWDATE, MYSQL_TYPE_NEWDECIMAL, MYSQL_TYPE_NULL, MYSQL_TYPE_SET, MYSQL_TYPE_SHORT, MYSQL_TYPE_STRING, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, MYSQL_TYPE_YEAR, st_mysql_bind::pack_length, st_mysql_bind::skip_result, skip_result_fixed(), skip_result_string(), skip_result_with_length(), TRUE, and st_mysql_field::type.
Referenced by mysql_stmt_bind_result(), and update_stmt_fields().
skip_result_fixed()
static void skip_result_fixed (MYSQL_BIND * param, MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3737 of file libmysql.c.
 {
   (*row)+= param->pack_length;
 }
References st_mysql_bind::pack_length.
Referenced by setup_one_fetch_function().
skip_result_string()
static void skip_result_string (MYSQL_BIND *param __attribute__(unused), MYSQL_FIELD * field, uchar ** row) static
Definition at line 3756 of file libmysql.c.
 {
   ulong length= net_field_length(row);
   (*row)+= length;
   if (field->max_length < length)
     field->max_length= length;
 }
References G3D::length(), st_mysql_field::max_length, and net_field_length().
Referenced by setup_one_fetch_function().
skip_result_with_length()
static void skip_result_with_length (MYSQL_BIND *param __attribute__(unused), MYSQL_FIELD *field __attribute__(unused), uchar ** row) static
Definition at line 3746 of file libmysql.c.
 {
   ulong length= net_field_length(row);
   (*row)+= length;
 }
References G3D::length(), and net_field_length().
Referenced by setup_one_fetch_function().
stmt_clear_error()
static void stmt_clear_error (MYSQL_STMT * stmt) static
Definition at line 1323 of file libmysql.c.
 {
   if (stmt->last_errno)
   {
     stmt->last_errno= 0;
     stmt->last_error[0]= '\0';
     strmov(stmt->sqlstate, not_error_sqlstate);
   }
 }
References st_mysql_stmt::last_errno, st_mysql_stmt::last_error, not_error_sqlstate, st_mysql_stmt::sqlstate, and strmov().
Referenced by reset_stmt_handle().
stmt_fetch_row()
static int stmt_fetch_row (MYSQL_STMT * stmt, uchar * row) static
Definition at line 4064 of file libmysql.c.
 {
   MYSQL_BIND  *my_bind, *end;
   MYSQL_FIELD *field;
   uchar *null_ptr, bit;
   int truncation_count= 0;
   /*
     Precondition: if stmt->field_count is zero or row is NULL, read_row_*
     function must return no data.
   */
   DBUG_ASSERT(stmt->field_count);
   DBUG_ASSERT(row);
   if (!stmt->bind_result_done)
   {
     /* If output parameters were not bound we should just return success */
     return 0;
   }
   null_ptr= row;
   row+= (stmt->field_count+9)/8;        /* skip null bits */
   bit= 4;                   /* first 2 bits are reserved */
   /* Copy complete row to application buffers */
   for (my_bind= stmt->bind, end= my_bind + stmt->field_count,
          field= stmt->fields ;
        my_bind < end ;
        my_bind++, field++)
   {
     *my_bind->error= 0;
     if (*null_ptr & bit)
     {
       /*
         We should set both row_ptr and is_null to be able to see
         nulls in mysql_stmt_fetch_column. This is because is_null may point
         to user data which can be overwritten between mysql_stmt_fetch and
         mysql_stmt_fetch_column, and in this case nullness of column will be
         lost. See mysql_stmt_fetch_column for details.
       */
       my_bind->row_ptr= NULL;
       *my_bind->is_null= 1;
     }
     else
     {
       *my_bind->is_null= 0;
       my_bind->row_ptr= row;
       (*my_bind->fetch_result)(my_bind, field, &row);
       truncation_count+= *my_bind->error;
     }
     if (!((bit<<=1) & 255))
     {
       bit= 1;                   /* To next uchar */
       null_ptr++;
     }
   }
   if (truncation_count && (stmt->bind_result_done & REPORT_DATA_TRUNCATION))
     return MYSQL_DATA_TRUNCATED;
   return 0;
 }
References st_mysql_stmt::bind, st_mysql_stmt::bind_result_done, DBUG_ASSERT, st_mysql_bind::error, st_mysql_bind::fetch_result, st_mysql_stmt::field_count, st_mysql_stmt::fields, st_mysql_bind::is_null, MYSQL_DATA_TRUNCATED, NULL, REPORT_DATA_TRUNCATION, and st_mysql_bind::row_ptr.
Referenced by mysql_stmt_fetch().
stmt_read_row_buffered()
static int stmt_read_row_buffered (MYSQL_STMT * stmt, unsigned char ** row) static
Definition at line 2143 of file libmysql.c.
 {
   if (stmt->data_cursor)
   {
     *row= (uchar *) stmt->data_cursor->data;
     stmt->data_cursor= stmt->data_cursor->next;
     return 0;
   }
   *row= 0;
   return MYSQL_NO_DATA;
 }
References st_mysql_rows::data, st_mysql_stmt::data_cursor, MYSQL_NO_DATA, and st_mysql_rows::next.
Referenced by mysql_stmt_data_seek(), mysql_stmt_store_result(), and stmt_read_row_from_cursor().
stmt_read_row_from_cursor()
static int stmt_read_row_from_cursor (MYSQL_STMT * stmt, unsigned char ** row) static
Definition at line 2233 of file libmysql.c.
 {
   if (stmt->data_cursor)
     return stmt_read_row_buffered(stmt, row);
   if (stmt->server_status & SERVER_STATUS_LAST_ROW_SENT)
     stmt->server_status &= ~SERVER_STATUS_LAST_ROW_SENT;
   else
   {
     MYSQL *mysql= stmt->mysql;
     NET *net= &mysql->net;
     MYSQL_DATA *result= &stmt->result;
     uchar buff[4 /* statement id */ +
                4 /* number of rows to fetch */];
     free_root(&result->alloc, MYF(MY_KEEP_PREALLOC));
     result->data= NULL;
     result->rows= 0;
     /* Send row request to the server */
     int4store(buff, stmt->stmt_id);
     int4store(buff + 4, stmt->prefetch_rows); /* number of rows to fetch */
     if ((*mysql->methods->advanced_command)(mysql, COM_STMT_FETCH,
                                             buff, sizeof(buff), (uchar*) 0, 0,
                                             1, stmt))
     {
       /*
         Don't set stmt error if stmt->mysql is NULL, as the error in this case
         has already been set by mysql_prune_stmt_list().
       */
       if (stmt->mysql)
         set_stmt_errmsg(stmt, net);
       return 1;
     }
     if ((*mysql->methods->read_rows_from_cursor)(stmt))
       return 1;
     stmt->server_status= mysql->server_status;
     stmt->data_cursor= result->data;
     return stmt_read_row_buffered(stmt, row);
   }
   *row= 0;
   return MYSQL_NO_DATA;
 }
References st_mysql_methods::advanced_command, COM_STMT_FETCH, st_mysql_stmt::data_cursor, free_root(), int4store, st_mysql::methods, MY_KEEP_PREALLOC, MYF, st_mysql_stmt::mysql, MYSQL_NO_DATA, st_mysql::net, NULL, st_mysql_stmt::prefetch_rows, st_mysql_methods::read_rows_from_cursor, st_mysql_stmt::result, st_mysql::server_status, st_mysql_stmt::server_status, SERVER_STATUS_LAST_ROW_SENT, set_stmt_errmsg(), st_mysql_stmt::stmt_id, and stmt_read_row_buffered().
Referenced by prepare_to_fetch_result().
stmt_read_row_no_data() [1/2]
static int stmt_read_row_no_data (MYSQL_STMT *stmt __attribute__(unused), unsigned char **row __attribute__(unused)) static
Definition at line 2283 of file libmysql.c.
 {
   return MYSQL_NO_DATA;
 }
References MYSQL_NO_DATA.
stmt_read_row_no_data() [2/2]
static int stmt_read_row_no_data (MYSQL_STMT * stmt, unsigned char ** row) static
Referenced by mysql_stmt_fetch().
stmt_read_row_no_result_set() [1/2]
static int stmt_read_row_no_result_set (MYSQL_STMT *stmt __attribute__(unused), unsigned char **row __attribute__(unused)) static
Definition at line 2290 of file libmysql.c.
 {
   set_stmt_error(stmt, CR_NO_RESULT_SET, unknown_sqlstate, NULL);
   return 1;
 }
References CR_NO_RESULT_SET, NULL, set_stmt_error(), and unknown_sqlstate.
stmt_read_row_no_result_set() [2/2]
static int stmt_read_row_no_result_set (MYSQL_STMT * stmt, unsigned char ** row) static
Referenced by mysql_stmt_fetch(), mysql_stmt_init(), and reset_stmt_handle().
stmt_read_row_unbuffered()
static int stmt_read_row_unbuffered (MYSQL_STMT * stmt, unsigned char ** row) static
Definition at line 2174 of file libmysql.c.
 {
   int rc= 1;
   MYSQL *mysql= stmt->mysql;
   /*
     This function won't be called if stmt->field_count is zero
     or execution wasn't done: this is ensured by mysql_stmt_execute.
   */
   if (!mysql)
   {
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     return 1;
   }
   if (mysql->status != MYSQL_STATUS_STATEMENT_GET_RESULT)
   {
     set_stmt_error(stmt, stmt->unbuffered_fetch_cancelled ?
                    CR_FETCH_CANCELED : CR_COMMANDS_OUT_OF_SYNC,
                    unknown_sqlstate, NULL);
     goto error;
   }
   if ((*mysql->methods->unbuffered_fetch)(mysql, (char**) row))
   {
     set_stmt_errmsg(stmt, &mysql->net);
     /*
       If there was an error, there are no more pending rows:
       reset statement status to not hang up in following
       mysql_stmt_close (it will try to flush result set before
       closing the statement).
     */
     mysql->status= MYSQL_STATUS_READY;
     goto error;
   }
   if (!*row)
   {
     mysql->status= MYSQL_STATUS_READY;
     rc= MYSQL_NO_DATA;
     goto error;
   }
   return 0;
 error:
   if (mysql->unbuffered_fetch_owner == &stmt->unbuffered_fetch_cancelled)
     mysql->unbuffered_fetch_owner= 0;
   return rc;
 }
References CR_COMMANDS_OUT_OF_SYNC, CR_FETCH_CANCELED, CR_SERVER_LOST, error(), st_mysql::methods, st_mysql_stmt::mysql, MYSQL_NO_DATA, MYSQL_STATUS_READY, MYSQL_STATUS_STATEMENT_GET_RESULT, st_mysql::net, NULL, set_stmt_errmsg(), set_stmt_error(), st_mysql::status, st_mysql_methods::unbuffered_fetch, st_mysql_stmt::unbuffered_fetch_cancelled, st_mysql::unbuffered_fetch_owner, and unknown_sqlstate.
Referenced by prepare_to_fetch_result().
stmt_update_metadata()
static void stmt_update_metadata (MYSQL_STMT * stmt, MYSQL_ROWS * data) static
Definition at line 4291 of file libmysql.c.
 {
   MYSQL_BIND  *my_bind, *end;
   MYSQL_FIELD *field;
   uchar *null_ptr, bit;
   uchar *row= (uchar*) data->data;
 #ifndef DBUG_OFF
   uchar *row_end= row + data->length;
 #endif
   null_ptr= row;
   row+= (stmt->field_count+9)/8;        /* skip null bits */
   bit= 4;                   /* first 2 bits are reserved */
   /* Go through all fields and calculate metadata */
   for (my_bind= stmt->bind, end= my_bind + stmt->field_count, field= stmt->fields ;
        my_bind < end ;
        my_bind++, field++)
   {
     if (!(*null_ptr & bit))
       (*my_bind->skip_result)(my_bind, field, &row);
     DBUG_ASSERT(row <= row_end);
     if (!((bit<<=1) & 255))
     {
       bit= 1;                   /* To next uchar */
       null_ptr++;
     }
   }
 }
References st_mysql_stmt::bind, DBUG_ASSERT, endif(), st_mysql_stmt::field_count, st_mysql_stmt::fields, and st_mysql_bind::skip_result.
Referenced by mysql_stmt_store_result().
store_param()
static my_bool store_param (MYSQL_STMT * stmt, MYSQL_BIND * param) static
Definition at line 1984 of file libmysql.c.
 {
   NET *net= &stmt->mysql->net;
   DBUG_ENTER("store_param");
   DBUG_PRINT("enter",("type: %d  buffer: 0x%lx  length: %lu  is_null: %d",
               param->buffer_type,
               (long) (param->buffer ? param->buffer : NullS),
                       *param->length, *param->is_null));
   if (*param->is_null)
     store_param_null(net, param);
   else
   {
     /*
       Param->length should ALWAYS point to the correct length for the type
       Either to the length pointer given by the user or param->buffer_length
     */
     if ((my_realloc_str(net, *param->length)))
     {
       set_stmt_errmsg(stmt, net);
       DBUG_RETURN(1);
     }
     (*param->store_param_func)(net, param);
   }
   DBUG_RETURN(0);
 }
References st_mysql_bind::buffer, st_mysql_bind::buffer_type, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql_bind::is_null, st_mysql_bind::length, my_realloc_str(), st_mysql_stmt::mysql, st_mysql::net, NullS, set_stmt_errmsg(), st_mysql_bind::store_param_func, and store_param_null().
Referenced by cli_stmt_execute().
store_param_date()
static void store_param_date (NET * net, MYSQL_BIND * param) static
Definition at line 1934 of file libmysql.c.
 {
   MYSQL_TIME tm= *((MYSQL_TIME *) param->buffer);
   tm.hour= tm.minute= tm.second= tm.second_part= 0;
   net_store_datetime(net, &tm);
 }
References st_mysql_bind::buffer, st_mysql_time::hour, st_mysql_time::minute, net_store_datetime(), st_mysql_time::second, and st_mysql_time::second_part.
Referenced by mysql_stmt_bind_param().
store_param_datetime()
static void store_param_datetime (NET * net, MYSQL_BIND * param) static
Definition at line 1941 of file libmysql.c.
 {
   MYSQL_TIME *tm= (MYSQL_TIME *) param->buffer;
   net_store_datetime(net, tm);
 }
References st_mysql_bind::buffer, and net_store_datetime().
Referenced by mysql_stmt_bind_param().
store_param_double()
static void store_param_double (NET * net, MYSQL_BIND * param) static
Definition at line 1876 of file libmysql.c.
 {
   double value= *(double*) param->buffer;
   float8store(net->write_pos, value);
   net->write_pos+= 8;
 }
References st_mysql_bind::buffer, float8store, and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_float()
static void store_param_float (NET * net, MYSQL_BIND * param) static
Definition at line 1869 of file libmysql.c.
 {
   float value= *(float*) param->buffer;
   float4store(net->write_pos, value);
   net->write_pos+= 4;
 }
References st_mysql_bind::buffer, float4store, and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_int32()
static void store_param_int32 (NET * net, MYSQL_BIND * param) static
Definition at line 1855 of file libmysql.c.
 {
   int32 value= *(int32*) param->buffer;
   int4store(net->write_pos,value);
   net->write_pos+=4;
 }
References st_mysql_bind::buffer, int4store, and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_int64()
static void store_param_int64 (NET * net, MYSQL_BIND * param) static
Definition at line 1862 of file libmysql.c.
 {
   longlong value= *(longlong*) param->buffer;
   int8store(net->write_pos,value);
   net->write_pos+= 8;
 }
References st_mysql_bind::buffer, int8store, and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_null()
static void store_param_null (NET * net, MYSQL_BIND * param) static
Definition at line 1971 of file libmysql.c.
 {
   uint pos= param->param_number;
   net->buff[pos/8]|=  (uchar) (1 << (pos & 7));
 }
References st_net::buff, st_mysql_bind::param_number, and pos().
Referenced by store_param().
store_param_short()
static void store_param_short (NET * net, MYSQL_BIND * param) static
Definition at line 1848 of file libmysql.c.
 {
   short value= *(short*) param->buffer;
   int2store(net->write_pos,value);
   net->write_pos+=2;
 }
References st_mysql_bind::buffer, int2store, and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_str()
static void store_param_str (NET * net, MYSQL_BIND * param) static
Definition at line 1947 of file libmysql.c.
 {
   /* param->length is always set in mysql_stmt_bind_param */
   ulong length= *param->length;
   uchar *to= net_store_length(net->write_pos, length);
   memcpy(to, param->buffer, length);
   net->write_pos= to+length;
 }
References st_mysql_bind::buffer, G3D::length(), st_mysql_bind::length, memcpy, net_store_length(), and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_time()
static void store_param_time (NET * net, MYSQL_BIND * param) static
Definition at line 1883 of file libmysql.c.
 {
   MYSQL_TIME *tm= (MYSQL_TIME *) param->buffer;
   char buff[MAX_TIME_REP_LENGTH], *pos;
   uint length;
   pos= buff+1;
   pos[0]= tm->neg ? 1: 0;
   int4store(pos+1, tm->day);
   pos[5]= (uchar) tm->hour;
   pos[6]= (uchar) tm->minute;
   pos[7]= (uchar) tm->second;
   int4store(pos+8, tm->second_part);
   if (tm->second_part)
     length= 12;
   else if (tm->hour || tm->minute || tm->second || tm->day)
     length= 8;
   else
     length= 0;
   buff[0]= (char) length++;
   memcpy((char *)net->write_pos, buff, length);
   net->write_pos+= length;
 }
References st_mysql_bind::buffer, st_mysql_time::day, st_mysql_time::hour, int4store, G3D::length(), MAX_TIME_REP_LENGTH, memcpy, st_mysql_time::minute, st_mysql_time::neg, pos(), st_mysql_time::second, st_mysql_time::second_part, and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_tinyint()
static void store_param_tinyint (NET * net, MYSQL_BIND * param) static
Definition at line 1843 of file libmysql.c.
 {
   *(net->write_pos++)= *(uchar *) param->buffer;
 }
References st_mysql_bind::buffer, and st_net::write_pos.
Referenced by mysql_stmt_bind_param().
store_param_type()
static void store_param_type (unsigned char ** pos, MYSQL_BIND * param) static
Definition at line 1819 of file libmysql.c.
 {
   uint typecode= param->buffer_type | (param->is_unsigned ? 32768 : 0);
   int2store(*pos, typecode);
   *pos+= 2;
 }
References st_mysql_bind::buffer_type, int2store, st_mysql_bind::is_unsigned, and pos().
Referenced by cli_stmt_execute().
update_stmt_fields()
static void update_stmt_fields (MYSQL_STMT * stmt) static
Update result set columns metadata if it was sent again in reply to COM_STMT_EXECUTE.
Note
If the new field count is different from the original one, an error is set and no update is performed.
Definition at line 1687 of file libmysql.c.
 {
   MYSQL_FIELD *field= stmt->mysql->fields;
   MYSQL_FIELD *field_end= field + stmt->field_count;
   MYSQL_FIELD *stmt_field= stmt->fields;
   MYSQL_BIND *my_bind= stmt->bind_result_done ? stmt->bind : 0;
   if (stmt->field_count != stmt->mysql->field_count)
   {
     /*
       The tables used in the statement were altered,
       and the query now returns a different number of columns.
       There is no way to continue without reallocating the bind
       array:
       - if the number of columns increased, mysql_stmt_fetch()
       will write beyond allocated memory
       - if the number of columns decreased, some user-bound
       buffers will be left unassigned without user knowing
       that.
     */
     set_stmt_error(stmt, CR_NEW_STMT_METADATA, unknown_sqlstate, NULL);
     return;
   }
   for (; field < field_end; ++field, ++stmt_field)
   {
     stmt_field->charsetnr= field->charsetnr;
     stmt_field->length   = field->length;
     stmt_field->type     = field->type;
     stmt_field->flags    = field->flags;
     stmt_field->decimals = field->decimals;
     if (my_bind)
     {
       /* Ignore return value: it should be 0 if bind_result succeeded. */
       (void) setup_one_fetch_function(my_bind++, stmt_field);
     }
   }
 }
References st_mysql_stmt::bind, st_mysql_stmt::bind_result_done, st_mysql_field::charsetnr, CR_NEW_STMT_METADATA, st_mysql_field::decimals, st_mysql::field_count, st_mysql_stmt::field_count, st_mysql::fields, st_mysql_stmt::fields, st_mysql_field::flags, st_mysql_field::length, st_mysql_stmt::mysql, NULL, set_stmt_error(), setup_one_fetch_function(), st_mysql_field::type, and unknown_sqlstate.
Referenced by reinit_result_set_metadata().
Variable Documentation
int_is_null_false
my_bool int_is_null_false = 0 static
Definition at line 2566 of file libmysql.c.
Referenced by mysql_stmt_bind_param().
int_is_null_true
my_bool int_is_null_true = 1 static
Definition at line 2565 of file libmysql.c.
Referenced by mysql_stmt_bind_param().
max_allowed_packet
ulong max_allowed_packet = 1024L*1024L*1024L
Definition at line 68 of file libmysql.c.
Referenced by my_net_local_init().
mysql_client_init
my_bool mysql_client_init = 0 static
Definition at line 94 of file libmysql.c.
Referenced by mysql_server_end(), and mysql_server_init().
mysql_internal_parameters
MYSQL_PARAMETERS mysql_internal_parameters static
Initial value:
=
{&max_allowed_packet, &net_buffer_length, 0}
Definition at line 220 of file libmysql.c.
Referenced by mysql_get_parameters().
net_buffer_length
ulong net_buffer_length =8192
Definition at line 67 of file libmysql.c.
Referenced by my_net_local_init().
org_my_init_done
my_bool org_my_init_done = 0 static
Definition at line 95 of file libmysql.c.
Referenced by mysql_server_end(), and mysql_server_init().