Azerotcore-wotlk: ReputationMgr Class Reference
ReputationMgr Class Reference
#include <ReputationMgr.h>
Public Member Functions
ReputationMgr (Player *owner)
~ReputationMgr ()
void SaveToDB (CharacterDatabaseTransaction trans)
void LoadFromDB (PreparedQueryResult result)
uint8 GetVisibleFactionCount () const
uint8 GetHonoredFactionCount () const
uint8 GetReveredFactionCount () const
uint8 GetExaltedFactionCount () const
FactionStateList const & GetStateList () const
FactionState const * GetState (FactionEntry const *factionEntry) const
FactionState const * GetState (RepListID id) const
bool IsAtWar (uint32 faction_id) const
bool IsAtWar (FactionEntry const *factionEntry) const
int32 GetReputation (uint32 faction_id) const
int32 GetReputation (FactionEntry const *factionEntry) const
int32 GetBaseReputation (FactionEntry const *factionEntry) const
ReputationRank GetRank (FactionEntry const *factionEntry) const
ReputationRank GetBaseRank (FactionEntry const *factionEntry) const
uint32 GetReputationRankStrIndex (FactionEntry const *factionEntry) const
ReputationRank const * GetForcedRankIfAny (FactionTemplateEntry const *factionTemplateEntry) const
bool SetReputation (FactionEntry const *factionEntry, int32 standing)
bool ModifyReputation (FactionEntry const *factionEntry, int32 standing, bool spillOverOnly=false)
void SetVisible (FactionTemplateEntry const *factionTemplateEntry)
void SetVisible (FactionEntry const *factionEntry)
void SetAtWar (RepListID repListID, bool on)
void SetInactive (RepListID repListID, bool on)
void ApplyForceReaction (uint32 faction_id, ReputationRank rank, bool apply)
bool SetOneFactionReputation (FactionEntry const *factionEntry, int32 standing, bool incremental)
Public for chat command needs.
void SendInitialReputations ()
void SendForceReactions ()
void SendState (FactionState const *faction)
void SendStates ()
Static Public Member Functions
static ReputationRank ReputationToRank (int32 standing)
Static Public Attributes
static const int32 PointsInRank [MAX_REPUTATION_RANK] = {36000, 3000, 3000, 3000, 6000, 12000, 21000, 1000}
static const int32 Reputation_Cap = 42999
static const int32 Reputation_Bottom = -42000
Private Member Functions
void Initialize ()
uint32 GetDefaultStateFlags (FactionEntry const *factionEntry) const
bool SetReputation (FactionEntry const *factionEntry, int32 standing, bool incremental, bool spillOverOnly)
void SetVisible (FactionState *faction)
void SetAtWar (FactionState *faction, bool atWar) const
void SetInactive (FactionState *faction, bool inactive) const
void SendVisible (FactionState const *faction) const
void UpdateRankCounters (ReputationRank old_rank, ReputationRank new_rank)
Private Attributes
Player * _player
FactionStateList _factions
ForcedReactions _forcedReactions
uint8 _visibleFactionCount: 8
uint8 _honoredFactionCount: 8
uint8 _reveredFactionCount: 8
uint8 _exaltedFactionCount: 8
bool _sendFactionIncreased
Detailed Description
Definition at line 50 of file ReputationMgr.h.
Constructor & Destructor Documentation
ReputationMgr()
ReputationMgr::ReputationMgr (Player * owner) inline explicit
Definition at line 53 of file ReputationMgr.h.
                                           : _player(owner),
         _visibleFactionCount(0), _honoredFactionCount(0), _reveredFactionCount(0), _exaltedFactionCount(0), _sendFactionIncreased(false) {}
~ReputationMgr()
ReputationMgr::~ReputationMgr () inline
Definition at line 55 of file ReputationMgr.h.
 {}
Member Function Documentation
ApplyForceReaction()
void ReputationMgr::ApplyForceReaction (uint32 faction_id, ReputationRank rank, bool apply)
Definition at line 126 of file ReputationMgr.cpp.
 {
     if (apply)
         _forcedReactions[faction_id] = rank;
     else
         _forcedReactions.erase(faction_id);
 }
References _forcedReactions, and ByteConverter::apply().
Referenced by AuraEffect::HandleForceReaction().
GetBaseRank()
ReputationRank ReputationMgr::GetBaseRank (FactionEntry const * factionEntry) const
Definition at line 120 of file ReputationMgr.cpp.
 {
     int32 reputation = GetBaseReputation(factionEntry);
     return ReputationToRank(reputation);
 }
References GetBaseReputation(), and ReputationToRank().
Referenced by Initialize().
GetBaseReputation()
int32 ReputationMgr::GetBaseReputation (FactionEntry const * factionEntry) const
Definition at line 80 of file ReputationMgr.cpp.
 {
     if (!factionEntry)
         return 0;
     uint32 raceMask = _player->getRaceMask();
     uint32 classMask = _player->getClassMask();
     for (int i = 0; i < 4; i++)
     {
         if ((factionEntry->BaseRepRaceMask[i] & raceMask  ||
                 (factionEntry->BaseRepRaceMask[i] == 0  &&
                  factionEntry->BaseRepClassMask[i] != 0)) &&
                 (factionEntry->BaseRepClassMask[i] & classMask ||
                  factionEntry->BaseRepClassMask[i] == 0))
             return factionEntry->BaseRepValue[i];
     }
     // in faction.dbc exist factions with (RepListId >=0, listed in character reputation list) with all BaseRepRaceMask[i] == 0
     return 0;
 }
References _player, FactionEntry::BaseRepClassMask, FactionEntry::BaseRepRaceMask, FactionEntry::BaseRepValue, Unit::getClassMask(), and Unit::getRaceMask().
Referenced by GetBaseRank(), GetReputation(), LoadFromDB(), and SetOneFactionReputation().
GetDefaultStateFlags()
uint32 ReputationMgr::GetDefaultStateFlags (FactionEntry const * factionEntry) const private
Definition at line 134 of file ReputationMgr.cpp.
 {
     if (!factionEntry)
         return 0;
     uint32 raceMask = _player->getRaceMask();
     uint32 classMask = _player->getClassMask();
     for (int i = 0; i < 4; i++)
     {
         if ((factionEntry->BaseRepRaceMask[i] & raceMask  ||
                 (factionEntry->BaseRepRaceMask[i] == 0  &&
                  factionEntry->BaseRepClassMask[i] != 0)) &&
                 (factionEntry->BaseRepClassMask[i] & classMask ||
                  factionEntry->BaseRepClassMask[i] == 0))
             return factionEntry->ReputationFlags[i];
     }
     return 0;
 }
References _player, FactionEntry::BaseRepClassMask, FactionEntry::BaseRepRaceMask, Unit::getClassMask(), Unit::getRaceMask(), and FactionEntry::ReputationFlags.
Referenced by Initialize().
GetExaltedFactionCount()
uint8 ReputationMgr::GetExaltedFactionCount () const inline
Definition at line 69 of file ReputationMgr.h.
 { return _exaltedFactionCount; }
References _exaltedFactionCount.
GetForcedRankIfAny()
ReputationRank const* ReputationMgr::GetForcedRankIfAny (FactionTemplateEntry const * factionTemplateEntry) const inline
Definition at line 98 of file ReputationMgr.h.
     {
         ForcedReactions::const_iterator forceItr = _forcedReactions.find(factionTemplateEntry->faction);
         return forceItr != _forcedReactions.end() ? &forceItr->second : nullptr;
     }
References _forcedReactions, and FactionTemplateEntry::faction.
Referenced by Unit::_IsValidAttackTarget(), and Unit::GetReactionTo().
GetHonoredFactionCount()
uint8 ReputationMgr::GetHonoredFactionCount () const inline
Definition at line 67 of file ReputationMgr.h.
 { return _honoredFactionCount; }
References _honoredFactionCount.
GetRank()
ReputationRank ReputationMgr::GetRank (FactionEntry const * factionEntry) const
Definition at line 114 of file ReputationMgr.cpp.
 {
     int32 reputation = GetReputation(factionEntry);
     return ReputationToRank(reputation);
 }
References GetReputation(), and ReputationToRank().
Referenced by Player::GetReputationRank(), GetReputationRankStrIndex(), character_commandscript::HandleCharacterReputationCommand(), LoadFromDB(), Player::RewardReputation(), and SetReputation().
GetReputation() [1/2]
int32 ReputationMgr::GetReputation (FactionEntry const * factionEntry) const
Definition at line 102 of file ReputationMgr.cpp.
 {
     // Faction without recorded reputation. Just ignore.
     if (!factionEntry)
         return 0;
     if (FactionState const* state = GetState(factionEntry))
         return GetBaseReputation(factionEntry) + state->Standing;
     return 0;
 }
References GetBaseReputation(), and GetState().
GetReputation() [2/2]
int32 ReputationMgr::GetReputation (uint32 faction_id) const
Definition at line 67 of file ReputationMgr.cpp.
 {
     FactionEntry const* factionEntry = sFactionStore.LookupEntry(faction_id);
     if (!factionEntry)
     {
         LOG_ERROR("reputation", "ReputationMgr::GetReputation: Can't get reputation of %s for unknown faction (faction id) #%u.", _player->GetName().c_str(), faction_id);
         return 0;
     }
     return GetReputation(factionEntry);
 }
References _player, WorldObject::GetName(), LOG_ERROR, and sFactionStore.
Referenced by GetRank(), Player::GetReputation(), character_commandscript::HandleCharacterReputationCommand(), spell_gen_oracle_wolvar_reputation::HandleDummy(), lookup_commandscript::HandleLookupFactionCommand(), modify_commandscript::HandleModifyRepCommand(), quest_commandscript::HandleQuestComplete(), and AchievementMgr::UpdateAchievementCriteria().
GetReputationRankStrIndex()
uint32 ReputationMgr::GetReputationRankStrIndex (FactionEntry const * factionEntry) const inline
Definition at line 93 of file ReputationMgr.h.
     {
         return ReputationRankStrIndex[GetRank(factionEntry)];
     };
References GetRank(), and ReputationRankStrIndex.
Referenced by lookup_commandscript::HandleLookupFactionCommand().
GetReveredFactionCount()
uint8 ReputationMgr::GetReveredFactionCount () const inline
Definition at line 68 of file ReputationMgr.h.
 { return _reveredFactionCount; }
References _reveredFactionCount.
GetState() [1/2]
FactionState const* ReputationMgr::GetState (FactionEntry const * factionEntry) const inline
Definition at line 73 of file ReputationMgr.h.
     {
         return factionEntry->CanHaveReputation() ? GetState(factionEntry->reputationListID) : nullptr;
     }
References FactionEntry::CanHaveReputation(), and FactionEntry::reputationListID.
Referenced by Unit::_IsValidAttackTarget(), GetReputation(), lookup_commandscript::HandleLookupFactionCommand(), modify_commandscript::HandleModifyRepCommand(), and IsAtWar().
GetState() [2/2]
FactionState const* ReputationMgr::GetState (RepListID id) const inline
Definition at line 78 of file ReputationMgr.h.
     {
         FactionStateList::const_iterator repItr = _factions.find (id);
         return repItr != _factions.end() ? &repItr->second : nullptr;
     }
References _factions.
GetStateList()
FactionStateList const& ReputationMgr::GetStateList () const inline
Definition at line 71 of file ReputationMgr.h.
 { return _factions; }
References _factions.
Referenced by character_commandscript::HandleCharacterReputationCommand().
GetVisibleFactionCount()
uint8 ReputationMgr::GetVisibleFactionCount () const inline
Definition at line 66 of file ReputationMgr.h.
 { return _visibleFactionCount; }
References _visibleFactionCount.
Initialize()
void ReputationMgr::Initialize (void) private
Definition at line 252 of file ReputationMgr.cpp.
 {
     _factions.clear();
     _visibleFactionCount = 0;
     _honoredFactionCount = 0;
     _reveredFactionCount = 0;
     _exaltedFactionCount = 0;
     _sendFactionIncreased = false;
     for (unsigned int i = 1; i < sFactionStore.GetNumRows(); i++)
     {
         FactionEntry const* factionEntry = sFactionStore.LookupEntry(i);
         if (factionEntry && (factionEntry->reputationListID >= 0))
         {
             FactionState newFaction;
             newFaction.ID = factionEntry->ID;
             newFaction.ReputationListID = factionEntry->reputationListID;
             newFaction.Standing = 0;
             newFaction.Flags = GetDefaultStateFlags(factionEntry);
             newFaction.needSend = true;
             newFaction.needSave = true;
             if (newFaction.Flags & FACTION_FLAG_VISIBLE)
                 ++_visibleFactionCount;
             UpdateRankCounters(REP_HOSTILE, GetBaseRank(factionEntry));
             _factions[newFaction.ReputationListID] = newFaction;
         }
     }
 }
References _exaltedFactionCount, _factions, _honoredFactionCount, _reveredFactionCount, _sendFactionIncreased, _visibleFactionCount, FACTION_FLAG_VISIBLE, FactionState::Flags, GetBaseRank(), GetDefaultStateFlags(), FactionState::ID, FactionEntry::ID, FactionState::needSave, FactionState::needSend, REP_HOSTILE, FactionState::ReputationListID, FactionEntry::reputationListID, sFactionStore, FactionState::Standing, and UpdateRankCounters().
Referenced by LoadFromDB().
IsAtWar() [1/2]
bool ReputationMgr::IsAtWar (FactionEntry const * factionEntry) const
Definition at line 57 of file ReputationMgr.cpp.
 {
     if (!factionEntry)
         return false;
     if (FactionState const* factionState = GetState(factionEntry))
         return (factionState->Flags & FACTION_FLAG_AT_WAR);
     return false;
 }
References FACTION_FLAG_AT_WAR, and GetState().
IsAtWar() [2/2]
bool ReputationMgr::IsAtWar (uint32 faction_id) const
Definition at line 44 of file ReputationMgr.cpp.
 {
     FactionEntry const* factionEntry = sFactionStore.LookupEntry(faction_id);
     if (!factionEntry)
     {
         LOG_ERROR("reputation", "ReputationMgr::IsAtWar: Can't get AtWar flag of %s for unknown faction (faction id) #%u.", _player->GetName().c_str(), faction_id);
         return 0;
     }
     return IsAtWar(factionEntry);
 }
References _player, WorldObject::GetName(), LOG_ERROR, and sFactionStore.
Referenced by Unit::GetReactionTo().
LoadFromDB()
void ReputationMgr::LoadFromDB (PreparedQueryResult result)
Definition at line 513 of file ReputationMgr.cpp.
 {
     // Set initial reputations (so everything is nifty before DB data load)
     Initialize();
     //QueryResult* result = CharacterDatabase.PQuery("SELECT faction, standing, flags FROM character_reputation WHERE guid = '%u'", GetGUID().GetCounter());
     if (result)
     {
         do
         {
             Field* fields = result->Fetch();
             FactionEntry const* factionEntry = sFactionStore.LookupEntry(fields[0].GetUInt16());
             if (factionEntry && (factionEntry->reputationListID >= 0))
             {
                 FactionState* faction = &_factions[factionEntry->reputationListID];
                 // update standing to current
                 faction->Standing = fields[1].GetInt32();
                 // update counters
                 int32 BaseRep = GetBaseReputation(factionEntry);
                 ReputationRank old_rank = ReputationToRank(BaseRep);
                 ReputationRank new_rank = ReputationToRank(BaseRep + faction->Standing);
                 UpdateRankCounters(old_rank, new_rank);
                 uint32 dbFactionFlags = fields[2].GetUInt16();
                 if (dbFactionFlags & FACTION_FLAG_VISIBLE)
                     SetVisible(faction);                    // have internal checks for forced invisibility
                 if (dbFactionFlags & FACTION_FLAG_INACTIVE)
                     SetInactive(faction, true);              // have internal checks for visibility requirement
                 if (dbFactionFlags & FACTION_FLAG_AT_WAR)  // DB at war
                 {
                     // Xinef: dont set at war for friendly hidden reputations
                     SetAtWar(faction, bool(!(dbFactionFlags & FACTION_FLAG_HIDDEN) || GetRank(factionEntry) < REP_NEUTRAL)); // have internal checks for FACTION_FLAG_PEACE_FORCED
                 }
                 else                                        // DB not at war
                 {
                     // allow remove if visible (and then not FACTION_FLAG_INVISIBLE_FORCED or FACTION_FLAG_HIDDEN)
                     if (faction->Flags & FACTION_FLAG_VISIBLE)
                         SetAtWar(faction, false);            // have internal checks for FACTION_FLAG_PEACE_FORCED
                 }
                 // set atWar for hostile
                 if (GetRank(factionEntry) <= REP_HOSTILE)
                     SetAtWar(faction, true);
                 // reset changed flag if values similar to saved in DB
                 if (faction->Flags == dbFactionFlags)
                 {
                     faction->needSend = false;
                     faction->needSave = false;
                 }
             }
         } while (result->NextRow());
     }
 }
References _factions, FACTION_FLAG_AT_WAR, FACTION_FLAG_HIDDEN, FACTION_FLAG_INACTIVE, FACTION_FLAG_VISIBLE, FactionState::Flags, GetBaseReputation(), Field::GetInt32(), GetRank(), Field::GetUInt16(), Initialize(), FactionState::needSave, FactionState::needSend, REP_HOSTILE, REP_NEUTRAL, FactionEntry::reputationListID, ReputationToRank(), SetAtWar(), SetInactive(), SetVisible(), sFactionStore, FactionState::Standing, and UpdateRankCounters().
Referenced by Player::LoadFromDB().
ModifyReputation()
bool ReputationMgr::ModifyReputation (FactionEntry const * factionEntry, int32 standing, bool spillOverOnly = false) inline
Definition at line 109 of file ReputationMgr.h.
     {
         return SetReputation(factionEntry, standing, true, spillOverOnly);
     }
References SetReputation().
Referenced by Spell::EffectReputation(), OutdoorPvPSI::HandleAreaTrigger(), and Player::RewardReputation().
ReputationToRank()
ReputationRank ReputationMgr::ReputationToRank (int32 standing) static
Definition at line 32 of file ReputationMgr.cpp.
 {
     int32 limit = Reputation_Cap + 1;
     for (int i = MAX_REPUTATION_RANK - 1; i >= MIN_REPUTATION_RANK; --i)
     {
         limit -= PointsInRank[i];
         if (standing >= limit)
             return ReputationRank(i);
     }
     return MIN_REPUTATION_RANK;
 }
References MAX_REPUTATION_RANK, MIN_REPUTATION_RANK, PointsInRank, and Reputation_Cap.
Referenced by GetBaseRank(), GetRank(), LoadFromDB(), and SetOneFactionReputation().
SaveToDB()
void ReputationMgr::SaveToDB (CharacterDatabaseTransaction trans)
Definition at line 575 of file ReputationMgr.cpp.
 {
     for (FactionStateList::iterator itr = _factions.begin(); itr != _factions.end(); ++itr)
     {
         if (itr->second.needSave)
         {
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_REPUTATION_BY_FACTION);
             stmt->setUInt32(0, _player->GetGUID().GetCounter());
             stmt->setUInt16(1, uint16(itr->second.ID));
             trans->Append(stmt);
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHAR_REPUTATION_BY_FACTION);
             stmt->setUInt32(0, _player->GetGUID().GetCounter());
             stmt->setUInt16(1, uint16(itr->second.ID));
             stmt->setInt32(2, itr->second.Standing);
             stmt->setUInt16(3, uint16(itr->second.Flags));
             trans->Append(stmt);
             itr->second.needSave = false;
         }
     }
 }
References _factions, _player, CHAR_DEL_CHAR_REPUTATION_BY_FACTION, CHAR_INS_CHAR_REPUTATION_BY_FACTION, CharacterDatabase, ObjectGuid::GetCounter(), Object::GetGUID(), PreparedStatementBase::setInt32(), PreparedStatementBase::setUInt16(), and PreparedStatementBase::setUInt32().
Referenced by Player::SaveToDB().
SendForceReactions()
void ReputationMgr::SendForceReactions ()
Definition at line 154 of file ReputationMgr.cpp.
 {
     WorldPacket data;
     data.Initialize(SMSG_SET_FORCED_REACTIONS, 4 + _forcedReactions.size() * (4 + 4));
     data << uint32(_forcedReactions.size());
     for (ForcedReactions::const_iterator itr = _forcedReactions.begin(); itr != _forcedReactions.end(); ++itr)
     {
         data << uint32(itr->first);                         // faction_id (Faction.dbc)
         data << uint32(itr->second);                        // reputation rank
     }
     _player->SendDirectMessage(&data);
 }
References _forcedReactions, _player, Player::SendDirectMessage(), and SMSG_SET_FORCED_REACTIONS.
Referenced by AuraEffect::HandleForceReaction(), and Player::SendInitialPacketsBeforeAddToMap().
SendInitialReputations()
void ReputationMgr::SendInitialReputations ()
Definition at line 200 of file ReputationMgr.cpp.
 {
     WorldPacket data(SMSG_INITIALIZE_FACTIONS, (4 + 128 * 5));
     data << uint32 (0x00000080);
     RepListID a = 0;
     for (FactionStateList::iterator itr = _factions.begin(); itr != _factions.end(); ++itr)
     {
         // fill in absent fields
         for (; a != itr->first; a++)
         {
             data << uint8  (0x00);
             data << uint32 (0x00000000);
         }
         // fill in encountered data
         data << uint8  (itr->second.Flags);
         data << uint32 (itr->second.Standing);
         itr->second.needSend = false;
         ++a;
     }
     // fill in absent fields
     for (; a != 128; a++)
     {
         data << uint8  (0x00);
         data << uint32 (0x00000000);
     }
     _player->SendDirectMessage(&data);
 }
References _factions, _player, mpq::a, Player::SendDirectMessage(), and SMSG_INITIALIZE_FACTIONS.
Referenced by Player::SendInitialPacketsBeforeAddToMap().
SendState()
void ReputationMgr::SendState (FactionState const * faction)
Definition at line 167 of file ReputationMgr.cpp.
 {
     uint32 count = 1;
     WorldPacket data(SMSG_SET_FACTION_STANDING, 17);
     data << float(0);
     data << uint8(_sendFactionIncreased);
     _sendFactionIncreased = false; // Reset
     size_t p_count = data.wpos();
     data << uint32(count);
     data << uint32(faction->ReputationListID);
     data << uint32(faction->Standing);
     for (FactionStateList::iterator itr = _factions.begin(); itr != _factions.end(); ++itr)
     {
         if (itr->second.needSend)
         {
             itr->second.needSend = false;
             if (itr->second.ReputationListID != faction->ReputationListID)
             {
                 data << uint32(itr->second.ReputationListID);
                 data << uint32(itr->second.Standing);
                 ++count;
             }
         }
     }
     data.put<uint32>(p_count, count);
     _player->SendDirectMessage(&data);
 }
References _factions, _player, _sendFactionIncreased, count(), FactionState::ReputationListID, Player::SendDirectMessage(), SMSG_SET_FACTION_STANDING, and FactionState::Standing.
Referenced by modify_commandscript::HandleModifyRepCommand(), SendStates(), and SetReputation().
SendStates()
void ReputationMgr::SendStates ()
Definition at line 235 of file ReputationMgr.cpp.
 {
     for (FactionStateList::iterator itr = _factions.begin(); itr != _factions.end(); ++itr)
         SendState(&(itr->second));
 }
References _factions, and SendState().
Referenced by WorldSession::HandlePlayerLoginFromDB(), and WorldSession::HandleSetFactionCheat().
SendVisible()
void ReputationMgr::SendVisible (FactionState const * faction) const private
Definition at line 241 of file ReputationMgr.cpp.
 {
     if (_player->GetSession()->PlayerLoading())
         return;
     // make faction visible in reputation list at client
     WorldPacket data(SMSG_SET_FACTION_VISIBLE, 4);
     data << faction->ReputationListID;
     _player->SendDirectMessage(&data);
 }
References _player, Player::GetSession(), WorldSession::PlayerLoading(), FactionState::ReputationListID, Player::SendDirectMessage(), and SMSG_SET_FACTION_VISIBLE.
Referenced by SetVisible().
SetAtWar() [1/2]
void ReputationMgr::SetAtWar (FactionState * faction, bool atWar) const private
Definition at line 466 of file ReputationMgr.cpp.
 {
     // not allow declare war to own faction
     if (atWar && (faction->Flags & FACTION_FLAG_PEACE_FORCED))
         return;
     // already set
     if (((faction->Flags & FACTION_FLAG_AT_WAR) != 0) == atWar)
         return;
     if (atWar)
         faction->Flags |= FACTION_FLAG_AT_WAR;
     else
         faction->Flags &= ~FACTION_FLAG_AT_WAR;
     faction->needSend = true;
     faction->needSave = true;
 }
References FACTION_FLAG_AT_WAR, FACTION_FLAG_PEACE_FORCED, FactionState::Flags, FactionState::needSave, and FactionState::needSend.
SetAtWar() [2/2]
void ReputationMgr::SetAtWar (RepListID repListID, bool on)
Definition at line 453 of file ReputationMgr.cpp.
 {
     FactionStateList::iterator itr = _factions.find(repListID);
     if (itr == _factions.end())
         return;
     // always invisible or hidden faction can't change war state
     if (itr->second.Flags & (FACTION_FLAG_INVISIBLE_FORCED | FACTION_FLAG_HIDDEN))
         return;
     SetAtWar(&itr->second, on);
 }
References _factions, FACTION_FLAG_HIDDEN, and FACTION_FLAG_INVISIBLE_FORCED.
Referenced by WorldSession::HandleSetFactionAtWar(), LoadFromDB(), and SetOneFactionReputation().
SetInactive() [1/2]
void ReputationMgr::SetInactive (FactionState * faction, bool inactive) const private
Definition at line 494 of file ReputationMgr.cpp.
 {
     // always invisible or hidden faction can't be inactive
     if (inactive && ((faction->Flags & (FACTION_FLAG_INVISIBLE_FORCED | FACTION_FLAG_HIDDEN)) || !(faction->Flags & FACTION_FLAG_VISIBLE)))
         return;
     // already set
     if (((faction->Flags & FACTION_FLAG_INACTIVE) != 0) == inactive)
         return;
     if (inactive)
         faction->Flags |= FACTION_FLAG_INACTIVE;
     else
         faction->Flags &= ~FACTION_FLAG_INACTIVE;
     faction->needSend = true;
     faction->needSave = true;
 }
References FACTION_FLAG_HIDDEN, FACTION_FLAG_INACTIVE, FACTION_FLAG_INVISIBLE_FORCED, FACTION_FLAG_VISIBLE, FactionState::Flags, FactionState::needSave, and FactionState::needSend.
SetInactive() [2/2]
void ReputationMgr::SetInactive (RepListID repListID, bool on)
Definition at line 485 of file ReputationMgr.cpp.
 {
     FactionStateList::iterator itr = _factions.find(repListID);
     if (itr == _factions.end())
         return;
     SetInactive(&itr->second, on);
 }
References _factions.
Referenced by WorldSession::HandleSetFactionInactiveOpcode(), and LoadFromDB().
SetOneFactionReputation()
bool ReputationMgr::SetOneFactionReputation (FactionEntry const * factionEntry, int32 standing, bool incremental)
Public for chat command needs.
Definition at line 357 of file ReputationMgr.cpp.
 {
     FactionStateList::iterator itr = _factions.find(factionEntry->reputationListID);
     if (itr != _factions.end())
     {
         int32 BaseRep = GetBaseReputation(factionEntry);
         if (incremental)
         {
             // int32 *= float cause one point loss?
             standing = int32(floor((float)standing * sWorld->getRate(RATE_REPUTATION_GAIN) + 0.5f));
             standing += itr->second.Standing + BaseRep;
         }
         if (standing > Reputation_Cap)
             standing = Reputation_Cap;
         else if (standing < Reputation_Bottom)
             standing = Reputation_Bottom;
         ReputationRank old_rank = ReputationToRank(itr->second.Standing + BaseRep);
         ReputationRank new_rank = ReputationToRank(standing);
         itr->second.Standing = standing - BaseRep;
         itr->second.needSend = true;
         itr->second.needSave = true;
         SetVisible(&itr->second);
         if (new_rank <= REP_HOSTILE)
             SetAtWar(&itr->second, true);
         if (new_rank > old_rank)
             _sendFactionIncreased = true;
         sScriptMgr->OnPlayerReputationChange(_player, factionEntry->ID, standing, incremental);
         if (new_rank != old_rank)
             sScriptMgr->OnPlayerReputationRankChange(_player, factionEntry->ID, new_rank, old_rank, _sendFactionIncreased);
         UpdateRankCounters(old_rank, new_rank);
         _player->ReputationChanged(factionEntry);
         _player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS,          factionEntry->ID);
         _player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION,         factionEntry->ID);
         _player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION, factionEntry->ID);
         _player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION, factionEntry->ID);
         _player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION, factionEntry->ID);
         return true;
     }
     return false;
 }
References _factions, _player, _sendFactionIncreased, ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS, G3D::floor(), GetBaseReputation(), FactionEntry::ID, RATE_REPUTATION_GAIN, REP_HOSTILE, Reputation_Bottom, Reputation_Cap, Player::ReputationChanged(), FactionEntry::reputationListID, ReputationToRank(), SetAtWar(), SetVisible(), sScriptMgr, sWorld, Player::UpdateAchievementCriteria(), and UpdateRankCounters().
Referenced by modify_commandscript::HandleModifyRepCommand(), WorldSession::HandlePlayerLoginFromDB(), and SetReputation().
SetReputation() [1/2]
bool ReputationMgr::SetReputation (FactionEntry const * factionEntry, int32 standing) inline
Definition at line 105 of file ReputationMgr.h.
     {
         return SetReputation(factionEntry, standing, false, false);
     }
Referenced by spell_gen_oracle_wolvar_reputation::HandleDummy(), quest_commandscript::HandleQuestComplete(), ModifyReputation(), and Player::SetReputation().
SetReputation() [2/2]
bool ReputationMgr::SetReputation (FactionEntry const * factionEntry, int32 standing, bool incremental, bool spillOverOnly) private
Definition at line 285 of file ReputationMgr.cpp.
 {
     bool res = false;
     // if spillover definition exists in DB, override DBC
     if (const RepSpilloverTemplate* repTemplate = sObjectMgr->GetRepSpilloverTemplate(factionEntry->ID))
     {
         for (uint32 i = 0; i < MAX_SPILLOVER_FACTIONS; ++i)
         {
             if (repTemplate->faction[i])
             {
                 if (_player->GetReputationRank(repTemplate->faction[i]) <= ReputationRank(repTemplate->faction_rank[i]))
                 {
                     // bonuses are already given, so just modify standing by rate
                     int32 spilloverRep = int32(standing * repTemplate->faction_rate[i]);
                     SetOneFactionReputation(sFactionStore.LookupEntry(repTemplate->faction[i]), spilloverRep, incremental);
                 }
             }
         }
     }
     else
     {
         float spillOverRepOut = float(standing);
         // check for sub-factions that receive spillover
         SimpleFactionsList const* flist = GetFactionTeamList(factionEntry->ID);
         // if has no sub-factions, check for factions with same parent
         if (!flist && factionEntry->team && factionEntry->spilloverRateOut != 0.0f)
         {
             spillOverRepOut *= factionEntry->spilloverRateOut;
             if (FactionEntry const* parent = sFactionStore.LookupEntry(factionEntry->team))
             {
                 FactionStateList::iterator parentState = _factions.find(parent->reputationListID);
                 // some team factions have own reputation standing, in this case do not spill to other sub-factions
                 if (parentState != _factions.end() && (parentState->second.Flags & FACTION_FLAG_SPECIAL))
                 {
                     SetOneFactionReputation(parent, int32(spillOverRepOut), incremental);
                 }
                 else    // spill to "sister" factions
                 {
                     flist = GetFactionTeamList(factionEntry->team);
                 }
             }
         }
         if (flist)
         {
             // Spillover to affiliated factions
             for (SimpleFactionsList::const_iterator itr = flist->begin(); itr != flist->end(); ++itr)
             {
                 if (FactionEntry const* factionEntryCalc = sFactionStore.LookupEntry(*itr))
                 {
                     if (factionEntryCalc == factionEntry || GetRank(factionEntryCalc) > ReputationRank(factionEntryCalc->spilloverMaxRankIn))
                         continue;
                     int32 spilloverRep = int32(spillOverRepOut * factionEntryCalc->spilloverRateIn);
                     if (spilloverRep != 0 || !incremental)
                         res = SetOneFactionReputation(factionEntryCalc, spilloverRep, incremental);
                 }
             }
         }
     }
     // spillover done, update faction itself
     FactionStateList::iterator faction = _factions.find(factionEntry->reputationListID);
     if (faction != _factions.end())
     {
         // Xinef: if we update spillover only, do not update main reputation (rank exceeds creature reward rate)
         if (!spillOverOnly)
             res = SetOneFactionReputation(factionEntry, standing, incremental);
         // only this faction gets reported to client, even if it has no own visible standing
         SendState(&faction->second);
     }
     return res;
 }
References _factions, _player, FACTION_FLAG_SPECIAL, GetFactionTeamList(), GetRank(), Player::GetReputationRank(), FactionEntry::ID, MAX_SPILLOVER_FACTIONS, FactionEntry::reputationListID, SendState(), SetOneFactionReputation(), sFactionStore, sObjectMgr, FactionEntry::spilloverRateOut, and FactionEntry::team.
SetVisible() [1/3]
void ReputationMgr::SetVisible (FactionEntry const * factionEntry)
Definition at line 421 of file ReputationMgr.cpp.
 {
     if (factionEntry->reputationListID < 0)
         return;
     FactionStateList::iterator itr = _factions.find(factionEntry->reputationListID);
     if (itr == _factions.end())
         return;
     SetVisible(&itr->second);
 }
References _factions, FactionEntry::reputationListID, and SetVisible().
SetVisible() [2/3]
void ReputationMgr::SetVisible (FactionState * faction) private
Definition at line 433 of file ReputationMgr.cpp.
 {
     // always invisible or hidden faction can't be make visible
     // except if faction has FACTION_FLAG_SPECIAL
     if (faction->Flags & (FACTION_FLAG_INVISIBLE_FORCED | FACTION_FLAG_HIDDEN) && !(faction->Flags & FACTION_FLAG_SPECIAL))
         return;
     // already set
     if (faction->Flags & FACTION_FLAG_VISIBLE)
         return;
     faction->Flags |= FACTION_FLAG_VISIBLE;
     faction->needSend = true;
     faction->needSave = true;
     ++_visibleFactionCount;
     SendVisible(faction);
 }
References _visibleFactionCount, FACTION_FLAG_HIDDEN, FACTION_FLAG_INVISIBLE_FORCED, FACTION_FLAG_SPECIAL, FACTION_FLAG_VISIBLE, FactionState::Flags, FactionState::needSave, FactionState::needSend, and SendVisible().
SetVisible() [3/3]
void ReputationMgr::SetVisible (FactionTemplateEntry const * factionTemplateEntry)
Definition at line 410 of file ReputationMgr.cpp.
 {
     if (!factionTemplateEntry->faction)
         return;
     if (FactionEntry const* factionEntry = sFactionStore.LookupEntry(factionTemplateEntry->faction))
         // Never show factions of the opposing team
         if (!(factionEntry->BaseRepRaceMask[1] & _player->getRaceMask() && factionEntry->BaseRepValue[1] == Reputation_Bottom))
             SetVisible(factionEntry);
 }
References _player, FactionTemplateEntry::faction, Unit::getRaceMask(), Reputation_Bottom, and sFactionStore.
Referenced by Player::AddQuest(), WorldSession::HandleGossipHelloOpcode(), LoadFromDB(), SetOneFactionReputation(), and SetVisible().
UpdateRankCounters()
void ReputationMgr::UpdateRankCounters (ReputationRank old_rank, ReputationRank new_rank) private
Definition at line 598 of file ReputationMgr.cpp.
 {
     if (old_rank >= REP_EXALTED)
         --_exaltedFactionCount;
     if (old_rank >= REP_REVERED)
         --_reveredFactionCount;
     if (old_rank >= REP_HONORED)
         --_honoredFactionCount;
     if (new_rank >= REP_EXALTED)
         ++_exaltedFactionCount;
     if (new_rank >= REP_REVERED)
         ++_reveredFactionCount;
     if (new_rank >= REP_HONORED)
         ++_honoredFactionCount;
 }
References _exaltedFactionCount, _honoredFactionCount, _reveredFactionCount, REP_EXALTED, REP_HONORED, and REP_REVERED.
Referenced by Initialize(), LoadFromDB(), and SetOneFactionReputation().
Member Data Documentation
_exaltedFactionCount
uint8 ReputationMgr::_exaltedFactionCount private
Definition at line 146 of file ReputationMgr.h.
Referenced by GetExaltedFactionCount(), Initialize(), and UpdateRankCounters().
_factions
FactionStateList ReputationMgr::_factions private
Definition at line 141 of file ReputationMgr.h.
Referenced by GetState(), GetStateList(), Initialize(), LoadFromDB(), SaveToDB(), SendInitialReputations(), SendState(), SendStates(), SetAtWar(), SetInactive(), SetOneFactionReputation(), SetReputation(), and SetVisible().
_forcedReactions
ForcedReactions ReputationMgr::_forcedReactions private
Definition at line 142 of file ReputationMgr.h.
Referenced by ApplyForceReaction(), GetForcedRankIfAny(), and SendForceReactions().
_honoredFactionCount
uint8 ReputationMgr::_honoredFactionCount private
Definition at line 144 of file ReputationMgr.h.
Referenced by GetHonoredFactionCount(), Initialize(), and UpdateRankCounters().
_player
Player* ReputationMgr::_player private
Definition at line 140 of file ReputationMgr.h.
Referenced by GetBaseReputation(), GetDefaultStateFlags(), GetReputation(), IsAtWar(), SaveToDB(), SendForceReactions(), SendInitialReputations(), SendState(), SendVisible(), SetOneFactionReputation(), SetReputation(), and SetVisible().
_reveredFactionCount
uint8 ReputationMgr::_reveredFactionCount private
Definition at line 145 of file ReputationMgr.h.
Referenced by GetReveredFactionCount(), Initialize(), and UpdateRankCounters().
_sendFactionIncreased
bool ReputationMgr::_sendFactionIncreased private
Definition at line 147 of file ReputationMgr.h.
Referenced by Initialize(), SendState(), and SetOneFactionReputation().
_visibleFactionCount
uint8 ReputationMgr::_visibleFactionCount private
Definition at line 143 of file ReputationMgr.h.
Referenced by GetVisibleFactionCount(), Initialize(), and SetVisible().
PointsInRank
const int32 ReputationMgr::PointsInRank = {36000, 3000, 3000, 3000, 6000, 12000, 21000, 1000} static
Definition at line 60 of file ReputationMgr.h.
Referenced by modify_commandscript::HandleModifyRepCommand(), and ReputationToRank().
Reputation_Bottom
const int32 ReputationMgr::Reputation_Bottom = -42000 static
Definition at line 62 of file ReputationMgr.h.
Referenced by SetOneFactionReputation(), and SetVisible().
Reputation_Cap
const int32 ReputationMgr::Reputation_Cap = 42999 static
Definition at line 61 of file ReputationMgr.h.
Referenced by ObjectMgr::LoadQuests(), ReputationToRank(), and SetOneFactionReputation().
The documentation for this class was generated from the following files:
src/server/game/Reputation/ReputationMgr.h
src/server/game/Reputation/ReputationMgr.cpp