Azerotcore-wotlk: go_suppression_device::go_suppression_deviceAI Struct Reference
go_suppression_device::go_suppression_deviceAI Struct Reference
Public Member Functions
go_suppression_deviceAI (GameObject *go)
void InitializeAI () override
void UpdateAI (uint32 diff) override
void OnLootStateChanged (uint32 state, Unit *)
void DoAction (int32 action) override
void Activate ()
void Deactivate ()
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void Reset ()
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Private Attributes
InstanceScript * _instance
EventMap _events
bool _active
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 143 of file boss_broodlord_lashlayer.cpp.
Constructor & Destructor Documentation
go_suppression_deviceAI()
go_suppression_device::go_suppression_deviceAI::go_suppression_deviceAI (GameObject * go) inline
Definition at line 145 of file boss_broodlord_lashlayer.cpp.
 : GameObjectAI(go), _instance(go->GetInstanceScript()), _active(true) { }
Member Function Documentation
Activate()
void go_suppression_device::go_suppression_deviceAI::Activate () inline
Definition at line 205 of file boss_broodlord_lashlayer.cpp.
             {
                 if (_active)
                     return;
                 _active = true;
                 if (me->GetGoState() == GO_STATE_ACTIVE)
                     me->SetGoState(GO_STATE_READY);
                 me->SetLootState(GO_READY);
                 me->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                 _events.ScheduleEvent(EVENT_SUPPRESSION_CAST, 1000);
             }
References _active, _events, EVENT_SUPPRESSION_CAST, GAMEOBJECT_FLAGS, GameObject::GetGoState(), GO_FLAG_NOT_SELECTABLE, GO_READY, GO_STATE_ACTIVE, GO_STATE_READY, GameObjectAI::me, Object::RemoveFlag(), EventMap::ScheduleEvent(), GameObject::SetGoState(), and GameObject::SetLootState().
Referenced by UpdateAI().
Deactivate()
void go_suppression_device::go_suppression_deviceAI::Deactivate () inline
Definition at line 217 of file boss_broodlord_lashlayer.cpp.
             {
                 if (!_active)
                     return;
                 _active = false;
                 me->SetGoState(GO_STATE_ACTIVE);
                 me->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                 _events.CancelEvent(EVENT_SUPPRESSION_CAST);
             }
References _active, _events, EventMap::CancelEvent(), EVENT_SUPPRESSION_CAST, GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GameObjectAI::me, Object::SetFlag(), and GameObject::SetGoState().
Referenced by DoAction(), InitializeAI(), and OnLootStateChanged().
DoAction()
void go_suppression_device::go_suppression_deviceAI::DoAction (int32 action) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 196 of file boss_broodlord_lashlayer.cpp.
             {
                 if (action == ACTION_DEACTIVATE)
                 {
                     Deactivate();
                     _events.CancelEvent(EVENT_SUPPRESSION_RESET);
                 }
             }
References _events, ACTION_DEACTIVATE, EventMap::CancelEvent(), Deactivate(), and EVENT_SUPPRESSION_RESET.
InitializeAI()
void go_suppression_device::go_suppression_deviceAI::InitializeAI () inline override virtual
Reimplemented from GameObjectAI.
Definition at line 147 of file boss_broodlord_lashlayer.cpp.
             {
                 if (_instance->GetBossState(DATA_BROODLORD_LASHLAYER) == DONE)
                 {
                     Deactivate();
                     return;
                 }
                 _events.ScheduleEvent(EVENT_SUPPRESSION_CAST, 5000);
             }
References _events, _instance, DATA_BROODLORD_LASHLAYER, Deactivate(), DONE, EVENT_SUPPRESSION_CAST, InstanceScript::GetBossState(), and EventMap::ScheduleEvent().
OnLootStateChanged()
void go_suppression_device::go_suppression_deviceAI::OnLootStateChanged (uint32 state, Unit *) inline
Definition at line 181 of file boss_broodlord_lashlayer.cpp.
             {
                 switch (state)
                 {
                     case GO_ACTIVATED:
                         Deactivate();
                         _events.CancelEvent(EVENT_SUPPRESSION_CAST);
                         _events.ScheduleEvent(EVENT_SUPPRESSION_RESET, 30000, 120000);
                         break;
                     case GO_JUST_DEACTIVATED: // This case prevents the Gameobject despawn by Disarm Trap
                         me->SetLootState(GO_READY);
                         break;
                 }
             }
References _events, EventMap::CancelEvent(), Deactivate(), EVENT_SUPPRESSION_CAST, EVENT_SUPPRESSION_RESET, GO_ACTIVATED, GO_JUST_DEACTIVATED, GO_READY, GameObjectAI::me, EventMap::ScheduleEvent(), and GameObject::SetLootState().
UpdateAI()
void go_suppression_device::go_suppression_deviceAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 158 of file boss_broodlord_lashlayer.cpp.
             {
                 _events.Update(diff);
                 while (uint32 eventId = _events.ExecuteEvent())
                 {
                     switch (eventId)
                     {
                         case EVENT_SUPPRESSION_CAST:
                             if (me->GetGoState() == GO_STATE_READY)
{
                                 me->CastSpell(nullptr, SPELL_SUPPRESSION_AURA);
                                 me->SendCustomAnim(0);
                             }
                             _events.ScheduleEvent(EVENT_SUPPRESSION_CAST, 5000);
                             break;
                         case EVENT_SUPPRESSION_RESET:
                             Activate();
                             break;
                     }
                 }
             }
References _events, Activate(), GameObject::CastSpell(), EVENT_SUPPRESSION_CAST, EVENT_SUPPRESSION_RESET, EventMap::ExecuteEvent(), GameObject::GetGoState(), GO_STATE_READY, GameObjectAI::me, EventMap::ScheduleEvent(), GameObject::SendCustomAnim(), SPELL_SUPPRESSION_AURA, and EventMap::Update().
Member Data Documentation
_active
bool go_suppression_device::go_suppression_deviceAI::_active private
Definition at line 230 of file boss_broodlord_lashlayer.cpp.
Referenced by Activate(), and Deactivate().
_events
EventMap go_suppression_device::go_suppression_deviceAI::_events private
Definition at line 229 of file boss_broodlord_lashlayer.cpp.
Referenced by Activate(), Deactivate(), DoAction(), InitializeAI(), OnLootStateChanged(), and UpdateAI().
_instance
InstanceScript* go_suppression_device::go_suppression_deviceAI::_instance private
Definition at line 228 of file boss_broodlord_lashlayer.cpp.
Referenced by InitializeAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_broodlord_lashlayer.cpp