Azerotcore-wotlk: Guild::LogHolder Class Reference
Guild::LogHolder Class Reference
Public Member Functions
LogHolder (uint32 guildId, uint32 maxRecords)
~LogHolder ()
uint8 GetSize () const
uint32 GetGuildId () const
bool CanInsert () const
void LoadEvent (LogEntry *entry)
void AddEvent (CharacterDatabaseTransaction trans, LogEntry *entry)
void WritePacket (WorldPacket &data) const
uint32 GetNextGUID ()
Private Attributes
GuildLog m_log
uint32 m_guildId
uint32 m_maxRecords
uint32 m_nextGUID
Detailed Description
Definition at line 466 of file Guild.h.
Constructor & Destructor Documentation
LogHolder()
Guild::LogHolder::LogHolder (uint32 guildId, uint32 maxRecords) inline
Definition at line 469 of file Guild.h.
 : m_guildId(guildId), m_maxRecords(maxRecords), m_nextGUID(uint32(GUILD_EVENT_LOG_GUID_UNDEFINED)) { }
~LogHolder()
Guild::LogHolder::~LogHolder ()
Definition at line 125 of file Guild.cpp.
 {
     // Cleanup
     for (GuildLog::iterator itr = m_log.begin(); itr != m_log.end(); ++itr)
         delete (*itr);
 }
References m_log.
Member Function Documentation
AddEvent()
void Guild::LogHolder::AddEvent (CharacterDatabaseTransaction trans, LogEntry * entry) inline
Definition at line 142 of file Guild.cpp.
 {
     // Check max records limit
     if (m_log.size() >= m_maxRecords)
     {
         LogEntry* oldEntry = m_log.front();
         delete oldEntry;
         m_log.pop_front();
     }
     // Add event to list
     m_log.push_back(entry);
     // Save to DB
     entry->SaveToDB(trans);
 }
References Guild::LogEntry::SaveToDB().
Referenced by Guild::_LogBankEvent(), and Guild::_LogEvent().
CanInsert()
bool Guild::LogHolder::CanInsert () const inline
Definition at line 475 of file Guild.h.
 { return m_log.size() < m_maxRecords; }
References m_log, and m_maxRecords.
Referenced by Guild::LoadBankEventLogFromDB(), and Guild::LoadEventLogFromDB().
GetGuildId()
uint32 Guild::LogHolder::GetGuildId () const inline
Definition at line 473 of file Guild.h.
 { return m_guildId; }
References m_guildId.
GetNextGUID()
uint32 Guild::LogHolder::GetNextGUID () inline
Definition at line 165 of file Guild.cpp.
 {
     // Next guid was not initialized. It means there are no records for this holder in DB yet.
     // Start from the beginning.
     if (m_nextGUID == uint32(GUILD_EVENT_LOG_GUID_UNDEFINED))
         m_nextGUID = 0;
     else
         m_nextGUID = (m_nextGUID + 1) % m_maxRecords;
     return m_nextGUID;
 }
References GUILD_EVENT_LOG_GUID_UNDEFINED.
Referenced by Guild::_LogBankEvent(), and Guild::_LogEvent().
GetSize()
uint8 Guild::LogHolder::GetSize () const inline
Definition at line 472 of file Guild.h.
 { return uint8(m_log.size()); }
References m_log.
Referenced by Guild::SendBankLog(), and Guild::SendEventLog().
LoadEvent()
void Guild::LogHolder::LoadEvent (LogEntry * entry) inline
Definition at line 133 of file Guild.cpp.
 {
     if (m_nextGUID == uint32(GUILD_EVENT_LOG_GUID_UNDEFINED))
         m_nextGUID = entry->GetGUID();
     m_log.push_front(entry);
 }
References Guild::LogEntry::GetGUID(), and GUILD_EVENT_LOG_GUID_UNDEFINED.
Referenced by Guild::LoadBankEventLogFromDB(), and Guild::LoadEventLogFromDB().
WritePacket()
void Guild::LogHolder::WritePacket (WorldPacket & data) const inline
Definition at line 158 of file Guild.cpp.
 {
     data << uint8(m_log.size());
     for (GuildLog::const_iterator itr = m_log.begin(); itr != m_log.end(); ++itr)
         (*itr)->WritePacket(data);
 }
Referenced by Guild::SendBankLog(), and Guild::SendEventLog().
Member Data Documentation
m_guildId
uint32 Guild::LogHolder::m_guildId private
Definition at line 486 of file Guild.h.
Referenced by GetGuildId().
m_log
GuildLog Guild::LogHolder::m_log private
Definition at line 485 of file Guild.h.
Referenced by CanInsert(), GetSize(), and ~LogHolder().
m_maxRecords
uint32 Guild::LogHolder::m_maxRecords private
Definition at line 487 of file Guild.h.
Referenced by CanInsert().
m_nextGUID
uint32 Guild::LogHolder::m_nextGUID private
Definition at line 488 of file Guild.h.
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp