Azerotcore-wotlk: deps/mysqllite/mysys/my_seek.c File Reference
my_seek.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
Functions
my_off_t my_seek (File fd, my_off_t pos, int whence, myf MyFlags)
my_off_t my_tell (File fd, myf MyFlags)
Function Documentation
my_seek()
my_off_t my_seek (File fd, my_off_t pos, int whence, myf MyFlags)
Definition at line 46 of file my_seek.c.
 {
   os_off_t newpos= -1;
   DBUG_ENTER("my_seek");
   DBUG_PRINT("my",("fd: %d Pos: %llu  Whence: %d  MyFlags: %d",
            fd, (ulonglong) pos, whence, MyFlags));
   DBUG_ASSERT(pos != MY_FILEPOS_ERROR);     /* safety check */
   /*
       Make sure we are using a valid file descriptor!
   */
   DBUG_ASSERT(fd != -1);
 #if defined (_WIN32)
   newpos= my_win_lseek(fd, pos, whence);
 #else
   newpos= lseek(fd, pos, whence);
 #endif
   if (newpos == (os_off_t) -1)
   {
     my_errno= errno;
     if (MyFlags & MY_WME)
       my_error(EE_CANT_SEEK, MYF(0), my_filename(fd), my_errno);
     DBUG_PRINT("error", ("lseek: %llu  errno: %d", (ulonglong) newpos, errno));
     DBUG_RETURN(MY_FILEPOS_ERROR);
   }
   if ((my_off_t) newpos != pos)
   {
     DBUG_PRINT("exit",("pos: %llu", (ulonglong) newpos));
   }
   DBUG_RETURN((my_off_t) newpos);
 } /* my_seek */
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_SEEK, errno, my_errno, my_error(), my_filename(), MY_FILEPOS_ERROR, MY_WME, MYF, and pos().
Referenced by inline_mysql_file_seek(), my_b_append_tell(), my_b_filelength(), my_b_fill(), my_chsize(), my_lock(), my_pwrite(), and my_tell().
my_tell()
my_off_t my_tell (File fd, myf MyFlags)
Definition at line 82 of file my_seek.c.
 {
   os_off_t pos;
   DBUG_ENTER("my_tell");
   DBUG_PRINT("my",("fd: %d  MyFlags: %d",fd, MyFlags));
   DBUG_ASSERT(fd >= 0);
 #if defined (HAVE_TELL) && !defined (_WIN32)
   pos= tell(fd);
 #else
   pos= my_seek(fd, 0L, MY_SEEK_CUR,0);
 #endif
   if (pos == (os_off_t) -1)
   {
     my_errno= errno;
     if (MyFlags & MY_WME)
       my_error(EE_CANT_SEEK, MYF(0), my_filename(fd), my_errno);
     DBUG_PRINT("error", ("tell: %llu  errno: %d", (ulonglong) pos, my_errno));
   }
   DBUG_PRINT("exit",("pos: %llu", (ulonglong) pos));
   DBUG_RETURN((my_off_t) pos);
 } /* my_tell */
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_SEEK, errno, my_errno, my_error(), my_filename(), my_seek(), MY_SEEK_CUR, MY_WME, MYF, and pos().
Referenced by inline_mysql_file_tell(), and my_b_append_tell().