Azerotcore-wotlk: instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript Struct Reference
instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript Struct Reference
Public Member Functions
instance_onyxias_lair_InstanceMapScript (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *pCreature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
ObjectGuid GetGuidData (uint32 uiData) const override
std::string GetSaveData () override
void Load (const char *in) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
ObjectGuid m_uiOnyxiasGUID
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string str_data
uint16 ManyWhelpsCounter
GuidVector minions
bool bDeepBreath
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 32 of file instance_onyxias_lair.cpp.
Constructor & Destructor Documentation
instance_onyxias_lair_InstanceMapScript()
instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::instance_onyxias_lair_InstanceMapScript (Map * pMap) inline
Definition at line 34 of file instance_onyxias_lair.cpp.
 : InstanceScript(pMap) {Initialize();};
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
Definition at line 174 of file instance_onyxias_lair.cpp.
         {
             switch(criteria_id)
             {
                 case ACHIEV_CRITERIA_MANY_WHELPS_10_PLAYER:
                 case ACHIEV_CRITERIA_MANY_WHELPS_25_PLAYER:
                     return ManyWhelpsCounter >= 50;
                 case ACHIEV_CRITERIA_DEEP_BREATH_10_PLAYER:
                 case ACHIEV_CRITERIA_DEEP_BREATH_25_PLAYER:
                     return bDeepBreath;
             }
             return false;
         }
References ACHIEV_CRITERIA_DEEP_BREATH_10_PLAYER, ACHIEV_CRITERIA_DEEP_BREATH_25_PLAYER, ACHIEV_CRITERIA_MANY_WHELPS_10_PLAYER, ACHIEV_CRITERIA_MANY_WHELPS_25_PLAYER, bDeepBreath, and ManyWhelpsCounter.
GetData()
uint32 instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::GetData (uint32 uiType) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 113 of file instance_onyxias_lair.cpp.
         {
             switch(uiType)
             {
                 case DATA_ONYXIA:
                     return m_auiEncounter[0];
             }
             return 0;
         }
References DATA_ONYXIA, and m_auiEncounter.
GetGuidData()
ObjectGuid instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::GetGuidData (uint32 uiData) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 124 of file instance_onyxias_lair.cpp.
         {
             switch (uiData)
             {
                 case DATA_ONYXIA:
                     return m_uiOnyxiasGUID;
             }
             return ObjectGuid::Empty;
         }
References DATA_ONYXIA, ObjectGuid::Empty, and m_uiOnyxiasGUID.
GetSaveData()
std::string instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 135 of file instance_onyxias_lair.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "O L " << m_auiEncounter[0];
             str_data = saveStream.str();
             OUT_SAVE_INST_DATA_COMPLETE;
             return str_data;
         }
References m_auiEncounter, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, and str_data.
Initialize()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 43 of file instance_onyxias_lair.cpp.
         {
             memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
             ManyWhelpsCounter = 0;
             bDeepBreath = true;
         }
References bDeepBreath, m_auiEncounter, and ManyWhelpsCounter.
Referenced by instance_onyxias_lair_InstanceMapScript().
IsEncounterInProgress()
bool instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 50 of file instance_onyxias_lair.cpp.
         {
             for( uint8 i = 0; i < MAX_ENCOUNTER; ++i )
                 if( m_auiEncounter[i] == IN_PROGRESS )
                     return true;
             return false;
         }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
Load()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 145 of file instance_onyxias_lair.cpp.
         {
             if( !in )
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             uint16 data0;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2 >> data0;
             if( dataHead1 == 'O' && dataHead2 == 'L' )
             {
                 m_auiEncounter[0] = data0;
                 for( uint8 i = 0; i < MAX_ENCOUNTER; ++i )
                     if( m_auiEncounter[i] == IN_PROGRESS )
                         m_auiEncounter[i] = NOT_STARTED;
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnCreatureCreate (Creature * pCreature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 59 of file instance_onyxias_lair.cpp.
         {
             switch( pCreature->GetEntry() )
             {
                 case NPC_ONYXIA:
                     m_uiOnyxiasGUID = pCreature->GetGUID();
                     break;
                 case NPC_ONYXIAN_WHELP:
                 case NPC_ONYXIAN_LAIR_GUARD:
                     minions.push_back(pCreature->GetGUID());
                     break;
             }
         }
References Object::GetEntry(), Object::GetGUID(), m_uiOnyxiasGUID, minions, NPC_ONYXIA, NPC_ONYXIAN_LAIR_GUARD, and NPC_ONYXIAN_WHELP.
OnGameObjectCreate()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 73 of file instance_onyxias_lair.cpp.
         {
             switch( go->GetEntry() )
             {
                 case GO_WHELP_SPAWNER:
                     go->CastSpell((Unit*)nullptr, 17646);
                     if( Creature* onyxia = instance->GetCreature(m_uiOnyxiasGUID) )
                         onyxia->AI()->DoAction(-1);
                     break;
             }
         }
References GameObject::CastSpell(), Map::GetCreature(), Object::GetEntry(), GO_WHELP_SPAWNER, InstanceScript::instance, and m_uiOnyxiasGUID.
SetData()
void instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::SetData (uint32 uiType, uint32 uiData) inline override virtual
Reimplemented from ZoneScript.
Definition at line 85 of file instance_onyxias_lair.cpp.
         {
             switch(uiType)
             {
                 case DATA_ONYXIA:
                     m_auiEncounter[0] = uiData;
                     ManyWhelpsCounter = 0;
                     bDeepBreath = true;
                     if( uiData == NOT_STARTED )
                     {
                         for (ObjectGuid const& guid : minions)
                             if (Creature* c = instance->GetCreature(guid))
                                 c->DespawnOrUnsummon();
                         minions.clear();
                     }
                     break;
                 case DATA_WHELP_SUMMONED:
                     ++ManyWhelpsCounter;
                     break;
                 case DATA_DEEP_BREATH_FAILED:
                     bDeepBreath = false;
                     break;
             }
             if (uiType < MAX_ENCOUNTER && uiData == DONE)
                 SaveToDB();
         }
References bDeepBreath, DATA_DEEP_BREATH_FAILED, DATA_ONYXIA, DATA_WHELP_SUMMONED, DONE, Map::GetCreature(), InstanceScript::instance, m_auiEncounter, ManyWhelpsCounter, MAX_ENCOUNTER, minions, NOT_STARTED, and InstanceScript::SaveToDB().
Member Data Documentation
bDeepBreath
bool instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::bDeepBreath
Definition at line 41 of file instance_onyxias_lair.cpp.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
m_auiEncounter
uint32 instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Definition at line 37 of file instance_onyxias_lair.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), IsEncounterInProgress(), Load(), and SetData().
m_uiOnyxiasGUID
ObjectGuid instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::m_uiOnyxiasGUID
Definition at line 36 of file instance_onyxias_lair.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and OnGameObjectCreate().
ManyWhelpsCounter
uint16 instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::ManyWhelpsCounter
Definition at line 39 of file instance_onyxias_lair.cpp.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
minions
GuidVector instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::minions
Definition at line 40 of file instance_onyxias_lair.cpp.
Referenced by OnCreatureCreate(), and SetData().
str_data
std::string instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::str_data
Definition at line 38 of file instance_onyxias_lair.cpp.
Referenced by GetSaveData().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/OnyxiasLair/instance_onyxias_lair.cpp