Azerotcore-wotlk: BGQueueInviteEvent Class Reference
BGQueueInviteEvent Class Reference
#include <BattlegroundQueue.h>
Public Member Functions
BGQueueInviteEvent (ObjectGuid pl_guid, uint32 BgInstanceGUID, BattlegroundTypeId BgTypeId, uint8 arenaType, uint32 removeTime)
~BGQueueInviteEvent () override=default
bool Execute (uint64 e_time, uint32 p_time) override
void Abort (uint64 e_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
void ScheduleAbort ()
Private Attributes
ObjectGuid m_PlayerGuid
uint32 m_BgInstanceGUID
BattlegroundTypeId m_BgTypeId
uint8 m_ArenaType
uint32 m_RemoveTime
Detailed Description
Definition at line 153 of file BattlegroundQueue.h.
Constructor & Destructor Documentation
BGQueueInviteEvent()
BGQueueInviteEvent::BGQueueInviteEvent (ObjectGuid pl_guid, uint32 BgInstanceGUID, BattlegroundTypeId BgTypeId, uint8 arenaType, uint32 removeTime) inline
Definition at line 156 of file BattlegroundQueue.h.
                                                                                                                                    :
         m_PlayerGuid(pl_guid), m_BgInstanceGUID(BgInstanceGUID), m_BgTypeId(BgTypeId), m_ArenaType(arenaType), m_RemoveTime(removeTime)
     { }
~BGQueueInviteEvent()
BGQueueInviteEvent::~BGQueueInviteEvent () override default
Member Function Documentation
Abort()
void BGQueueInviteEvent::Abort (uint64 e_time) override virtual
Reimplemented from BasicEvent.
Definition at line 1212 of file BattlegroundQueue.cpp.
 {
     //do nothing
 }
Execute()
bool BGQueueInviteEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
Definition at line 1179 of file BattlegroundQueue.cpp.
 {
     Player* player = ObjectAccessor::FindConnectedPlayer(m_PlayerGuid);
     // player logged off, so he is no longer in queue
     if (!player)
         return true;
     Battleground* bg = sBattlegroundMgr->GetBattleground(m_BgInstanceGUID);
     // if battleground ended, do nothing
     if (!bg)
         return true;
     // check if still in queue for this battleground
     BattlegroundQueueTypeId bgQueueTypeId = BattlegroundMgr::BGQueueTypeId(m_BgTypeId, m_ArenaType);
     uint32 queueSlot = player->GetBattlegroundQueueIndex(bgQueueTypeId);
     if (queueSlot < PLAYER_MAX_BATTLEGROUND_QUEUES)
     {
         // confirm the player is invited to this instance id (he didn't requeue in the meanwhile)
         BattlegroundQueue& bgQueue = sBattlegroundMgr->GetBattlegroundQueue(bgQueueTypeId);
         if (bgQueue.IsPlayerInvited(m_PlayerGuid, m_BgInstanceGUID, m_RemoveTime))
         {
             // send remaining time in queue
             WorldPacket data;
             sBattlegroundMgr->BuildBattlegroundStatusPacket(&data, bg, queueSlot, STATUS_WAIT_JOIN, INVITE_ACCEPT_WAIT_TIME - INVITATION_REMIND_TIME, 0, m_ArenaType, TEAM_NEUTRAL, bg->isRated(), m_BgTypeId);
             player->GetSession()->SendPacket(&data);
         }
     }
     return true;
 }
References BattlegroundMgr::BGQueueTypeId(), ObjectAccessor::FindConnectedPlayer(), Player::GetBattlegroundQueueIndex(), Player::GetSession(), INVITATION_REMIND_TIME, INVITE_ACCEPT_WAIT_TIME, BattlegroundQueue::IsPlayerInvited(), Battleground::isRated(), PLAYER_MAX_BATTLEGROUND_QUEUES, sBattlegroundMgr, WorldSession::SendPacket(), STATUS_WAIT_JOIN, and TEAM_NEUTRAL.
Member Data Documentation
m_ArenaType
uint8 BGQueueInviteEvent::m_ArenaType private
Definition at line 167 of file BattlegroundQueue.h.
m_BgInstanceGUID
uint32 BGQueueInviteEvent::m_BgInstanceGUID private
Definition at line 165 of file BattlegroundQueue.h.
m_BgTypeId
BattlegroundTypeId BGQueueInviteEvent::m_BgTypeId private
Definition at line 166 of file BattlegroundQueue.h.
m_PlayerGuid
ObjectGuid BGQueueInviteEvent::m_PlayerGuid private
Definition at line 164 of file BattlegroundQueue.h.
m_RemoveTime
uint32 BGQueueInviteEvent::m_RemoveTime private
Definition at line 168 of file BattlegroundQueue.h.
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/BattlegroundQueue.h
src/server/game/Battlegrounds/BattlegroundQueue.cpp