Azerotcore-wotlk: deps/mysqllite/vio/vio.c File Reference
vio.c File Reference
#include "vio_priv.h"
Functions
static my_bool has_no_data (Vio *vio __attribute__((unused)))
static void vio_init (Vio *vio, enum enum_vio_type type, my_socket sd, HANDLE hPipe, uint flags)
void vio_reset (Vio *vio, enum enum_vio_type type, my_socket sd, HANDLE hPipe, uint flags)
Vio * vio_new (my_socket sd, enum enum_vio_type type, uint flags)
void vio_delete (Vio *vio)
void vio_end (void)
Function Documentation
has_no_data()
static my_bool has_no_data (Vio *vio __attribute__(unused)) static
Definition at line 47 of file vio.c.
 {
   return FALSE;
 }
References FALSE.
Referenced by vio_init().
vio_delete()
void vio_delete (Vio * vio)
Definition at line 269 of file vio.c.
 {
   if (!vio)
     return; /* It must be safe to delete null pointers. */
   if (vio->type != VIO_CLOSED)
     vio->vioclose(vio);
   my_free(vio->read_buffer);
   my_free(vio);
 }
References my_free(), st_vio::read_buffer, st_vio::type, VIO_CLOSED, and st_vio::vioclose.
Referenced by vio_init().
vio_end()
void vio_end (void)
Definition at line 286 of file vio.c.
 {
 #ifdef HAVE_YASSL
   yaSSL_CleanUp();
 #endif
 }
Referenced by mysql_server_end().
vio_init()
static void vio_init (Vio * vio, enum enum_vio_type type, my_socket sd, HANDLE hPipe, uint flags) static
Definition at line 56 of file vio.c.
 {
   DBUG_ENTER("vio_init");
   DBUG_PRINT("enter", ("type: %d  sd: %d  flags: %d", type, sd, flags));
 #ifndef HAVE_VIO_READ_BUFF
   flags&= ~VIO_BUFFERED_READ;
 #endif
   bzero((char*) vio, sizeof(*vio));
   vio->type = type;
   vio->sd   = sd;
   vio->hPipe    = hPipe;
   vio->localhost= flags & VIO_LOCALHOST;
   if ((flags & VIO_BUFFERED_READ) &&
       !(vio->read_buffer= (char*)my_malloc(VIO_READ_BUFFER_SIZE, MYF(MY_WME))))
     flags&= ~VIO_BUFFERED_READ;
 #ifdef _WIN32
   if (type == VIO_TYPE_NAMEDPIPE)
   {
     vio->viodelete  =vio_delete;
     vio->vioerrno   =vio_errno;
     vio->read           =vio_read_pipe;
     vio->write          =vio_write_pipe;
     vio->fastsend   =vio_fastsend;
     vio->viokeepalive   =vio_keepalive;
     vio->should_retry   =vio_should_retry;
     vio->was_interrupted=vio_was_interrupted;
     vio->vioclose   =vio_close_pipe;
     vio->peer_addr  =vio_peer_addr;
     vio->vioblocking    =vio_blocking;
     vio->is_blocking    =vio_is_blocking;
     vio->poll_read      =no_poll_read;
     vio->is_connected   =vio_is_connected_pipe;
     vio->has_data       =has_no_data;
     vio->timeout=vio_win32_timeout;
     /* Set default timeout */
     vio->read_timeout_ms= INFINITE;
     vio->write_timeout_ms= INFINITE;
     vio->pipe_overlapped.hEvent= CreateEvent(NULL, TRUE, FALSE, NULL);
     DBUG_VOID_RETURN;
   }
 #endif
 #ifdef HAVE_SMEM
   if (type == VIO_TYPE_SHARED_MEMORY)
   {
     vio->viodelete  =vio_delete;
     vio->vioerrno   =vio_errno;
     vio->read           =vio_read_shared_memory;
     vio->write          =vio_write_shared_memory;
     vio->fastsend   =vio_fastsend;
     vio->viokeepalive   =vio_keepalive;
     vio->should_retry   =vio_should_retry;
     vio->was_interrupted=vio_was_interrupted;
     vio->vioclose   =vio_close_shared_memory;
     vio->peer_addr  =vio_peer_addr;
     vio->vioblocking    =vio_blocking;
     vio->is_blocking    =vio_is_blocking;
     vio->poll_read      =no_poll_read;
     vio->is_connected   =vio_is_connected_shared_memory;
     vio->has_data       =has_no_data;
     /* Currently, shared memory is on Windows only, hence the below is ok*/
     vio->timeout= vio_win32_timeout;
     /* Set default timeout */
     vio->read_timeout_ms= INFINITE;
     vio->write_timeout_ms= INFINITE;
     DBUG_VOID_RETURN;
   }
 #endif
 #ifdef HAVE_OPENSSL
   if (type == VIO_TYPE_SSL)
   {
     vio->viodelete  =vio_ssl_delete;
     vio->vioerrno   =vio_errno;
     vio->read       =vio_ssl_read;
     vio->write      =vio_ssl_write;
     vio->fastsend   =vio_fastsend;
     vio->viokeepalive   =vio_keepalive;
     vio->should_retry   =vio_should_retry;
     vio->was_interrupted=vio_was_interrupted;
     vio->vioclose   =vio_ssl_close;
     vio->peer_addr  =vio_peer_addr;
     vio->vioblocking    =vio_ssl_blocking;
     vio->is_blocking    =vio_is_blocking;
     vio->timeout    =vio_timeout;
     vio->poll_read      =vio_poll_read;
     vio->is_connected   =vio_is_connected;
     vio->has_data       =vio_ssl_has_data;
     DBUG_VOID_RETURN;
   }
 #endif /* HAVE_OPENSSL */
   vio->viodelete        =vio_delete;
   vio->vioerrno         =vio_errno;
   vio->read=            (flags & VIO_BUFFERED_READ) ? vio_read_buff : vio_read;
   vio->write            =vio_write;
   vio->fastsend         =vio_fastsend;
   vio->viokeepalive     =vio_keepalive;
   vio->should_retry     =vio_should_retry;
   vio->was_interrupted  =vio_was_interrupted;
   vio->vioclose         =vio_close;
   vio->peer_addr        =vio_peer_addr;
   vio->vioblocking      =vio_blocking;
   vio->is_blocking      =vio_is_blocking;
   vio->timeout          =vio_timeout;
   vio->poll_read        =vio_poll_read;
   vio->is_connected     =vio_is_connected;
   vio->has_data=        (flags & VIO_BUFFERED_READ) ?
                             vio_buff_has_data : has_no_data;
   DBUG_VOID_RETURN;
 }
References bzero, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, FALSE, st_vio::fastsend, st_vio::has_data, has_no_data(), st_vio::hPipe, st_vio::is_blocking, st_vio::is_connected, st_vio::localhost, my_malloc(), MY_WME, MYF, NULL, st_vio::peer_addr, st_vio::poll_read, st_vio::read, st_vio::read_buffer, st_vio::sd, st_vio::should_retry, st_vio::timeout, TRUE, st_vio::type, vio_blocking, vio_buff_has_data(), VIO_BUFFERED_READ, vio_close, vio_delete(), vio_errno, vio_fastsend, vio_is_blocking, vio_is_connected, vio_keepalive, VIO_LOCALHOST, vio_peer_addr, vio_poll_read, vio_read, vio_read_buff(), VIO_READ_BUFFER_SIZE, vio_should_retry, vio_timeout, VIO_TYPE_NAMEDPIPE, VIO_TYPE_SHARED_MEMORY, VIO_TYPE_SSL, vio_was_interrupted, vio_write, st_vio::vioblocking, st_vio::vioclose, st_vio::viodelete, st_vio::vioerrno, st_vio::viokeepalive, st_vio::was_interrupted, and st_vio::write.
Referenced by vio_new(), and vio_reset().
vio_new()
Vio* vio_new (my_socket sd, enum enum_vio_type type, uint flags)
Definition at line 184 of file vio.c.
 {
   Vio *vio;
   DBUG_ENTER("vio_new");
   DBUG_PRINT("enter", ("sd: %d", sd));
   if ((vio = (Vio*) my_malloc(sizeof(*vio),MYF(MY_WME))))
   {
     vio_init(vio, type, sd, 0, flags);
     sprintf(vio->desc,
         (vio->type == VIO_TYPE_SOCKET ? "socket (%d)" : "TCP/IP (%d)"),
         vio->sd);
 #if !defined(__WIN__)
 #if !defined(NO_FCNTL_NONBLOCK)
     /*
       We call fcntl() to set the flags and then immediately read them back
       to make sure that we and the system are in agreement on the state of
       things.
       An example of why we need to do this is FreeBSD (and apparently some
       other BSD-derived systems, like Mac OS X), where the system sometimes
       reports that the socket is set for non-blocking when it really will
       block.
     */
     fcntl(sd, F_SETFL, 0);
     vio->fcntl_mode= fcntl(sd, F_GETFL);
 #elif defined(HAVE_SYS_IOCTL_H)         /* hpux */
     /* Non blocking sockets doesn't work good on HPUX 11.0 */
     (void) ioctl(sd,FIOSNBIO,0);
     vio->fcntl_mode &= ~O_NONBLOCK;
 #endif
 #else /* !defined(__WIN__) */
     {
       /* set to blocking mode by default */
       ulong arg=0, r;
       r = ioctlsocket(sd,FIONBIO,(void*) &arg);
       vio->fcntl_mode &= ~O_NONBLOCK;
     }
 #endif
   }
   DBUG_RETURN(vio);
 }
References arg(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::desc, st_vio::fcntl_mode, my_malloc(), MY_WME, MYF, st_vio::sd, sprintf(), st_vio::type, vio_init(), and VIO_TYPE_SOCKET.
Referenced by CLI_MYSQL_REAL_CONNECT().
vio_reset()
void vio_reset (Vio * vio, enum enum_vio_type type, my_socket sd, HANDLE hPipe, uint flags)
Definition at line 174 of file vio.c.
 {
   my_free(vio->read_buffer);
   vio_init(vio, type, sd, hPipe, flags);
 }
References my_free(), st_vio::read_buffer, and vio_init().