Azerotcore-wotlk: dtNavMesh Class Reference
dtNavMesh Class Reference
Detour
#include <DetourNavMesh.h>
Public Member Functions
dtNavMesh ()
~dtNavMesh ()
Initialization and Tile Management
dtStatus init (const dtNavMeshParams *params)
dtStatus init (unsigned char *data, const int dataSize, const int flags)
const dtNavMeshParams * getParams () const
The navigation mesh initialization params.
dtStatus addTile (unsigned char *data, int dataSize, int flags, dtTileRef lastRef, dtTileRef *result)
dtStatus removeTile (dtTileRef ref, unsigned char **data, int *dataSize)
Query Functions
void calcTileLoc (const float *pos, int *tx, int *ty) const
const dtMeshTile * getTileAt (const int x, const int y, const int layer) const
int getTilesAt (const int x, const int y, dtMeshTile const **tiles, const int maxTiles) const
dtTileRef getTileRefAt (int x, int y, int layer) const
dtTileRef getTileRef (const dtMeshTile *tile) const
const dtMeshTile * getTileByRef (dtTileRef ref) const
int getMaxTiles () const
const dtMeshTile * getTile (int i) const
dtStatus getTileAndPolyByRef (const dtPolyRef ref, const dtMeshTile **tile, const dtPoly **poly) const
void getTileAndPolyByRefUnsafe (const dtPolyRef ref, const dtMeshTile **tile, const dtPoly **poly) const
bool isValidPolyRef (dtPolyRef ref) const
dtPolyRef getPolyRefBase (const dtMeshTile *tile) const
dtStatus getOffMeshConnectionPolyEndPoints (dtPolyRef prevRef, dtPolyRef polyRef, float *startPos, float *endPos) const
const dtOffMeshConnection * getOffMeshConnectionByRef (dtPolyRef ref) const
State Management
These functions do not effect dtTileRef or dtPolyRef's.
dtStatus setPolyFlags (dtPolyRef ref, unsigned short flags)
dtStatus getPolyFlags (dtPolyRef ref, unsigned short *resultFlags) const
dtStatus setPolyArea (dtPolyRef ref, unsigned char area)
dtStatus getPolyArea (dtPolyRef ref, unsigned char *resultArea) const
int getTileStateSize (const dtMeshTile *tile) const
dtStatus storeTileState (const dtMeshTile *tile, unsigned char *data, const int maxDataSize) const
dtStatus restoreTileState (dtMeshTile *tile, const unsigned char *data, const int maxDataSize)
Encoding and Decoding
These functions are generally meant for internal use only.
dtPolyRef encodePolyId (unsigned int salt, unsigned int it, unsigned int ip) const
void decodePolyId (dtPolyRef ref, unsigned int &salt, unsigned int &it, unsigned int &ip) const
unsigned int decodePolyIdSalt (dtPolyRef ref) const
unsigned int decodePolyIdTile (dtPolyRef ref) const
unsigned int decodePolyIdPoly (dtPolyRef ref) const
Private Member Functions
dtNavMesh (const dtNavMesh &)
dtNavMesh & operator= (const dtNavMesh &)
dtMeshTile * getTile (int i)
Returns pointer to tile in the tile array.
int getTilesAt (const int x, const int y, dtMeshTile **tiles, const int maxTiles) const
Returns neighbour tile based on side.
int getNeighbourTilesAt (const int x, const int y, const int side, dtMeshTile **tiles, const int maxTiles) const
Returns neighbour tile based on side.
int findConnectingPolys (const float *va, const float *vb, const dtMeshTile *tile, int side, dtPolyRef *con, float *conarea, int maxcon) const
Returns all polygons in neighbour tile based on portal defined by the segment.
void connectIntLinks (dtMeshTile *tile)
Builds internal polygons links for a tile.
void baseOffMeshLinks (dtMeshTile *tile)
Builds internal polygons links for a tile.
void connectExtLinks (dtMeshTile *tile, dtMeshTile *target, int side)
Builds external polygon links for a tile.
void connectExtOffMeshLinks (dtMeshTile *tile, dtMeshTile *target, int side)
Builds external polygon links for a tile.
void unconnectLinks (dtMeshTile *tile, dtMeshTile *target)
Removes external links at specified side.
int queryPolygonsInTile (const dtMeshTile *tile, const float *qmin, const float *qmax, dtPolyRef *polys, const int maxPolys) const
Queries polygons within a tile.
dtPolyRef findNearestPolyInTile (const dtMeshTile *tile, const float *center, const float *halfExtents, float *nearestPt) const
Find nearest polygon within a tile.
bool getPolyHeight (const dtMeshTile *tile, const dtPoly *poly, const float *pos, float *height) const
Returns whether position is over the poly and the height at the position if so.
void closestPointOnPoly (dtPolyRef ref, const float *pos, float *closest, bool *posOverPoly) const
Returns closest point on polygon.
Private Attributes
dtNavMeshParams m_params
Current initialization params. TODO: do not store this info twice.
float m_orig [3]
Origin of the tile (0,0)
float m_tileWidth
float m_tileHeight
Dimensions of each tile.
int m_maxTiles
Max number of tiles.
int m_tileLutSize
Tile hash lookup size (must be pot).
int m_tileLutMask
Tile hash lookup mask.
dtMeshTile ** m_posLookup
Tile hash lookup.
dtMeshTile * m_nextFree
Freelist of tiles.
dtMeshTile * m_tiles
List of tiles.
Friends
class dtNavMeshQuery
Detailed Description
A navigation mesh based on tiles of convex polygons.
The navigation mesh consists of one or more tiles defining three primary types of structural data:
A polygon mesh which defines most of the navigation graph. (See rcPolyMesh for its structure.) A detail mesh used for determining surface height on the polygon mesh. (See rcPolyMeshDetail for its structure.) Off-mesh connections, which define custom point-to-point edges within the navigation graph.
The general build process is as follows:
Create rcPolyMesh and rcPolyMeshDetail data using the Recast build pipeline.
Optionally, create off-mesh connection data.
Combine the source data into a dtNavMeshCreateParams structure.
Create a tile data array using dtCreateNavMeshData().
Allocate at dtNavMesh object and initialize it. (For single tile navigation meshes, the tile data is loaded during this step.)
For multi-tile navigation meshes, load the tile data using dtNavMesh::addTile().
Notes:
This class is usually used in conjunction with the dtNavMeshQuery class for pathfinding.
Technically, all navigation meshes are tiled. A 'solo' mesh is simply a navigation mesh initialized to have only a single tile.
This class does not implement any asynchronous methods. So the dtStatus result of all methods will always contain either a success or failure flag.
See also
dtNavMeshQuery, dtCreateNavMeshData, dtNavMeshCreateParams, dtAllocNavMesh, dtFreeNavMesh
Definition at line 350 of file DetourNavMesh.h.
Constructor & Destructor Documentation
dtNavMesh() [1/2]
dtNavMesh::dtNavMesh ()
Definition at line 188 of file DetourNavMesh.cpp.
                      :
     m_tileWidth(0),
     m_tileHeight(0),
     m_maxTiles(0),
     m_tileLutSize(0),
     m_tileLutMask(0),
     m_posLookup(0),
     m_nextFree(0),
     m_tiles(0)
 {
 #ifndef DT_POLYREF64
     m_saltBits = 0;
     m_tileBits = 0;
     m_polyBits = 0;
 #endif
     memset(&m_params, 0, sizeof(dtNavMeshParams));
     m_orig[0] = 0;
     m_orig[1] = 0;
     m_orig[2] = 0;
 }
References m_orig, m_params, and memset.
~dtNavMesh()
dtNavMesh::~dtNavMesh ()
Definition at line 209 of file DetourNavMesh.cpp.
 {
     for (int i = 0; i < m_maxTiles; ++i)
     {
         if (m_tiles[i].flags & DT_TILE_FREE_DATA)
         {
             dtFree(m_tiles[i].data);
             m_tiles[i].data = 0;
             m_tiles[i].dataSize = 0;
         }
     }
     dtFree(m_posLookup);
     dtFree(m_tiles);
 }
References dtMeshTile::data, dtMeshTile::dataSize, DT_TILE_FREE_DATA, dtFree(), m_maxTiles, m_posLookup, and m_tiles.
Referenced by dtFreeNavMesh().
dtNavMesh() [2/2]
dtNavMesh::dtNavMesh (const dtNavMesh &) private
Member Function Documentation
addTile()
dtStatus dtNavMesh::addTile (unsigned char * data, int dataSize, int flags, dtTileRef lastRef, dtTileRef * result)
Adds a tile to the navigation mesh.
Parameters
[in] data Data for the new tile mesh. (See: dtCreateNavMeshData)
[in] dataSize Data size of the new tile mesh.
[in] flags Tile flags. (See: dtTileFlags)
[in] lastRef The desired reference for the tile. (When reloading a tile.) [opt] [Default: 0]
[out] result The tile reference. (If the tile was succesfully added.) [opt]
Returns
The status flags for the operation.
The add operation will fail if the data is in the wrong format, the allocated tile space is full, or there is a tile already at the specified reference.
The lastRef parameter is used to restore a tile with the same tile reference it had previously used. In this case the dtPolyRef's for the tile will be restored to the same values they were before the tile was removed.
The nav mesh assumes exclusive access to the data passed and will make changes to the dynamic portion of the data. For that reason the data should not be reused in other nav meshes until the tile has been successfully removed from this nav mesh.
See also
dtCreateNavMeshData, removeTile
Definition at line 908 of file DetourNavMesh.cpp.
 {
     // Make sure the data is in right format.
     dtMeshHeader* header = (dtMeshHeader*)data;
     if (header->magic != DT_NAVMESH_MAGIC)
         return DT_FAILURE | DT_WRONG_MAGIC;
     if (header->version != DT_NAVMESH_VERSION)
         return DT_FAILURE | DT_WRONG_VERSION;
     // Make sure the location is free.
     if (getTileAt(header->x, header->y, header->layer))
         return DT_FAILURE | DT_ALREADY_OCCUPIED;
     // Allocate a tile.
     dtMeshTile* tile = 0;
     if (!lastRef)
     {
         if (m_nextFree)
         {
             tile = m_nextFree;
             m_nextFree = tile->next;
             tile->next = 0;
         }
     }
     else
     {
         // Try to relocate the tile to specific index with same salt.
         int tileIndex = (int)decodePolyIdTile((dtPolyRef)lastRef);
         if (tileIndex >= m_maxTiles)
             return DT_FAILURE | DT_OUT_OF_MEMORY;
         // Try to find the specific tile id from the free list.
         dtMeshTile* target = &m_tiles[tileIndex];
         dtMeshTile* prev = 0;
         tile = m_nextFree;
         while (tile && tile != target)
         {
             prev = tile;
             tile = tile->next;
         }
         // Could not find the correct location.
         if (tile != target)
             return DT_FAILURE | DT_OUT_OF_MEMORY;
         // Remove from freelist
         if (!prev)
             m_nextFree = tile->next;
         else
             prev->next = tile->next;
         // Restore salt.
         tile->salt = decodePolyIdSalt((dtPolyRef)lastRef);
     }
     // Make sure we could allocate a tile.
     if (!tile)
         return DT_FAILURE | DT_OUT_OF_MEMORY;
     // Insert tile into the position lut.
     int h = computeTileHash(header->x, header->y, m_tileLutMask);
     tile->next = m_posLookup[h];
     m_posLookup[h] = tile;
     // Patch header pointers.
     const int headerSize = dtAlign4(sizeof(dtMeshHeader));
     const int vertsSize = dtAlign4(sizeof(float)*3*header->vertCount);
     const int polysSize = dtAlign4(sizeof(dtPoly)*header->polyCount);
     const int linksSize = dtAlign4(sizeof(dtLink)*(header->maxLinkCount));
     const int detailMeshesSize = dtAlign4(sizeof(dtPolyDetail)*header->detailMeshCount);
     const int detailVertsSize = dtAlign4(sizeof(float)*3*header->detailVertCount);
     const int detailTrisSize = dtAlign4(sizeof(unsigned char)*4*header->detailTriCount);
     const int bvtreeSize = dtAlign4(sizeof(dtBVNode)*header->bvNodeCount);
     const int offMeshLinksSize = dtAlign4(sizeof(dtOffMeshConnection)*header->offMeshConCount);
     unsigned char* d = data + headerSize;
     tile->verts = dtGetThenAdvanceBufferPointer<float>(d, vertsSize);
     tile->polys = dtGetThenAdvanceBufferPointer<dtPoly>(d, polysSize);
     tile->links = dtGetThenAdvanceBufferPointer<dtLink>(d, linksSize);
     tile->detailMeshes = dtGetThenAdvanceBufferPointer<dtPolyDetail>(d, detailMeshesSize);
     tile->detailVerts = dtGetThenAdvanceBufferPointer<float>(d, detailVertsSize);
     tile->detailTris = dtGetThenAdvanceBufferPointer<unsigned char>(d, detailTrisSize);
     tile->bvTree = dtGetThenAdvanceBufferPointer<dtBVNode>(d, bvtreeSize);
     tile->offMeshCons = dtGetThenAdvanceBufferPointer<dtOffMeshConnection>(d, offMeshLinksSize);
     // If there are no items in the bvtree, reset the tree pointer.
     if (!bvtreeSize)
         tile->bvTree = 0;
     // Build links freelist
     tile->linksFreeList = 0;
     tile->links[header->maxLinkCount-1].next = DT_NULL_LINK;
     for (int i = 0; i < header->maxLinkCount-1; ++i)
         tile->links[i].next = i+1;
     // Init tile.
     tile->header = header;
     tile->data = data;
     tile->dataSize = dataSize;
     tile->flags = flags;
     connectIntLinks(tile);
     // Base off-mesh connections to their starting polygons and connect connections inside the tile.
     baseOffMeshLinks(tile);
     connectExtOffMeshLinks(tile, tile, -1);
     // Create connections with neighbour tiles.
     static const int MAX_NEIS = 32;
     dtMeshTile* neis[MAX_NEIS];
     int nneis;
     // Connect with layers in current tile.
     nneis = getTilesAt(header->x, header->y, neis, MAX_NEIS);
     for (int j = 0; j < nneis; ++j)
     {
         if (neis[j] == tile)
             continue;
         connectExtLinks(tile, neis[j], -1);
         connectExtLinks(neis[j], tile, -1);
         connectExtOffMeshLinks(tile, neis[j], -1);
         connectExtOffMeshLinks(neis[j], tile, -1);
     }
     // Connect with neighbour tiles.
     for (int i = 0; i < 8; ++i)
     {
         nneis = getNeighbourTilesAt(header->x, header->y, i, neis, MAX_NEIS);
         for (int j = 0; j < nneis; ++j)
         {
             connectExtLinks(tile, neis[j], i);
             connectExtLinks(neis[j], tile, dtOppositeTile(i));
             connectExtOffMeshLinks(tile, neis[j], i);
             connectExtOffMeshLinks(neis[j], tile, dtOppositeTile(i));
         }
     }
     if (result)
         *result = getTileRef(tile);
     return DT_SUCCESS;
 }
References baseOffMeshLinks(), dtMeshHeader::bvNodeCount, dtMeshTile::bvTree, computeTileHash(), connectExtLinks(), connectExtOffMeshLinks(), connectIntLinks(), mpq::d, dtMeshTile::data, dtMeshTile::dataSize, decodePolyIdSalt(), decodePolyIdTile(), dtMeshHeader::detailMeshCount, dtMeshTile::detailMeshes, dtMeshHeader::detailTriCount, dtMeshTile::detailTris, dtMeshHeader::detailVertCount, dtMeshTile::detailVerts, DT_ALREADY_OCCUPIED, DT_FAILURE, DT_NAVMESH_MAGIC, DT_NAVMESH_VERSION, DT_NULL_LINK, DT_OUT_OF_MEMORY, DT_SUCCESS, DT_WRONG_MAGIC, DT_WRONG_VERSION, dtAlign4(), dtOppositeTile(), dtMeshTile::flags, getNeighbourTilesAt(), getTileAt(), getTileRef(), getTilesAt(), dtMeshTile::header, dtMeshHeader::layer, dtMeshTile::links, dtMeshTile::linksFreeList, m_maxTiles, m_nextFree, m_posLookup, m_tileLutMask, m_tiles, dtMeshHeader::magic, dtMeshHeader::maxLinkCount, dtLink::next, dtMeshTile::next, dtMeshHeader::offMeshConCount, dtMeshTile::offMeshCons, dtMeshHeader::polyCount, dtMeshTile::polys, prev(), dtMeshTile::salt, dtMeshHeader::version, dtMeshHeader::vertCount, dtMeshTile::verts, dtMeshHeader::x, and dtMeshHeader::y.
Referenced by MMAP::MapBuilder::buildMoveMapTile(), init(), MMAP::MMapMgr::loadMap(), and LoadTile().
baseOffMeshLinks()
void dtNavMesh::baseOffMeshLinks (dtMeshTile * tile) private
Builds internal polygons links for a tile.
Definition at line 561 of file DetourNavMesh.cpp.
 {
     if (!tile) return;
     dtPolyRef base = getPolyRefBase(tile);
     // Base off-mesh connection start points.
     for (int i = 0; i < tile->header->offMeshConCount; ++i)
     {
         dtOffMeshConnection* con = &tile->offMeshCons[i];
         dtPoly* poly = &tile->polys[con->poly];
         const float halfExtents[3] = { con->rad, tile->header->walkableClimb, con->rad };
         // Find polygon to connect to.
         const float* p = &con->pos[0]; // First vertex
         float nearestPt[3];
         dtPolyRef ref = findNearestPolyInTile(tile, p, halfExtents, nearestPt);
         if (!ref) continue;
         // findNearestPoly may return too optimistic results, further check to make sure.
         if (dtSqr(nearestPt[0]-p[0])+dtSqr(nearestPt[2]-p[2]) > dtSqr(con->rad))
             continue;
         // Make sure the location is on current mesh.
         float* v = &tile->verts[poly->verts[0]*3];
         dtVcopy(v, nearestPt);
         // Link off-mesh connection to target poly.
         unsigned int idx = allocLink(tile);
         if (idx != DT_NULL_LINK)
         {
             dtLink* link = &tile->links[idx];
             link->ref = ref;
             link->edge = (unsigned char)0;
             link->side = 0xff;
             link->bmin = link->bmax = 0;
             // Add to linked list.
             link->next = poly->firstLink;
             poly->firstLink = idx;
         }
         // Start end-point is always connect back to off-mesh connection.
         unsigned int tidx = allocLink(tile);
         if (tidx != DT_NULL_LINK)
         {
             const unsigned short landPolyIdx = (unsigned short)decodePolyIdPoly(ref);
             dtPoly* landPoly = &tile->polys[landPolyIdx];
             dtLink* link = &tile->links[tidx];
             link->ref = base | (dtPolyRef)(con->poly);
             link->edge = 0xff;
             link->side = 0xff;
             link->bmin = link->bmax = 0;
             // Add to linked list.
             link->next = landPoly->firstLink;
             landPoly->firstLink = tidx;
         }
     }
 }
References allocLink(), decodePolyIdPoly(), DT_NULL_LINK, dtSqr(), dtVcopy(), findNearestPolyInTile(), dtPoly::firstLink, getPolyRefBase(), dtMeshTile::header, idx, dtMeshTile::links, dtMeshHeader::offMeshConCount, dtMeshTile::offMeshCons, dtOffMeshConnection::poly, dtMeshTile::polys, dtOffMeshConnection::pos, dtOffMeshConnection::rad, dtPoly::verts, dtMeshTile::verts, and dtMeshHeader::walkableClimb.
Referenced by addTile().
calcTileLoc()
void dtNavMesh::calcTileLoc (const float * pos, int * tx, int * ty) const
Calculates the tile grid location for the specified world position.
Parameters
[in] pos The world position for the query. [(x, y, z)]
[out] tx The tile's x-location. (x, y)
[out] ty The tile's y-location. (x, y)
Definition at line 1184 of file DetourNavMesh.cpp.
 {
     *tx = (int)floorf((pos[0]-m_orig[0]) / m_tileWidth);
     *ty = (int)floorf((pos[2]-m_orig[2]) / m_tileHeight);
 }
References m_orig, m_tileHeight, m_tileWidth, and pos().
Referenced by PathGenerator::HaveTile(), and dtNavMeshQuery::queryPolygons().
closestPointOnPoly()
void dtNavMesh::closestPointOnPoly (dtPolyRef ref, const float * pos, float * closest, bool * posOverPoly) const private
Returns closest point on polygon.
Definition at line 728 of file DetourNavMesh.cpp.
 {
     const dtMeshTile* tile = 0;
     const dtPoly* poly = 0;
     getTileAndPolyByRefUnsafe(ref, &tile, &poly);
     dtVcopy(closest, pos);
     if (getPolyHeight(tile, poly, pos, &closest[1]))
     {
         if (posOverPoly)
             *posOverPoly = true;
         return;
     }
     if (posOverPoly)
         *posOverPoly = false;
     // Off-mesh connections don't have detail polygons.
     if (poly->getType() == DT_POLYTYPE_OFFMESH_CONNECTION)
     {
         const float* v0 = &tile->verts[poly->verts[0]*3];
         const float* v1 = &tile->verts[poly->verts[1]*3];
         float t;
         dtDistancePtSegSqr2D(pos, v0, v1, t);
         dtVlerp(closest, v0, v1, t);
         return;
     }
     // Outside poly that is not an offmesh connection.
     closestPointOnDetailEdges<true>(tile, poly, pos, closest);
 }
References DT_POLYTYPE_OFFMESH_CONNECTION, dtDistancePtSegSqr2D(), dtVcopy(), dtVlerp(), getPolyHeight(), getTileAndPolyByRefUnsafe(), dtPoly::getType(), pos(), dtPoly::verts, and dtMeshTile::verts.
Referenced by dtNavMeshQuery::closestPointOnPoly(), and findNearestPolyInTile().
connectExtLinks()
void dtNavMesh::connectExtLinks (dtMeshTile * tile, dtMeshTile * target, int side) private
Builds external polygon links for a tile.
Definition at line 387 of file DetourNavMesh.cpp.
 {
     if (!tile) return;
     // Connect border links.
     for (int i = 0; i < tile->header->polyCount; ++i)
     {
         dtPoly* poly = &tile->polys[i];
         // Create new links.
 //      unsigned short m = DT_EXT_LINK | (unsigned short)side;
         const int nv = poly->vertCount;
         for (int j = 0; j < nv; ++j)
         {
             // Skip non-portal edges.
             if ((poly->neis[j] & DT_EXT_LINK) == 0)
                 continue;
             const int dir = (int)(poly->neis[j] & 0xff);
             if (side != -1 && dir != side)
                 continue;
             // Create new links
             const float* va = &tile->verts[poly->verts[j]*3];
             const float* vb = &tile->verts[poly->verts[(j+1) % nv]*3];
             dtPolyRef nei[4];
             float neia[4*2];
             int nnei = findConnectingPolys(va,vb, target, dtOppositeTile(dir), nei,neia,4);
             for (int k = 0; k < nnei; ++k)
             {
                 unsigned int idx = allocLink(tile);
                 if (idx != DT_NULL_LINK)
                 {
                     dtLink* link = &tile->links[idx];
                     link->ref = nei[k];
                     link->edge = (unsigned char)j;
                     link->side = (unsigned char)dir;
                     link->next = poly->firstLink;
                     poly->firstLink = idx;
                     // Compress portal limits to a byte value.
                     if (dir == 0 || dir == 4)
                     {
                         float tmin = (neia[k*2+0]-va[2]) / (vb[2]-va[2]);
                         float tmax = (neia[k*2+1]-va[2]) / (vb[2]-va[2]);
                         if (tmin > tmax)
                             dtSwap(tmin,tmax);
                         link->bmin = (unsigned char)(dtClamp(tmin, 0.0f, 1.0f)*255.0f);
                         link->bmax = (unsigned char)(dtClamp(tmax, 0.0f, 1.0f)*255.0f);
                     }
                     else if (dir == 2 || dir == 6)
                     {
                         float tmin = (neia[k*2+0]-va[0]) / (vb[0]-va[0]);
                         float tmax = (neia[k*2+1]-va[0]) / (vb[0]-va[0]);
                         if (tmin > tmax)
                             dtSwap(tmin,tmax);
                         link->bmin = (unsigned char)(dtClamp(tmin, 0.0f, 1.0f)*255.0f);
                         link->bmax = (unsigned char)(dtClamp(tmax, 0.0f, 1.0f)*255.0f);
                     }
                 }
             }
         }
     }
 }
References allocLink(), DT_EXT_LINK, DT_NULL_LINK, dtClamp(), dtOppositeTile(), dtSwap(), findConnectingPolys(), dtPoly::firstLink, dtMeshTile::header, idx, dtMeshTile::links, dtPoly::neis, dtMeshHeader::polyCount, dtMeshTile::polys, dtPoly::vertCount, dtPoly::verts, and dtMeshTile::verts.
Referenced by addTile().
connectExtOffMeshLinks()
void dtNavMesh::connectExtOffMeshLinks (dtMeshTile * tile, dtMeshTile * target, int side) private
Builds external polygon links for a tile.
Definition at line 454 of file DetourNavMesh.cpp.
 {
     if (!tile) return;
     // Connect off-mesh links.
     // We are interested on links which land from target tile to this tile.
     const unsigned char oppositeSide = (side == -1) ? 0xff : (unsigned char)dtOppositeTile(side);
     for (int i = 0; i < target->header->offMeshConCount; ++i)
     {
         dtOffMeshConnection* targetCon = &target->offMeshCons[i];
         if (targetCon->side != oppositeSide)
             continue;
         dtPoly* targetPoly = &target->polys[targetCon->poly];
         // Skip off-mesh connections which start location could not be connected at all.
         if (targetPoly->firstLink == DT_NULL_LINK)
             continue;
         const float halfExtents[3] = { targetCon->rad, target->header->walkableClimb, targetCon->rad };
         // Find polygon to connect to.
         const float* p = &targetCon->pos[3];
         float nearestPt[3];
         dtPolyRef ref = findNearestPolyInTile(tile, p, halfExtents, nearestPt);
         if (!ref)
             continue;
         // findNearestPoly may return too optimistic results, further check to make sure.
         if (dtSqr(nearestPt[0]-p[0])+dtSqr(nearestPt[2]-p[2]) > dtSqr(targetCon->rad))
             continue;
         // Make sure the location is on current mesh.
         float* v = &target->verts[targetPoly->verts[1]*3];
         dtVcopy(v, nearestPt);
         // Link off-mesh connection to target poly.
         unsigned int idx = allocLink(target);
         if (idx != DT_NULL_LINK)
         {
             dtLink* link = &target->links[idx];
             link->ref = ref;
             link->edge = (unsigned char)1;
             link->side = oppositeSide;
             link->bmin = link->bmax = 0;
             // Add to linked list.
             link->next = targetPoly->firstLink;
             targetPoly->firstLink = idx;
         }
         // Link target poly to off-mesh connection.
         if (targetCon->flags & DT_OFFMESH_CON_BIDIR)
         {
             unsigned int tidx = allocLink(tile);
             if (tidx != DT_NULL_LINK)
             {
                 const unsigned short landPolyIdx = (unsigned short)decodePolyIdPoly(ref);
                 dtPoly* landPoly = &tile->polys[landPolyIdx];
                 dtLink* link = &tile->links[tidx];
                 link->ref = getPolyRefBase(target) | (dtPolyRef)(targetCon->poly);
                 link->edge = 0xff;
                 link->side = (unsigned char)(side == -1 ? 0xff : side);
                 link->bmin = link->bmax = 0;
                 // Add to linked list.
                 link->next = landPoly->firstLink;
                 landPoly->firstLink = tidx;
             }
         }
     }
 }
References allocLink(), decodePolyIdPoly(), DT_NULL_LINK, DT_OFFMESH_CON_BIDIR, dtOppositeTile(), dtSqr(), dtVcopy(), findNearestPolyInTile(), dtPoly::firstLink, dtOffMeshConnection::flags, getPolyRefBase(), dtMeshTile::header, idx, dtMeshTile::links, dtMeshHeader::offMeshConCount, dtMeshTile::offMeshCons, dtOffMeshConnection::poly, dtMeshTile::polys, dtOffMeshConnection::pos, dtOffMeshConnection::rad, dtOffMeshConnection::side, dtPoly::verts, dtMeshTile::verts, and dtMeshHeader::walkableClimb.
Referenced by addTile().
connectIntLinks()
void dtNavMesh::connectIntLinks (dtMeshTile * tile) private
Builds internal polygons links for a tile.
Definition at line 524 of file DetourNavMesh.cpp.
 {
     if (!tile) return;
     dtPolyRef base = getPolyRefBase(tile);
     for (int i = 0; i < tile->header->polyCount; ++i)
     {
         dtPoly* poly = &tile->polys[i];
         poly->firstLink = DT_NULL_LINK;
         if (poly->getType() == DT_POLYTYPE_OFFMESH_CONNECTION)
             continue;
         // Build edge links backwards so that the links will be
         // in the linked list from lowest index to highest.
         for (int j = poly->vertCount-1; j >= 0; --j)
         {
             // Skip hard and non-internal edges.
             if (poly->neis[j] == 0 || (poly->neis[j] & DT_EXT_LINK)) continue;
             unsigned int idx = allocLink(tile);
             if (idx != DT_NULL_LINK)
             {
                 dtLink* link = &tile->links[idx];
                 link->ref = base | (dtPolyRef)(poly->neis[j]-1);
                 link->edge = (unsigned char)j;
                 link->side = 0xff;
                 link->bmin = link->bmax = 0;
                 // Add to linked list.
                 link->next = poly->firstLink;
                 poly->firstLink = idx;
             }
         }
     }
 }
References allocLink(), DT_EXT_LINK, DT_NULL_LINK, DT_POLYTYPE_OFFMESH_CONNECTION, dtPoly::firstLink, getPolyRefBase(), dtPoly::getType(), dtMeshTile::header, idx, dtMeshTile::links, dtPoly::neis, dtMeshHeader::polyCount, dtMeshTile::polys, and dtPoly::vertCount.
Referenced by addTile().
decodePolyId()
void dtNavMesh::decodePolyId (dtPolyRef ref, unsigned int & salt, unsigned int & it, unsigned int & ip) const inline
Decodes a standard polygon reference.
Note
This function is generally meant for internal use only.
Parameters
[in] ref The polygon reference to decode.
[out] salt The tile's salt value.
[out] it The index of the tile.
[out] ip The index of the polygon within the tile.
See also
encodePolyId
Definition at line 557 of file DetourNavMesh.h.
     {
 #ifdef DT_POLYREF64
         const dtPolyRef saltMask = ((dtPolyRef)1<<DT_SALT_BITS)-1;
         const dtPolyRef tileMask = ((dtPolyRef)1<<DT_TILE_BITS)-1;
         const dtPolyRef polyMask = ((dtPolyRef)1<<DT_POLY_BITS)-1;
         salt = (unsigned int)((ref >> (DT_POLY_BITS+DT_TILE_BITS)) & saltMask);
         it = (unsigned int)((ref >> DT_POLY_BITS) & tileMask);
         ip = (unsigned int)(ref & polyMask);
 #else
         const dtPolyRef saltMask = ((dtPolyRef)1<<m_saltBits)-1;
         const dtPolyRef tileMask = ((dtPolyRef)1<<m_tileBits)-1;
         const dtPolyRef polyMask = ((dtPolyRef)1<<m_polyBits)-1;
         salt = (unsigned int)((ref >> (m_polyBits+m_tileBits)) & saltMask);
         it = (unsigned int)((ref >> m_polyBits) & tileMask);
         ip = (unsigned int)(ref & polyMask);
 #endif
     }
References DT_POLY_BITS, DT_SALT_BITS, and DT_TILE_BITS.
Referenced by getOffMeshConnectionByRef(), getOffMeshConnectionPolyEndPoints(), getPolyArea(), getPolyFlags(), getTileAndPolyByRef(), getTileAndPolyByRefUnsafe(), isValidPolyRef(), setPolyArea(), and setPolyFlags().
decodePolyIdPoly()
unsigned int dtNavMesh::decodePolyIdPoly (dtPolyRef ref) const inline
Extracts the polygon's index (within its tile) from the specified polygon reference.
Note
This function is generally meant for internal use only.
Parameters
[in] ref The polygon reference.
See also
encodePolyId
Definition at line 610 of file DetourNavMesh.h.
     {
 #ifdef DT_POLYREF64
         const dtPolyRef polyMask = ((dtPolyRef)1<<DT_POLY_BITS)-1;
         return (unsigned int)(ref & polyMask);
 #else
         const dtPolyRef polyMask = ((dtPolyRef)1<<m_polyBits)-1;
         return (unsigned int)(ref & polyMask);
 #endif
     }
References DT_POLY_BITS.
Referenced by baseOffMeshLinks(), and connectExtOffMeshLinks().
decodePolyIdSalt()
unsigned int dtNavMesh::decodePolyIdSalt (dtPolyRef ref) const inline
Extracts a tile's salt value from the specified polygon reference.
Note
This function is generally meant for internal use only.
Parameters
[in] ref The polygon reference.
See also
encodePolyId
Definition at line 580 of file DetourNavMesh.h.
     {
 #ifdef DT_POLYREF64
         const dtPolyRef saltMask = ((dtPolyRef)1<<DT_SALT_BITS)-1;
         return (unsigned int)((ref >> (DT_POLY_BITS+DT_TILE_BITS)) & saltMask);
 #else
         const dtPolyRef saltMask = ((dtPolyRef)1<<m_saltBits)-1;
         return (unsigned int)((ref >> (m_polyBits+m_tileBits)) & saltMask);
 #endif
     }
References DT_POLY_BITS, DT_SALT_BITS, and DT_TILE_BITS.
Referenced by addTile(), getTileByRef(), and removeTile().
decodePolyIdTile()
unsigned int dtNavMesh::decodePolyIdTile (dtPolyRef ref) const inline
Extracts the tile's index from the specified polygon reference.
Note
This function is generally meant for internal use only.
Parameters
[in] ref The polygon reference.
See also
encodePolyId
Definition at line 595 of file DetourNavMesh.h.
     {
 #ifdef DT_POLYREF64
         const dtPolyRef tileMask = ((dtPolyRef)1<<DT_TILE_BITS)-1;
         return (unsigned int)((ref >> DT_POLY_BITS) & tileMask);
 #else
         const dtPolyRef tileMask = ((dtPolyRef)1<<m_tileBits)-1;
         return (unsigned int)((ref >> m_polyBits) & tileMask);
 #endif
     }
References DT_POLY_BITS, and DT_TILE_BITS.
Referenced by addTile(), getTileByRef(), removeTile(), and unconnectLinks().
encodePolyId()
dtPolyRef dtNavMesh::encodePolyId (unsigned int salt, unsigned int it, unsigned int ip) const inline
Derives a standard polygon reference.
Note
This function is generally meant for internal use only.
Parameters
[in] salt The tile's salt value.
[in] it The index of the tile.
[in] ip The index of the polygon within the tile.
Definition at line 541 of file DetourNavMesh.h.
     {
 #ifdef DT_POLYREF64
         return ((dtPolyRef)salt << (DT_POLY_BITS+DT_TILE_BITS)) | ((dtPolyRef)it << DT_POLY_BITS) | (dtPolyRef)ip;
 #else
         return ((dtPolyRef)salt << (m_polyBits+m_tileBits)) | ((dtPolyRef)it << m_polyBits) | (dtPolyRef)ip;
 #endif
     }
References DT_POLY_BITS, and DT_TILE_BITS.
Referenced by getPolyRefBase(), and getTileRef().
findConnectingPolys()
int dtNavMesh::findConnectingPolys (const float * va, const float * vb, const dtMeshTile * tile, int side, dtPolyRef * con, float * conarea, int maxcon) const private
Returns all polygons in neighbour tile based on portal defined by the segment.
Definition at line 300 of file DetourNavMesh.cpp.
 {
     if (!tile) return 0;
     float amin[2], amax[2];
     calcSlabEndPoints(va, vb, amin, amax, side);
     const float apos = getSlabCoord(va, side);
     // Remove links pointing to 'side' and compact the links array.
     float bmin[2], bmax[2];
     unsigned short m = DT_EXT_LINK | (unsigned short)side;
     int n = 0;
     dtPolyRef base = getPolyRefBase(tile);
     for (int i = 0; i < tile->header->polyCount; ++i)
     {
         dtPoly* poly = &tile->polys[i];
         const int nv = poly->vertCount;
         for (int j = 0; j < nv; ++j)
         {
             // Skip edges which do not point to the right side.
             if (poly->neis[j] != m) continue;
             const float* vc = &tile->verts[poly->verts[j]*3];
             const float* vd = &tile->verts[poly->verts[(j+1) % nv]*3];
             const float bpos = getSlabCoord(vc, side);
             // Segments are not close enough.
             if (dtAbs(apos-bpos) > 0.01f)
                 continue;
             // Check if the segments touch.
             calcSlabEndPoints(vc,vd, bmin,bmax, side);
             if (!overlapSlabs(amin,amax, bmin,bmax, 0.01f, tile->header->walkableClimb)) continue;
             // Add return value.
             if (n < maxcon)
             {
                 conarea[n*2+0] = dtMax(amin[0], bmin[0]);
                 conarea[n*2+1] = dtMin(amax[0], bmax[0]);
                 con[n] = base | (dtPolyRef)i;
                 n++;
             }
             break;
         }
     }
     return n;
 }
References calcSlabEndPoints(), DT_EXT_LINK, dtAbs(), dtMax(), dtMin(), getPolyRefBase(), getSlabCoord(), dtMeshTile::header, dtPoly::neis, overlapSlabs(), dtMeshHeader::polyCount, dtMeshTile::polys, dtPoly::vertCount, dtPoly::verts, dtMeshTile::verts, and dtMeshHeader::walkableClimb.
Referenced by connectExtLinks().
findNearestPolyInTile()
dtPolyRef dtNavMesh::findNearestPolyInTile (const dtMeshTile * tile, const float * center, const float * halfExtents, float * nearestPt) const private
Find nearest polygon within a tile.
Definition at line 760 of file DetourNavMesh.cpp.
 {
     float bmin[3], bmax[3];
     dtVsub(bmin, center, halfExtents);
     dtVadd(bmax, center, halfExtents);
     // Get nearby polygons from proximity grid.
     dtPolyRef polys[128];
     int polyCount = queryPolygonsInTile(tile, bmin, bmax, polys, 128);
     // Find nearest polygon amongst the nearby polygons.
     dtPolyRef nearest = 0;
     float nearestDistanceSqr = FLT_MAX;
     for (int i = 0; i < polyCount; ++i)
     {
         dtPolyRef ref = polys[i];
         float closestPtPoly[3];
         float diff[3];
         bool posOverPoly = false;
         float d;
         closestPointOnPoly(ref, center, closestPtPoly, &posOverPoly);
         // If a point is directly over a polygon and closer than
         // climb height, favor that instead of straight line nearest point.
         dtVsub(diff, center, closestPtPoly);
         if (posOverPoly)
         {
             d = dtAbs(diff[1]) - tile->header->walkableClimb;
             d = d > 0 ? d*d : 0;
         }
         else
         {
             d = dtVlenSqr(diff);
         }
         if (d < nearestDistanceSqr)
         {
             dtVcopy(nearestPt, closestPtPoly);
             nearestDistanceSqr = d;
             nearest = ref;
         }
     }
     return nearest;
 }
References align::center, closestPointOnPoly(), mpq::d, diff(), dtAbs(), dtVadd(), dtVcopy(), dtVlenSqr(), dtVsub(), FLT_MAX, dtMeshTile::header, queryPolygonsInTile(), and dtMeshHeader::walkableClimb.
Referenced by baseOffMeshLinks(), and connectExtOffMeshLinks().
getMaxTiles()
int dtNavMesh::getMaxTiles () const
The maximum number of tiles supported by the navigation mesh.
Returns
The maximum number of tiles supported by the navigation mesh.
Definition at line 1169 of file DetourNavMesh.cpp.
 {
     return m_maxTiles;
 }
References m_maxTiles.
Referenced by dtNavMeshQuery::findRandomPoint(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), and mmaps_commandscript::HandleMmapStatsCommand().
getNeighbourTilesAt()
int dtNavMesh::getNeighbourTilesAt (const int x, const int y, const int side, dtMeshTile ** tiles, const int maxTiles) const private
Returns neighbour tile based on side.
Definition at line 1069 of file DetourNavMesh.cpp.
 {
     int nx = x, ny = y;
     switch (side)
     {
         case 0: nx++; break;
         case 1: nx++; ny++; break;
         case 2: ny++; break;
         case 3: nx--; ny++; break;
         case 4: nx--; break;
         case 5: nx--; ny--; break;
         case 6: ny--; break;
         case 7: nx++; ny--; break;
     };
     return getTilesAt(nx, ny, tiles, maxTiles);
 }
References getTilesAt(), G3D::x, and G3D::y.
Referenced by addTile(), and removeTile().
getOffMeshConnectionByRef()
const dtOffMeshConnection * dtNavMesh::getOffMeshConnectionByRef (dtPolyRef ref) const
Gets the specified off-mesh connection.
Parameters
[in] ref The polygon reference of the off-mesh connection.
Returns
The specified off-mesh connection, or null if the polygon reference is not valid.
Definition at line 1495 of file DetourNavMesh.cpp.
 {
     unsigned int salt, it, ip;
     if (!ref)
         return 0;
     // Get current polygon
     decodePolyId(ref, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return 0;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return 0;
     const dtMeshTile* tile = &m_tiles[it];
     if (ip >= (unsigned int)tile->header->polyCount) return 0;
     const dtPoly* poly = &tile->polys[ip];
     // Make sure that the current poly is indeed off-mesh link.
     if (poly->getType() != DT_POLYTYPE_OFFMESH_CONNECTION)
         return 0;
     const unsigned int idx =  ip - tile->header->offMeshBase;
     dtAssert(idx < (unsigned int)tile->header->offMeshConCount);
     return &tile->offMeshCons[idx];
 }
References decodePolyId(), DT_POLYTYPE_OFFMESH_CONNECTION, dtAssert, dtPoly::getType(), dtMeshTile::header, idx, m_maxTiles, m_tiles, dtMeshHeader::offMeshBase, dtMeshHeader::offMeshConCount, dtMeshTile::offMeshCons, dtMeshHeader::polyCount, and dtMeshTile::polys.
getOffMeshConnectionPolyEndPoints()
dtStatus dtNavMesh::getOffMeshConnectionPolyEndPoints (dtPolyRef prevRef, dtPolyRef polyRef, float * startPos, float * endPos) const
Gets the endpoints for an off-mesh connection, ordered by "direction of travel".
Parameters
[in] prevRef The reference of the polygon before the connection.
[in] polyRef The reference of the off-mesh connection polygon.
[out] startPos The start position of the off-mesh connection. [(x, y, z)]
[out] endPos The end position of the off-mesh connection. [(x, y, z)]
Returns
The status flags for the operation.
Off-mesh connections are stored in the navigation mesh as special 2-vertex polygons with a single edge. At least one of the vertices is expected to be inside a normal polygon. So an off-mesh connection is "entered" from a normal polygon at one of its endpoints. This is the polygon identified by the prevRef parameter.
Definition at line 1452 of file DetourNavMesh.cpp.
 {
     unsigned int salt, it, ip;
     if (!polyRef)
         return DT_FAILURE;
     // Get current polygon
     decodePolyId(polyRef, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return DT_FAILURE | DT_INVALID_PARAM;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return DT_FAILURE | DT_INVALID_PARAM;
     const dtMeshTile* tile = &m_tiles[it];
     if (ip >= (unsigned int)tile->header->polyCount) return DT_FAILURE | DT_INVALID_PARAM;
     const dtPoly* poly = &tile->polys[ip];
     // Make sure that the current poly is indeed off-mesh link.
     if (poly->getType() != DT_POLYTYPE_OFFMESH_CONNECTION)
         return DT_FAILURE;
     // Figure out which way to hand out the vertices.
     int idx0 = 0, idx1 = 1;
     // Find link that points to first vertex.
     for (unsigned int i = poly->firstLink; i != DT_NULL_LINK; i = tile->links[i].next)
     {
         if (tile->links[i].edge == 0)
         {
             if (tile->links[i].ref != prevRef)
             {
                 idx0 = 1;
                 idx1 = 0;
             }
             break;
         }
     }
     dtVcopy(startPos, &tile->verts[poly->verts[idx0]*3]);
     dtVcopy(endPos, &tile->verts[poly->verts[idx1]*3]);
     return DT_SUCCESS;
 }
References decodePolyId(), DT_FAILURE, DT_INVALID_PARAM, DT_NULL_LINK, DT_POLYTYPE_OFFMESH_CONNECTION, DT_SUCCESS, dtVcopy(), dtLink::edge, dtPoly::firstLink, dtPoly::getType(), dtMeshTile::header, dtMeshTile::links, m_maxTiles, m_tiles, dtLink::next, dtMeshHeader::polyCount, dtMeshTile::polys, dtLink::ref, dtPoly::verts, and dtMeshTile::verts.
Referenced by PathGenerator::FindSmoothPath().
getParams()
const dtNavMeshParams * dtNavMesh::getParams () const
The navigation mesh initialization params.
Note
The parameters are created automatically when the single tile initialization is performed.
Definition at line 294 of file DetourNavMesh.cpp.
 {
     return &m_params;
 }
References m_params.
Referenced by MMAP::MapBuilder::buildMoveMapTile(), and mmaps_commandscript::HandleMmapLocCommand().
getPolyArea()
dtStatus dtNavMesh::getPolyArea (dtPolyRef ref, unsigned char * resultArea) const
Gets the user defined area for the specified polygon.
Parameters
[in] ref The polygon reference.
[out] resultArea The area id for the polygon.
Returns
The status flags for the operation.
Definition at line 1569 of file DetourNavMesh.cpp.
 {
     if (!ref) return DT_FAILURE;
     unsigned int salt, it, ip;
     decodePolyId(ref, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return DT_FAILURE | DT_INVALID_PARAM;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return DT_FAILURE | DT_INVALID_PARAM;
     const dtMeshTile* tile = &m_tiles[it];
     if (ip >= (unsigned int)tile->header->polyCount) return DT_FAILURE | DT_INVALID_PARAM;
     const dtPoly* poly = &tile->polys[ip];
     *resultArea = poly->getArea();
     return DT_SUCCESS;
 }
References decodePolyId(), DT_FAILURE, DT_INVALID_PARAM, DT_SUCCESS, dtPoly::getArea(), dtMeshTile::header, m_maxTiles, m_tiles, dtMeshHeader::polyCount, and dtMeshTile::polys.
getPolyFlags()
dtStatus dtNavMesh::getPolyFlags (dtPolyRef ref, unsigned short * resultFlags) const
Gets the user defined flags for the specified polygon.
Parameters
[in] ref The polygon reference.
[out] resultFlags The polygon flags.
Returns
The status flags for the operation.
Definition at line 1537 of file DetourNavMesh.cpp.
 {
     if (!ref) return DT_FAILURE;
     unsigned int salt, it, ip;
     decodePolyId(ref, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return DT_FAILURE | DT_INVALID_PARAM;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return DT_FAILURE | DT_INVALID_PARAM;
     const dtMeshTile* tile = &m_tiles[it];
     if (ip >= (unsigned int)tile->header->polyCount) return DT_FAILURE | DT_INVALID_PARAM;
     const dtPoly* poly = &tile->polys[ip];
     *resultFlags = poly->flags;
     return DT_SUCCESS;
 }
References decodePolyId(), DT_FAILURE, DT_INVALID_PARAM, DT_SUCCESS, dtPoly::flags, dtMeshTile::header, m_maxTiles, m_tiles, dtMeshHeader::polyCount, and dtMeshTile::polys.
getPolyHeight()
bool dtNavMesh::getPolyHeight (const dtMeshTile * tile, const dtPoly * poly, const float * pos, float * height) const private
Returns whether position is over the poly and the height at the position if so.
Definition at line 677 of file DetourNavMesh.cpp.
 {
     // Off-mesh connections do not have detail polys and getting height
     // over them does not make sense.
     if (poly->getType() == DT_POLYTYPE_OFFMESH_CONNECTION)
         return false;
     const unsigned int ip = (unsigned int)(poly - tile->polys);
     const dtPolyDetail* pd = &tile->detailMeshes[ip];
     float verts[DT_VERTS_PER_POLYGON*3];
     const int nv = poly->vertCount;
     for (int i = 0; i < nv; ++i)
         dtVcopy(&verts[i*3], &tile->verts[poly->verts[i]*3]);
     if (!dtPointInPolygon(pos, verts, nv))
         return false;
     if (!height)
         return true;
     // Find height at the location.
     for (int j = 0; j < pd->triCount; ++j)
     {
         const unsigned char* t = &tile->detailTris[(pd->triBase+j)*4];
         const float* v[3];
         for (int k = 0; k < 3; ++k)
         {
             if (t[k] < poly->vertCount)
                 v[k] = &tile->verts[poly->verts[t[k]]*3];
             else
                 v[k] = &tile->detailVerts[(pd->vertBase+(t[k]-poly->vertCount))*3];
         }
         float h;
         if (dtClosestHeightPointTriangle(pos, v[0], v[1], v[2], h))
         {
             *height = h;
             return true;
         }
     }
     // If all triangle checks failed above (can happen with degenerate triangles
     // or larger floating point values) the point is on an edge, so just select
     // closest. This should almost never happen so the extra iteration here is
     // ok.
     float closest[3];
     closestPointOnDetailEdges<false>(tile, poly, pos, closest);
     *height = closest[1];
     return true;
 }
References dtMeshTile::detailMeshes, dtMeshTile::detailTris, dtMeshTile::detailVerts, DT_POLYTYPE_OFFMESH_CONNECTION, DT_VERTS_PER_POLYGON, dtClosestHeightPointTriangle(), dtPointInPolygon(), dtVcopy(), dtPoly::getType(), dtMeshTile::polys, pos(), dtPolyDetail::triBase, dtPolyDetail::triCount, dtPolyDetail::vertBase, dtPoly::vertCount, dtPoly::verts, and dtMeshTile::verts.
Referenced by closestPointOnPoly(), and dtNavMeshQuery::getPolyHeight().
getPolyRefBase()
dtPolyRef dtNavMesh::getPolyRefBase (const dtMeshTile * tile) const
Gets the polygon reference for the tile's base polygon.
Parameters
[in] tile The tile.
Returns
The polygon reference for the base polygon in the specified tile.
Example use case:
const dtPolyRef base = navmesh->getPolyRefBase(tile);
for (int i = 0; i < tile->header->polyCount; ++i)
{
    const dtPoly* p = &tile->polys[i];
    const dtPolyRef ref = base | (dtPolyRef)i;
    // Use the reference to access the polygon data.
}
Definition at line 1349 of file DetourNavMesh.cpp.
 {
     if (!tile) return 0;
     const unsigned int it = (unsigned int)(tile - m_tiles);
     return encodePolyId(tile->salt, it, 0);
 }
References encodePolyId(), m_tiles, and dtMeshTile::salt.
Referenced by baseOffMeshLinks(), connectExtOffMeshLinks(), connectIntLinks(), findConnectingPolys(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findRandomPoint(), dtNavMeshQuery::getPolyWallSegments(), dtNavMeshQuery::moveAlongSurface(), dtNavMeshQuery::queryPolygonsInTile(), and queryPolygonsInTile().
getTile() [1/2]
dtMeshTile * dtNavMesh::getTile (int i) private
Returns pointer to tile in the tile array.
Definition at line 1174 of file DetourNavMesh.cpp.
 {
     return &m_tiles[i];
 }
References m_tiles.
getTile() [2/2]
const dtMeshTile * dtNavMesh::getTile (int i) const
Gets the tile at the specified index.
Parameters
[in] i The tile index. [Limit: 0 >= index < getMaxTiles()]
Returns
The tile at the specified index.
Definition at line 1179 of file DetourNavMesh.cpp.
 {
     return &m_tiles[i];
 }
References m_tiles.
Referenced by dtNavMeshQuery::findRandomPoint(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), and mmaps_commandscript::HandleMmapStatsCommand().
getTileAndPolyByRef()
dtStatus dtNavMesh::getTileAndPolyByRef (const dtPolyRef ref, const dtMeshTile ** tile, const dtPoly ** poly) const
Gets the tile and polygon for the specified polygon reference.
Parameters
[in] ref The reference for the a polygon.
[out] tile The tile containing the polygon.
[out] poly The polygon.
Returns
The status flags for the operation.
Definition at line 1190 of file DetourNavMesh.cpp.
 {
     if (!ref) return DT_FAILURE;
     unsigned int salt, it, ip;
     decodePolyId(ref, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return DT_FAILURE | DT_INVALID_PARAM;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return DT_FAILURE | DT_INVALID_PARAM;
     if (ip >= (unsigned int)m_tiles[it].header->polyCount) return DT_FAILURE | DT_INVALID_PARAM;
     *tile = &m_tiles[it];
     *poly = &m_tiles[it].polys[ip];
     return DT_SUCCESS;
 }
References decodePolyId(), DT_FAILURE, DT_INVALID_PARAM, DT_SUCCESS, m_maxTiles, m_tiles, and dtMeshTile::polys.
Referenced by dtNavMeshQuery::appendPortals(), dtNavMeshQuery::closestPointOnPolyBoundary(), dtNavMeshQuery::getPolyHeight(), dtNavMeshQuery::getPolyWallSegments(), dtNavMeshQuery::getPortalPoints(), mmaps_commandscript::HandleMmapLocCommand(), dtNavMeshQuery::isValidPolyRef(), and dtNavMeshQuery::updateSlicedFindPath().
getTileAndPolyByRefUnsafe()
void dtNavMesh::getTileAndPolyByRefUnsafe (const dtPolyRef ref, const dtMeshTile ** tile, const dtPoly ** poly) const
Returns the tile and polygon for the specified polygon reference.
Parameters
[in] ref A known valid reference for a polygon.
[out] tile The tile containing the polygon.
[out] poly The polygon.
Warning
Only use this function if it is known that the provided polygon reference is valid. This function is faster than getTileAndPolyByRef, but it does not validate the reference.
Definition at line 1208 of file DetourNavMesh.cpp.
 {
     unsigned int salt, it, ip;
     decodePolyId(ref, salt, it, ip);
     *tile = &m_tiles[it];
     *poly = &m_tiles[it].polys[ip];
 }
References decodePolyId(), m_tiles, and dtMeshTile::polys.
Referenced by closestPointOnPoly(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::getPolyWallSegments(), dtNavMeshQuery::moveAlongSurface(), dtNavMeshQuery::raycast(), and dtNavMeshQuery::updateSlicedFindPath().
getTileAt()
const dtMeshTile * dtNavMesh::getTileAt (const int x, const int y, const int layer) const
Gets the tile at the specified grid location.
Parameters
[in] x The tile's x-location. (x, y, layer)
[in] y The tile's y-location. (x, y, layer)
[in] layer The tile's layer. (x, y, layer)
Returns
The tile, or null if the tile does not exist.
Definition at line 1050 of file DetourNavMesh.cpp.
 {
     // Find tile based on hash.
     int h = computeTileHash(x,y,m_tileLutMask);
     dtMeshTile* tile = m_posLookup[h];
     while (tile)
     {
         if (tile->header &&
             tile->header->x == x &&
             tile->header->y == y &&
             tile->header->layer == layer)
         {
             return tile;
         }
         tile = tile->next;
     }
     return 0;
 }
References computeTileHash(), dtMeshTile::header, dtMeshHeader::layer, m_posLookup, m_tileLutMask, dtMeshTile::next, G3D::x, dtMeshHeader::x, G3D::y, and dtMeshHeader::y.
Referenced by addTile(), and PathGenerator::HaveTile().
getTileByRef()
const dtMeshTile * dtNavMesh::getTileByRef (dtTileRef ref) const
Gets the tile for the specified tile reference.
Parameters
[in] ref The tile reference of the tile to retrieve.
Returns
The tile for the specified reference, or null if the reference is invalid.
Definition at line 1155 of file DetourNavMesh.cpp.
 {
     if (!ref)
         return 0;
     unsigned int tileIndex = decodePolyIdTile((dtPolyRef)ref);
     unsigned int tileSalt = decodePolyIdSalt((dtPolyRef)ref);
     if ((int)tileIndex >= m_maxTiles)
         return 0;
     const dtMeshTile* tile = &m_tiles[tileIndex];
     if (tile->salt != tileSalt)
         return 0;
     return tile;
 }
References decodePolyIdSalt(), decodePolyIdTile(), m_maxTiles, m_tiles, and dtMeshTile::salt.
Referenced by dtNavMeshQuery::initSlicedFindPath().
getTileRef()
dtTileRef dtNavMesh::getTileRef (const dtMeshTile * tile) const
Gets the tile reference for the specified tile.
Parameters
[in] tile The tile.
Returns
The tile reference of the tile.
Definition at line 1328 of file DetourNavMesh.cpp.
 {
     if (!tile) return 0;
     const unsigned int it = (unsigned int)(tile - m_tiles);
     return (dtTileRef)encodePolyId(tile->salt, it, 0);
 }
References encodePolyId(), m_tiles, and dtMeshTile::salt.
Referenced by addTile(), getTileRefAt(), restoreTileState(), storeTileState(), and unconnectLinks().
getTileRefAt()
dtTileRef dtNavMesh::getTileRefAt (int x, int y, int layer) const
Gets the tile reference for the tile at specified grid location.
Parameters
[in] x The tile's x-location. (x, y, layer)
[in] y The tile's y-location. (x, y, layer)
[in] layer The tile's layer. (x, y, layer)
Returns
The tile reference of the tile, or 0 if there is none.
Definition at line 1136 of file DetourNavMesh.cpp.
 {
     // Find tile based on hash.
     int h = computeTileHash(x,y,m_tileLutMask);
     dtMeshTile* tile = m_posLookup[h];
     while (tile)
     {
         if (tile->header &&
             tile->header->x == x &&
             tile->header->y == y &&
             tile->header->layer == layer)
         {
             return getTileRef(tile);
         }
         tile = tile->next;
     }
     return 0;
 }
References computeTileHash(), getTileRef(), dtMeshTile::header, dtMeshHeader::layer, m_posLookup, m_tileLutMask, dtMeshTile::next, G3D::x, dtMeshHeader::x, G3D::y, and dtMeshHeader::y.
getTilesAt() [1/2]
int dtNavMesh::getTilesAt (const int x, const int y, dtMeshTile ** tiles, const int maxTiles) const private
Returns neighbour tile based on side.
Definition at line 1087 of file DetourNavMesh.cpp.
 {
     int n = 0;
     // Find tile based on hash.
     int h = computeTileHash(x,y,m_tileLutMask);
     dtMeshTile* tile = m_posLookup[h];
     while (tile)
     {
         if (tile->header &&
             tile->header->x == x &&
             tile->header->y == y)
         {
             if (n < maxTiles)
                 tiles[n++] = tile;
         }
         tile = tile->next;
     }
     return n;
 }
References computeTileHash(), dtMeshTile::header, m_posLookup, m_tileLutMask, dtMeshTile::next, G3D::x, dtMeshHeader::x, G3D::y, and dtMeshHeader::y.
getTilesAt() [2/2]
int dtNavMesh::getTilesAt (const int x, const int y, dtMeshTile const ** tiles, const int maxTiles) const
Gets all tiles at the specified grid location. (All layers.)
Parameters
[in] x The tile's x-location. (x, y)
[in] y The tile's y-location. (x, y)
[out] tiles A pointer to an array of tiles that will hold the result.
[in] maxTiles The maximum tiles the tiles parameter can hold.
Returns
The number of tiles returned in the tiles array.
This function will not fail if the tiles array is too small to hold the entire result set. It will simply fill the array to capacity.
Definition at line 1113 of file DetourNavMesh.cpp.
 {
     int n = 0;
     // Find tile based on hash.
     int h = computeTileHash(x,y,m_tileLutMask);
     dtMeshTile* tile = m_posLookup[h];
     while (tile)
     {
         if (tile->header &&
             tile->header->x == x &&
             tile->header->y == y)
         {
             if (n < maxTiles)
                 tiles[n++] = tile;
         }
         tile = tile->next;
     }
     return n;
 }
References computeTileHash(), dtMeshTile::header, m_posLookup, m_tileLutMask, dtMeshTile::next, G3D::x, dtMeshHeader::x, G3D::y, and dtMeshHeader::y.
Referenced by addTile(), getNeighbourTilesAt(), dtNavMeshQuery::queryPolygons(), and removeTile().
getTileStateSize()
int dtNavMesh::getTileStateSize (const dtMeshTile * tile) const
Gets the size of the buffer required by storeTileState to store the specified tile's state.
Parameters
[in] tile The tile.
Returns
The size of the buffer required to store the state.
See also
storeTileState
Definition at line 1370 of file DetourNavMesh.cpp.
 {
     if (!tile) return 0;
     const int headerSize = dtAlign4(sizeof(dtTileState));
     const int polyStateSize = dtAlign4(sizeof(dtPolyState) * tile->header->polyCount);
     return headerSize + polyStateSize;
 }
References dtAlign4(), dtMeshTile::header, and dtMeshHeader::polyCount.
Referenced by restoreTileState(), and storeTileState().
init() [1/2]
dtStatus dtNavMesh::init (const dtNavMeshParams * params)
Initializes the navigation mesh for tiled use.
Parameters
[in] params Initialization parameters.
Returns
The status flags for the operation.
Definition at line 224 of file DetourNavMesh.cpp.
 {
     memcpy(&m_params, params, sizeof(dtNavMeshParams));
     dtVcopy(m_orig, params->orig);
     m_tileWidth = params->tileWidth;
     m_tileHeight = params->tileHeight;
     // Init tiles
     m_maxTiles = params->maxTiles;
     m_tileLutSize = dtNextPow2(params->maxTiles/4);
     if (!m_tileLutSize) m_tileLutSize = 1;
     m_tileLutMask = m_tileLutSize-1;
     m_tiles = (dtMeshTile*)dtAlloc(sizeof(dtMeshTile)*m_maxTiles, DT_ALLOC_PERM);
     if (!m_tiles)
         return DT_FAILURE | DT_OUT_OF_MEMORY;
     m_posLookup = (dtMeshTile**)dtAlloc(sizeof(dtMeshTile*)*m_tileLutSize, DT_ALLOC_PERM);
     if (!m_posLookup)
         return DT_FAILURE | DT_OUT_OF_MEMORY;
     memset(m_tiles, 0, sizeof(dtMeshTile)*m_maxTiles);
     memset(m_posLookup, 0, sizeof(dtMeshTile*)*m_tileLutSize);
     m_nextFree = 0;
     for (int i = m_maxTiles-1; i >= 0; --i)
     {
         m_tiles[i].salt = 1;
         m_tiles[i].next = m_nextFree;
         m_nextFree = &m_tiles[i];
     }
     // Init ID generator values.
 #ifndef DT_POLYREF64
     m_tileBits = dtIlog2(dtNextPow2((unsigned int)params->maxTiles));
     m_polyBits = dtIlog2(dtNextPow2((unsigned int)params->maxPolys));
     // Only allow 31 salt bits, since the salt mask is calculated using 32bit uint and it will overflow.
     m_saltBits = dtMin((unsigned int)31, 32 - m_tileBits - m_polyBits);
     if (m_saltBits < 10)
         return DT_FAILURE | DT_INVALID_PARAM;
 #endif
     return DT_SUCCESS;
 }
References DT_ALLOC_PERM, DT_FAILURE, DT_INVALID_PARAM, DT_OUT_OF_MEMORY, DT_SUCCESS, dtAlloc(), dtIlog2(), dtMin(), dtNextPow2(), dtVcopy(), m_maxTiles, m_nextFree, m_orig, m_params, m_posLookup, m_tileHeight, m_tileLutMask, m_tileLutSize, m_tiles, m_tileWidth, dtNavMeshParams::maxPolys, dtNavMeshParams::maxTiles, memcpy, memset, dtMeshTile::next, dtNavMeshParams::orig, dtMeshTile::salt, dtNavMeshParams::tileHeight, and dtNavMeshParams::tileWidth.
Referenced by MMAP::MapBuilder::buildNavMesh(), init(), MMAP::MMapMgr::loadMapData(), and main().
init() [2/2]
dtStatus dtNavMesh::init (unsigned char * data, const int dataSize, const int flags)
Initializes the navigation mesh for single tile use.
Parameters
[in] data Data of the new tile. (See: dtCreateNavMeshData)
[in] dataSize The data size of the new tile.
[in] flags The tile flags. (See: dtTileFlags)
Returns
The status flags for the operation.
See also
dtCreateNavMeshData
Definition at line 267 of file DetourNavMesh.cpp.
 {
     // Make sure the data is in right format.
     dtMeshHeader* header = (dtMeshHeader*)data;
     if (header->magic != DT_NAVMESH_MAGIC)
         return DT_FAILURE | DT_WRONG_MAGIC;
     if (header->version != DT_NAVMESH_VERSION)
         return DT_FAILURE | DT_WRONG_VERSION;
     dtNavMeshParams params;
     dtVcopy(params.orig, header->bmin);
     params.tileWidth = header->bmax[0] - header->bmin[0];
     params.tileHeight = header->bmax[2] - header->bmin[2];
     params.maxTiles = 1;
     params.maxPolys = header->polyCount;
     dtStatus status = init(&params);
     if (dtStatusFailed(status))
         return status;
     return addTile(data, dataSize, flags, 0, 0);
 }
References addTile(), dtMeshHeader::bmax, dtMeshHeader::bmin, DT_FAILURE, DT_NAVMESH_MAGIC, DT_NAVMESH_VERSION, DT_WRONG_MAGIC, DT_WRONG_VERSION, dtStatusFailed(), dtVcopy(), init(), dtMeshHeader::magic, dtNavMeshParams::maxPolys, dtNavMeshParams::maxTiles, dtNavMeshParams::orig, dtMeshHeader::polyCount, dtNavMeshParams::tileHeight, dtNavMeshParams::tileWidth, and dtMeshHeader::version.
isValidPolyRef()
bool dtNavMesh::isValidPolyRef (dtPolyRef ref) const
Checks the validity of a polygon reference.
Parameters
[in] ref The polygon reference to check.
Returns
True if polygon reference is valid for the navigation mesh.
Definition at line 1216 of file DetourNavMesh.cpp.
 {
     if (!ref) return false;
     unsigned int salt, it, ip;
     decodePolyId(ref, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return false;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return false;
     if (ip >= (unsigned int)m_tiles[it].header->polyCount) return false;
     return true;
 }
References decodePolyId(), m_maxTiles, and m_tiles.
Referenced by dtNavMeshQuery::closestPointOnPoly(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::getPathFromDijkstraSearch(), dtNavMeshQuery::initSlicedFindPath(), dtNavMeshQuery::moveAlongSurface(), dtNavMeshQuery::raycast(), and dtNavMeshQuery::updateSlicedFindPath().
operator=()
dtNavMesh& dtNavMesh::operator= (const dtNavMesh &) private
queryPolygonsInTile()
int dtNavMesh::queryPolygonsInTile (const dtMeshTile * tile, const float * qmin, const float * qmax, dtPolyRef * polys, const int maxPolys) const private
Queries polygons within a tile.
Definition at line 808 of file DetourNavMesh.cpp.
 {
     if (tile->bvTree)
     {
         const dtBVNode* node = &tile->bvTree[0];
         const dtBVNode* end = &tile->bvTree[tile->header->bvNodeCount];
         const float* tbmin = tile->header->bmin;
         const float* tbmax = tile->header->bmax;
         const float qfac = tile->header->bvQuantFactor;
         // Calculate quantized box
         unsigned short bmin[3], bmax[3];
         // dtClamp query box to world box.
         float minx = dtClamp(qmin[0], tbmin[0], tbmax[0]) - tbmin[0];
         float miny = dtClamp(qmin[1], tbmin[1], tbmax[1]) - tbmin[1];
         float minz = dtClamp(qmin[2], tbmin[2], tbmax[2]) - tbmin[2];
         float maxx = dtClamp(qmax[0], tbmin[0], tbmax[0]) - tbmin[0];
         float maxy = dtClamp(qmax[1], tbmin[1], tbmax[1]) - tbmin[1];
         float maxz = dtClamp(qmax[2], tbmin[2], tbmax[2]) - tbmin[2];
         // Quantize
         bmin[0] = (unsigned short)(qfac * minx) & 0xfffe;
         bmin[1] = (unsigned short)(qfac * miny) & 0xfffe;
         bmin[2] = (unsigned short)(qfac * minz) & 0xfffe;
         bmax[0] = (unsigned short)(qfac * maxx + 1) | 1;
         bmax[1] = (unsigned short)(qfac * maxy + 1) | 1;
         bmax[2] = (unsigned short)(qfac * maxz + 1) | 1;
         // Traverse tree
         dtPolyRef base = getPolyRefBase(tile);
         int n = 0;
         while (node < end)
         {
             const bool overlap = dtOverlapQuantBounds(bmin, bmax, node->bmin, node->bmax);
             const bool isLeafNode = node->i >= 0;
             if (isLeafNode && overlap)
             {
                 if (n < maxPolys)
                     polys[n++] = base | (dtPolyRef)node->i;
             }
             if (overlap || isLeafNode)
                 node++;
             else
             {
                 const int escapeIndex = -node->i;
                 node += escapeIndex;
             }
         }
         return n;
     }
     else
     {
         float bmin[3], bmax[3];
         int n = 0;
         dtPolyRef base = getPolyRefBase(tile);
         for (int i = 0; i < tile->header->polyCount; ++i)
         {
             dtPoly* p = &tile->polys[i];
             // Do not return off-mesh connection polygons.
             if (p->getType() == DT_POLYTYPE_OFFMESH_CONNECTION)
                 continue;
             // Calc polygon bounds.
             const float* v = &tile->verts[p->verts[0]*3];
             dtVcopy(bmin, v);
             dtVcopy(bmax, v);
             for (int j = 1; j < p->vertCount; ++j)
             {
                 v = &tile->verts[p->verts[j]*3];
                 dtVmin(bmin, v);
                 dtVmax(bmax, v);
             }
             if (dtOverlapBounds(qmin,qmax, bmin,bmax))
             {
                 if (n < maxPolys)
                     polys[n++] = base | (dtPolyRef)i;
             }
         }
         return n;
     }
 }
References dtBVNode::bmax, dtMeshHeader::bmax, dtBVNode::bmin, dtMeshHeader::bmin, dtMeshHeader::bvNodeCount, dtMeshHeader::bvQuantFactor, dtMeshTile::bvTree, DT_POLYTYPE_OFFMESH_CONNECTION, dtClamp(), dtOverlapBounds(), dtOverlapQuantBounds(), dtVcopy(), dtVmax(), dtVmin(), getPolyRefBase(), dtPoly::getType(), dtMeshTile::header, dtBVNode::i, dtMeshHeader::polyCount, dtMeshTile::polys, dtPoly::vertCount, dtPoly::verts, and dtMeshTile::verts.
Referenced by findNearestPolyInTile().
removeTile()
dtStatus dtNavMesh::removeTile (dtTileRef ref, unsigned char ** data, int * dataSize)
Removes the specified tile from the navigation mesh.
Parameters
[in] ref The reference of the tile to remove.
[out] data Data associated with deleted tile.
[out] dataSize Size of the data associated with deleted tile.
Returns
The status flags for the operation.
This function returns the data for the tile so that, if desired, it can be added back to the navigation mesh at a later point.
See also
addTile
Definition at line 1233 of file DetourNavMesh.cpp.
 {
     if (!ref)
         return DT_FAILURE | DT_INVALID_PARAM;
     unsigned int tileIndex = decodePolyIdTile((dtPolyRef)ref);
     unsigned int tileSalt = decodePolyIdSalt((dtPolyRef)ref);
     if ((int)tileIndex >= m_maxTiles)
         return DT_FAILURE | DT_INVALID_PARAM;
     dtMeshTile* tile = &m_tiles[tileIndex];
     if (tile->salt != tileSalt)
         return DT_FAILURE | DT_INVALID_PARAM;
     // Remove tile from hash lookup.
     int h = computeTileHash(tile->header->x,tile->header->y,m_tileLutMask);
     dtMeshTile* prev = 0;
     dtMeshTile* cur = m_posLookup[h];
     while (cur)
     {
         if (cur == tile)
         {
             if (prev)
                 prev->next = cur->next;
             else
                 m_posLookup[h] = cur->next;
             break;
         }
         prev = cur;
         cur = cur->next;
     }
     // Remove connections to neighbour tiles.
     static const int MAX_NEIS = 32;
     dtMeshTile* neis[MAX_NEIS];
     int nneis;
     // Disconnect from other layers in current tile.
     nneis = getTilesAt(tile->header->x, tile->header->y, neis, MAX_NEIS);
     for (int j = 0; j < nneis; ++j)
     {
         if (neis[j] == tile) continue;
         unconnectLinks(neis[j], tile);
     }
     // Disconnect from neighbour tiles.
     for (int i = 0; i < 8; ++i)
     {
         nneis = getNeighbourTilesAt(tile->header->x, tile->header->y, i, neis, MAX_NEIS);
         for (int j = 0; j < nneis; ++j)
             unconnectLinks(neis[j], tile);
     }
     // Reset tile.
     if (tile->flags & DT_TILE_FREE_DATA)
     {
         // Owns data
         dtFree(tile->data);
         tile->data = 0;
         tile->dataSize = 0;
         if (data) *data = 0;
         if (dataSize) *dataSize = 0;
     }
     else
     {
         if (data) *data = tile->data;
         if (dataSize) *dataSize = tile->dataSize;
     }
     tile->header = 0;
     tile->flags = 0;
     tile->linksFreeList = 0;
     tile->polys = 0;
     tile->verts = 0;
     tile->links = 0;
     tile->detailMeshes = 0;
     tile->detailVerts = 0;
     tile->detailTris = 0;
     tile->bvTree = 0;
     tile->offMeshCons = 0;
     // Update salt, salt should never be zero.
 #ifdef DT_POLYREF64
     tile->salt = (tile->salt+1) & ((1<<DT_SALT_BITS)-1);
 #else
     tile->salt = (tile->salt+1) & ((1<<m_saltBits)-1);
 #endif
     if (tile->salt == 0)
         tile->salt++;
     // Add to free list.
     tile->next = m_nextFree;
     m_nextFree = tile;
     return DT_SUCCESS;
 }
References dtMeshTile::bvTree, computeTileHash(), dtMeshTile::data, dtMeshTile::dataSize, decodePolyIdSalt(), decodePolyIdTile(), dtMeshTile::detailMeshes, dtMeshTile::detailTris, dtMeshTile::detailVerts, DT_FAILURE, DT_INVALID_PARAM, DT_SALT_BITS, DT_SUCCESS, DT_TILE_FREE_DATA, dtFree(), dtMeshTile::flags, getNeighbourTilesAt(), getTilesAt(), dtMeshTile::header, dtMeshTile::links, dtMeshTile::linksFreeList, m_maxTiles, m_nextFree, m_posLookup, m_tileLutMask, m_tiles, dtMeshTile::next, dtMeshTile::offMeshCons, dtMeshTile::polys, prev(), dtMeshTile::salt, unconnectLinks(), dtMeshTile::verts, dtMeshHeader::x, and dtMeshHeader::y.
Referenced by MMAP::MapBuilder::buildMoveMapTile(), and MMAP::MMapMgr::unloadMap().
restoreTileState()
dtStatus dtNavMesh::restoreTileState (dtMeshTile * tile, const unsigned char * data, const int maxDataSize)
Restores the state of the tile.
Parameters
[in] tile The tile.
[in] data The new state. (Obtained from storeTileState.)
[in] maxDataSize The size of the state within the data buffer.
Returns
The status flags for the operation.
Tile state includes non-structural data such as polygon flags, area ids, etc.
Note
This function does not impact the tile's dtTileRef and dtPolyRef's.
See also
storeTileState
Definition at line 1415 of file DetourNavMesh.cpp.
 {
     // Make sure there is enough space to store the state.
     const int sizeReq = getTileStateSize(tile);
     if (maxDataSize < sizeReq)
         return DT_FAILURE | DT_INVALID_PARAM;
     const dtTileState* tileState = dtGetThenAdvanceBufferPointer<const dtTileState>(data, dtAlign4(sizeof(dtTileState)));
     const dtPolyState* polyStates = dtGetThenAdvanceBufferPointer<const dtPolyState>(data, dtAlign4(sizeof(dtPolyState) * tile->header->polyCount));
     // Check that the restore is possible.
     if (tileState->magic != DT_NAVMESH_STATE_MAGIC)
         return DT_FAILURE | DT_WRONG_MAGIC;
     if (tileState->version != DT_NAVMESH_STATE_VERSION)
         return DT_FAILURE | DT_WRONG_VERSION;
     if (tileState->ref != getTileRef(tile))
         return DT_FAILURE | DT_INVALID_PARAM;
     // Restore per poly state.
     for (int i = 0; i < tile->header->polyCount; ++i)
     {
         dtPoly* p = &tile->polys[i];
         const dtPolyState* s = &polyStates[i];
         p->flags = s->flags;
         p->setArea(s->area);
     }
     return DT_SUCCESS;
 }
References dtPolyState::area, DT_FAILURE, DT_INVALID_PARAM, DT_NAVMESH_STATE_MAGIC, DT_NAVMESH_STATE_VERSION, DT_SUCCESS, DT_WRONG_MAGIC, DT_WRONG_VERSION, dtAlign4(), dtPoly::flags, dtPolyState::flags, getTileRef(), getTileStateSize(), dtMeshTile::header, dtTileState::magic, dtMeshHeader::polyCount, dtMeshTile::polys, dtTileState::ref, dtPoly::setArea(), and dtTileState::version.
setPolyArea()
dtStatus dtNavMesh::setPolyArea (dtPolyRef ref, unsigned char area)
Sets the user defined area for the specified polygon.
Parameters
[in] ref The polygon reference.
[in] area The new area id for the polygon. [Limit: < DT_MAX_AREAS]
Returns
The status flags for the operation.
Definition at line 1553 of file DetourNavMesh.cpp.
 {
     if (!ref) return DT_FAILURE;
     unsigned int salt, it, ip;
     decodePolyId(ref, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return DT_FAILURE | DT_INVALID_PARAM;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return DT_FAILURE | DT_INVALID_PARAM;
     dtMeshTile* tile = &m_tiles[it];
     if (ip >= (unsigned int)tile->header->polyCount) return DT_FAILURE | DT_INVALID_PARAM;
     dtPoly* poly = &tile->polys[ip];
     poly->setArea(area);
     return DT_SUCCESS;
 }
References decodePolyId(), DT_FAILURE, DT_INVALID_PARAM, DT_SUCCESS, dtMeshTile::header, m_maxTiles, m_tiles, dtMeshHeader::polyCount, dtMeshTile::polys, and dtPoly::setArea().
setPolyFlags()
dtStatus dtNavMesh::setPolyFlags (dtPolyRef ref, unsigned short flags)
Sets the user defined flags for the specified polygon.
Parameters
[in] ref The polygon reference.
[in] flags The new flags for the polygon.
Returns
The status flags for the operation.
Definition at line 1520 of file DetourNavMesh.cpp.
 {
     if (!ref) return DT_FAILURE;
     unsigned int salt, it, ip;
     decodePolyId(ref, salt, it, ip);
     if (it >= (unsigned int)m_maxTiles) return DT_FAILURE | DT_INVALID_PARAM;
     if (m_tiles[it].salt != salt || m_tiles[it].header == 0) return DT_FAILURE | DT_INVALID_PARAM;
     dtMeshTile* tile = &m_tiles[it];
     if (ip >= (unsigned int)tile->header->polyCount) return DT_FAILURE | DT_INVALID_PARAM;
     dtPoly* poly = &tile->polys[ip];
     // Change flags.
     poly->flags = flags;
     return DT_SUCCESS;
 }
References decodePolyId(), DT_FAILURE, DT_INVALID_PARAM, DT_SUCCESS, dtPoly::flags, dtMeshTile::header, m_maxTiles, m_tiles, dtMeshHeader::polyCount, and dtMeshTile::polys.
storeTileState()
dtStatus dtNavMesh::storeTileState (const dtMeshTile * tile, unsigned char * data, const int maxDataSize) const
Stores the non-structural state of the tile in the specified buffer. (Flags, area ids, etc.)
Parameters
[in] tile The tile.
[out] data The buffer to store the tile's state in.
[in] maxDataSize The size of the data buffer. [Limit: >= getTileStateSize]
Returns
The status flags for the operation.
Tile state includes non-structural data such as polygon flags, area ids, etc.
Note
The state data is only valid until the tile reference changes.
See also
getTileStateSize, restoreTileState
Definition at line 1383 of file DetourNavMesh.cpp.
 {
     // Make sure there is enough space to store the state.
     const int sizeReq = getTileStateSize(tile);
     if (maxDataSize < sizeReq)
         return DT_FAILURE | DT_BUFFER_TOO_SMALL;
     dtTileState* tileState = dtGetThenAdvanceBufferPointer<dtTileState>(data, dtAlign4(sizeof(dtTileState)));
     dtPolyState* polyStates = dtGetThenAdvanceBufferPointer<dtPolyState>(data, dtAlign4(sizeof(dtPolyState) * tile->header->polyCount));
     // Store tile state.
     tileState->magic = DT_NAVMESH_STATE_MAGIC;
     tileState->version = DT_NAVMESH_STATE_VERSION;
     tileState->ref = getTileRef(tile);
     // Store per poly state.
     for (int i = 0; i < tile->header->polyCount; ++i)
     {
         const dtPoly* p = &tile->polys[i];
         dtPolyState* s = &polyStates[i];
         s->flags = p->flags;
         s->area = p->getArea();
     }
     return DT_SUCCESS;
 }
References dtPolyState::area, DT_BUFFER_TOO_SMALL, DT_FAILURE, DT_NAVMESH_STATE_MAGIC, DT_NAVMESH_STATE_VERSION, DT_SUCCESS, dtAlign4(), dtPoly::flags, dtPolyState::flags, dtPoly::getArea(), getTileRef(), getTileStateSize(), dtMeshTile::header, dtTileState::magic, dtMeshHeader::polyCount, dtMeshTile::polys, dtTileState::ref, and dtTileState::version.
unconnectLinks()
void dtNavMesh::unconnectLinks (dtMeshTile * tile, dtMeshTile * target) private
Removes external links at specified side.
Definition at line 353 of file DetourNavMesh.cpp.
 {
     if (!tile || !target) return;
     const unsigned int targetNum = decodePolyIdTile(getTileRef(target));
     for (int i = 0; i < tile->header->polyCount; ++i)
     {
         dtPoly* poly = &tile->polys[i];
         unsigned int j = poly->firstLink;
         unsigned int pj = DT_NULL_LINK;
         while (j != DT_NULL_LINK)
         {
             if (decodePolyIdTile(tile->links[j].ref) == targetNum)
             {
                 // Remove link.
                 unsigned int nj = tile->links[j].next;
                 if (pj == DT_NULL_LINK)
                     poly->firstLink = nj;
                 else
                     tile->links[pj].next = nj;
                 freeLink(tile, j);
                 j = nj;
             }
             else
             {
                 // Advance
                 pj = j;
                 j = tile->links[j].next;
             }
         }
     }
 }
References decodePolyIdTile(), DT_NULL_LINK, dtPoly::firstLink, freeLink(), getTileRef(), dtMeshTile::header, dtMeshTile::links, dtLink::next, dtMeshHeader::polyCount, dtMeshTile::polys, and dtLink::ref.
Referenced by removeTile().
Friends And Related Function Documentation
dtNavMeshQuery
friend class dtNavMeshQuery friend
Definition at line 688 of file DetourNavMesh.h.
Member Data Documentation
m_maxTiles
int dtNavMesh::m_maxTiles private
Max number of tiles.
Definition at line 674 of file DetourNavMesh.h.
Referenced by addTile(), getMaxTiles(), getOffMeshConnectionByRef(), getOffMeshConnectionPolyEndPoints(), getPolyArea(), getPolyFlags(), getTileAndPolyByRef(), getTileByRef(), init(), isValidPolyRef(), removeTile(), setPolyArea(), setPolyFlags(), and ~dtNavMesh().
m_nextFree
dtMeshTile* dtNavMesh::m_nextFree private
Freelist of tiles.
Definition at line 679 of file DetourNavMesh.h.
Referenced by addTile(), init(), and removeTile().
m_orig
float dtNavMesh::m_orig[3] private
Origin of the tile (0,0)
Definition at line 672 of file DetourNavMesh.h.
Referenced by calcTileLoc(), dtNavMesh(), and init().
m_params
dtNavMeshParams dtNavMesh::m_params private
Current initialization params. TODO: do not store this info twice.
Definition at line 671 of file DetourNavMesh.h.
Referenced by dtNavMesh(), getParams(), and init().
m_posLookup
dtMeshTile** dtNavMesh::m_posLookup private
Tile hash lookup.
Definition at line 678 of file DetourNavMesh.h.
Referenced by addTile(), getTileAt(), getTileRefAt(), getTilesAt(), init(), removeTile(), and ~dtNavMesh().
m_tileHeight
float dtNavMesh::m_tileHeight private
Dimensions of each tile.
Definition at line 673 of file DetourNavMesh.h.
Referenced by calcTileLoc(), and init().
m_tileLutMask
int dtNavMesh::m_tileLutMask private
Tile hash lookup mask.
Definition at line 676 of file DetourNavMesh.h.
Referenced by addTile(), getTileAt(), getTileRefAt(), getTilesAt(), init(), and removeTile().
m_tileLutSize
int dtNavMesh::m_tileLutSize private
Tile hash lookup size (must be pot).
Definition at line 675 of file DetourNavMesh.h.
Referenced by init().
m_tiles
dtMeshTile* dtNavMesh::m_tiles private
List of tiles.
Definition at line 680 of file DetourNavMesh.h.
Referenced by addTile(), getOffMeshConnectionByRef(), getOffMeshConnectionPolyEndPoints(), getPolyArea(), getPolyFlags(), getPolyRefBase(), getTile(), getTileAndPolyByRef(), getTileAndPolyByRefUnsafe(), getTileByRef(), getTileRef(), init(), isValidPolyRef(), removeTile(), setPolyArea(), setPolyFlags(), and ~dtNavMesh().
m_tileWidth
float dtNavMesh::m_tileWidth private
Definition at line 673 of file DetourNavMesh.h.
Referenced by calcTileLoc(), and init().
The documentation for this class was generated from the following files:
deps/recastnavigation/Detour/Include/DetourNavMesh.h
deps/recastnavigation/Detour/Source/DetourNavMesh.cpp