Azerotcore-wotlk: boss_doomrel Class Reference
boss_doomrel Class Reference
Classes
struct boss_doomrelAI
Public Member Functions
boss_doomrel ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 123 of file boss_tomb_of_seven.cpp.
Constructor & Destructor Documentation
boss_doomrel()
boss_doomrel::boss_doomrel () inline
Definition at line 126 of file boss_tomb_of_seven.cpp.
 : CreatureScript("boss_doomrel") { }
Member Function Documentation
GetAI()
CreatureAI* boss_doomrel::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 160 of file boss_tomb_of_seven.cpp.
     {
         return GetBlackrockDepthsAI<boss_doomrelAI>(creature);
     }
OnGossipHello()
bool boss_doomrel::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 152 of file boss_tomb_of_seven.cpp.
     {
         AddGossipItemFor(player, GOSSIP_DOOMREL_START_COMBAT, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, SAY_DOOMREL_HELLO, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_DOOMREL_START_COMBAT, GOSSIP_SENDER_MAIN, SAY_DOOMREL_HELLO, and SendGossipMenuFor().
OnGossipSelect()
bool boss_doomrel::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 128 of file boss_tomb_of_seven.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF+1:
                 AddGossipItemFor(player, GOSSIP_TEXT_CONTINUE, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 SendGossipMenuFor(player, SAY_QUEST_COMPLETED, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+2:
                 CloseGossipMenuFor(player);
                 creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 // Start encounter
                 InstanceScript* instance = creature->GetInstanceScript();
                 if (instance)
                 {
                     instance->SetData(TYPE_TOMB_OF_SEVEN, IN_PROGRESS);
                 }
                 creature->AI()->Talk(SAY_START_FIGHT);
                 break;
         }
         return true;
     }
References AddGossipItemFor(), Creature::AI(), ClearGossipMenuFor(), CloseGossipMenuFor(), Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_CONTINUE, IN_PROGRESS, Object::RemoveFlag(), SAY_QUEST_COMPLETED, SAY_START_FIGHT, SendGossipMenuFor(), ZoneScript::SetData(), CreatureAI::Talk(), TYPE_TOMB_OF_SEVEN, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_tomb_of_seven.cpp