Azerotcore-wotlk: G3D::Pointer< ValueType > Class Template Reference
G3D::Pointer< ValueType > Class Template Reference
#include <Pointer.h>
Classes
class Accessor
class FcnAccessor
class IndirectValue
class Interface
class Memory
class SharedAccessor
Public Member Functions
Pointer ()
Pointer (ValueType *v)
bool isNull () const
Pointer & operator= (const Pointer &r)
Pointer (const Pointer &p)
template<class Class >
Pointer (const shared_ptr< Class > &object, ValueType(Class::*getMethod)() const, void(Class::*setMethod)(ValueType))
template<class Class >
Pointer (const shared_ptr< Class > &object, const ValueType &(Class::*getMethod)() const, void(Class::*setMethod)(ValueType))
Pointer (ValueType(*getMethod)(), void(*setMethod)(ValueType))
Pointer (const ValueType &(*getMethod)(), void(*setMethod)(ValueType))
template<class Class >
Pointer (const shared_ptr< Class > &object, ValueType(Class::*getMethod)() const, void(Class::*setMethod)(const ValueType &))
template<class Class >
Pointer (const shared_ptr< Class > &object, const ValueType &(Class::*getMethod)() const, void(Class::*setMethod)(const ValueType &))
template<class Class >
Pointer (Class *object, const ValueType &(Class::*getMethod)() const, void(Class::*setMethod)(const ValueType &))
template<class Class >
Pointer (Class *object, ValueType(Class::*getMethod)() const, void(Class::*setMethod)(const ValueType &))
template<class Class >
Pointer (Class *object, const ValueType &(Class::*getMethod)() const, void(Class::*setMethod)(ValueType))
template<class Class >
Pointer (Class *object, ValueType(Class::*getMethod)() const, void(Class::*setMethod)(ValueType))
~Pointer ()
const ValueType getValue () const
void setValue (const ValueType &v)
Assign a value to the referenced element. If this Pointer was initialized with a NULL setMethod, the call is ignored.
IndirectValue operator* ()
const ValueType operator* () const
Private Attributes
Interface * m_interface
Detailed Description
template<typename ValueType>
class G3D::Pointer< ValueType >
Acts like a pointer to a value of type ValueType (i.e., ValueType*), but can operate through accessor methods as well as on a value in memory. This is useful for implementing scripting languages and other applications that need to connect existing APIs by reference.
Because the accessors require values to be passed by value (instead of by reference) this is primarily useful for objects whose memory size is small.
class Foo {
public:
   void setEnabled(bool b);
   bool getEnabled() const;
};
Foo  f;
bool b;
Pointer<bool> p1(&b);
Pointer<bool> p2(&f, &Foo::getEnabled, &Foo::setEnabled);
*p1 = true;
*p2 = false;
*p2 = *p1; \/\/ Value assignment
p2 = p1; \/\/ Pointer aliasing
\/\/ Or, equivalently:
p1.setValue(true);
p2.setValue(false);
p2.setValue(p1.getValue());
p2 = p1;
Note: Because of the way that dereference is implemented, you cannot pass *p through a function that takes varargs (...), e.g., printf("%d", *p) will produce a compile-time error. Instead use printf("%d",(bool)*p) or printf("%d", p.getValue()).
[McGuire], GUIs for Real-time Programs, using Universal Pointers, SIGGRAPH 2008 Poster.
Definition at line 63 of file Pointer.h.
Constructor & Destructor Documentation
Pointer() [1/13]
template<typename ValueType > G3D::Pointer< ValueType >::Pointer () inline
Definition at line 207 of file Pointer.h.
 : m_interface(NULL) {};
Pointer() [2/13]
template<typename ValueType > G3D::Pointer< ValueType >::Pointer (ValueType * v) inline
Allows implicit cast from real pointer
Definition at line 210 of file Pointer.h.
 : m_interface(new Memory(v)) {}
Pointer() [3/13]
template<typename ValueType > G3D::Pointer< ValueType >::Pointer (const Pointer< ValueType > & p) inline
Definition at line 227 of file Pointer.h.
                               : m_interface(NULL) {
         this[0] = p;
     }
Pointer() [4/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (const shared_ptr< Class > & object, ValueType(Class::*)() const getMethod, void(Class::*)(ValueType) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 234 of file Pointer.h.
                                                :
         m_interface(new SharedAccessor<Class, ValueType (Class::*)() const, void (Class::*)(ValueType)>(object, getMethod, setMethod)) {}
Pointer() [5/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (const shared_ptr< Class > & object, const ValueType &(Class::*)() const getMethod, void(Class::*)(ValueType) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 241 of file Pointer.h.
                                                :
         m_interface(new SharedAccessor<Class, const ValueType& (Class::*)() const, void (Class::*)(ValueType)>(object, getMethod, setMethod)) {}
Pointer() [6/13]
template<typename ValueType > G3D::Pointer< ValueType >::Pointer (ValueType(*)() getMethod, void(*)(ValueType) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 248 of file Pointer.h.
                                           :
         m_interface(new FcnAccessor<ValueType (*)(), void (*)(ValueType)>(getMethod, setMethod)) {}
Pointer() [7/13]
template<typename ValueType > G3D::Pointer< ValueType >::Pointer (const ValueType &(*)() getMethod, void(*)(ValueType) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 253 of file Pointer.h.
                                           :
         m_interface(new FcnAccessor<const ValueType& (*)(), void (*)(ValueType)>(getMethod, setMethod)) {}
Pointer() [8/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (const shared_ptr< Class > & object, ValueType(Class::*)() const getMethod, void(Class::*)(const ValueType &) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 260 of file Pointer.h.
                                                       :
         m_interface(new SharedAccessor<Class, ValueType (Class::*)() const, void (Class::*)(const ValueType&)>(object, getMethod, setMethod)) {}
Pointer() [9/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (const shared_ptr< Class > & object, const ValueType &(Class::*)() const getMethod, void(Class::*)(const ValueType &) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 267 of file Pointer.h.
                                                       :
         m_interface(new SharedAccessor<Class, const ValueType& (Class::*)() const, void (Class::*)(const ValueType&)>(object, getMethod, setMethod)) {}
Pointer() [10/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (Class * object, const ValueType &(Class::*)() const getMethod, void(Class::*)(const ValueType &) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 274 of file Pointer.h.
                                                       :
         m_interface(new Accessor<Class, const ValueType& (Class::*)() const, void (Class::*)(const ValueType&)>(object, getMethod, setMethod)) {}
Pointer() [11/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (Class * object, ValueType(Class::*)() const getMethod, void(Class::*)(const ValueType &) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 281 of file Pointer.h.
                                                       :
         m_interface(new Accessor<Class, ValueType (Class::*)() const, void (Class::*)(const ValueType&)>(object, getMethod, setMethod)) {}
Pointer() [12/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (Class * object, const ValueType &(Class::*)() const getMethod, void(Class::*)(ValueType) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 288 of file Pointer.h.
                                                :
         m_interface(new Accessor<Class, const ValueType& (Class::*)() const, void (Class::*)(ValueType)>(object, getMethod, setMethod)) {}
Pointer() [13/13]
template<typename ValueType > template<class Class > G3D::Pointer< ValueType >::Pointer (Class * object, ValueType(Class::*)() const getMethod, void(Class::*)(ValueType) setMethod) inline
Parameters
setMethod May be NULL
Definition at line 295 of file Pointer.h.
                                                :
         m_interface(new Accessor<Class, ValueType (Class::*)() const, void (Class::*)(ValueType)>(object, getMethod, setMethod)) {}
~Pointer()
template<typename ValueType > G3D::Pointer< ValueType >::~Pointer () inline
Definition at line 300 of file Pointer.h.
                {
         delete m_interface;
     }
References G3D::Pointer< ValueType >::m_interface.
Member Function Documentation
getValue()
template<typename ValueType > const ValueType G3D::Pointer< ValueType >::getValue () const inline
Definition at line 304 of file Pointer.h.
{
         debugAssert(m_interface != NULL);
         return m_interface->get();
     }
References debugAssert, G3D::Pointer< ValueType >::Interface::get(), G3D::Pointer< ValueType >::m_interface, and NULL.
Referenced by G3D::Pointer< ValueType >::IndirectValue::operator ValueType(), and G3D::Pointer< ValueType >::operator*().
isNull()
template<typename ValueType > bool G3D::Pointer< ValueType >::isNull () const inline
Definition at line 212 of file Pointer.h.
{
         return (m_interface == NULL) || m_interface->isNull();
     }
References G3D::Pointer< ValueType >::Interface::isNull(), G3D::Pointer< ValueType >::m_interface, and NULL.
Referenced by G3D::isNull(), and G3D::notNull().
operator*() [1/2]
template<typename ValueType > IndirectValue G3D::Pointer< ValueType >::operator* () inline
Definition at line 335 of file Pointer.h.
{
         return IndirectValue(this);
     }
operator*() [2/2]
template<typename ValueType > const ValueType G3D::Pointer< ValueType >::operator* () const inline
Definition at line 339 of file Pointer.h.
{
         return getValue();
     }
References G3D::Pointer< ValueType >::getValue().
operator=()
template<typename ValueType > Pointer& G3D::Pointer< ValueType >::operator= (const Pointer< ValueType > & r) inline
Definition at line 217 of file Pointer.h.
{
         delete m_interface;
         if (r.m_interface != NULL) {
             m_interface = r.m_interface->clone();
         } else {
             m_interface = NULL;
         }
         return this[0];
     }
References G3D::Pointer< ValueType >::Interface::clone(), G3D::Pointer< ValueType >::m_interface, and NULL.
setValue()
template<typename ValueType > void G3D::Pointer< ValueType >::setValue (const ValueType & v) inline
Assign a value to the referenced element. If this Pointer was initialized with a NULL setMethod, the call is ignored.
Definition at line 311 of file Pointer.h.
{
         debugAssert(m_interface != NULL);
         m_interface->set(v);
     }
References debugAssert, G3D::Pointer< ValueType >::m_interface, NULL, and G3D::Pointer< ValueType >::Interface::set().
Referenced by G3D::Pointer< ValueType >::IndirectValue::operator=().
Member Data Documentation
m_interface
template<typename ValueType > Interface* G3D::Pointer< ValueType >::m_interface private
Definition at line 203 of file Pointer.h.
Referenced by G3D::Pointer< ValueType >::getValue(), G3D::Pointer< ValueType >::isNull(), G3D::Pointer< ValueType >::operator=(), G3D::Pointer< ValueType >::setValue(), and G3D::Pointer< ValueType >::~Pointer().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Pointer.h