Azerotcore-wotlk: Acore::CreatureRelocationNotifier Struct Reference
Acore::CreatureRelocationNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
CreatureRelocationNotifier (Creature &c)
template<class T >
void Visit (GridRefMgr< T > &)
void Visit (PlayerMapType &)
Public Attributes
Creature & i_creature
Detailed Description
Definition at line 80 of file GridNotifiers.h.
Constructor & Destructor Documentation
CreatureRelocationNotifier()
Acore::CreatureRelocationNotifier::CreatureRelocationNotifier (Creature & c) inline
Definition at line 83 of file GridNotifiers.h.
 : i_creature(c) {}
Member Function Documentation
Visit() [1/2]
template<class T > void Acore::CreatureRelocationNotifier::Visit (GridRefMgr< T > &) inline
Definition at line 84 of file GridNotifiers.h.
 {}
Visit() [2/2]
void CreatureRelocationNotifier::Visit (PlayerMapType & m)
Definition at line 181 of file GridNotifiers.cpp.
 {
     for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         Player* player = iter->GetSource();
         // NOTIFY_VISIBILITY_CHANGED does not guarantee that player will do it himself (because distance is also checked), but screw it, it's not that important
         if (!player->m_seer->isNeedNotify(NOTIFY_VISIBILITY_CHANGED))
             player->UpdateVisibilityOf(&i_creature);
         // NOTIFY_AI_RELOCATION does not guarantee that player will do it himself (because distance is also checked), but screw it, it's not that important
         if (!player->m_seer->isNeedNotify(NOTIFY_AI_RELOCATION) && !i_creature.IsMoveInLineOfSightStrictlyDisabled())
             CreatureUnitRelocationWorker(&i_creature, player);
     }
 }
References GridRefMgr< OBJECT >::begin(), CreatureUnitRelocationWorker(), GridRefMgr< OBJECT >::end(), i_creature, Creature::IsMoveInLineOfSightStrictlyDisabled(), WorldObject::isNeedNotify(), Player::m_seer, NOTIFY_AI_RELOCATION, NOTIFY_VISIBILITY_CHANGED, and Player::UpdateVisibilityOf().
Member Data Documentation
i_creature
Creature& Acore::CreatureRelocationNotifier::i_creature
Definition at line 82 of file GridNotifiers.h.
Referenced by Visit().
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp